### ISSUE TITLE
foo.md renamed to foo.null while sharing

### ISSUE THREAD

**Issue by contrapunctus-1** [TeamAmaze/AmazeFileManager#1012]
Amaze v3.2.1 from F-Droid, on a Moto G5s Plus running Android v7.1.1.

When I send a file from Conversations, select Amaze as the file picker [1], and select a file foo.md, the file that gets sent is renamed to foo.null. Does not occur with other file managers.

[1] I can't send from Amaze directly, as the Share menu mysteriously omits Conversations - but I suppose that's a subject for a different ticket.

**Comment by EmmanuelMess** [comment]
I haven't tested with `Conversations` but with other apps and the extension seems to be intact. Anyone can replicate in current master?
