### ISSUE TITLE
Crash in TextReader with ACTION_VIEW and a null Uri

### ISSUE THREAD

**Issue by commonsguy** [TeamAmaze/AmazeFileManager#1014]
With Amaze 3.2.1, if another app uses `ACTION_VIEW` with a MIME type of `text/plain` but a `null` `Uri`, Amaze crashes with this:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amaze.filemanager.filesystem.BaseFile.getName()' on a null object reference
    at com.amaze.filemanager.activities.TextReader.onCreate(TextReader.java:207)
```

That is because [here](https://github.com/TeamAmaze/AmazeFileManager/blob/v.3.2.1/app/src/main/java/com/amaze/filemanager/activities/TextReader.java#L197-L207), you skip initializing `mFile` if the `Uri` is `null`, but then try calling `getName()` on `mFile` immediately thereafter.

Another app should not be providing a `null` `Uri` in this case, of course. But, still, ideally, you check if `mFile` is `null` before referencing it here.

The attached project can reproduce the error, though you will need to place a file named `hello_world.txt` in the `Download/` directory of external storage for it to work.
[MyApplication-20180211a.zip](https://github.com/TeamAmaze/AmazeFileManager/files/1714370/MyApplication-20180211a.zip)

**Comment by EmmanuelMess** [comment]
Related #963
