### ISSUE TITLE
Warn on input checklist

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1020]
This is all the EditFields that should be modified to recommend a specific extension:

- [x] Compress dialog's
- [x] Text file creation
- [x] Encrypted file creation ~~?~~

**Comment by TranceLove** [comment]
Will look into them after sunrise.

However, out of curiosity and in fact didn't look into the insides of file encryption yet... but do we need to allow users to specify another file extension on encrypting files? I thought files encrypted by Amaze had been designated a fixed file extension, although I think it is possible to decrypt the files outside Amaze?

**Comment by EmmanuelMess** [comment]
Encryption is horrendously broken by my standards, and nothing identifies the encrypted file but the extension, so it would be obligatory.

**Comment by VishalNehra** [comment]
'broken'?  take an example of old blackberry devices. They could only understand their own extension (.rem). There is no standard to this unless you find some library extension which doesn't make sense since we've already implemented it.

**Comment by VishalNehra** [comment]
Decryption outside amaze is not possible

**Comment by EmmanuelMess** [comment]
[Magic number](https://en.wikipedia.org/wiki/List_of_file_signatures)

**Comment by VishalNehra** [comment]
Making folder a single file before encryption? Doesn't make sense to me... The only thing that I think can be done is to change encrypted file names in directories to some random gibberish and only the name of directory encrypted to end with .aze.

**Comment by VishalNehra** [comment]
Ps. .aze stands for amaze encrypted. Tell this to the guy who prepared that wiki page to add it to the list.

**Comment by EmmanuelMess** [comment]
>Making folder a single file before encryption? Doesn't make sense to me... The only thing that I think can be done is to change encrypted file names in directories to some random gibberish and only the name of directory encrypted to end with .aze.

You mean "can" as in is possible or should be done? Because tarballing a folder is easy. And I think I already explained that gibberish filenames are horrendously confusing when you have 20 text files and need to open *the* one.

> Ps. .aze stands for amaze encrypted. Tell this to the guy who prepared that wiki page to add it to the list.

Please tell me this is a joke, that list references extension, file type and *header*.

**Comment by TranceLove** [comment]
Ah... the discussion goes way off the topic. I'd suggest leaving file encryption to a separate issue (which seems very big).

However, naming an encrypted folder with an `.aze` ala how XCode/OSX handles xcode project folders seems a good way to go.

**Comment by EmmanuelMess** [comment]
Yes

**Comment by TranceLove** [comment]
12b8981 implement mkfile, mkdir. Seeing rename was using a dialog on its own, I also changed it to use the same dialog layout.

Not sure if my idea of callback placements and arguments fit your purpose though.

**Comment by TranceLove** [comment]
Sorry for removing a comment and the 3 commits that made earlier as they should undergo the same PR->review->approve workflow before they exist in `fix-warnoninput` branch.

See #1021.

**Comment by TranceLove** [comment]
>  Encrypted file creation ~~?~~

Currently encrypted filename is determined by `CryptUtil` itself = `<filename.ext>.aze`. Does it mean that we are allowing user to enter the filename of the encrypted file, in the dialog having `<filename.ext>.aze` as default value and warn user if filename doesn't end with `.aze`?

Beware, you may have to allow user to decrypt a file encrypted by Amaze, without having the `.aze` file extension.

**Comment by EmmanuelMess** [comment]
.aze is obligatory

**Comment by EmmanuelMess** [comment]
This (and other issues) should be closed when fixed *on master*.

**Comment by VishalNehra** [comment]
Issues mentioned here are fixed on master.

**Comment by EmmanuelMess** [comment]
Aren't the fixes on [fix-warnoninput](https://github.com/TeamAmaze/AmazeFileManager/tree/fix-warnoninput)? If the branch was merged this should be closed.

**Comment by EmmanuelMess** [comment]
Souldn't there be a PR from fix-warninput to master?
