### ISSUE TITLE
Paralelize services

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1024]
[ProgressiveService](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/asynchronous/services/ProgressiveService.java)s run sequentially, but running them in parallel can bring considerable speed improvements. 
Also [CopyService](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/asynchronous/services/CopyService.java) can be further parallelized (e.g. via copying several folders at the same time).

**Comment by VishalNehra** [comment]
[ServiceWatcherUtils](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/utils/ServiceWatcherUtil.java)'s job is to serialize all the services and keeps track of and waits if any other service is currently running.
I think this approach is just fine for mobile/android devices with very limited amount of resources and slower NAND.

**Comment by EmmanuelMess** [comment]
Shouldn't we test limits? Phones have more cores every year (more or less), maybe tie the thread number to the device's capabilities.

I think significant time reductions can be achieved, with two threads the time to do an arbitrary operation halves, if the halves aren't interdependent and threading overheads are sufficiently small (like when copying different folders).

Of course we have to also take into account the testing difficulties, test automation should help.

**Comment by mirh** [comment]
Also please note that more threads==>more memory consumption. 

In other news, I just tried to delete a number of files, and for the whole duration of the operation the program UI was hanged. 
Could any of this help?

**Comment by VishalNehra** [comment]
Devices consume too much memory even in single service execution, parallelising it might cause too many problems.

**Comment by EmmanuelMess** [comment]
This has to be tested on a prototype first. IO in parallel could have issues.
