### ISSUE TITLE
Appbar doesn't turn grey after rotating while item is selected

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1034]
Appbar doesn't remain grey after an item was selected and screen was rotated.

**Comment by EmmanuelMess** [comment]
I'm assigned? Also, by grey you mean ActionMenu?

**Comment by VishalNehra** [comment]
Yes, as far as I can remember, you rewrote the whole appbar code. 
After rotation if an item was selected, the view below toolbar doesn't remain grey but changes back to primary color, only the upper half (toolbar) stays to selected color.

**Comment by EmmanuelMess** [comment]
Ah, I understand now, the BottomBar is failing.

**Comment by EmmanuelMess** [comment]
Should BottomBar be visible when ActionMenu is visible?

**Comment by VishalNehra** [comment]
Yes, let the whole toolbar turn grey like it currently does.
