### ISSUE TITLE
My usb device (otg) does not appear in the file provider (nexus 5 api 23 stock)

### ISSUE THREAD

**Issue by fiasko131** [TeamAmaze/AmazeFileManager#1046]
Hi,
Can not select the root of my usb key to interact with, it does not appear.
Amaze v3.2.1
![screenshot_20180223-012458](https://user-images.githubusercontent.com/3296760/36572178-943023cc-183a-11e8-9ed6-27b6e4a76e15.png)

![screenshot_20180223-012444](https://user-images.githubusercontent.com/3296760/36572172-8a3e753a-183a-11e8-9276-d4a4f6ec7308.png)

Any ideas?

(no problem with solidexplorer) see #878

**Comment by VishalNehra** [comment]
Press on three dot menu icon and then show external storage in the second screenshot.

**Comment by fiasko131** [comment]
Thanks!

There is a way to show external storage by default?
`Intent safIntent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);`
`mainActivity.startActivityForResult(safIntent, mainActivity.REQUEST_CODE_SAF);`

And also the code does not seem to keep (in the preferences) the access granted to the USB device and it is necessary to renew the authorization each time unlike solidexplorer?

**Comment by EmmanuelMess** [comment]
> There is a way to show external storage by default?

[It doesn't seem so.](https://stackoverflow.com/a/41981631/3124150)

> And also the code does not seem to keep (in the preferences) the access granted to the USB device and it is necessary to renew the authorization each time unlike solidexplorer?

See #1272
