### ISSUE TITLE
Drawer show non usb mass storage devices OTG

### ISSUE THREAD

**Issue by fiasko131** [TeamAmaze/AmazeFileManager#1055]
I add this in your isUsbDeviceConnected method for check if interface protocol equals 80 for usb mass storage device:

```Java
boolean usbMassStorage = false;
for (UsbDevice device :  usbManager.getDeviceList().values()) {
	for (int i =0;i<device.getInterfaceCount();i++){
		UsbInterface intf = device.getInterface(i);

                //Normaly we can compare with UsbConstants.USB_CLASS_MASS_STORAGE 
                //but intf.getInterfaceProtocol() return 80 and not 8 as indicated in the doc
                //(see doc link below)

		if (intf.getInterfaceProtocol()==80){
			usbMassStorage = true;
			break;
		}
	}
	if (usbMassStorage)break;
}
if (usbMassStorage) return true;
else return false;
```

Cheers

**Comment by EmmanuelMess** [comment]
Are you supposing there's only one device connected?

**Comment by EmmanuelMess** [comment]
Also, is there some reference for that 80? I could only find [some usages](https://findusages.com/search/android.hardware.usb.UsbInterface/getInterfaceProtocol$0?offset=22)...

**Comment by fiasko131** [comment]
For the uses I published my first post in the lines of codes:
look here: [https://developer.android.com/reference/android/hardware/usb/UsbConstants.html]()

Depending on the desired strategy it is possible to do this if you want to list several OTGs:
```java
        private static ArrayList<String> otgList = new ArrayList<>();

	public static boolean isUsbMassSorageDevicesConnected(){
		otgList.clear();
		UsbManager usbManager = (UsbManager) getSystemService(USB_SERVICE);
		boolean usbMassStorage = false;
		for (UsbDevice device :  usbManager.getDeviceList().values()) {
			for (int i =0;i<device.getInterfaceCount();i++){
				UsbInterface intf = device.getInterface(i);
				if (intf.getInterfaceProtocol()==80){
					usbMassStorage = true;
					Log.i("proto",device.getManufacturerName()+" 
                                        "+String.valueOf(intf.getInterfaceProtocol()));
					otgList.add(device.getManufacturerName());
				}
			}
		}
		if (usbMassStorage) return true;
		else return false;
	}
```
and then in your getStorageDirectories() method:
```java
....
if (SDK_INT >= Build.VERSION_CODES.KITKAT) {
	if (isUsbMassSorageDevicesConnected()){
		for (String otg : otgList){
                        //We could also overload the constant PREFIX_OTG as
                        //this to differentiate: rv.add ("&" + otg + "&" + PREFIX_OTG + "/");
			rv.add(PREFIX_OTG + "/");
		}
	}
	//if (isUsbDeviceConnected(context)) rv.add(PREFIX_OTG + "/");
}
...
```

**Comment by EmmanuelMess** [comment]
I don't understand why `(intf.getInterfaceProtocol()==80)`?

**Comment by fiasko131** [comment]
Are you see links above?
`(intf.getInterfaceProtocol()` return 80 if the usb connected on OTG is a mass storage device and it's only type available for an file explorer in my opinion.

**Comment by EmmanuelMess** [comment]
> (intf.getInterfaceProtocol() return 80 if the usb connected on OTG is a mass storage device and it's only type available for an file explorer in my opinion.

Haven't seen a single official documentation saying that. I need to know if other protocols should also be handled, or if there are edge cases where "false positives" occur.

**Comment by fiasko131** [comment]
Otherwise if I connect a USB receiver for mouse ... it will appear on your storages list !!

As I mentioned above in my code option you can use this:
```java
if (intf.getInterfaceClass() == UsbConstants.USB_CLASS_MASS_STORAGE && 
                                    intf.getInterfaceSubclass() == 6 &&
                                    intf.getInterfaceProtocol() == 80 &&
                                    intf.getEndpointCount() == 2) {
                                    usbMassStorage = true;
 }
```
Check only `intf.getInterfaceClass() == UsbConstants.USB_CLASS_MASS_STORAGE` if you want ... it's documented [here](https://developer.android.com/reference/android/hardware/usb/UsbConstants.html)
