### ISSUE TITLE
Apks category

### ISSUE THREAD

**Issue by jalalaghazadeh** [TeamAmaze/AmazeFileManager#1059]
Hi dude at AmazeTeam
I need help in understanding how your app find files based on categories (specially APKs)?
#223

**Comment by EmmanuelMess** [comment]
AFAIK by extension.

**Comment by jalalaghazadeh** [comment]
@EmmanuelMess so you search all the folders in memory in order to find .apk file? and may I ask how exactly you do it?

**Comment by jalalaghazadeh** [comment]
Thank you so mush, I was big help...
