### ISSUE TITLE
Drawer at landscape mode can drag to reveal white background

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#1061]
Attempt to close the drawer at landscape mode will reveal the white background beneath.

Halfway closing the drawer
![screenshot_20180226-144732](https://user-images.githubusercontent.com/251819/36656732-9e284766-1b04-11e8-94aa-625de875dde7.png)
Afterwards,
![screenshot_20180226-145045](https://user-images.githubusercontent.com/251819/36656744-ac4833f6-1b04-11e8-8458-1fd9904082a7.png)

Not related to #1060 - same symptom came up with or without it.

**Comment by VishalNehra** [comment]
I've tried fixing this in the past. Came to a conclusion that it's the bug in API and can't be fixed. If we do fixing this, it won't even open up after rotating it back to normal. So leaving this to it is the conclusion that I reached upon.
Anyone else is welcome to try fixing this though.

**Comment by VishalNehra** [comment]
Please confirm if this is reproducable right now... I don't think it is, maybe in certain rare scenario. @TranceLove

**Comment by EmmanuelMess** [comment]
Removing issue wont fix as it has a milestone and pr.
