### ISSUE TITLE
Tab 1 is right and tab 2 is left.

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1070]
Tab 1 is right and tab 2 is left. They should be inverted.
When fixing this bug beware of database data.

**Comment by VishalNehra** [comment]
Why should this be inverted? Right tab is default and primary, I don't plan on changing that.

**Comment by EmmanuelMess** [comment]
I usually start counting from the left, but I suppose we can leave as is.
