### ISSUE TITLE
Drawer in landscape shows bottom menu group 

### ISSUE THREAD

**Issue by abhishekd08** [TeamAmaze/AmazeFileManager#1072]
Navigation drawer in landscape mode shows last menu group (ftp server, app manager, setting) above the upper menu items ... It should appear after scrolling to buttom.

**Comment by abhishekd08** [comment]
Is is supposed to behave like that ? If not then can I work on that issue ?

**Comment by EmmanuelMess** [comment]
Can't replicate, what screen size?

Also, I'l assign it to you, it seems this should be fixed for the release of 3.3.0.

**Comment by abhishekd08** [comment]
I have a 5 inch screen size phone and downloaded the app from play store so i guess it is the master branch itself.

**Comment by EmmanuelMess** [comment]
No, it isn't, that's [the last release](https://github.com/TeamAmaze/AmazeFileManager/tree/v.3.2.1). If you can compile master and test your bug, I'll then reopen.

**Comment by abhishekd08** [comment]
you are right, bug is not in the master. Sorry for the mistake.
