### ISSUE TITLE
Cannot save file to SD card

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1073]
Cannot save file to SD card via share to Amaze. It says "Operation not allowed".
The problem seems to be here:
https://github.com/TeamAmaze/AmazeFileManager/blob/e928b4c2ac14befa11ab04821533c7f863dc884e/app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java#L643-L666
`boolean result = file.canWrite();`
Returns false, incorrectly.

**Comment by TranceLove** [comment]
Possibly related to [external storage access using SAF](https://stackoverflow.com/questions/36862675/android-sd-card-write-permission-using-saf-storage-access-framework)

[Reference](https://developer.android.com/guide/topics/providers/document-provider.html?hl=en).
