### ISSUE TITLE
Grid/list layout database loading is broken

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1077]
Grid/list layout database loading is broken, changes aren't loaded correctly.

**Comment by VishalNehra** [comment]
Database ain't broken but loading changes to the views is.

**Comment by VishalNehra** [comment]
Is this still an issue?

**Comment by EmmanuelMess** [comment]
No idea, but it was never fixed, so probably.

**Comment by VishalNehra** [comment]
I can't reproduce this.
