### ISSUE TITLE
opening a music with odyssey music player from amaze file manager doesn't work

### ISSUE THREAD

**Issue by kodeblacc** [TeamAmaze/AmazeFileManager#1079]
#### Expected behavior
I expected that when I selected the option to open a music file from amaze explorer with odyssey music player, I'll be able to play the music
#### Actual behavior
When I open a music from amaze explorer with odyssey music player, it doesn't play and the track name has changed to a number.

#### How to reproduce
- install amaze file manager
- install odyssey music player  (both apps are open source and can be downloaded from fdroid)
- make sure all permessions are enabled on both apps (for clarification)
- launch the amaze file manager
- select any music to play
- hold the music file down to highlight it and clcik the 3 dots menu on the top for options
- select the open with option and select odyssey music player as desired music player
- file name is changed and music doesn't play even when I clicked play
<hr>

* Device: Infinix note 4
* Software version:  Amaze explorer v3.2.1 Odyssey music player v1.1.13
* Operating system: Android 7.0

#### Recording Of The Bug
https://youtu.be/n0QDoQxiMu8

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/open-a-music-with-odyssey-music-player-from-amaze-file-manager-doesn-t-work">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by EmmanuelMess** [comment]
How do you know this isn't a bug in Odyssey music player?

**Comment by EmmanuelMess** [comment]
Will reopen when you have answered.

**Comment by kodeblacc** [comment]
Well I don't know.
I just reported the bug, I really don't know which of the apps has the
fault.
I simply reported what I experienced

**Comment by EmmanuelMess** [comment]
Sorry, I hadn't seen the video. Vinyl opens it, so the problem is in Odyssey.

**Comment by kodeblacc** [comment]
Oh okay. Thanks for confirming it.
What do I do in that regard?

**Comment by EmmanuelMess** [comment]
Create an issue with Odyssey, maybe.

**Comment by kodeblacc** [comment]
Yea will do that.
Thanks for the assist
