### ISSUE TITLE
Publish nightlies on F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [TeamAmaze/AmazeFileManager#1082]
Amaze has lots of bugs preventing it from operating normally. Since the release cycle is long it takes a lot of time to deliver bugfixes to users. I guess we should have nightly builds on F-Droid.

**Comment by EmmanuelMess** [comment]
How broken can nightly builds be?

**Comment by KOLANICH** [comment]
Yes, they can, but they rotate often and sometimes severe bugs will be fixed and non-severe harming noone introduced. For example that the file manager crashes on some file names is a severe bug, it is marked as fixed, but I cannot install it since there is no build.

**Comment by VishalNehra** [comment]
Would love to bring nightlies.. last time I checked, there was no support to build nightlies in fdroid. Can you guide me to it?

**Comment by KOLANICH** [comment]
A package is marked as unstable when its [versionCode](https://developer.android.com/guide/topics/manifest/manifest-element.html#vcode) is higher than [Current Version Code](https://f-droid.org/en/docs/Build_Metadata_Reference/#Current-Version-Code) in the metadata. Some apps prefer to have 2 separate ids for beta and stable to allow users to install both.

**Comment by VishalNehra** [comment]
But how do I get it to build nightlies automatically? 
I followed [this](https://f-droid.org/en/docs/Publishing_Nightly_Builds/) guide with no success.

**Comment by mirh** [comment]
> How broken can nightly builds be?

Possibly a lot, but it has been almost 3/4 of a year since last release, and it would be time for some new binary..

**Comment by EmmanuelMess** [comment]
We're on that, see milestone [v3.3.0](https://github.com/TeamAmaze/AmazeFileManager/issues?utf8=%E2%9C%93&q=is%3Aopen+sort%3Aupdated-desc+milestone%3Av3.3.0+).

**Comment by EmmanuelMess** [comment]
@KOLANICH 
> A package is marked as unstable when its versionCode is higher than Current Version Code in the metadata. Some apps prefer to have 2 separate ids for beta and stable to allow users to install both.

Do we need to have a manifest for FDroid in the repo?

**Comment by KOLANICH** [comment]
>Do we need to have a manifest for FDroid in the repo?

No. F-Droid has an own one for what I guess you mean under a "manifest".

**Comment by EmmanuelMess** [comment]
Ah, so we should make `Current Version Code` modifications there?

**Comment by ShapeShifter499** [comment]
Any updates with this?

**Comment by ShapeShifter499** [comment]
3.3 hotfix 2 

This build did not get into F-Droid.
