### ISSUE TITLE
Can't open files from CompressedExplorerFragment

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1088]
Unable to open file from fragment, it just extracts to parent of compressed file.
Bug introduced in #837

**Comment by EmmanuelMess** [comment]
Cannot replicate. I tried to open a text file and (in a zip) and it seems to work fine.

**Comment by VishalNehra** [comment]
For me it always gets extracted instead of opening up after pressing on it.

**Comment by EmmanuelMess** [comment]
In a zip?

**Comment by VishalNehra** [comment]
Yes
