### ISSUE TITLE
The Add folder/file Option  Is restricting Acess To Folder Option In Grid View

### ISSUE THREAD

**Issue by organik1** [TeamAmaze/AmazeFileManager#1092]
#### Expected behavior
The Icon is supposed to exist at a corner where it doesnt restrict any feature from being reached. 

#### Actual behavior
I use amaze file manager on grid view, and the number of columns is set to (2) it happens that I cant access the three dots on the last folder or file due to it being overlapped by the add file/folder(+)  icon.

#### How to reproduce
* Launch Amaze file manager.
* From the three dots at the upper right corner of the interface, choose 'grid view' from the menu when you click on the three dots.
* Go to Amaze f.m setting and set the number of columns so that no space is left at the bottom
* From you can see that (+) icon is overlapping any folder that falls into the extreme right.

### Device details

* Browser: Google Chrome
* Operating system: Android Nougat v7.0
* Device model:  Infinix Hot4 Pro

#### Recording Of The Bug
![PicsArt_03-06-02.32.11.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520346591/xcobiunadjalxxgsuh7e.jpg)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@organik/the-add-folder-file-option-is-restricting-acess-to-folder-option-in-grid-view">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by EmmanuelMess** [comment]
This would classify as secondary action:
<img height="350" src="https://user-images.githubusercontent.com/10991116/37117711-bd33b054-2230-11e8-8c24-b88063e1e02e.png"/>
We can move it, although it wouldn't look right (pun intended).
<img height="350" src="https://user-images.githubusercontent.com/10991116/37117815-10085442-2231-11e8-89cd-e25087010e03.png"/>
My proposition would be to move the menu button to the left a bit:
<img height="200" src="https://user-images.githubusercontent.com/10991116/37117927-5a28a798-2231-11e8-8a3c-258060848c84.png"/>

**Comment by VishalNehra** [comment]
Another option is to simply add an empty row in the end just like in list view.

**Comment by EmmanuelMess** [comment]
Wouldn't it be too big?

**Comment by VishalNehra** [comment]
If it would be, we can't always decrease it's height. I don't think there's any guideline to this, so we can always change it according to user feedback.

**Comment by EmmanuelMess** [comment]
I had forgotten the list ends at some point :laughing:
