### ISSUE TITLE
Root explorer file list has duplicated entries

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#1097]
After enabled root explorer, device root directory does not immediately visible, nor superuser permission dialog (SuperSU in my case) won't show up. Restarted app and go to `/system`, entries are doubled.

Go to storage that doesn't need root (`/storage/self/primary` for my Oneplus One + Slim7) directory/file listings are running normally.

<img height="350px" src="https://user-images.githubusercontent.com/251819/37196268-283e0044-23b1-11e8-8613-bb16fa9f0221.png"/>

Both entry of the same directory/file can open the corresponding directory/file however.

Verified on Oneplus One running Slim7 (7.1.2) and Samsung Galaxy S2 (GT-I9100) running Slimsaber (5.1.1), both rooted, running current master.

**Comment by VishalNehra** [comment]
Partially related to issue #1078
