### ISSUE TITLE
Download several pictures: overwrites ones with others

### ISSUE THREAD

**Issue by alleluia20** [TeamAmaze/AmazeFileManager#1105]
I was displaying an email using the Outlook app. The email had several pictures attached. I tried to download them to my DCIM/Camera folder, individually by opening each picture with Photos, clicking on "share", and select "save as" (I am not aware of another more efficient method, or any way to bulk save, please let me know if you know one...).

The problem is that Amaze downloads only a few of the pictures, because one of the  previously downloaded photos is sometimes replaced with the photo that I am currently downloading. It apparently has to do with a mix-up in the filenames, because the file names of some of the saved pictures do not match the names of the attachments at the email. I mean, as an example: I may have img1.jpg, img2.jpg, img3.jpg and img4.jpg at the email, I just have img1.jpg and img3.jpg saved. When trying to download a third picture, one of the two saved pictures is replaced with the new one; and, then, photo img1.jpg saved in the folder may look like photo img2.jpg attached to the email.

I tried Solid Explorer and I had no issue.

Regards.

**Comment by EmmanuelMess** [comment]
Which app version are you using?

**Comment by alleluia20** [comment]
The current Amaze on Google Play (version
 3.2.1). Same for Outlook.

**Comment by VishalNehra** [comment]
This feature had some changes so I don't think current master has this issue.
@alleluia20 please test the beta version when it comes out and report.
