### ISSUE TITLE
Incompatible SDK API use which may cause crash to your APP.

### ISSUE THREAD

**Issue by jay2013** [TeamAmaze/AmazeFileManager#1112]
Hi AmazeFile Manager Developers,
I develop a tool to detect incompatible SDK API use in android application. Today I use my tool to check AmazeFileManager downloaded from F-Droid.  My tool report many bugs. Although I believe most of them are real bugs, I cannot be 100% sure because I am not very familiar with Android developing. So 
please help to check it, it must be very helpful to your APP.

The attachment below is the bug report that my tool give. please help to double check! 
I also really hope to get your feedback. 
thank you!

[Supplementary explanation]
There are totally two type of bug in the report. The first one is like this: "API called in method not in [list]", the list here are sdk levels, it means your app run under these SDK version can not call API because no such API in these sdk levels.
Type two is like "API called in method no living level", it means your application can never reach this API
use, so if these API uses are not in external library, you can remove it from your own code.

APIs or methods in our report are given in signature format like "<declaringType: returnType methodName(paramTypeList)>".

And finally, the reachable path is actually one possible call stack. it is always start from dummyMainMethod which is created by our tool. So you should read it from bottom to top. 

Yes, many of these bugs seem to be in third-library codes. But it do cause problems in your app. Some third-library API say that they can only be run at specific SDK Level by using "@TargetApi(Build.VERSION_CODES.N)", however, Application codes tend to ignore this warning.

Donejie He
hedongjie@ict.ac.cn

[com.amaze.filemanager_63.apk.report.txt](https://github.com/TeamAmaze/AmazeFileManager/files/1834196/com.amaze.filemanager_63.apk.report.txt)

**Comment by EmmanuelMess** [comment]
Isn't this caused by ProGuard?

**Comment by jay2013** [comment]
[Supplementary explanation]
There are totally two type of bug in the report. The first one is like this: "API called in method not in [list]", the list here are sdk levels, it means your app run under these SDK versions can not call API because no such API in these sdk levels.
Type two is like "API called in method no living level", it means your application can never reach this API
use, so if these API uses are not in external library, you can remove it directly from your own code.

APIs or methods in our report are given in signature format like "<declaringType: returnType methodName(paramTypeList)>".

And finally, the reachable path is actually one possible call stack. it is always start from dummyMainMethod which is created by our tool. So you should read it from bottom to top.

Yes, many of these bugs seem to be in third-library codes. But it do cause problems in your app. Some third-library API say that they can only be run at specific SDK Level by using "@targetapi(Build.VERSION_CODES.N)", however, Application codes tend to ignore this warning.

**Comment by jay2013** [comment]
Hi， how can I use FTPTileService in your app?

**Comment by EmmanuelMess** [comment]
This doesn't seem to be causing troubles, as it would create crashes under some APIs and we are not seeing missing method crashes.
