### ISSUE TITLE
No way to edit or remove previously saved cloud connections?

### ISSUE THREAD

**Issue by vaguerant** [TeamAmaze/AmazeFileManager#1113]
I apologize if I'm missing something obvious, but I can't find any way to manage cloud connections (specifically SMB shares in my case) after I've saved them. I entered an SMB server wrong, and then created a new connection as I couldn't find an edit function. Now I can't find a delete function either in order to remove the broken share.

**Comment by EmmanuelMess** [comment]
In 3.2.1 long press connection in drawer, in 3.3.0 press the pencil icon.

**Comment by vaguerant** [comment]
I'm on 3.2.1, but a long press doesn't seem to do anything at all here. I get the gray, expanding "you long pressed a thing" animation, then .... absolutely nothing happens. Still, if it's fixed in current master, I guess this issue is already resolved, so I will close.
