### ISSUE TITLE
New folder crashes the app

### ISSUE THREAD

**Issue by abdulmalikkhan655** [TeamAmaze/AmazeFileManager#1116]
#### Expected behavior
according to my knowlege  I make a new folder there Enter his name and click the OK button And in this way  becomes a new folder create my sdcard 

#### Actual behavior
first of all i open this application and goto manu and select ext sdcard option  Click on the new folder and enter the name of the new folder there The application is closed as soon as I enter the name As you can see in the video

#### How to reproduce
* [download ](https://play.google.com/store/apps/details?id=com.amaze.filemanager)Amaze File Managerr version  3.2.1
* Install
*  Go to option
* select extsdcard
* create new folder 
* give the new name of folder 
* click on create 
* note bug 
* Browser: Amaze File Managerr version  3.2.1
* Operating system:android version 4.4.4
* Smart Phone samsung j1 ace 

#### Recording Of The Bug
https://youtu.be/GIiV0ew0ty0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulmalikkhan/bug-found-in-amaze-file-manager-apps-when-i-create-new-folder-apps-is-crashed-new-folder-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by EmmanuelMess** [comment]
You should click "Report" at least one time to send us the crash.
