### ISSUE TITLE
App carshes after launch on emulator

### ISSUE THREAD

**Issue by michaelsam94** [TeamAmaze/AmazeFileManager#1118]
while trying on nexus4 emulator runnig api 19 to solve this #1116 I got this crash 

![amaze_device](https://user-images.githubusercontent.com/9461037/38001198-d4804640-322b-11e8-8429-ed7b6a053ecf.JPG)
![issue_amze](https://user-images.githubusercontent.com/9461037/38001199-d4b218b4-322b-11e8-8033-ae1143ba5210.JPG)

**Comment by EmmanuelMess** [comment]
Which version?

**Comment by michaelsam94** [comment]
Version 3.2.1

**Comment by EmmanuelMess** [comment]
This was fixed by FABsMenu library.
