### ISSUE TITLE
Drawer width should follow design guidelines

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1119]
> Side nav width: Equal to the screen width minus the height of the action bar. In the example shown above, the nav drawer is 56dp from the right edge of the screen.
>
> Maximum width: The maximum width of the nav drawer is 280dp on mobile and 320dp on tablet. This is calculated by multiplying the standard increment by five (the standard increment is 56dp on mobile and 64dp on tablet).

Source: [Patterns – Navigation drawer](https://material.io/guidelines/patterns/navigation-drawer.html#).

This app [just makes the drawer width be 304dp](https://github.com/TeamAmaze/AmazeFileManager/blob/eeba4b5ee45aa721ece6770991d94453db6b2b54/app/src/main/res/values/dimens.xml#L5).

**Comment by TranceLove** [comment]
Closing, since #1123 was merged, which also fixed #1122, which also fixed this.
