### ISSUE TITLE
Adding folder to bookmarks make app crashes

### ISSUE THREAD

**Issue by michaelsam94** [TeamAmaze/AmazeFileManager#1128]
## **Expected behavior**
adding folder to bookmark show toast the app not crash

## **Actual behavior**
adding folder to bookmark show toast and app crashes

### How to reproduce

- Launch Amaze filemanager
- Press on 3 dots to show menu of actions 
- Press on Add to Bookmark

### TESTING ENVIRONMENT
Operating system: ANDROID V7.0 
App Version: v3.2.1
## Recording Of The Bug
<img height="500px" src="https://user-images.githubusercontent.com/9461037/38152142-93b47216-3466-11e8-9e56-4d89d1cd89a6.png"/> <img height="500px" src="https://user-images.githubusercontent.com/9461037/38152147-97cd1a74-3466-11e8-99ee-b23cc081fd02.png"/>

**Comment by michaelsam94** [comment]
the problem here try to modify ui element from background thread 
![add](https://user-images.githubusercontent.com/9461037/38156283-10cbf4b6-347d-11e8-9fd0-0db5f65ad398.JPG)
this function in DataUtils class need to call callback from uithread not from background thread

**Comment by michaelsam94** [comment]
need to centralize writing to sqlDatabase in UtilsHandler to run all writes to database in background thread

**Comment by EmmanuelMess** [comment]
Please don't put an image of a piece of code in the project if you can throw the link to it in the comment. Example:
```
https://github.com/TeamAmaze/AmazeFileManager/blob/e7d4533c340199254280c77fd47191f4b63d25a5/app/src/main/java/com/amaze/filemanager/activities/MainActivity.java#L268-L273
```
Causes:

https://github.com/TeamAmaze/AmazeFileManager/blob/e7d4533c340199254280c77fd47191f4b63d25a5/app/src/main/java/com/amaze/filemanager/activities/MainActivity.java#L268-L273

**Comment by michaelsam94** [comment]
Okay @EmmanuelMess I will consider this next time.

**Comment by michaelsam94** [comment]
@EmmanuelMess  I need to refactor UtilsHandler can I do this or this not important now?

**Comment by EmmanuelMess** [comment]
Refractory would be problematic as v3.3.0 is feature complete and I don't want more bugs. Bug fixes are ok though, leading to a grey area where you PR (with refractoring) will probably be pulled but could lead to bugs, which I don't want. Hence, do what you have (to reduce bugs) but carefully, please.

**Comment by michaelsam94** [comment]
@EmmanuelMess I will be careful and If I change any part I will make sure not affect other parts
