### ISSUE TITLE
Drawer can start to not close on item selection

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1130]
Sometimes the drawer starts to not close when an item is selected. Haven't pinpointed the cause yet.

**Comment by VishalNehra** [comment]
Noticed this bug too, after your drawer remake.

**Comment by EmmanuelMess** [comment]
@VishalNehra can you replicate anymore? Because I stopped being able to replicate.

**Comment by VishalNehra** [comment]
Yes, I can.

**Comment by TranceLove** [comment]
@EmmanuelMess try to see if you can reproduce the problem in this way.

1. Launch app
2. Select file/directory on your device, then tap copy or cut
3. Change to other tab
4. Open drawer
5. Select any item except settings (which would lead to Preference activity)
6. Drawer not closed, but tab did load

Tested with Oneplus One running Slim7 (7.1.2) and Galaxy S2 running SlimLP (5.1.1).

**Comment by EmmanuelMess** [comment]
Thanks! I'll try to fix!
