### ISSUE TITLE
'Save as' activity not working

### ISSUE THREAD

**Issue by mcyusuf** [TeamAmaze/AmazeFileManager#1132]
#### Expected behavior
Calling the 'save as' activity via the share option should perform a task

#### Actual behavior
The amaze file manager 'save as' activity does nothing when called from the share menu.

#### How to reproduce
* Download and install amaze file manager from [here](https://f-droid.org/app/com.amaze.filemanager)
* Select a file and click share from the menu shown.
* Choose the 'save as' activity from the menu that shows.
---
* App: amaze file manager (version 3.2.1)
* Operating system: Android Nougat on Tecno K7

#### Recording Of The Bug
(https://youtu.be/visceD0Yjzk)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mcyusuf/save-as-activity-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by VishalNehra** [comment]
Fixed on #917 
Test and report else wait for beta update.
