### ISSUE TITLE
Sharing a shopping list file to amaze file manager crashes the app

### ISSUE THREAD

**Issue by kodeblacc** [TeamAmaze/AmazeFileManager#1151]
#### Expected behavior
I expected that I'll be able to share my shopping list file to amaze file manager.

#### Actual behavior
When I share the shopping list file, and select a preferred folder to save it to, the app crashes

#### How to reproduce
- download amaze file manager and shopping list software from fdroid
- Launch the shopping list app, create a list
- access the menu click share and select amaze file manager
- on the file manager select a desired folder click the download icon and the app crashes

* Device: Infinix note 4
* Operating system: Android 7.0
- Software version: Amaze file manager v 3.2.1
Shopping list 0.9.0

#### Recording Of The Bug
https://youtu.be/Gq9QWP7kc9k
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/sharing-a-shopping-list-file-to-amaze-file-manager-crashes-the-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by VishalNehra** [comment]
Should be fixed with 3.5.0
Please test.
