### ISSUE TITLE
How to set drawer's header image like this app?

### ISSUE THREAD

**Issue by zaen323** [TeamAmaze/AmazeFileManager#1152]
(question tag maybe?)

Hi there, I want to first thank the team for making such a wonderful app open source.

I was impressed by how stylish the header in the navigation drawer looked, and wanted to implement it the way in an app of my own.

However, after spending some time diving into the source code, I could not really understand how it worked. Some questions are:
- navView.setBackgroundColor(Utils.getColor(mainActivity, R.color._color_))  (or setting background attribute in the xml) changes the entire drawer's color, how to avoid this?
- The source codes defining the ui are almost all written in Java file, is it preferable to xml? (Or is there any reason for writing them in Java? )

And generally, I am curious how you make it work.

It would be nice if you could share some in-depth explanation. Maybe I am asking too much...? but any help means a lot to me.

Thank you.

**Comment by EmmanuelMess** [comment]
I converted the drawer to NavigationView, but left some of the code as it was before, you should link to the lines you feel could be done in XML, but generally, if it's not done in XML it's because the color can be changed by the user (not known at compile time).
