### ISSUE TITLE
USB OTG doesn't show in drawer

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1162]
When I connect a pendrive to my phone it doesn't show in Amaze but is shows in notifications.
API 23 Moto E2.

PS: difficult to debug because I can't connect my computer and pendrive at the same time.

**Comment by VishalNehra** [comment]
@EmmanuelMess suggest you to use wireless adb.

**Comment by EmmanuelMess** [comment]
I tried, couldn't get it to work (although that was some time ago, will check again).
