### ISSUE TITLE
Add explanation to position variable to prevent multithreading mistakes

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1179]
This variable:
https://github.com/TeamAmaze/AmazeFileManager/blob/5cf10b4545bfe534ac8de1077e771c2434ab80a3/app/src/main/java/com/amaze/filemanager/utils/ServiceWatcherUtil.java#L33
cannot be edited by two thread simultaneously, that should be explained in a javadoc.

**Comment by TranceLove** [comment]
Should be solved by #1193.
