### ISSUE TITLE
Refresh loop

### ISSUE THREAD

**Issue by KarmusDK** [TeamAmaze/AmazeFileManager#1189]
When going into a folder with an ongoing download of a temporary file, the app constantly refreshes the file view and navigation becomes unavailable. Only possible way out is forcing a close of the app from the outside.

Steps to reproduce: Download a map in application MAPS.ME and navigate to the location folder while the file is transferring.

Btw, it would be nice to add a Refresh button to the navigation, so that you can trigger a refresh manually and not happen automatically, as it is now.

**Comment by VishalNehra** [comment]
Thanks for reporting. We've already fixed the issue, you're requested to join our beta program to try the fix at the earliest or wait for another stable release. 
See [milestone 3.3.0](https://github.com/TeamAmaze/AmazeFileManager/milestone/1)

**Comment by nikfrei** [comment]
Sorry to comment on closed. Is this issue solved? I am experiencing it with the latest version available on F-droid.

**Comment by VishalNehra** [comment]
Yes, we're releasing v3.3.0RC1. It should be available on fdroid in few days.
