### ISSUE TITLE
Compact view for List mode

### ISSUE THREAD

**Issue by leewdch** [TeamAmaze/AmazeFileManager#1194]
Right now it's impossible reading file names using tags or whatever recurring patterns such as random signs or epoch prefixes. I'd like to compact view list like in the VLC app

![screenshot_20180423-164523](https://user-images.githubusercontent.com/11262717/39135072-6a90b484-4718-11e8-83c7-5e8b08ae8cdc.png)
![screenshot_20180423-170153](https://user-images.githubusercontent.com/11262717/39135081-6d5d640a-4718-11e8-9099-ced0f36bb78b.png)

**Comment by EmmanuelMess** [comment]
Already fixed, wait for release.

**Comment by leewdch** [comment]
has this been fixed in latest beta?

**Comment by EmmanuelMess** [comment]
No.
