### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by organik1** [TeamAmaze/AmazeFileManager#1214]
Hello Dev.
There's an issue with amaze file manager where when a file is shared to the same folder from a third party (not stock) filemanager, using  amaze's "save as" option, the file in question becomes corrupt. 
However is stock is used to share the file.. The file is renamed to null without extensions but not corrupt.

To explain better.
Launch a third party file manager, opena folder (let's choose DCIM), pick a file and opt to share it, select amaze's -save as- from the menu and now from the directory choose the same folder (DCIM) and save the file there.  

Please I hope this issue is looked into, I just lost a very important file because of this. Thank you.

(The two third party file manager that I made use of, and which produce this issue is DIR file manager And Simple FileManager.

**Comment by EmmanuelMess** [comment]
Which file manager was used to share the file?

**Comment by organik1** [comment]
Dir file manager and simple file manager..

**Comment by TranceLove** [comment]
Sounds like a overwrite-itself problem... if I understand correctly the symptom looks like this

1. Open a file, e.g DSC1001.jpg
2. Share this file from the file manager's own menu
3. Select Amaze "Save As..."
4. Amaze popped up, choose the same folder as DSC1001.jpg
5. File was overwritten by itself, undefined behaviour (that file may or may not be corrupt)

I think we should add a overwrite confirmation dialog to prompt user, or even further, give a new name to the duplicated file or simply block overwriting.

Couldn't reproduce it with CM File Manager (it's the nearest thing I can found on hand), so I couldn't mark the bug label yet.

And sorry again for your loss of file...
