### ISSUE TITLE
Text files from Simple File Manager Causes Amaze File Manager To Crash

### ISSUE THREAD

**Issue by organik1** [TeamAmaze/AmazeFileManager#1220]
### Actual behavior

Amaze file manager crashes when its text editor is selected as a medium to open text files on simple file manager.

How to reproduce

1. Download simple file manager (https://m.apkpure.com/simple-file-manager/com.simplemobiletools.filemanager)

2. Launch simple file manager and locate a text file. (.txt)

3. Opt to Open the text file and select Amaze text editor from the menu of text editors.

4. Amaze file manager should force close

Testing Environment

App Version: Amaze file manager v3.2.1 and simple file manager v3.4.0

Operating system: Android v6.0 marshmallow

Device : ITEL p12 (spread chipset)

**Comment by EmmanuelMess** [comment]
Already fixed in master
