### ISSUE TITLE
Make searching in hidden file optional

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1243]
When searching, it is more often that one searches for one's own (not hidden) files, rather than hidden files. I propose that when the "show hidden files" setting is enabled each time the user searches he should have the option of searching hidden files.

**Comment by mk410gd** [comment]
@EmmanuelMess The actual situation is that if the "show hidden files" option is disabled, you can also search and show hiden files/folders.

**Comment by EmmanuelMess** [comment]
I should probably make another issue with that bug. Thanks for the info.

PS:
I was ill and working on projects for school for most of this week, so I wasn't able to look at any GitHub notification...and they accumulated quite a bit. I'm able to work now, so I apologize for the lateness.

**Comment by VishnuSanal** [comment]
fixed with #2126 :D
