### ISSUE TITLE
Forbid FTP startup when device is locked

### ISSUE THREAD

**Issue by germanfr** [TeamAmaze/AmazeFileManager#1253]
I can currently enable FTP from the lock screen with the notification shortcut. I think that is a potential security risk. It should ask for the pin/pattern like when you try to turn off geolocation.

Also, it'd be great if the button was greyed out when the server is off, like other buttons do.

![screenshot_20180527-121401](https://user-images.githubusercontent.com/10391266/40585152-e4880e68-61ad-11e8-9990-07f4bd829ffd.png)

**Comment by EmmanuelMess** [comment]
@VishalNehra  where is the code for this? I'll see if I can fix.

**Comment by VishalNehra** [comment]
The button *IS* grayed out when it's off. I think only initially it's on when you add it for the first time and the server is not activated.
As for this issue, I don't think there's any security risk in it. I can turn off location tile from lockscreen just fine. The security lies within the protocol itself, use SFTP if you're concerned.

**Comment by TranceLove** [comment]
> @VishalNehra where is the code for this? I'll see if I can fix.

`FTPTileService`?

**Comment by germanfr** [comment]
@VishalNehra you can see in the screenshot how the tile is visibly "on" while the server is not running and it's been there for months.

And not asking for the pin IS a security risk because anyone without access could just turn on the server and access my files if I don't have a password or they have the password somehow. On Android 7.0 I'm asked for the pin to turn on/off location, also to make a call from the lock screen, but I don't need to unlock the app itself each time I want to use it if the device is unlocked.

It doesn't harm anyone and I guess is not that hard to implement.

**Comment by VishalNehra** [comment]
@germanfr alright, we shall work on it.
