### ISSUE TITLE
Should we migrate from GitHub?

### ISSUE THREAD

**Issue by KOLANICH** [TeamAmaze/AmazeFileManager#1269]

**Comment by EmmanuelMess** [comment]
Why should we?

**Comment by TranceLove** [comment]
The typical M$ takeover fear I think...

My opinion, they are making their own Linux for their own cloud, and many big corporations have their public repo here. Purists choose to leave, but I'd choose to trust github can still be independent - the M$ I see today is not the clowns back in the SCO/Novell lawsuit days.

Unless they start to charge even open source repos which are not using MFC or not for Windows, I think we should still be safe here.

Just need to make sure all the code has the GPL header so nobody has no ground to steal our code.

And backup... don't say you don't do any backups.

**Comment by KOLANICH** [comment]
>M$ I see today is not the clowns

MS have transformed own website into crap full of trackers and unusable without JS. if you try to download Visual Studio or read KBs you can feel it.

**Comment by EmmanuelMess** [comment]
A new issue can be created if there is good motive to think we MUST move somewhere else.

**Comment by TranceLove** [comment]
> MS have transformed own website into crap full of trackers and unusable without JS. if you try to download Visual Studio or read KBs you can feel it.

Another story then - those JS fanatics who prefer awesomeness over accessibility and usability 😏
