### ISSUE TITLE
Change of drawer layout

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1273]
I propose a few changes in drawer. 
1. Although the current layout designed by @EmmanuelMess is much better than 'long-press' design where to interact with bookmarks we had to long press on them, but the pencil (edit) icon seems too much redundant specially when we have lots of bookmarks. 
I propose to change that and use a single 'edit' sublabel.
This seems more clean, it's even mentioned in [Material Design Guidelines](https://material.io/design/components/navigation-drawer.html).
Refer to image attached of Google Keep at the end.
2. The selection in drawer should have 12% opacity of the accent color (refer attachment below).

![screenshot_keep_20180609-024432](https://user-images.githubusercontent.com/5211568/41182169-21a7e94c-6b92-11e8-8d58-dc181828c9ec.png)
![](https://material.io/design/assets/1nsuL8VDpBW_LZYXgabK1H0uq6icmmKYt/nav-drawer-intro.png)

**Comment by EmmanuelMess** [comment]
Beware that (I think) the device in the second image is using Material Design 2.

**Comment by VishalNehra** [comment]
Will create separate issues for MD 2 migration.
