### ISSUE TITLE
Release 3.3.0 on f-droid

### ISSUE THREAD

**Issue by mrmotallebi** [TeamAmaze/AmazeFileManager#1280]
Creating new issue since previous one couldn't be re-opened.

Thanks.

**Comment by k3b** [comment]
previous closed issue was #1068

**Comment by EmmanuelMess** [comment]
Why are you opening new issue?

**Comment by mrmotallebi** [comment]
Sorry, my mistake. I thought 3.3.0 has been released.

**Comment by guillaume-d** [comment]
3.3.0 is out since a couple of weeks but F-Droid still cannot build it, saying "cannot find symbol ImageView".
So I guess this should be reopened or somehow addressed.
