### ISSUE TITLE
failed when copy file from SMB

### ISSUE THREAD

**Issue by ted423** [TeamAmaze/AmazeFileManager#1281]
12.43G,multi file
and ES File Explore success

**Comment by EmmanuelMess** [comment]
multi file?

**Comment by ted423** [comment]
this is the folder 
![image](https://user-images.githubusercontent.com/7042766/41381941-75546a94-6f9c-11e8-83b9-0fcc5a6ea329.png)

**Comment by VishalNehra** [comment]
Working fine on master. Please re-open if persists after v3.3.0

**Comment by ted423** [comment]
but when I copy big file(4GB),it always show failed,I'm using ES File Explore

**Comment by ted423** [comment]
it only copy 120M

**Comment by ted423** [comment]
@VasilisKos 
https://youtu.be/9lGbgd_lVrE

**Comment by ted423** [comment]
where to get 3.3.0?

**Comment by EmmanuelMess** [comment]
It is still to be released
