### ISSUE TITLE
Can't edit, remove, or rename SMB connections. 

### ISSUE THREAD

**Issue by sid32** [TeamAmaze/AmazeFileManager#1282]
So I have 2 SMB connections, one working, one not, they are all labeled as SMB Connection and I can't edit names, edit settings, etc.

**Comment by EmmanuelMess** [comment]
Long pressing button in drawer?

**Comment by sid32** [comment]
Nope.

**Comment by EmmanuelMess** [comment]
Ok, it will most likely be fixed with version 3.3.0, when it is released, do open another issue if the problem persists.
