### ISSUE TITLE
Add Intents to start FTP server. 

### ISSUE THREAD

**Issue by sid32** [TeamAmaze/AmazeFileManager#1283]
Basically add an Intent to start FTP server.

**Comment by EmmanuelMess** [comment]
Is there a standard intent for FTP?

**Comment by sid32** [comment]
No. Here are the instructions for start FTP in  ES File Explorer with Tasker.

1、StartESFtp
Tasks->New Task("StartESFtp")->Add Action->Misc->Send Intent->
Action: android.intent.action.MAIN
Package: com.estrongs.android.pop
Class: com.estrongs.android.pop.ftp.ESFtpShortcut
Target: Activity
2、StopESFtp
Tasks->New Task("StopESFtp")->Add Action->Misc->Send Intent->
Action: android.intent.action.MAIN
Extra1: mode:2
Package: com.estrongs.android.pop
Class: com.estrongs.android.pop.ftp.ESFtpShortcut
Target: Activity

**Comment by EmmanuelMess** [comment]
It seems that being able to respond to something like this would be ideal:

```
File file = new File(dir,name);
String mimeType = "text/qif";
String target= "ftp://login:password@my.example.org:port/my/directory/";
intent = new Intent(android.content.Intent.ACTION_SENDTO);
intent.setDataAndType(android.net.Uri.parse(target),mimeType);
intent.putExtra(Intent.EXTRA_STREAM, Uri.fromFile(file));
```

-- [source](http://michael.totschnig.org/SendWithFtp/)
