### ISSUE TITLE
3.2.2 still not in FDroid

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1288]
Have no idea how to release to FDroid.

**Comment by VishalNehra** [comment]
Normally their system compiles automatically once we bump up versions in manifest, but since we've changed the project structure (by removing MainActivity specific to fdroid) their build will fail. 
We need to contact them to get this problem fixed.

**Comment by EmmanuelMess** [comment]
But 3.2.2 still has the old system

**Comment by VishalNehra** [comment]
They run the source compile from master. And our master is still at version code 63. They'll update only when we bump up versions on our master, not on any other branch.

**Comment by EmmanuelMess** [comment]
We implement full gitflow (adding 'development' branch and reverting 'master' to the last release)? @TranceLove @VishalNehra ?

**Comment by Bubu** [comment]
> They run the source compile from master. And our master is still at version code 63. They'll update only when we bump up versions on our master, not on any other branch.

Not quite true. F-Droid is set up to look for tags in this repo to detect updates. There no 3.2.2 tag, so f-droid won't ever attempt to build anything here.

**Comment by EmmanuelMess** [comment]
Can one make a tag outside master and make FDroid update?

**Comment by Bubu** [comment]
A tag has nothing to do with any branches. It's basically just a pointer to a specific commit.

**Comment by EmmanuelMess** [comment]
We now have tag 3.2.2, lets hope FDroid picks it up.

**Comment by EmmanuelMess** [comment]
@VishalNehra thanks! Closing then.
