### ISSUE TITLE
SMB connection entries are corrupted 

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1289]
I was testing something and noticed after adding a new SMB connection, it loads fine for that time, but after restarting Amaze the entry in drawer is corrupted and after pressing on it, nothing happens. Even pressing on edit icon doesn't give any response.
Find the screenshot attached below. The server name was Vishal and it automatically changed to something else.
![screenshot_amaze_20180615-024013](https://user-images.githubusercontent.com/5211568/41458903-8b140fba-70a5-11e8-9a6d-448fd56eb235.png)

**Comment by TranceLove** [comment]
Seems database data is still intact, but the drawer entry was not created correctly.

**Comment by TranceLove** [comment]
Database data is still intact, but the column values were incorrectly inserted.
