### ISSUE TITLE
This item isn't available in your country [Google Play Store]

### ISSUE THREAD

**Issue by ivadham** [TeamAmaze/AmazeFileManager#1297]
I can't download **Amaze File Manager** on Google Play in Iran. You think you can fix that?
<img src="https://user-images.githubusercontent.com/11696957/41580234-5fbf50a6-73af-11e8-8f54-0e9d25bef331.png" width="480">

**Comment by EmmanuelMess** [comment]
For now, you can download from [FDroid](https://f-droid.org/packages/com.amaze.filemanager/).

**Comment by VishalNehra** [comment]
I've enable Amaze for 7 countries which were disabled due to the inability to process in-app purchases in them. Changes should reflect in few hours time.
