### ISSUE TITLE
Socket for secure FTP connection is cut and IP not visible

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1301]
Phone: Moto E Gen 2 4G
<img src="https://user-images.githubusercontent.com/10991116/41665112-98de96f2-747d-11e8-8353-4450f8f08582.png" height="250px"/>

**Comment by TranceLove** [comment]
You say you're running on 4G... but Amaze should have disallowed you to even start the FTP server at all.

If you are running on 4G with Wifi AP enabled, at my case it showed me an IP that is not the AP's IP (192.168.43.1). This should be fixed, but I'm not sure this is related to your problem.

(e.g. they gave you an IPv6 that we cannot display?)

**Comment by EmmanuelMess** [comment]
The phone model is called that, not running on 4G.
