### ISSUE TITLE
Notification layout

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1305]
Having the completed and total size to the right doesn't seems right from a design standpoint. Maybe move it below the title?
Also, the title isn't aligned to the progress bar.
What do you think?

<img src="https://user-images.githubusercontent.com/10991116/41687584-adbf7014-74be-11e8-9c7d-206cf2e9562d.png" height="150px"/>

**Comment by VishalNehra** [comment]
Please tell your configs here, layouts are completely fine on the devices I tested.
