### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1315]
The idea is to have a standarized way of releasing.

I propose releasing a `x.y.zrc1` first (as beta in FDroid and Play), check for bug reports and then release `x.y.zrc2` if a high priority bug appears or re-releasing `x.y.zrc1` as `x.y.z` (as final non-beta version) if not.

**Comment by TranceLove** [comment]
Sounds fair.

**Comment by VishalNehra** [comment]
Milestone v3.3.0 is complete. We release rc1 now on beta channel. Everyone agree?

**Comment by EmmanuelMess** [comment]
Remember to release as beta for FDroid too

**Comment by TranceLove** [comment]
I'm voting +1 for rc1 too. But a little question: though not required, should #1325 be available with 3.3.0 too?

**Comment by VishalNehra** [comment]
Oh, my bad. Didn't get a chance to test it yesterday, had planned for after coming back from work.
Will test now.

**Comment by VishalNehra** [comment]
>Remember to release as beta for FDroid too

I don't know how to release as beta on FDroid. Tried in past, there's no concrete guide, so didn't succeed. See [here](https://github.com/TeamAmaze/AmazeFileManager/issues/1082#issuecomment-370564203)

**Comment by EmmanuelMess** [comment]
Sorry, nevermind then.

**Comment by sid32** [comment]
Think its time to release the beta to the Play Store and have the testers weigh in.

**Comment by VishalNehra** [comment]
I get database downgrade fc in building release3.3.0 branch. Did you not pull #1262 to the branch @EmmanuelMess ?

**Comment by EmmanuelMess** [comment]
> I get database downgrade fc in building release3.3.0 branch. Did you not pull #1262 to the branch @EmmanuelMess ? I think we approved in the PR to merge to 3.3.0 release.

Has milestone 3.4.0.

**Comment by VishalNehra** [comment]
Maybe we forgot to change milestone. See comments there.

**Comment by EmmanuelMess** [comment]
[You said](https://github.com/TeamAmaze/AmazeFileManager/pull/1262#issuecomment-397741213):

> @EmmanuelMess please add commits to this PR, I think we can push this with v3.3.0 so let's not wait over these things.

And nobody answered (sorry, didn't see the comment).

**Comment by VishalNehra** [comment]
So now you see it, please merge it to release 3.3.0 branch.

**Comment by EmmanuelMess** [comment]
No, it is a feature, if you want a fix from in there, I can make a specific PR.

**Comment by VishalNehra** [comment]
But we did agree for that feature to be shipped with v3.3.0

**Comment by EmmanuelMess** [comment]
> But we did agree for that feature to be shipped with v3.3.0

Where? As I tell you I only saw:

> @EmmanuelMess please add commits to this PR, I think we can push this with v3.3.0 so let's not wait over these things.

"I think we can push this with v3.3.0 so let's not wait over these things." is not anyone but you agreeing to ship the feature with 3.3.0.

**Comment by EmmanuelMess** [comment]
@VishalNehra you created a tag for rc1? Won't that trigger an FDroid build?

**Comment by EmmanuelMess** [comment]
Is there some way to get notified when a milestone's deadline changes?

**Comment by VishalNehra** [comment]
Not sure... Might as well create new ones from next time.
