### ISSUE TITLE
SSH support

### ISSUE THREAD

**Issue by Astuceman** [TeamAmaze/AmazeFileManager#1321]
Hi

I really wish to switch to Amaze but I need to get SSH support (I'm using a nas to store my data)
I'm willing to pay like I have done with Es File Explorer Pro

I'm concerned with privacy that's why i'm here

**Comment by EmmanuelMess** [comment]
Wait for release 3.3.0.

**Comment by Limero** [comment]
If you don't want to wait, join the beta program and get the release candidate. https://play.google.com/apps/testing/com.amaze.filemanager

**Comment by Astuceman** [comment]
👍
Thanks
