### ISSUE TITLE
Bug: Directories are treated as files SFTP

### ISSUE THREAD

**Issue by Limero** [TeamAmaze/AmazeFileManager#1330]
With the new SFTP feature, when connected to a server, some directories are incorrectly treated as files, prompting them to be downloaded when clicked instead of opened.

Version: v3.3.0RC1

This is the root of my server. Nothing here should be files, it's all directories.
![screenshot_amaze_20180702-074135](https://user-images.githubusercontent.com/639787/42149131-43a2481c-7dd5-11e8-8cc7-6a2634ff72f6.png)

**Comment by TranceLove** [comment]
May I know what OS your SSH server is running on? I used to test with OpenSSH running on Ubuntu which had been working fine.

**Comment by Limero** [comment]
My server is running Fedora Atomic Host.

**Comment by TranceLove** [comment]
OK, got it, directory symlinks were identified as files. Let me work on it after sunrise.
