### ISSUE TITLE
Feature: Default path for SFTP connection

### ISSUE THREAD

**Issue by Limero** [TeamAmaze/AmazeFileManager#1331]
It would be fantastic if it was possible to set the default path for a SFTP connection. Right now when I connect to my server I am put in the root / and have to manually go to the directory that I want to browse.

This feature would allow a connection to default to directories other than /, such as always going to the home directory.

**Comment by VishalNehra** [comment]
I feel this is already been requested in some other issue, and is a duplicate 🤔
