### ISSUE TITLE
FTP Server don't start

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1337]
FTP server is not getting started. I can reproduce on my device, also [reported by a beta tester](https://plus.google.com/+VishalNehra/posts/2KzfRZ3GHqM) on G+
Will post logs later.

**Comment by sid32** [comment]
Also, would be nice if we could write to device over FTP. Solid Explorer lets you do that.

**Comment by wired2051** [comment]
I also can't start FTP Server anymore - and it definitely worked. 
Device: Huawei P9 lite, Android 7.0, EMUI 5.0.1

**Comment by EmmanuelMess** [comment]
@VishalNehra, or anyone experiencing the issue, please post logs.

**Comment by wired2051** [comment]
> please post logs

I'd be glad to but tell me how.

**Comment by EmmanuelMess** [comment]
[This](https://play.google.com/store/apps/details?id=com.dp.logcatapp) logcat reader would seem good enough, please post logs from Amaze as text here.

**Comment by VishalNehra** [comment]
I think this can be closed for now.

**Comment by sid32** [comment]
> I think this can be closed for now.

FTP works in latest builds, but those of us who use Tasker/Macrodroid need you to publish updated Intents instructions for us to start the FTP with Intents in Oreo.

**Comment by wired2051** [comment]
For me it still doesn't work. I use Amaze 3.2.2 (latest version for Android 7 in F-Droid). My phone is a Huawei P9 lite working with Android 7.0, EMUI 5.0.4 (non-rooted).

I don't know what Tasker/Macrodroid means.

**Comment by VishalNehra** [comment]
@sid32 I think intents are still the same. @TranceLove can you please confirm if you changed the intents?

**Comment by VishalNehra** [comment]
@wired2051 the latest builds are not on fdroid. You can try them by signing up on play store beta program.

**Comment by sid32** [comment]
Im using the same intents as before and while the FTP now works in Orero, my intents do not start it. I think I might need to add the Package and Class intent properties, but I don't know what they are.
