### ISSUE TITLE
Bug: "Insufficient space" error can occur when moving local files

### ISSUE THREAD

**Issue by Limero** [TeamAmaze/AmazeFileManager#1345]
The function for calculating space needed for a move does not take in to account the space available when the move is done.

For example, if we have a device with 1GB of available storage space, then it's not possible to move any file/directory bigger than 1GB around the local file system.

Versions affected: v3.2.2, v3.3.0RC1 and most likely, previous versions.

**Comment by VishalNehra** [comment]
Will look into it.

**Comment by VishalNehra** [comment]
Duplicate to #895
