### ISSUE TITLE
SFTP connection doesn't save passwords with hyphen (-) in them

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1370]
My SFTP username contains a hyphen in it's password, same password for SMB but there it does get saved to the database.
Please have a look at screenshots below
![screenshot_amaze_20180719-020539](https://user-images.githubusercontent.com/5211568/42923701-8ef94686-8b44-11e8-91e2-fc944ef581a3.png)
![screenshot_amaze_20180719-020627](https://user-images.githubusercontent.com/5211568/42923702-8f2cc984-8b44-11e8-9931-6d5c0af47978.png)

**Comment by TranceLove** [comment]
Doesn't have a good idea on what happened... but see if #1371 works for you.
