### ISSUE TITLE
Can't creat or edit files or folder on root folder

### ISSUE THREAD

**Issue by frederiiiic** [TeamAmaze/AmazeFileManager#1376]
Hi there,

I'm using a FairPhone2 With FairPhone Open OS 18.03.01 / Android 6.0.1

I'm actually root on this terminal, and i tied to edit my build.prop with the app.

And unfortunatly when i edit the file with Amaze, it give me an error when saving, and the files didn't change. So i've tried to create files or folders on the root folder and it's not possible any times. Is that normal? Is there a way to desactivate that if it's a security restriction?

Anyway thanks for the job done, the app is very usefull.

**Comment by frederiiiic** [comment]
With some more reading and help, i've finally mounted rw myself with a terminal emulator the folder i wanted to edit.

And someone told me that the app used to do it in the past. So why did you drop that fonctionality?

**Comment by VishalNehra** [comment]
Issue with v3.3.0rc1?

**Comment by frederiiiic** [comment]
No, v3.2.2, installed from F-droid.

**Comment by VishalNehra** [comment]
No worries, the bug is present in v3.3.0RC1 and I'm working on a fix as we talk. 
But to try it early I suggest you sign-up to beta testing from Play Store and try v3.3.0RC2 when I comes out.

**Comment by frederiiiic** [comment]
I don't use the play Store, but i can test it with an .apk or something.

**Comment by frederiiiic** [comment]
Ok, Thanks a lot for your work :)

**Comment by EmmanuelMess** [comment]
> I don't use the play Store, but i can test it with an .apk or something.

There are apk's for all releases in the [releases](https://github.com/TeamAmaze/AmazeFileManager/releases) section, beware of bugs though.
