### ISSUE TITLE
Password protected zip files

### ISSUE THREAD

**Issue by lafriks** [TeamAmaze/AmazeFileManager#138]
I don't know how about other password types but at least aes256 password protected zip files are not working

**Comment by guyguy2** [comment]
Is this enhancement to open password protected zip files or to be able to zip them with a password or both?

**Comment by lafriks** [comment]
I would be interested at least in opening them

**Comment by IOI-655321** [comment]
Opening them is the main functionality I need.

Both would be even better but not essential.

**Comment by trymeouteh** [comment]
Please allow us to open, read and create password protected 7z files.

**Comment by EmmanuelMess** [comment]
> Please allow us to open, read and create password protected 7z files and zip files.

7z file creating would be better left to another app to deal with IMO.
