### ISSUE TITLE
Translations for "Internal storage"

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#1398]
With #1378 merged into `master`, we need translators help out translating "Internal storage" again.

**Comment by EmmanuelMess** [comment]
If we create an issue for every translation we are going to have a lot unsolvable issues...

**Comment by TranceLove** [comment]
Because this one is hitting the core, I hope this can remind people to help out filling the gap.

**Comment by EmmanuelMess** [comment]
Under current 'closing issues' conditions (issue fixed) you have created a virtually eternal issue.

---------------------------------------

With that said, I suppose translations for "Internal storage" can be posted here and I'll do my best to move them to the app.

**Comment by maverick74** [comment]
@EmmanuelMess in **pt** ( or pt-pt if you prefer) "internal storage" translates to "**Armazenamento Interno**"

**Comment by maverick74** [comment]
Would be good to have bug #1531 also taken into consideration

**Comment by EmmanuelMess** [comment]
Use transifex.

**Comment by maverick74** [comment]
@EmmanuelMess funny, i don't seem to be able to find the project there...

can you share a link or something?

**Comment by TranceLove** [comment]
> @EmmanuelMess funny, i don't seem to be able to find the project there...
> 
> can you share a link or something?

Try this: https://www.transifex.com/amaze/amaze-file-manager
