### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 8, Size: 3

### ISSUE THREAD

**Issue by manlevan** [TeamAmaze/AmazeFileManager#1402]
at java.util.ArrayList.get(ArrayList.java:437)
       at com.amaze.filemanager.adapters.glide.RecyclerPreloadModelProvider.getPreloadItems(RecyclerPreloadModelProvider.java:38)
       at com.bumptech.glide.ListPreloader.preload(ListPreloader.java:173)
       at com.bumptech.glide.ListPreloader.preload(ListPreloader.java:154)
       at com.bumptech.glide.ListPreloader.onScroll(ListPreloader.java:142)

**Comment by VishalNehra** [comment]
How can we reproduce? Is this in master or in beta on play store?

**Comment by hoverPaul** [comment]
I also could reproduce this error in master.
My reproduce scene is when I search sth
1.search keywords in search bar,if there will too much file to match;
2.search process is going on,then scroll the search results;

It will crash then exit amaza  exception

**Comment by pf4edward** [comment]
Reproducable when attempting to search for file you know is in a sub-directory:
0) Force Stop Amaze App using Android's App-Info. Remove Amaze App from Recent Apps menu.
1) Run Amaze and go to a folder with sub-folders.  Start with folder hierarchies that is accessible & RW'able using Amaze
2) Click the magnifying glass
3) Type in a partial name of file you KNOW is in a sub-folder.
4) It begins to search, then in a moment, the app FC's. Logcat records the java.lang.IndexOutOfBoundsException.

**Comment by pf4edward** [comment]
But then, you run Amaze and do a search for a file in folder you begin with.  The app does NOT FC!!

Search again for a file you KNOW is in a sub-folder, and it does not FC!!!
Hmmmm...

**Comment by VishalNehra** [comment]
do report again with crash logs if still an issue. You should easily get crash stacktrace in new version.
