### ISSUE TITLE
Read/Open password protected 7zip files

### ISSUE THREAD

**Issue by IOI-655321** [TeamAmaze/AmazeFileManager#1407]
I use 7zip files with encryption to store a few things and its handy to be able to access these on my phone.  Id love to move to open source amaze from Solid Explorer but this is a sticking point for me. 

Can support for these files be added?  Or am I missing something when trying to open them.

**Comment by EmmanuelMess** [comment]
Related #138

**Comment by IOI-655321** [comment]
Thanks

**Comment by trymeouteh** [comment]
Please allow us to open, read and create password protected 7z files.

**Comment by bowiechen** [comment]
I believe this is fixed in #1222 so this issue should be closed.

**Comment by EmmanuelMess** [comment]
> Unless its just me I still cant open encrypted files in amaze from Google play (on f-droid its not been updated in ages).

Until the next major release the feature won't be available, we are testing and fixing  bugs.

**Comment by EmmanuelMess** [comment]
> An encrypted .7z files isnt even recognised as a zip file, an encrypted .zip file shows as a zip file but does nothing when trying to open, using extract shows an error saying the file is corrupt (it isnt as i can open and extract it fine in solid explorer) doesnt even prompt me for a password which is probably why it fails.

Please open another issue and upload the file for us to replicate.
