### ISSUE TITLE
Cannot browse /data/data via FTP even though Settings > Advanced > Root Explorer is active

### ISSUE THREAD

**Issue by finefoot** [TeamAmaze/AmazeFileManager#1409]
I activated Settings > Advanced > Root Explorer and am able to browse /data/data just fine in the regular File Manager. However, the FTP Server doesn't work with this path. I am using FileZilla to connect to the server and no files or folders are listed.

Thank you very much in advance. :+1:

**Comment by EmmanuelMess** [comment]
Which Amaze version?

**Comment by emmi474** [comment]
> Did you try using 'Custom path' option and setting this path as root from FTP service options menu?

Yes, I tried with the default `/storage/emulated/0` as well as `/`, `/data` and `/data/data`. Neither of them worked.

**Comment by TranceLove** [comment]
Symptom verified on Oneplus One running Slim7 (7.1.2) with current master.

**Comment by VishalNehra** [comment]
Can you try this again with new root library @TranceLove

**Comment by TranceLove** [comment]
Seems a `SuFile` based FileSystem is inevitable.

**Comment by VishalNehra** [comment]
If this is too much work we can ship this later. We have higher priority for things like AESCrypt.

**Comment by TranceLove** [comment]
@VishalNehra I have implemented a prototype. libsu SuFile is just a drop in replacement to java.io.File, so it isn't hard as expected.

Need some more work like deciding whether to switch to this FileSystem implementation though. Also need to work out if robolectric test cases is even possible and resemble the real device. You know, GitHub CI's emulator simply won't allow us to root it 😌

Just stay tuned. I'm positive that this can hit the PR soon😏
