### ISSUE TITLE
Cannot rename file on OTG storage

### ISSUE THREAD

**Issue by trentcameron** [TeamAmaze/AmazeFileManager#1419]
Good Day,

When I attempt to rename a file located on a OTG connected drive, the app crashes.  However if I rename the same file on the local storage, then simply copy it over to the OTG connected storage with the changed name it works fine. (So the file's fine)

Android 6.0.1 using Amaze 3.2.2 (same issue on previous versions)

Cheers and much thanks,

**Comment by tryton-vanmeer** [comment]
I tested on the latest version (3.2.2) and on master. I can confirm this bug happens for me too. Currently working on debugging the issue and will create a PR if I solve it.
