### ISSUE TITLE
Back button issue 2

### ISSUE THREAD

**Issue by Aakash1217** [TeamAmaze/AmazeFileManager#1424]
If an image file is opened and then the back button is pressed to quit, this app **takes me to the gallery app** and then, by further pressing the back button 2 times or so, I am able to go the folder from where the image was opened. It is expected from it to **directly do that action**, **not via the gallery app**.

**Comment by EmmanuelMess** [comment]
So:
1. Press on image file
2. Gallery app opens
3. Back is pressed
4. Amaze reopens
5. Back pressed
6. Gallery app reopens
7. Press back a few times
8. Parent of image-containing-folder opens

Is that correct? Which Amaze and Android versions are you using? Which gallery app?

**Comment by Aakash1217** [comment]
No no. The sequence will be like:
1. Press on image file
2. Image opens in gallery app
3. Back button pressed
4. Gallery app home page opens **(instead of the image-containing-folder in the file manager)**
5. Back button pressed
6. Image-containing-folder in the file manager opens **(it should be open at the 4th step)**

**Comment by Aakash1217** [comment]
App version: **Beta 3.3.0RC1**
Device OS: **Android 6.0.1**
**Android stock gallery app**

**Comment by EmmanuelMess** [comment]
> Gallery app home page opens **(instead of the image-containing-folder in the file manager)**

This would be a problem with the gallery, you can show them the corresponding guidelines [here](https://developer.android.com/training/design-navigation/ancestral-temporal#between-apps).

**Comment by Aakash1217** [comment]
I was ok with the app version 3.3.2. Then why is it showing such misbehaviour in the beta version.

**Comment by EmmanuelMess** [comment]
It might be a gallery update...
