### ISSUE TITLE
Add more encryption methods

### ISSUE THREAD

**Issue by toxub23** [TeamAmaze/AmazeFileManager#1436]
It would be good if you added the possibility of encryption and decryption with other methods than AES, eg Twofish, Serpent, Blowfish. And it would be useful to have a secure delete function with overwrite and hex editor. For example, I often use the hex editor to edit various files and photos.

**Comment by VishalNehra** [comment]
Not enough manpower, maybe sometime in future.

**Comment by toxub23** [comment]
@VishalNehra Speaking of safe deleting files, I meant something like in #1368.
