### ISSUE TITLE
Copy and cut operation of files

### ISSUE THREAD

**Issue by HaydenHu** [TeamAmaze/AmazeFileManager#1442]
It is recommended that drag and drop files or folder operations be supported, like Solid Explorer.

**Comment by EmmanuelMess** [comment]
Drag and drop? That seems like it would be a bit counter intuitive in a list, what about google drive's lower bar.

**Comment by HaydenHu** [comment]
Both ES file browsers and Solid Explorer I've used support drag-and-drop operations, which are easy to use! Especially Amaze has two lists, which are very useful if you add drag-and-drop operations, as Solid Explorer does.

**Comment by VishnuSanal** [comment]
we have implemented this! :)
