### ISSUE TITLE
Gallery has not been updated since the image was deleted

### ISSUE THREAD

**Issue by RealMoMo** [TeamAmaze/AmazeFileManager#1445]
Android5.0
I use the following code.

MainFragment.java
line 785---809
  if (Build.VERSION.SDK_INT >= 19) {

                            path[0] = arg;

                            MediaScannerConnection.MediaScannerConnectionClient mediaScannerConnectionClient = new MediaScannerConnection.MediaScannerConnectionClient() {
                                @Override
                                public void onMediaScannerConnected() {

                                }

                                @Override
                                public void onScanCompleted(String path, Uri uri) {

                                    Log.d("SCAN completed", path);
                                }
                            };

                            if (mediaScannerConnection != null) {
                                mediaScannerConnection.disconnect();
                            }
                            mediaScannerConnection = new MediaScannerConnection(context, mediaScannerConnectionClient);
                            //FileUtils.scanFile(context, mediaScannerConnection, path);
                        } else {
                            FileUtils.scanFile(new File(arg), context);
                        }

**Comment by EmmanuelMess** [comment]
Could you explain what is the bug?
