### ISSUE TITLE
Unable to read & write files in the root directory

### ISSUE THREAD

**Issue by tumuyan** [TeamAmaze/AmazeFileManager#1447]
Root permission has been provided, but Unable to read and write files in the directory of /data/data/app_packagename (with permission -rw--------). 
Cannot  open and copy , Cannot display the md5/sha-256 information.

I also could not rename a file from quickAccessPref[1] (Recent)

**Comment by VishalNehra** [comment]
What version do you use. I reckon this has already been fixed so suggest you to wait for next beta.

**Comment by tumuyan** [comment]
>           What version do you use. I reckon this has already been fixed so suggest you to wait for next beta.
"3.3.0RC6" 
https://github.com/TeamAmaze/AmazeFileManager/releases/download/v.3.3.0-rc6/3.3.0RC6.apk

**Comment by VishalNehra** [comment]
Should be fixed by #1434
