### ISSUE TITLE
Device crashes when rotating while compressing some file

### ISSUE THREAD

**Issue by touficbatache** [TeamAmaze/AmazeFileManager#1449]
1. Compress a file that will take a bit time to complete (just so u can reproduce)
2. Rotate your device
The app will crash...

**Comment by EmmanuelMess** [comment]
Amaze version?

**Comment by touficbatache** [comment]
3.2.2

**Comment by touficbatache** [comment]
It also crashes when you open a zip archive and rotate the device while it's open..

**Comment by EmmanuelMess** [comment]
Wait for update or enrol for Amaze beta app in Google Play. And retest.

If you can provide logcat it would be very helpful in detecting if the issue has already been created (and maybe fixed).

**Comment by touficbatache** [comment]
Okay, I'll try to provide a logcat tomorrow...

**Comment by touficbatache** [comment]
I just installed the beta... I can't open an archive...

**Comment by VishalNehra** [comment]
@touficbatache may we ask what compression method did this archive use?

**Comment by touficbatache** [comment]
With Amaze version 3.2.2

**Comment by VishalNehra** [comment]
@touficbatache not amaze version, but the compression method of the archive. If you can't open archive that means Amaze doesn't support that compression format. I request you to try some other archive.

**Comment by touficbatache** [comment]
I made the archive with that version of Amaze..

**Comment by EmmanuelMess** [comment]
OK, crashing reported might have to do with the process restarting and the intent being null, but without logcat I can't know for certain. 

Not being able to open the compressed file in new version is bad, but might be another issue,  #1458.
