### ISSUE TITLE
The option to show the time of folders\files

### ISSUE THREAD

**Issue by AnonJump** [TeamAmaze/AmazeFileManager#1457]
I would like to see in the program an option that, when turned on, will display the time (hours and minutes) for the folder / file change. For example, similar is implemented in the Root Explorer.

Now in Amaze File Manager:
"Folder name"
Month, year

In the possible future:
"Folder name"
Month, year; time:minutes

**Comment by mk410gd** [comment]
@EmmanuelMess Can I take this issue?

**Comment by EmmanuelMess** [comment]
First I think we need to deal with the fact that there are two dates in the life of the folder, the creation time and the modification time (not taking into account metadata change dates here).

I think the user is more likely to think that the time shown is the creation date, how would the user know it's the modification time that's being shown?

**Comment by EmmanuelMess** [comment]
Related #1028

**Comment by mk410gd** [comment]
@EmmanuelMess I think that actual "Show last modified" in the Setttings could be divided into "Show last modified Date" and "Show last modified Time". "Show last modified Time" would be default set to OFF and the user could change it at any time.
So if we applied it, the user would know he set the modified time display.

**Comment by AnonJump** [comment]
I wonder if it is worth adding _seconds_ to the option (hours, time, seconds)?

**Comment by EmmanuelMess** [comment]
@mk410gd we can't rely on the user reading that specific settings message for to know that he is reading the modification time.

**Comment by EmmanuelMess** [comment]
@AnonJump when would adding seconds be useful?

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess I think the date and time shown for the files / folders, is obvious to most users. Modification time is used to apply everywhere and in similar applications.

I still think that we should explicitly declare that it is the modification date, and not creation date. But I am unsure if the extra "cloggedness" would really be necessary.

@TranceLove @VishalNehra what do you say?

**Comment by TranceLove** [comment]
> I still think that we should explicitly declare that it is the modification date, and not creation date. But I am unsure if the extra "cloggedness" would really be necessary.

With my computing experience with Windows and Linux (GNOME, Cinnamon) I'm used to read the datetime beside the file in file managers that it is the file's last modified time. Adding the limited screen sizes of the majority of Android devices, I don't think it's a good idea to explicitly state the datetime is the file's last modification time.

**Comment by Fireant666** [comment]
Of course users will know & understand that it's referring to the modification date. What a crock of shit to suggest otherwise.
