### ISSUE TITLE
When searching, hidden files are shown

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1467]
Hidden files are shown when searching, even if the settings option is disabled.

**Comment by EmmanuelMess** [comment]
I would recommend prioritizing #1466.

**Comment by sd1998** [comment]
@EmmanuelMess I would like to work on this.

**Comment by EmmanuelMess** [comment]
@sd1998 no one is assigned, you can send a PR, will check it ASAP. Thanks!

**Comment by VishnuSanal** [comment]
Greetings of the Day

Is this issue still open? Could you let me work on this issue?

Regards

**Comment by EmmanuelMess** [comment]
@VishnuSanal Yes you can work on it.

**Comment by VishnuSanal** [comment]
Hello @EmmanuelMess

I've finished working on it. Could you please specify to which branch should I commit & create a PR?

Thank You

**Comment by EmmanuelMess** [comment]
@VishnuSanal Good question, @VishalNehra this would be 3.5 or 3.6?

**Comment by VishalNehra** [comment]
You can point PR to release/3.6 @VishnuSanal

**Comment by VishnuSanal** [comment]
Hello @EmmanuelMess, I submitted a PR. But I'm getting a build-failure. I cannot understand why! Would you please help me...

**Comment by EmmanuelMess** [comment]
@VishnuSanal please talk about the PR on the PR :). Sent help.
