### ISSUE TITLE
Force close when decrypting a file.

### ISSUE THREAD

**Issue by mujeebulhasan** [TeamAmaze/AmazeFileManager#1480]
App Version 3.2.2
Running on custom rom without google play services.
I encrypted a file and uploaded it to cloud and deleted from internal storage.
Now when I downloaded the same file from cloud and tried to decypt it it show 'Amaze has stopped'.

**Comment by mujeebulhasan** [comment]
Logcat:

10-20 15:27:06.913 16996 16996 W System.err: javax.crypto.AEADBadTagException
10-20 15:27:06.913 16996 16996 W System.err:    at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
10-20 15:27:06.913 16996 16996 W System.err:    at javax.crypto.Cipher.doFinal(Cipher.java:1741)
10-20 15:27:06.914 16996 16996 W System.err:    at com.amaze.filemanager.utils.files.CryptUtil.aesDecryptPassword(CryptUtil.java:343)
10-20 15:27:06.914 16996 16996 W System.err:    at com.amaze.filemanager.utils.files.CryptUtil.decryptPassword(CryptUtil.java:611)
10-20 15:27:06.914 16996 16996 W System.err:    at com.amaze.filemanager.database.CryptHandler.getAllEntries(CryptHandler.java:133)
10-20 15:27:06.914 16996 16996 W System.err:    at com.amaze.filemanager.utils.files.EncryptDecryptUtils.findEncryptedEntry(EncryptDecryptUtils.java:143)
10-20 15:27:06.914 16996 16996 W System.err:    at com.amaze.filemanager.utils.files.EncryptDecryptUtils.decryptFile(EncryptDecryptUtils.java:71)
10-20 15:27:06.914 16996 16996 W System.err:    at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:202)
10-20 15:27:06.914 16996 16996 W System.err:    at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
10-20 15:27:06.914 16996 16996 W System.err:    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
10-20 15:27:06.914 16996 16996 W System.err:    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
10-20 15:27:06.914 16996 16996 W System.err:    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
10-20 15:27:06.914 16996 16996 W System.err:    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
10-20 15:27:06.914 16996 16996 W System.err:    at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
10-20 15:27:06.914 16996 16996 W System.err:    at android.widget.AdapterView.performItemClick(AdapterView.java:318)
10-20 15:27:06.914 16996 16996 W System.err:    at android.widget.AbsListView.performItemClick(AbsListView.java:1160)
10-20 15:27:06.914 16996 16996 W System.err:    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3129)
10-20 15:27:06.914 16996 16996 W System.err:    at android.widget.AbsListView$3.run(AbsListView.java:4044)
10-20 15:27:06.914 16996 16996 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
10-20 15:27:06.914 16996 16996 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
10-20 15:27:06.914 16996 16996 W System.err:    at android.os.Looper.loop(Looper.java:164)
10-20 15:27:06.914 16996 16996 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6499)
10-20 15:27:06.914 16996 16996 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
10-20 15:27:06.914 16996 16996 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
10-20 15:27:06.914 16996 16996 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-20 15:27:06.914 16996 16996 W System.err:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
10-20 15:27:06.914 16996 16996 W System.err: Caused by: android.security.KeyStoreException: Signature/MAC verification failed
10-20 15:27:06.914 16996 16996 W System.err:    at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
10-20 15:27:06.914 16996 16996 W System.err:    at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
10-20 15:27:06.914 16996 16996 W System.err:    at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
10-20 15:27:06.914 16996 16996 W System.err:    at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
10-20 15:27:06.914 16996 16996 W System.err:    ... 25 more
10-20 15:27:06.915 16996 16996 W System.err: com.amaze.filemanager.exceptions.CryptException
10-20 15:27:06.915 16996 16996 W System.err:    at com.amaze.filemanager.utils.files.CryptUtil.decryptPassword(CryptUtil.java:618)
10-20 15:27:06.915 16996 16996 W System.err:    at com.amaze.filemanager.database.CryptHandler.getAllEntries(CryptHandler.java:133)
10-20 15:27:06.915 16996 16996 W System.err:    at com.amaze.filemanager.utils.files.EncryptDecryptUtils.findEncryptedEntry(EncryptDecryptUtils.java:143)
10-20 15:27:06.915 16996 16996 W System.err:    at com.amaze.filemanager.utils.files.EncryptDecryptUtils.decryptFile(EncryptDecryptUtils.java:71)
10-20 15:27:06.915 16996 16996 W System.err:    at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:202)
10-20 15:27:06.915 16996 16996 W System.err:    at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
10-20 15:27:06.915 16996 16996 W System.err:    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
10-20 15:27:06.916 16996 16996 W System.err:    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
10-20 15:27:06.916 16996 16996 W System.err:    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
10-20 15:27:06.916 16996 16996 W System.err:    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
10-20 15:27:06.916 16996 16996 W System.err:    at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
10-20 15:27:06.916 16996 16996 W System.err:    at android.widget.AdapterView.performItemClick(AdapterView.java:318)
10-20 15:27:06.916 16996 16996 W System.err:    at android.widget.AbsListView.performItemClick(AbsListView.java:1160)
10-20 15:27:06.916 16996 16996 W System.err:    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3129)
10-20 15:27:06.916 16996 16996 W System.err:    at android.widget.AbsListView$3.run(AbsListView.java:4044)
10-20 15:27:06.916 16996 16996 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
10-20 15:27:06.916 16996 16996 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
10-20 15:27:06.916 16996 16996 W System.err:    at android.os.Looper.loop(Looper.java:164)
10-20 15:27:06.916 16996 16996 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6499)
10-20 15:27:06.916 16996 16996 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
10-20 15:27:06.916 16996 16996 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
10-20 15:27:06.916 16996 16996 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-20 15:27:06.916 16996 16996 W System.err:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
10-20 15:27:07.250 16996 17029 D OpenGLRenderer: endAllActiveAnimators on 0x714fa35800 (MenuPopupWindow$MenuDropDownListView) with handle 0x71400ad1e0
10-20 15:27:07.341   711  2347 D audio_hw_primary: out_standby: enter: stream (0xf48a3800) usecase(1: low-latency-playback)

**Comment by VishalNehra** [comment]
This is not supported in current architecture. As soon as you remove the file you loose it's entry in database.
