### ISSUE TITLE
Improve handling of new-style OpenSSH key files

### ISSUE THREAD

**Issue by hvdijk** [TeamAmaze/AmazeFileManager#1485]
When using the new SFTP functionality (looking very nice, by the way!), when attempting to load a private key in the new-ish OpenSSH format (the type that begins with `-----BEGIN OPENSSH PRIVATE KEY-----`), the key will not load. A prompt is shown asking for a passphrase, but no matter what passphrase is entered, it will not be accepted.

This new private key format has been made the default as of OpenSSH 7.8, and as I created a new key for use on my phone, I inadvertently created one in this new format. I can understand that it may not be feasible to implement support for this format in a short time, but would it be possible to give a more useful error message?

**Comment by VishalNehra** [comment]
Exactly the problem I had. @TranceLove can you please give this a look.

**Comment by TranceLove** [comment]
According to https://github.com/hierynomus/sshj/issues/276, support is already there.

I'm also submitting a new PR with upgraded sshj and Espresso test to verify the behaviour.

**Comment by EmmanuelMess** [comment]
This should be fixed, test in next release candidate (next sunday) or by compiling
