### ISSUE TITLE
Back navigation breaks first item of Quick access lists

### ISSUE THREAD

**Issue by RigacciOrg** [TeamAmaze/AmazeFileManager#1496]
If you enable the **Back navigation** option, it happens that **the first item** of a **Quick access** lists (e.g the Images list, as in the attached image) is colored in gray and it behaves as back navigation instead of acting normally on the item itself.
Running Amaze version 3.2.2 from F-Droid, on Android Oreo 8.1.0.
![screen](https://user-images.githubusercontent.com/863803/47960315-6e966180-dff9-11e8-8cd4-c4214f4ec98b.png)

**Comment by EmmanuelMess** [comment]
It seems to work on master:

![screenshot_1541353111](https://user-images.githubusercontent.com/10991116/47967723-52b5ae80-e03f-11e8-8634-754e144ad265.png)
