### ISSUE TITLE
Still no shortcut generated?

### ISSUE THREAD

**Issue by RigacciOrg** [TeamAmaze/AmazeFileManager#1498]
It seems that I'm affected by #771, despite running Amaze 3.2.2 from F-Droid. I press the menu item "Add Shortcut", but nothing happen. I'm running Android One Oreo 8.1.0 (Xiaomi Mi A1), using Launcher3.
What can I do to help debugging?

**Comment by themangosteen** [comment]
On Android 11 on Moto G30 it is not working. Is that expected?
