### ISSUE TITLE
Encrypted File Cannot be Decrypted

### ISSUE THREAD

**Issue by QaziAbeelQureshi** [TeamAmaze/AmazeFileManager#1506]
Encryption works fine..
when i try to decrypt it doesn't  show me any error but in background it continuously tries to decrypt file.
but no further progress. 
Do anyone Else have this issue.

**Comment by utack** [comment]
Yes i have that issue. Why did you close it,did you find a solution?

**Comment by VishalNehra** [comment]
What version of Amaze do you use? @utack

**Comment by QaziAbeelQureshi** [comment]
For Me Its Working Now. !!!

**Comment by utack** [comment]
Sorry for not getting back to you sooner  
3.3.2 from F-Droid  
I think a single 2GB file is just too large to handle for a phone
