### ISSUE TITLE
Beginner Student

### ISSUE THREAD

**Issue by MrCrazy1376** [TeamAmaze/AmazeFileManager#1512]
Hello 
Thanks for good open source project
my question is how can i import or open this project in my android studio and edit it?

sorry for my simple question

**Comment by Adyel** [comment]
Goto to the folder where you want to save the project. Open your terminal /git and type 
`git clone https://github.com/TeamAmaze/AmazeFileManager.git`

**Comment by MrCrazy1376** [comment]
> Goto to the folder where you want to save the project. Open your terminal / git console and type
> `git clone https://github.com/TeamAmaze/AmazeFileManager.git`
> 
> Then open android studio > Import Project > Goto to the folder where you downloaded the project > select `build.gradle` > sync the gradle build.
> 
> Also, you can google "How to import gradle project in Android Studio"

thank you very much
