### ISSUE TITLE
Cannot create folder with certain name

### ISSUE THREAD

**Issue by reddeadbread** [TeamAmaze/AmazeFileManager#1522]
#### Describe the bug
While trying to create a folder with the same name as current folder, it fails and shows a toast with 'invalid name'.

#### Context
* Device: Xiaomi MI 6
* OS Version: Android 8.0.0
* App version: 3.3.0

#### How to reproduce

1. Open a folder
2. Click on '+' buttton
3. Click on 'folder'
4. Enter with the same name as current folder
5. Click 'Create'
6. It shows 'Invalid name'

#### Expected behavior
The folder should be created.

**Comment by TranceLove** [comment]
Verified the same symptom on LG Nexus 5x running stock firmware (8.1.0). Working on it.
