### ISSUE TITLE
How to check if write access on SD Card is granted

### ISSUE THREAD

**Issue by jalalaghazadeh** [TeamAmaze/AmazeFileManager#1540]
first of all, thank you for your awesome opensource file-manager which I learnt a lot from it.

I was trying to figure out how you check if write access permission to SD Card is granted or not before each action on SD Card contents. I have used your ` isWritableNormalOrSaf(final File folder, Context c)` from fileUtils but it didn't work and every time for example I try to delete a file from SD Card I have to go through all process of granting write access permission for SD Card. 

Would you explain how to did that in your app?

**Comment by EmmanuelMess** [comment]
Maybe @VishalNehra should answer.

**Comment by yxo-6o6uka** [comment]
Fwiw, i noticed a small file with a "techno" looking name is created before say a copy operation. This seems to be that test, perhaps not trusting a library call. If copy fails that test file is left behind.

**Comment by VishalNehra** [comment]
@jalalaghazadeh 
I didn't implement it, it was implemented by @arpitkh96 
But my guess is, the permission uri is being saved in the preferences. You can notice it after you grant permission for first time and manually open Amaze preferences. I can't pinpoint the code in source currently. Maybe will do later when I'm free.
