### ISSUE TITLE
Google Billing Permission (F-Droid)

### ISSUE THREAD

**Issue by Avispa** [TeamAmaze/AmazeFileManager#1542]
Noticed that from version 3.2.3 to 3.3.1 (F-Droid) Google billing permission was added. Since I banned Google stuff from my phone (and living with the obvious draw backs in convenience because of that) I even wonder more what it is needed for because it annihilates this decision somehow. Though I further wonder if there would by an option to remove it again and archive -- whatever it is needed for -- in another way.

Side question: where can I find changelog since I cannot even tell what has changed between the two versions and makes it kinda non-transparent in general. :/ (Maybe worth another topic?)

Thanks in advance as well as for the nice app in general

**Comment by VishalNehra** [comment]
Please refer to #1507 
As you can see, this is a non profit project and we work only in our free time. We can't find time to sum up a changelog with work done in a span of around 1 year b/w release.
But you can always read releases page and all the commit titles to get an idea of what was changed.
If any doubts, can reopen this and we shall discuss.
