### ISSUE TITLE
Epic fail

### ISSUE THREAD

**Issue by Fireant666** [TeamAmaze/AmazeFileManager#1545]
Settings options are wrong – Amaze is incapable of displaying the number of items in a folder; nor is it capable of displaying the date/time files were last modified.

**Comment by EmmanuelMess** [comment]
> Amaze is incapable of displaying the number of items in a folder

It can display it on top, under the path, when you open the directory.

> nor is it capable of displaying the date/time files were last modified.

Next version will always display the time. Date is displayed under the folder name.

If you still can't find these elements, do answer with Android version, Amaze version and a screenshot.

**Comment by bowiechen** [comment]
Closed since there were no responses from the user.
