### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LivingInfinite** [TeamAmaze/AmazeFileManager#1551]
Nexus 5, app version 3.3.2

> 12-21 15:11:56.969 29892-29892/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.amaze.filemanager, PID: 29892
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>         at android.app.ActivityThread.-wrap11(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.app.ActivityThread.main(ActivityThread.java:5417)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>      Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
>         at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:586)
>         at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:350)
>         at android.app.Activity.performCreate(Activity.java:6251)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:148) 
>         at android.app.ActivityThread.main(ActivityThread.java:5417) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by nazar-pc** [comment]
Same here, Nexus 6P, Lineage OS 15.1
Stopped working after update to 3.3.1 I think.
i'm installing it from F-Droid.

**Comment by nazar-pc** [comment]
We both are using 3.3.2 on different versions of Android and both have crashes.
I also had customized colors, but can't tell you which exactly, since app is not working for months for me.

**Comment by LivingInfinite** [comment]
Yes I believe I customized the colors as well.  
I uninstalled the app and re-installed. No crash anymore. 

Might want to look into changing the color prefs on an older version then updating to 3.3.X and see if you can reproduce.

**Comment by nazar-pc** [comment]
OK, I've got tired suffering without proper file manager and digged deeper with the help of Titanium Backup and manual tweaking of data backup.
Turns out, in my case there were 2 records in `utilities.db` file in `smb` table. Not sure why I had 2 records with the same name, since I'm pretty sure I removed one of them before.
Anyway, if I remove both of them and restore patched backup, everything works fine. If I only remove only one of those records - app crashes.

Re-added SMB connection after mentioned manipulations and it works again.

**Comment by Avispa** [comment]
Same here: crashes on first start but is fine on "second" start. If I didn't use it for a while it's like the "first" start again and crashes right away.

__Phone:__ *Samsung Galaxy S5*
__Version:__ Amaze 3.3.2 (f-droid) -- I guess, but not sure, **no** customised colours. (Maybe I had a look once but switched back to defaults.)

**Comment by Avispa** [comment]
I've checked:
* **No** customized colours
* Re-install (to reset settings) doesn't help in my case

#### What I forgot to mention before
Issue got introduced by version _3.3.2_ or maybe even _3.3.1_ (from F-Droid). However prior versions didn't have this bug.

**Comment by VishalNehra** [comment]
Can test with v3.5.0 guys? 
@Avispa

**Comment by nazar-pc** [comment]
I no longer have this app installed, sorry
