### ISSUE TITLE
Observe changes in directory

### ISSUE THREAD

**Issue by cofork** [TeamAmaze/AmazeFileManager#1563]
Android provides API to know changes in specific directory using `inotify`.
https://developer.android.com/reference/android/os/FileObserver

I think that it is useful if I can know added or deleted file while viewing file list.
This is the situation that to be consdered:
Open Download directory and download files on web browser with this app running in background.

**Comment by EmmanuelMess** [comment]
We already use this, AFAIK I had to develop a hack for Marshmallow.

**Comment by VishalNehra** [comment]
Why reopen? We implemented this already, didn't we.
