### ISSUE TITLE
Bookmark Issues

### ISSUE THREAD

**Issue by locke-d** [TeamAmaze/AmazeFileManager#1578]
Version 3.3.2 from fdroid. 

Adding a bookmark to the 2nd path, from the file menu, causes the app to crash out, if the first path already is bookmarked
1st Path: /data
2nd Path: /data/data

Bookmarks fail to open to path with the following :
Path: data/data/com.termux/file
Error: Bookmark not found, recreating...

**Comment by VishalNehra** [comment]
Not reproducible anymore on 3.6.1. Closing.
