### ISSUE TITLE
attr/fabSize and error: resource previously defined here

### ISSUE THREAD

**Issue by hamzadomain** [TeamAmaze/AmazeFileManager#1579]
error: duplicate value for resource 'attr/fabSize' with config ''.
error: resource previously defined here.

`<jahirfiquitiva.libs.fabsmenu.FABsMenuLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    fab:fabs_menu_overlayColor="#00000000"
    fab:fabs_menu_clickableOverlay="true"
    tools:layout_behavior="@string/fabs_menu_layout_behavior">

    
    <jahirfiquitiva.libs.fabsmenu.FABsMenu
        android:id="@+id/FABs_Menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:clipChildren="false"
        fab:fab_moreButtonPlusIcon="@drawable/ic_add_white_24dp"
        fab:fab_menuMargins="16dp"
        fab:fab_moreButtonSize="normal"
        fab:fab_labelsPosition="left"
        fab:fab_expandDirection="up">

        
        <jahirfiquitiva.libs.fabsmenu.TitleFAB
            android:id="@+id/menu_new_folder"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:srcCompat="@drawable/folder_fab"
            fab:fabSize="mini"
            fab:fab_title="@string/folder"/>

        <jahirfiquitiva.libs.fabsmenu.TitleFAB
            android:id="@+id/menu_new_file"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:srcCompat="@drawable/ic_insert_drive_file_white_48dp"
            fab:fabSize="mini"
            fab:fab_title="@string/file"/>

        <jahirfiquitiva.libs.fabsmenu.TitleFAB
            android:id="@+id/menu_new_cloud"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:srcCompat="@drawable/ic_cloud_white_24dp"
            fab:fabSize="mini"
            fab:fab_title="@string/cloud_connection"/>
    </jahirfiquitiva.libs.fabsmenu.FABsMenu>

</jahirfiquitiva.libs.fabsmenu.FABsMenuLayout>`

`<resources>
    <attr name="popup" format="reference" />
    <attr name="toolbar_theme" format="reference" />
    <attr name="ripple_color" format="color" />

    <declare-styleable name="Indicator">
        <attr name="dotDiameter" format="dimension" />
        <attr name="dotGap" format="dimension" />
        <attr name="animationDuration" format="integer" />
        <attr name="currentPageIndicatorColor" format="color" />
    </declare-styleable>
</resources>`

**Comment by EmmanuelMess** [comment]
Please explain what is you're trying to do.

**Comment by hamzadomain** [comment]
before update all gradl project and gradle module to last version
Now When bulid apk 
i have 2 message error
error: duplicate value for resource 'attr/fabSize' with config ''.
error: resource previously defined here.

**Comment by EmmanuelMess** [comment]
Can't help you with that, whoever updates gradle will have to deal with it.
