### ISSUE TITLE
long icon press shortcut

### ISSUE THREAD

**Issue by 532910** [TeamAmaze/AmazeFileManager#1586]
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

For example there may be "+" actions like New file or New folder.

**Comment by 532910** [comment]
Switched to https://github.com/zhanghai/MaterialFiles
Unsubscribing

**Comment by VishnuSanal** [comment]
> For example there may be "+" actions like New file or New folder.

IMO Quick Accesses or FTP Server & App Manager would be more useful...

**Comment by VishnuSanal** [comment]
I'd like to work on this issue. What should be the items?

**Comment by EmmanuelMess** [comment]
> I'd like to work on this issue. What should be the items?

No idea. @VishalNehra @TranceLove ?

**Comment by VishalNehra** [comment]
@EmmanuelMess Yea, I'd agree with @Vishnu_Sanal 's old comment. Basically things from left drawer. App manager, ftp server, recent files, quick access and top 3 bookmarks.

**Comment by VishnuSanal** [comment]
> Although the API currently supports a combination of up to five static and dynamic shortcuts for your app at any given time, we recommend that you publish only four distinct shortcuts to improve their visual appearance in the launcher.

From [best practices](https://developer.android.com/guide/topics/ui/shortcuts/best-practices). So, what should be the 4 items?
