### ISSUE TITLE
Amaze Crash if searching for .zip files

### ISSUE THREAD

**Issue by JaeTheHyena** [TeamAmaze/AmazeFileManager#1595]
When I'm in a folder and try to do a file search like ".mp3" to see all the MP3s, it works.
But if I try to search ".zip" the app just crashes.
I am running the version 3.3.0 on a Resurection Remix 7.0.0 S7 Edge.
Hope this issue will be fixed soon.
If you nees more logs or infos, I'll be glad to help.

**Comment by marcinadd** [comment]
I don't have this issue. Can you provide a log?

**Comment by JaeTheHyena** [comment]
@marcinadd sure, where can I find it/them for this app ?

**Comment by VishalNehra** [comment]
@JaeTheHyena don't worry, I'll extract the logs and put them here from Play console.

**Comment by JaeTheHyena** [comment]
Weird thing, the bug does not appears anymore and everything works perfectly now.
Sorry about that useless issue.
