### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by patelrithik** [TeamAmaze/AmazeFileManager#1597]
Android resource compilation failed
C:\Users\rishi\Downloads\AmazeFileManager-master\app\build\intermediates\incremental\mergeFdroidDebugResources\merged.dir\values\values.xml:5824: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
C:\Users\rishi\Downloads\AmazeFileManager-master\app\build\intermediates\incremental\mergeFdroidDebugResources\merged.dir\values\values.xml:5831: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
C:\Users\rishi\Downloads\AmazeFileManager-master\app\build\intermediates\incremental\mergeFdroidDebugResources\merged.dir\values\values.xml:10311: error: duplicate value for resource 'attr/fabSize' with config ''.
C:\Users\rishi\Downloads\AmazeFileManager-master\app\build\intermediates\incremental\mergeFdroidDebugResources\merged.dir\values\values.xml:10311: error: resource previously defined here.

**Comment by X-FAN** [comment]
Is this problem solved? I met the same issue.

**Comment by EmmanuelMess** [comment]
Don't update gradle. If you did reset changes or reclone.
