### ISSUE TITLE
Amaze cloud doesn't show up in Amaze File Manager

### ISSUE THREAD

**Issue by j-ed** [TeamAmaze/AmazeFileManager#1605]
I've just bought the **Amaze Cloud** app (v1.6) and opened it once but I couldn't find a cloud icon in the Amaze File Manager app (v3.3.2) afterwards. I also deleted the app data from my mobile phone (Galaxy S7) as recommended in https://github.com/TeamAmaze/AmazeFileManager/issues/551, but it still doesn't work.
Is the Amaze cloud integration broken or why doesn't it apoear in the File Manager menu?

**Comment by VishalNehra** [comment]
You can add cloud services from fab button (+ icon in bottom right). 
Also, no need to open Amaze cloud all the time. It was just one time setup.

**Comment by j-ed** [comment]
Awesome, that solved the problem. All of the screenshots in the play store are showing a cloud icon in the menu, so that I thought it wouldn't have been integrated into the app. The Amaze cloud app also doesn't give a hint where the new function can be found. I think it would be worse to improve the description prevent questions as mine 😉
