### ISSUE TITLE
根据busy.im/post/android-sdcard-write/处理后，每次重启设备都需要再申请权限

### ISSUE THREAD

**Issue by BraveMe** [TeamAmaze/AmazeFileManager#1608]
根据busy.im/post/android-sdcard-write/处理后，每次重启设备都需要再申请权限
请问如何只让App申请一次权限，后期不在需要申请。
没有理解saveTreeUri的作用，烦请解答 ，谢谢

**Comment by TranceLove** [comment]
虽然文章中有连结到我们的代码，但文章和你所指的 saveTreeUri()都不是我们写的，所以很抱歉，恕未能提供协助。

但无论如何，你提及的问题的确值得我们注意，尤其当 Android Q会引入 [scoped storage](https://developer.android.com/preview/privacy/scoped-storage)的概念；也催促着我们需要尽快在更多的地方从传统的 java.io.File改为使用 DocumentFile。谢谢。

To non-Chinese speaking fellows, here is the English version of the post in the question:
http://www.programmersought.com/article/5552552850/

The code in the post is not written by us, so we cannot provide support for that. However I too think the post is one of the alarms worth noticing, that we should migrate from `java.io.File` to `DocumentFile` as soon as we can.

**Comment by VishalNehra** [comment]
Thanks for the translation.
