### ISSUE TITLE
Option To Reuce Size of Action Bar

### ISSUE THREAD

**Issue by TheBrokenRail** [TeamAmaze/AmazeFileManager#1610]
***Normal***
![Screenshot_20190324-135400](https://user-images.githubusercontent.com/17478432/54883648-45f2f500-4e3e-11e9-935f-bcec8b8fdecd.jpg)
***Option Enabled***
![Screenshot_20190324-135400-edit](https://user-images.githubusercontent.com/17478432/54883653-54411100-4e3e-11e9-8300-9517c44f89f6.png)

**Comment by pjmkrpg** [comment]
Hi, why "Issue-WontFix" here?
There is indeed a lot of wasted space inside the top violet bar. Could we at least reduce the gap between the title (which, in my opinion, has no interest in being permanently displayed) and the path?
Thanks

**Comment by VishnuSanal** [comment]
hi! we've a collapsing action bar which would simulate the second screenshot, but without the icons. the icons along inside the collapsed action bar would look cluttered too.

**Comment by pjmkrpg** [comment]
I found it, thanks! It still think we could save some space here. Is there a simple way to reduce the gap in red?
![Screenshot_20221105-114923_Amaze](https://user-images.githubusercontent.com/22682674/200116705-475cca19-7e49-497e-b84a-e5d3877cf195.png)

**Comment by VishnuSanal** [comment]
> It still think we could save some space here. Is there a simple way to reduce the gap in red?

as of now, nope. as I mentioned above, the margins were given to make the UI look good & less cluttered. :)
