### ISSUE TITLE
 New Logo For Amaze File Manager

### ISSUE THREAD

**Issue by alexendre-maxim** [TeamAmaze/AmazeFileManager#1622]
Hi , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by mitchell-johnson** [comment]
Im not involved with the project but my suggestion would be go ahead and submit a PR with the new icon. if you dont know how to do that then someone can help there for sure.

**Comment by EmmanuelMess** [comment]
We already have a logo...
