### ISSUE TITLE
Can i upload this app on play store

### ISSUE THREAD

**Issue by abhinavojha9** [TeamAmaze/AmazeFileManager#1626]

**Comment by UnicornsOnLSD** [comment]
It's already on the Play Store?

**Comment by kenneth-Q** [comment]
What about f-droid
I think f-droid version should be update, right？😆

**Comment by UnicornsOnLSD** [comment]
@kenneth-Q the F-Droid version is just as up-to-date as the Play Store version

**Comment by kenneth-Q** [comment]
You are right
