### ISSUE TITLE
[AmazFileManager][v3.3.2]Can not unstall app from app manager

### ISSUE THREAD

**Issue by masudr4n4** [TeamAmaze/AmazeFileManager#1628]
<h4>Actual behavior</h4>
Nothing happening if i click unstall from app manager.
<h4>Expected behavior</h4>
Expected that i can unstall app from app manager.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>click navigation bar select "App manger"</li>
<li>choose any apps you installed from playstore or other plateform</li>
<li>Just click any trips you created</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:V3.3.2</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/­jtnE61e2rvU">https://youtu.be/­jtnE61e2rvU</a>

**Comment by masudr4n4** [comment]
cool but slow progress

**Comment by bowiechen** [comment]
Thanks for your patience and the bug report! We really appreciate it.
