### ISSUE TITLE
Crash on startup with NullPointerException on Tab.getOriginalPath

### ISSUE THREAD

**Issue by zhuowei** [TeamAmaze/AmazeFileManager#1632]
Amaze version: 3.3.2
Device: Nexus 6P (Android 8.1.0)

I was using the app manager, then after I closed the app I get a force close every time I try to reopen the application. The logcat shows:

```05-07 22:06:49.588 11095 11095 E AndroidRuntime: FATAL EXCEPTION: main
05-07 22:06:49.588 11095 11095 E AndroidRuntime: Process: com.amaze.filemanager, PID: 11095
05-07 22:06:49.588 11095 11095 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amaze.filemanager.database.models.Tab.getOriginalPath(boolean, android.content.SharedPreferences)' on a null object reference
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.amaze.filemanager.fragments.TabFragment.addTab(TabFragment.java:356)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.amaze.filemanager.fragments.TabFragment.onCreateView(TabFragment.java:140)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by asiongtobing** [comment]
05-07 22:06:49.588 11095 11095 E AndroidRuntime: Process: com.amaze.filemanager, PID: 11095
05-07 22:06:49.588 11095 11095 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amaze.filemanager.database.models.Tab.getOriginalPath(boolean, android.content.SharedPreferences)' on a null object reference
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.amaze.filemanager.fragments.TabFragment.addTab(TabFragment.java:356)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.amaze.filemanager.fragments.TabFragment.onCreateView(TabFragment.java:140)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-07 22:06:49.588 11095 11095 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mraklbrw** [comment]
I have a similar problem - the application closes with an error every time I start, after I have chosen the path "/" (I do not have root).
