### ISSUE TITLE
[Suggestion] SMBv3 support please

### ISSUE THREAD

**Issue by bluefiberbread** [TeamAmaze/AmazeFileManager#1633]
Amaze is currently stuck on SMBv1.

It'd be great if we could have support for the latest version of SMB

**Comment by TranceLove** [comment]
We will need to migrate to [smbj](https://github.com/hierynomus/smbj).

**Comment by maverick74** [comment]
Would like this as well

**Comment by Otiel** [comment]
Can you please confirm that there is no SMBv2 support as of today?
