### ISSUE TITLE
[IMPROVEMENT] File Copy operations

### ISSUE THREAD

**Issue by 0xlne** [TeamAmaze/AmazeFileManager#1636]
As a user, I noticed that operations on a large number of files are suboptimal.
In practice, Amaze creates a dummy file to which it copies the content of the original file, renaming it on completion. This approach means copy/move is much slower than when using unix operations

**Comment by VishalNehra** [comment]
Depends on which filesystem you're copying to. Internal to internal are
handled by NIO, without creation of any dummy file and have over 100 MB/s
speeds in general.
If you copy to SD Card , we need to create dummy file first to check for
permission. It is not renamed but deleted later after original files are
copied.
