### ISSUE TITLE
Amaze FingerPrint

### ISSUE THREAD

**Issue by ghost** [TeamAmaze/AmazeFileManager#1639]
FingerPrint is not working.

**Comment by TranceLove** [comment]
Please provide more detail on how it's not working, so we can try the same case on our devices.

Namely,
* the device you're using
* Android version, and best if you know the ROM you're using
* what were you doing (encrypting? decrypting?)
* what happened (crash? error dialog?)

**Comment by amanv4** [comment]
android version - 6
device - redmi note 3

when i lock app through your provided fingerprint lock then app it crash
