### ISSUE TITLE
Support .tar.gz, .tar.bz2 and .tar.xz archives

### ISSUE THREAD

**Issue by xmikos** [TeamAmaze/AmazeFileManager#164]
Please add support for .tar.gz, .tar.bz2 and .tar.xz archives. Also .tar (non-compressed one) seems to be supported, but _View_ is disabled, I can only _Extract_ it. Please also enable _View_ (for both .tar and compressed variants like .tar.gz, .tar.bz2 and .tar.xz).

**Comment by wb9688** [comment]
It can be done with commons-compress...

**Comment by EmmanuelMess** [comment]
Please provide files to test with.

**Comment by TranceLove** [comment]
Should be fixed by #1606.
