### ISSUE TITLE
Cannot use an ssh key created with ssh-keygen.

### ISSUE THREAD

**Issue by vext01** [TeamAmaze/AmazeFileManager#1640]
Hi,

I created an ssh key using ssh-keygen from termux. I planned to use the key for an sftp connection, however amaze rejects my passphrase. I'm certain I've entered the correct passphrase. I even created another with a one character password to test.

Any ideas?

Thanks

**Comment by vext01** [comment]
Perhaps this is the same as #1354?

**Comment by TranceLove** [comment]
Not exactly the same problem, but it IS a bug.

I suppose your key generated by `ssh-keygen` is of type `ed25519`? I could verify the symptom on Oneplus Two running Slim7 (7.1.2), against Linux Mint 19.1 (based on Ubuntu Bionic) too, while type `rsa` could pass the check.

Steps to reproduce
1. `ssh-keygen -t ed25519`
2. Enter passphrase when prompted
3. Place generated `id_rsa` to device
4. Place contents of `id_rsa.pub` to server's `authorized_keys`
5. Create Cloud connection in Amaze
6. Choose SCP/SFTP connection
7. Enter hostname, username for connecting server
8. Press `SSH Private Key` button
9. Choose the `id_rsa` placed on device in 3
10. Enter passphrase as necessary
11. Press create
12. Verify host signature in dialog
13. Toast popped up saying unable to login

**Comment by TranceLove** [comment]
sshj 0.27.0 supports ed25519 keys, but it requires bouncycastle 1.60, which we will have difficulty integrating them, as SpongyCastle (the BouncyCastle we have been using to prevent conflicts) stopped updating at 1.58.

On the other hand, I also tried to use sshj to authenticate with SSH server using ed25519 keys alone in desktop JVM, but still couldn't make it work. Before getting things clear, I think I will need more time fixing this issue, so I think this should happen after 3.3.3 milestone.

**Comment by TranceLove** [comment]
With Amaze now uses BouncyCastle (#1881), ED25519 authentication should be working - I'm using it too now. Please try the latest 3.5 series to see how it's work for you.

Closing.
