### ISSUE TITLE
Smb links are unsuccessful

### ISSUE THREAD

**Issue by wanglefeifei** [TeamAmaze/AmazeFileManager#1653]
https://github.com/wanglefeifei/react-native-demo/blob/master/20190724160004.jpg

**Comment by wanglefeifei** [comment]
You can't always search for devices, but ES can.

**Comment by EmmanuelMess** [comment]
Can you provide the link?

**Comment by wanglefeifei** [comment]
> Can you provide the link?

waht link?

**Comment by TranceLove** [comment]
I think he means SMB auto discovery was not successful?

**Comment by wanglefeifei** [comment]
> I think he means SMB auto discovery was not successful?

yes,Did you meet too?

**Comment by TranceLove** [comment]
Should have been. But I usually enter the IP address on my own, so not a big problem for me.

**Comment by wanglefeifei** [comment]
> Should have been. But I usually enter the IP address on my own, so not a big problem for me.

Why can't I play the video six minutes after I connect to smb?

**Comment by wanglefeifei** [comment]
> Should have been. But I usually enter the IP address on my own, so not a big problem for me.

Hey, is my brother still there?

**Comment by TranceLove** [comment]
> > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> 
> Why can't I play the video six minutes after I connect to smb?

Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...

BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.

**Comment by wanglefeifei** [comment]
> Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> 
> BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.

The SMB link was successful and the video was played for 6 minutes. It will disconnect automatically.

**Comment by wanglefeifei** [comment]
> > > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> > 
> > 
> > Why can't I play the video six minutes after I connect to smb?
> 
> Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> 
> BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.

Have you ever been in this situation?

**Comment by TranceLove** [comment]
> > > > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> > > 
> > > 
> > > Why can't I play the video six minutes after I connect to smb?
> > 
> > 
> > Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> > BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.
> 
> Have you ever been in this situation?

Never been doing this (I use Amaze mainly on retrieving files over SSH instead), but let's check.

**Comment by wanglefeifei** [comment]
> > > > > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> > > > 
> > > > 
> > > > Why can't I play the video six minutes after I connect to smb?
> > > 
> > > 
> > > Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> > > BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.
> > 
> > 
> > Have you ever been in this situation?
> 
> Never been doing this (I use Amaze mainly on retrieving files over SSH instead), but let's check.

Have you encountered this problem?

**Comment by EmmanuelMess** [comment]
I'll close this as it is dupe of #1654
