### ISSUE TITLE
FATAL EXCEPTION:java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by WangGuox1n** [TeamAmaze/AmazeFileManager#1661]
I'm using version 3.3.2, when testing the app, there is an exception :

**STACK_TRACE**
```
E/AndroidRuntime( 6141): FATAL EXCEPTION: main
E/AndroidRuntime( 6141): Process: com.amaze.filemanager, PID: 6141
E/AndroidRuntime( 6141): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime( 6141): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime( 6141): 	at java.util.ArrayList.get(ArrayList.java:308)
E/AndroidRuntime( 6141): 	at com.amaze.filemanager.asynchronous.asynctasks.DeleteTask.onPostExecute(DeleteTask.java:175)
E/AndroidRuntime( 6141): 	at com.amaze.filemanager.asynchronous.asynctasks.DeleteTask.onPostExecute(DeleteTask.java:51)
E/AndroidRuntime( 6141): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime( 6141): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime( 6141): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime( 6141): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6141): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 6141): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 6141): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6141): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6141): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 6141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 6141): 	at dalvik.system.NativeStart.main(Native Method)
```
is this a known issue? or  a new bug of AmazeFileManager?

**Comment by WangGuox1n** [comment]
Second Exception: 

**STACK_TRACE**= E/AndroidRuntime(16208): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime(16208): Process: com.amaze.filemanager, PID: 16208
E/AndroidRuntime(16208): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(16208): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(16208): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(16208): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(16208): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(16208): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(16208): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(16208): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(16208): Caused by: java.lang.NullPointerException
E/AndroidRuntime(16208): 	at com.amaze.filemanager.filesystem.MediaStoreHack.getTemporaryAlbumId(MediaStoreHack.java:148)
E/AndroidRuntime(16208): 	at com.amaze.filemanager.filesystem.MediaStoreHack.mkdir(MediaStoreHack.java:237)
E/AndroidRuntime(16208): 	at com.amaze.filemanager.filesystem.FileUtil.mkdir(FileUtil.java:513)
E/AndroidRuntime(16208): 	at com.amaze.filemanager.filesystem.Operations$1.doInBackground(Operations.java:170)
E/AndroidRuntime(16208): 	at com.amaze.filemanager.filesystem.Operations$1.doInBackground(Operations.java:84)
E/AndroidRuntime(16208): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(16208): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(16208): 	... 3 more

**Comment by VishalNehra** [comment]
When do you get this crash? Play store also reporting so many of these crashes.

**Comment by WangGuox1n** [comment]
Do you mean how I triggered this exception?  but I don't know the exact reproduce steps.






------------------ 原始邮件 ------------------
发件人: "Vishal Nehra"<notifications@github.com>;
发送时间: 2019年9月17日(星期二) 中午11:28
收件人: "TeamAmaze/AmazeFileManager"<AmazeFileManager@noreply.github.com>;
抄送: "王国新"<958804019@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TeamAmaze/AmazeFileManager] FATALEXCEPTION:java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0(#1661)




When do you get this crash? Play store also reporting so many of these crashes.

**Comment by bowiechen** [comment]
Closing this issue as steps to reproduce was not provided.

**Comment by anlalalu** [comment]
#1793 looks similar to one of these issues
