### ISSUE TITLE
Crash on starting FTP server on Android 9.0 when device is running as hotspot

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#1664]
Symptom found on LG Nexus 5x running AOSPExtended (9.0).

1. Switch off wifi
2. Switch on hotspot
3. Start Amaze
4. Open drawer
5. Tap FTP server
6. A toast saying "Error getting local inet address" popped up
7. Start FTP server
8. Amaze and FTP server crashed

Possibly reason is the behaviour change of `WifiManager` in Android Q causing problem getting hotspot's IP address (i.e. 192.168.43.1). More details to follow after getting the device back.

However, judging the scale of the changes required, I think the fix will happen past 3.3.3 release.

**Comment by bowiechen** [comment]
The same issue is reproducible on Android 10 (build QP1A.190711.019) on Google Pixel 2, no root.
