### ISSUE TITLE
Navigation drawer opens on Screen Rotation

### ISSUE THREAD

**Issue by bpsingh10** [TeamAmaze/AmazeFileManager#1676]
On screen rotation from portrait to landscape mode navigation drawer pop-up automatically. I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

The below image is in the portrait mode.

![Screenshot_2019-09-03-19-20-34-011_com amaze filemanager](https://user-images.githubusercontent.com/44584648/64181055-732edf00-ce83-11e9-80cf-4951f0dc54f5.png)

The below image is after screen rotation in Landscape mode where navigation drawer pop-up automatically. 

![Screenshot_2019-09-03-19-20-44-498_com amaze filemanager](https://user-images.githubusercontent.com/44584648/64181121-9194da80-ce83-11e9-9252-b6372e808b36.png)

**Comment by EmmanuelMess** [comment]
Not an issue.
