### ISSUE TITLE
'Cut' needs more visual cues

### ISSUE THREAD

**Issue by Wilker-a** [TeamAmaze/AmazeFileManager#1677]
hello \^-\^

in the current version (3.3.4), down to some older ones (current available stable release in F-Droid as of today), the 'cut' button for files has no effect at all upon clicking, it just deselect current selected items.

thank you for reading \^-\^

**Comment by VishalNehra** [comment]
That's how it's supposed to happen. You have to go to a destination directory and press on paste button. 
I confirm working as intended on 3.3.4

**Comment by Wilker-a** [comment]
i was about to say that no Paste button or similar is shown upon cutting, but it took me some time to find the button...

![the problem in action](https://user-images.githubusercontent.com/10854855/64300468-39c5a480-cf53-11e9-8159-d3d3a0fc4a5d.gif)

perhaps creating visual alerts (such as making the origin file have less opacity or keeping the toolbar grey whenever a file is in the clipboard) may solve further confusion? the paste button looks too subtle when put together with unrelated options, specially with no icon

in any case, thank you for the help \^\^

**Comment by VishalNehra** [comment]
Finally gonna get a fix here 😋

**Comment by VishalNehra** [comment]
Finally gonna get a fix here 😋

![Screenshot_20200712-044039](https://user-images.githubusercontent.com/5211568/87235756-04a0a300-c3fd-11ea-9605-c88e986ee11c.jpg)

**Comment by VishalNehra** [comment]
Finally gonna get a fix here 😋

![Screenshot_20200712-044118](https://user-images.githubusercontent.com/5211568/87235765-30238d80-c3fd-11ea-9edc-388d6a186a6c.jpg)

**Comment by VishalNehra** [comment]
Finally gonna get a fix here 😋

![Screenshot_20200712-044039](https://user-images.githubusercontent.com/5211568/87235775-4893a800-c3fd-11ea-8343-c38dc447bdea.jpg)

**Comment by Wilker-a** [comment]
seems good \^\^ minor improvement would be to make the purple "paste" text brighter or white and bold or something else to improve visibility in a dark environment such as this :3

**Comment by VishalNehra** [comment]
It's your lucky day, you wishes shall be granted @Wilker-a :P
