### ISSUE TITLE
Location of config file ?

### ISSUE THREAD

**Issue by bristow** [TeamAmaze/AmazeFileManager#1686]
Hi Amaze Team !

Little question...

Where is store the config file for Amaze (like cloud). I'd like to take it et push it on others devices ? Thanks for your work and don't forget F-droid :)

**Comment by VishalNehra** [comment]
You can't, amaze cloud is a paid software. You gotta purchase separately for other devices.

**Comment by bristow** [comment]
however, it doesn't seem to me that it is not charged for a samba connection...

**Comment by VishalNehra** [comment]
Config files are at `/data/app/com.amaze.filemanager/shared_preferences`
But you need root to copy them.
