### ISSUE TITLE
Remove static IV from codebase

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1692]
Play Store has recommended to remove static IV from our codebase. 
Please discuss here what other options are there.
Current proposed one is, we generate a random one and save it in preferences.

**Comment by EmmanuelMess** [comment]
What are static IVs?

**Comment by TranceLove** [comment]
@EmmanuelMess The Initialization Vector for file encrypt/decryption. At one point we thought of using build variables instead of hard coding the IV in source code

**Comment by asit-fdraschbacher** [comment]
I'd like to point out that this solution is still considered insecure. You need to generate a fresh IV for every encrypted file. Otherwise, an attacker is able to infer similarity between plain texts from comparing cipher texts.

**Comment by TranceLove** [comment]
@asit-fdraschbacher Yes, we are well aware of this vulnerability. Just we haven't prioritize it yet 🙇🏻‍♂
