### ISSUE TITLE
.mts video files do not display as video, how can I add to MIME-type?

### ISSUE THREAD

**Issue by ooyellow58** [TeamAmaze/AmazeFileManager#1696]

**Comment by bowiechen** [comment]
@ooyellow58 Can you share a valid *.mts file that we can test?

**Comment by TranceLove** [comment]
> @ooyellow58 Can you share a valid *.mts file that we can test?

Try this, available from [archive.org](https://archive.org/details/scm-10794-mtstestfile).

https://archive.org/download/scm-10794-mtstestfile/00007.mts
