### ISSUE TITLE
What's your plan for Android Q?

### ISSUE THREAD

**Issue by staltz** [TeamAmaze/AmazeFileManager#1700]
Hello fellow FOSS developer, I build the [Manyverse](https://github.com/staltz/manyverse) app which is also on F-Droid.

Have you heard of Google's schedule to deprecate shared external directories? [See this article](https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/).

Your app uses `Environment.getExternalStorageDirectory()` which Google is [deprecating in API level 29](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()).

https://github.com/TeamAmaze/AmazeFileManager/blob/7fccbd75715e9733c3298fbc9df84f35c7d1bf8a/app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java#L245

I think this is terrible news from Google, and I'd like to use `getExternalStorageDirectory()` too. This change in Android Q will affect all File Managers and significantly change the UX and possible features for users. I would like to know if you have any ideas what could be done.

**Comment by bowiechen** [comment]
Considering Google isn't enforcing mandatory use of Storage Access Framework until Android R, I'd say we have some more breathing room. We should look into utilizing SAF to gain filesystem access like [Solid Explorer has done](https://www.androidpolice.com/2019/07/28/solid-explorer-now-works-with-scoped-storage-on-android-q/).

**Comment by anderspitman** [comment]
@staltz have you made any progress on this? I'm planning an app that ideally should be able to read/write files/directories that are accessible from other apps. This really seems like a bad move on GOOG's part.

**Comment by anderspitman** [comment]
I've been doing more research the past couple hours. The entire Android storage ecosystem as it currently stands is mind-boggling. As far as I can tell, the best hope lies in the "all files access" (mentioned [here](https://developer.android.com/preview/privacy/storage#manage-device-storage), also discussed [here](https://medium.com/androiddevelopers/modern-user-storage-on-android-e9469e8624f9)) permission, which is coming in Android 11. I literally might wait to write my app until this is widespread.

**Comment by victorbnl** [comment]
I hate using libraires but Android storage is so messy I think it wouldn't hurt : https://github.com/anggrayudi/SimpleStorage

**Comment by EmmanuelMess** [comment]
We should probably maintain our own fork of it, at least for now if we are going to use that lib, for smb and sftp compatibility.

**Comment by TranceLove** [comment]
@victorbnl This looks cool BTW…may adopt this while writing the backend for the FTP server, if it needs to work across all generations of DocumentFile.

**Comment by TranceLove** [comment]
Looking closely at the library, SimpleStorage requires at least API 19, and also requires Kotlin. Additionally, it will also upgrades [Material Dialogs](https://github.com/afollestad/material-dialogs) which will break our code.

Sounds still a long way to go, when our codebase is still hybrid (Java+Kotlin).
