### ISSUE TITLE
Create issue and pull request templates

### ISSUE THREAD

**Issue by bowiechen** [TeamAmaze/AmazeFileManager#1713]
For the longevity of this app, I would like to create issue and PR templates for this repository. This helps the community report issues and push fixes more clearly and provide information in proper format for developers to parse through. 

Documentation on how to create said templates on GitHub can be found [here](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates).

I can handle this but I need more permissions in this repository.

**Comment by EmmanuelMess** [comment]
Template files can be pull requested.

**Comment by bowiechen** [comment]
Yeah, it is possible, but GitHub has [multiple issue templates](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates) that seems to be only editable to members of the repository.

**Comment by VishalNehra** [comment]
It's already done (:
