### ISSUE TITLE
Selection contextual toobar not dismissed when app is switched out and back to focus

### ISSUE THREAD

**Issue by bowiechen** [TeamAmaze/AmazeFileManager#1714]
**Expected behavior**

Contextual toobar should disappear when user switches app to background then to foreground.

**Actual behavior**

Selection contextual toobar is floating over the app UI that can be dismissed by pressing back.

**Steps to reproduce**

1. Select a file.
1. Switch app to background.
1. Switch Amaze back to foreground.

**Comment by pcsaunak** [comment]
I would like to work on this bug.

**Comment by VishalNehra** [comment]
@bowiechen suggest to keep the behivour instead. Consider user selects 15-20 items but before performing operation has to send a whatsapp message or something, when he comes back to Amaze all selection will be gone. 
@pcsaunak sorry I'm gonna have to reject the PR. I suggest you join our telegram group where we generally select bugs to solve  (:
https://t.me/joinchat/NNFgWxQUB8fFE3yCsC0w4g

Sorry again.

**Comment by pcsaunak** [comment]
Sure I will join the group.
