### ISSUE TITLE
Search treats result directories as files

### ISSUE THREAD

**Issue by bowiechen** [TeamAmaze/AmazeFileManager#1715]
**Expected behavior**

Tapping on the directory search results should open the directories. 

**Actual behavior**

The directory search results are treated as regular files. 

**Steps to reproduce**
1. Create a directory.
1. Search for the directory created. 
1. Tap on a result. 

**System info**
- Phone model: Google Pixel 2
- Android version: 10
- Rooted: No

**Comment by Soroyesodiq** [comment]
The current source code doesn't have this bug although the apk on the playstore still contain this bug. This should be solved when the apk on google play store is updated. So i think this issue should be closed.
