### ISSUE TITLE
When "Back Navigation" is enabled, the .. folder is shown as a search result

### ISSUE THREAD

**Issue by bowiechen** [TeamAmaze/AmazeFileManager#1716]
**Expected behavior**

When search results are populated, `..` folder (back navigation) should not be included in the list of results. 

**Actual behavior**

The `..` folder (back navigation) is shown as a search result.

**Steps to reproduce**
1. Go to "Settings" and enable "Back navigation" under "General" category.
1. Search for files. 

**System info**
- Phone model: Google Pixel 2
- Android version: 10
- Rooted: No

**Comment by Soroyesodiq** [comment]
I will like to work on this.
