### ISSUE TITLE
Is better to set secure FTP as default to procure a good security practice

### ISSUE THREAD

**Issue by albariko97** [TeamAmaze/AmazeFileManager#1779]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TranceLove** [comment]
It's always better to write at least some words to explain the legitimacy of your suggestion than simply submit an issue with an unmodified issue template.

#1780

**Comment by bowiechen** [comment]
@albariko97 can you expand on why you want this feature implemented?

**Comment by EmmanuelMess** [comment]
> @albariko97 can you expand on why you want this feature implemented?

Moved to new issue, this issue is closed.
