### ISSUE TITLE
Save As does not work on a file sent from OwnCloud

### ISSUE THREAD

**Issue by hman2** [TeamAmaze/AmazeFileManager#1782]
1 Open a folder in OwnCloud
2 Select a file.
2 From the three dots menu, select Send
3 select Save As (has Amaze icon!) -> Amaze gets opened
4 in Amaze I found no option to save the file. There is a red button with an arrow down, but it doesn't do anything, but to minimize Amaze, and you're back in OwnCloud.

Smartphone (please complete the following information):**
 - Device: Fairphone 2
 - OS: Android 7.1.2
 - Rooted: No
 - Version: 3.3.2

OwnCloud is version 2.13.1 (current). Sending files works with K-9...

**Comment by VishalNehra** [comment]
This should be fixed with 3.5.x beta program from play store. Please test and reopen if issue still there.
