### ISSUE TITLE
Some languages need to be in more than one file

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1790]
Okay, so this is an exception. Another being Yiddish language with yi, ji as language codes as per ISO standards.
It seems `id` is new and `in` is the old code and [android supports old code](https://stackoverflow.com/a/44336061/3168010) only. I made changes to the script in transifex, and according to their documentation [here](https://docs.transifex.com/transifex-github-integrations/github-tx-ui#linking-a-specific-project-with-a-github-repository), the language is one to one mapping, so it can't commit 2 files at a time.

We need testing for this though.
cc @zmni @bowiechen @EmmanuelMess

_Originally posted by @VishalNehra in https://github.com/TeamAmaze/AmazeFileManager/pull/1772#issuecomment-549163776_

**Comment by EmmanuelMess** [comment]
Sent an email to Transifex support, will be updating this thread when they respond.

_Originally posted by @EmmanuelMess in https://github.com/TeamAmaze/AmazeFileManager/pull/1772#issuecomment-549166349_

**Comment by EmmanuelMess** [comment]
@zmni @bowiechen @VishalNehra

Here's the situation:

> Hello Emmanuel,
> 
> Thank you for your response.
> 
> Please note that Transifex supports Indonesian (id). We cannot support
> different codes for the same language.
> More information about the standards we follow for the supported
> languages can be found in our documentation guide here:
> https://docs.transifex.com/faq/all#how-do-i-add-a-new-language [1]
> 
> In your case, you can add the other language (Indonesian) (id_ID),
> which is already supported by Transifex, and then map this to the
> language Indonesian (in) through the configuration file of Github
> Integration as it is described here [2] [language_mapping].
> 
> By default, Transifex uses ISO 639-1 language codes [3]. If you use
> language codes other than the standard ISO ones, the integration
> allows you to set up custom one-to-one language mappings. You'll just
> need to use something similar to the following configuration:
> 
> but in your case, you will need the following mapping instead:
> 
> language_mapping:
> id_ID: in
> 
> i.e 'TX CODE: 'Custom code'
> 
> I hope that the above helps.
> 
> If I can be of any further assistance, please let me know.
> 
> Regards,
> 
> 
> Links:
> ------
> [1] https://docs.transifex.com/faq/all#how-do-i-add-a-new-language
> [2]
> https://docs.transifex.com/transifex-github-integrations/github-tx-ui#linki=ng-a-specific-project-with-a-github-repository
> [3] http://www.loc.gov/standards/iso639-2/php/English_list.php
> 
> --
> Panagiotis Kavrakis
>  | Transifex [1]
> 
> Links:
> ------
> [1] https://www.transifex.com/

_Originally posted by @EmmanuelMess in https://github.com/TeamAmaze/AmazeFileManager/pull/1772#issuecomment-552874824_

**Comment by EmmanuelMess** [comment]
Can we create some sort of hard link to the in file/folder?

_Originally posted by @EmmanuelMess in https://github.com/TeamAmaze/AmazeFileManager/pull/1772#issuecomment-557910112_

**Comment by bowiechen** [comment]
I believe it is possible to have the build script move, copy, and rename files where necessary.
