### ISSUE TITLE
Search some text may cause crash

### ISSUE THREAD

**Issue by musicBoxes** [TeamAmaze/AmazeFileManager#1798]
To Reproduce
1. Go to a folder(not root)
2. Input a short string(such like "a") to search box
3. Search it(then crash...)

Crash occurs with high possibly when the input text is short(smaller than 3). I do not know the reason of this bug. It so weird.

**Comment by TranceLove** [comment]
Just went straight drop dead.

Relevant logcat entries
```
12-27 00:56:32.309  8664  8664 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
12-27 00:56:32.309  8664  8664 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
12-27 00:56:32.309  8664  8664 E AndroidRuntime: 	at com.amaze.filemanager.adapters.glide.RecyclerPreloadModelProvider.getPreloadItems(RecyclerPreloadModelProvider.java:36)
```

Index seems to be always out of result items array size (index is 3 or 4 when array size is 3).

**Comment by VishalNehra** [comment]
This is fixed. Please try 3.5.x series from google play beta program.
