### ISSUE TITLE
Amaze aborts when clicking on menu for last item in app manager

### ISSUE THREAD

**Issue by HtwoO** [TeamAmaze/AmazeFileManager#1800]
**Describe the bug**

Clicking on last item in app manager will make the app abort
I have experience this bug a few times, checked in Google play and I saw no new upgrade available.
One can work around this bug by changing the order of the app list and click on the item.

**To Reproduce**

Open the app,
click on the top right 3-horizontal-bar icon to open its global menu,
scroll down and click open app manager,
scroll down to the last page,
click on the 3-vertical-dot icon on the right,
Amaze aborts.

**Expected behavior**
It should popup a menu for the user to choose from "Open, Backup, ..."

**Screenshots**
N/A

**Smartphone:**
 - Device: [XiaoMi Mi6X]
 - OS: [Android 9]
 - Rooted: [No]
 - Version: [3.3.4]

**Additional context**
No

**Comment by TranceLove** [comment]
Confirmed the symptom on Android emulator running stock 9.0.

It seems pull #1801 that migrate to FloatingActionButtonSpeedDial will help fixing this too, as tested on Android emulator running stock 9.0.
