### ISSUE TITLE
Crash on ftp server start on recent commit with eventbus is merged

### ISSUE THREAD

**Issue by Bambooin** [TeamAmaze/AmazeFileManager#1805]
**Describe the bug**
Crash on ftp server start.

**To Reproduce**
1. Open Amaze
2. Click FTP Server
3. Amaze crash

**Smartphone (please complete the following information):**
 - Device: [Redmi]
 - OS: [Lineage OS 16.0]
 - Rooted: [No]
 - Version: [last commit build by myself]

**Additional context**
Logcat file was attached.
[log.txt](https://github.com/TeamAmaze/AmazeFileManager/files/4014796/log.txt)

**Comment by TranceLove** [comment]
Looks like related to proguard. Whenever I have `minifyEnabled true` in build.gradle, Amaze crashes on trying to access the FTP server functions.
