### ISSUE TITLE
Can't access /mnt when root browsing is enabled.

### ISSUE THREAD

**Issue by andreluisos** [TeamAmaze/AmazeFileManager#1807]
Most of the folders in the root directory becomes unaccessible when root browsing is enabled.

Before root access:
https://pasteboard.co/IOqsYTl.png

After root access (can't browse /mnt):
https://pasteboard.co/IOqtjAm.png
https://pasteboard.co/IOqtvXH.png

I'm using GenyMotion and I'm trying to give an specific app permissions to write on a mounted folder.

**Comment by TranceLove** [comment]
Didn't try Genymotion, but it is possibly due to the results of underlying shell command `ls` was incorrectly interpreted by Amaze.

See #1497

**Comment by VishalNehra** [comment]
If this is indeed the case, we can't take this up ATM with 3.5. Will take it up with 3.6.
