### ISSUE TITLE
Works on AndroidTV but could be better

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [TeamAmaze/AmazeFileManager#1827]
Hey there.

The good news, v3.4.2 works on my nvidia shieldTV (androidtv 9 | nvidia os v8.0.1).
The bad news, it is very difficult to see the current selected area.

It would be awesome if we could check if it is an firetv or androidtv device and then highlight more the selected areas. Otherwise a trigger could be DPAD control.

THX for your work. Nice to have an ES-FileExplorer alternative.

**Comment by bowiechen** [comment]
@sorryusernameisalreadytaken Could you perhaps attach some screenshots to demonstrate the selection area?

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> @sorryusernameisalreadytaken Could you perhaps attach some screenshots to demonstrate the selection area?

Sorry for the delay, no problem here are all my screens:
![screen01](https://user-images.githubusercontent.com/12913436/75610673-932e1b00-5b13-11ea-8f9c-01e139e33d6d.png)
![screen02](https://user-images.githubusercontent.com/12913436/75610677-975a3880-5b13-11ea-80c7-87dd53e4d8d1.png)
![screen03](https://user-images.githubusercontent.com/12913436/75610679-9aedbf80-5b13-11ea-92f7-42d2c5e3f544.png)
![screen04](https://user-images.githubusercontent.com/12913436/75610681-9de8b000-5b13-11ea-99fe-8fd655308f08.png)
![screen05](https://user-images.githubusercontent.com/12913436/75610682-a04b0a00-5b13-11ea-869a-c19be088ad8f.png)
![screen06](https://user-images.githubusercontent.com/12913436/75610685-a3de9100-5b13-11ea-9d21-5c57943825fb.png)
![screen07](https://user-images.githubusercontent.com/12913436/75610688-a6d98180-5b13-11ea-88fe-188e4f9e1183.png)
![screen08](https://user-images.githubusercontent.com/12913436/75610691-aa6d0880-5b13-11ea-979f-427caa171d4b.png)
![screen09](https://user-images.githubusercontent.com/12913436/75610693-ad67f900-5b13-11ea-9e5b-e11af93960b2.png)

If you need, I can try to make a video too. Just tell me.

**Comment by sorryusernameisalreadytaken** [comment]
Here is video to show how difficult it is to create a test folder in the amaze-data-folder:
[amaze_androidtv_dpad_gui.zip](https://github.com/TeamAmaze/AmazeFileManager/files/4285320/amaze_androidtv_dpad_gui.zip)

**Comment by VishalNehra** [comment]
I was working on this on the following branch... Can be picked up again. 

https://github.com/TeamAmaze/AmazeFileManager/tree/android-tv

**Comment by sorryusernameisalreadytaken** [comment]
any progress here? Is v3.6 milestone really possible?

**Comment by VishalNehra** [comment]
@sorryusernameisalreadytaken Sadly no progress as we've just finished 3.5
But definitely can be done with 3.6 
Please be patient 😇

**Comment by VishalNehra** [comment]
Reopening as few issues found with android tv layout while opening a file.
