### ISSUE TITLE
File size shown vertically when not enough space

### ISSUE THREAD

**Issue by sivaraam** [TeamAmaze/AmazeFileManager#1828]
**Describe the bug**
When there is not enough screen space to display the file size completely, it is shown in a vertical manner. It looks awkward and also makes one file entry take up a lot of space.

**To Reproduce**
1. Go to a file which has not been modified in this year (thus resulting in the complete modification date shown)

**Expected behavior**
The file size is show in a horizontal way which is readable to users.

**Screenshots**
![Screenshot_2020-01-24-08-33-23](https://user-images.githubusercontent.com/12448084/73613364-bfd93a80-461a-11ea-89a9-9699e53fb53a.png)

**Smartphone (please complete the following information):**
 - Device: Samsung SM-J111F
 - OS: Android 5.1.1
 - Rooted: Yes
 - Version: 3.4.1

**Comment by justdvnsh** [comment]
Solved the issue here.
https://github.com/justdvnsh/AmazeFileManager/commit/e3863f02ea57a1f2490672c60569295d243b6825
Please have a look at it, and I would create a pull request.

**Comment by justdvnsh** [comment]
Here is the new layout look.

**Comment by developerhb** [comment]
Hello maintainers. We can solve this issue by abbreviating month name i.e. December - Dec, November - Nov and so.
