### ISSUE TITLE
KitKat 4.4: Renaming a system file doesn't work (even if Supersu grant root access)

### ISSUE THREAD

**Issue by WiliTest** [TeamAmaze/AmazeFileManager#1835]
On Kitkat 4.4, renaming a system file doesn't work (even if Supersu grant root access to amaze).

It works using the FX File Explorer app (it only asks before to "mount read write").

(I could use FX File Explorer, but I prefer to use your open source app)

ps: thanks for your awesome work!

**Comment by TranceLove** [comment]
Couldn't reproduce the problem on GPD XD1 running LegacyROM (4.4.4) with SuperSU as root access. Create a file under `/system` (using `adb shell touch /system/test.txt`), it was able to be successfully renamed after grant root access.

May you provide more information, e.g. device, ROM, logcat?

**Comment by WiliTest** [comment]
I apologise, I missed your answer. I don't own this phone anymore. It was an Samsung S3 (LTE, 4g version) running the last supported android (no custom Rom).

**Comment by TranceLove** [comment]
Ahh... that's pity. Since it's not easy to have a rooted S3 around now...

**Comment by WiliTest** [comment]
I apologize for letting you down after all the work you have done for us.  I have a SaumsungS3Lte now so I can do more testing. 

1. I downloaded the latest version of amaze (3.4.3)
2. In Amaze settings, I have activated the root mode and I have checked in Superuser that Amaze have the root access.
3. In Amaze, I navigated to system/media/audio/ui  and choosed any file, select Rename and then change the filename. There is the little popup telling me that it's renaming and then nothing happen. 
4. In logcat I search for amaze and I got this warning : Failed to ensure directory: /storage/extSdCard/Android/data/com.amaze/files/external

Let me what else I can do. And thanks for your amazing work !

Samsung S3 GT-I9305
Android 4.4.4

**Comment by TranceLove** [comment]
Many thanks for the effort.

It seems the output of `mount` between different versions are different.

Nexus 5 emulator running stock 4.4.4 (API 19):
`/dev/block/vda /system ext4 ro,relatime,data=ordered 0 0`

Samsung Galaxy S2 (GT-i9100) running SlimLP (5.1.1):
`/dev/block/mmcblk0p9 /system ext4 ro,seclabel,noatime,user_xattr,barrier=1,data=ordered 0 0`

Nexus 5 emulator running stock 6.0 (API 23):
`/dev/block/vda /system ext4 ro,seclabel,relatime,data=ordered 0 0`

Oneplus 2 running AOSPExtended (7.1.2):
`/dev/block/bootdevice/by-name/system on /system type ext4 (ro,seclabel,relatime,data=ordered)`

Fairphone 3 running LineageOS 16.0 GSI:
`/dev/block/mmcblk0p60 on /system/product type ext4 (ro,seclabel,relatime,block_validity,discard,delalloc,barrier,user_xattr)`

See if I can make for patch for this.

**Comment by WiliTest** [comment]
Let me know when the patch is ready, I will test it.

**Comment by TranceLove** [comment]
> Let me know when the patch is ready, I will test it.

@WiliTest Check #1867

**Comment by WiliTest** [comment]
Is there a way to install the patch on my phone because I checked the app store and there is no new version yet.

**Comment by TranceLove** [comment]
> Is there a way to install the patch on my phone because I checked the app store and there is no new version yet.

Method 1: get your hands dirty by building your own version (difficult I know, YMMV)
Method 2: @EmmanuelMess @VishalNehra please help passing #1867 and consider making a hotfix build including it

(Sorry but you know... everyone on the Earth is busy fighting the coronavirus now, communications and workflow can be intermittent - please be patient, and sorry again for the inconvenience caused)

**Comment by WiliTest** [comment]
Sorry TranceLove (and  @EmmanuelMess and @VishalNehra ), I didn't want to put pressure on you, I just saw today that you replied 6 days ago, and thought that it was you guys that waited for me to test it. I will wait, I still have the phone and I don't use it as my primary phone so no inconvenience here. And thanks for your amazing job!
