### ISSUE TITLE
file search crashing

### ISSUE THREAD

**Issue by aha999** [TeamAmaze/AmazeFileManager#1837]
Mostly when searching a keyword, Amaze crashes before showing it.

Amaze version: 3.4.2

**Comment by EmmanuelMess** [comment]
Cannot replicate: Could you provide a logcat?

**Comment by aha999** [comment]
Sorry, can't provide logcat... Best i can do is a gif. 
More context... if i open Amaze, and then immediately search words "diagnostic" or "diagnostics", it crashes. it doesn't crash on other words for some reason after opening the app.

![bl38cQIrt1](https://user-images.githubusercontent.com/50620416/74574015-99a08c80-4f82-11ea-899c-433ad1c7495a.gif)

**Comment by EmmanuelMess** [comment]
Cannot replicate on master or release-3.4.

**Comment by imrandomizer** [comment]
@aha999  What version of Android you are using ? And can you also share the locale your device runs in ? 

Also can you share the list of files that come up when you search for the exact same keywords from a native/or any other file-browser ?
