### ISSUE TITLE
Share more than one file crashes the app

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1841]
To replicate share 2 images from Google Photos.

**Comment by justdvnsh** [comment]
Hi. I've resolved the issue. Here is my commit.
https://github.com/justdvnsh/AmazeFileManager/commit/1ee068f071585e8293e5cff9eff9c223c48d942c
Please have a look at it, and then I'll create a pull request.

**Comment by TranceLove** [comment]
> Hi. I've resolved the issue. Here is my commit.
> [justdvnsh@1ee068f](https://github.com/justdvnsh/AmazeFileManager/commit/1ee068f071585e8293e5cff9eff9c223c48d942c)
> Please have a look at it, and then I'll create a pull request.

Thank you for looking into it. Same fix as #1875.
