### ISSUE TITLE
Amaze doesn't save files that i save from the internet

### ISSUE THREAD

**Issue by aha999** [TeamAmaze/AmazeFileManager#1852]
**Describe the bug**
When in a web browser and i press Share and Save with amaze, then Save button (that's in the + spot) it doesn't save the file ( xml file ).

**To Reproduce**
1. Go to web browser
2. Open [xml format page](https://dl.xda-cdn.com/4/9/4/1/8/3/5/Vibrant_7.2.xml?key=XY73zql41bWPB-Em4am8UQ&ts=1583012986)
3. Press Share and Save with Amaze
4. when Amaze opens you can save the file into a wanted folder by pressing a download/save button in the bottom right corner
5. File is not saved.

**Expected behavior**
It should save the xml file.

**Smartphone (please complete the following information):**
 - Device: Lenovo P2
 - OS: Android 9 (LineageOS 16)
 - Rooted: No
 - Version: 3.4.2

**Additional context**

**Comment by TranceLove** [comment]
Culprit was mishandling of ACTION_SEND intent with URI as content (which Amaze shouldn't be handling).

**Comment by VishalNehra** [comment]
Feature working fine on my device. A logcat would help, if possible.

**Comment by VishalNehra** [comment]
Fixed on 3.5.x 
Please test beta program on google play and reopen if issue still there.
