### ISSUE TITLE
Amaze doesn't find files

### ISSUE THREAD

**Issue by aha999** [TeamAmaze/AmazeFileManager#1853]
**Describe the bug**
Amaze simply never seems to find the files i'm looking for

**To Reproduce**
1. Amaze file manager
2. Click on Search button
3. Try to find a file (i was trying to find a xml file this time)
4. nothing is found

**Expected behavior**
It should find the files that are present in the phone.

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: Android 9 (LineageOS 16)
 - Rooted: No
 - Version: 3.4.2 f-droid

**Additional context**
I tried then with another program and file search works perfectly and it finds the file, so it's amaze's bug.

**Comment by zeeshanbeg** [comment]
is this issue still present ? i would like to contribute to this
thanks

**Comment by VishalNehra** [comment]
Amaze search works fine with v3.5.0
Please test and report back @aha999

**Comment by VishalNehra** [comment]
@zeeshanbeg if you would like to improve search, I have something planned for next release. Request you to join our telegram channel to discuss.
