### ISSUE TITLE
app crashes on searching "android" in folder section

### ISSUE THREAD

**Issue by NayanAnsh** [TeamAmaze/AmazeFileManager#1862]
when in internal storage section searching  the word "android" cause  the app to crash.

**To Reproduce**
1. at internal storage page search "android"

**Expected behavior**
it Should show the folders containing words "android"

**Screenshots**

**Smartphone (please complete the following information):**
I have tested  this on two devices-
 - Device: realme x2 , moto g5 plus
 - OS:  Android 9 ,android 8.1
 - Rooted: Nope
 versionName- "3.3.0RC1"

**Comment by marcinadd** [comment]
This is probably the same issue as #1837.
