### ISSUE TITLE
two folders and one manifest file, is the complete Android Java app for this file manager

### ISSUE THREAD

**Issue by lse123** [TeamAmaze/AmazeFileManager#1868]
https://github.com/TeamAmaze/AmazeFileManager/tree/master/app/src/main

The structure here ^^^
with the two folders and one manifest file, is the complete Android Java app for this file manager app, so **Only this code needed[from this Repo]** to get and import in android studio to modify and learn from it??? 

java/com/amaze/filemanager |
  | res | 
  | AndroidManifest.xml |

**Comment by bowiechen** [comment]
The entire repo contains the full code for Amaze File Manager.

**Comment by lse123** [comment]
What IDE did you use? What folder import in Android Studio 3...?

**Comment by TranceLove** [comment]
Android Studio 3.

You choose **Checkout project from Version Control**, and choose `git` at the pull down

![1](https://user-images.githubusercontent.com/251819/79039812-73137080-7c16-11ea-935d-1ae9d2d03c1d.png)

Copy the repository URL up front at the code tab

![2](https://user-images.githubusercontent.com/251819/79039861-ce456300-7c16-11ea-9049-7d4489ed5037.png)

and paste to the URL field at the prompt

![3](https://user-images.githubusercontent.com/251819/79039837-a1914b80-7c16-11ea-865c-44740c33a333.png)

You should have the code you need.
