### ISSUE TITLE
Replace or augment Android Beam to work for Q and beyond

### ISSUE THREAD

**Issue by eehouse** [TeamAmaze/AmazeFileManager#1869]
As you all know, Android Beam has been deprecated. I miss it, and have managed to work around the reduced set of APIs to make it work (using NFC entirely, no BT or WiFi), on "Q" and earlier versions, for a couple of personal apps. I want it in a file browser, and Amaze is open source and looks good. Would you take a patch? I think it can make sense for files up to a few MB in size, and if the protocol recovers from dropped connections (it will :-) can be a reasonable user experience -- using NFC entirely.

The solution I've worked with uses card emulation. The app emulates an NFC card to accept connections, and when sending goes into reader mode (losing the ability to detect incoming connections while in that mode.) An app with an explicit "share" command removes the most difficult part of this, as there's no need to deal with the possibility that both devices are trying to send at the same time.

Once a connection is opened, it's synchronous and bi-directional, but individual packets are small and connections don't last long. So the protocol would need to be tolerant of that, breaking up a file, tracking and communicating what's received and what's pending, checksumming, showing progress to both users, etc. I haven't moved more than a few K at a time over NFC yet, but my experience tells me it's worth trying to scale up to larger files. At least photos, maybe more.

What I've done so far is in the projects https://github.com/eehouse/nfcclip and https://github.com/eehouse/xwords. Or, if the team thinks the feature would be accepted if it works well, I'll get a branch started and you can check that out.

**Comment by TranceLove** [comment]
Sounds cool. I think transmission rate is limited like bluetooth do? So it is really for transferring texts or small pictures.

For transferring files (megabytes should be the norm nowadays), perhaps establishing a P2P wifi connection (#1317) may do better? e.g. like, [TrebleShot](https://github.com/genonbeta/TrebleShot)?

**Comment by eehouse** [comment]
Did a quick mockup and a 550k file took 44 seconds to transfer. Even if
optimizations double the thruput that's pretty limiting.

I'll take a look at options for offloading. I'm not a P2P fan though. I've
spent time with the APIs with little success, except at crashing Android
hard. I shouldn't be able to do that from an app....

--Eric

**Comment by EmmanuelMess** [comment]
This is a filemanager, you should seek help from the TrebleShot team for this.
