### ISSUE TITLE
FTP 'S"? not working....Cant open ftp folder from windows 7.  im not really expert on this, did i doing it wrong?

### ISSUE THREAD

**Issue by sajadahmerah** [TeamAmaze/AmazeFileManager#1880]
**Describe the bug**
Cant open ftp folder from windows 7.

**To Reproduce**
1. Go to 'FTP'
2. Click on 'start'
3. open on windows explorer and type ftp://192.168.xx.xx:xxxx or ftps://192.168.xx.xx:xxxx just like on amaze showed on app..
4. See error, cant open ftp, it always working before using this update.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38830163/79623583-4ea02280-8147-11ea-9fe6-afa5e89ec2ad.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. hisense]
 - OS: [e.g. Android jelly bean]
 - Rooted: [e.g. No]
 - Version: amaze latest update playstore, i updated 17 april 2020.

**Additional context**
i dont have backup apk for amaze before this. i downgrade to 3.2.2 for temporary. FTP(no ftps) working fine, but layout looks bad because ip address text on amaze ftp is cant be read because too big.

**Comment by TranceLove** [comment]
It seems Windows Explorer does not support FTPS (FTP over SSL). You may be better off using FTP clients that supports FTPS.

FTPS support is confirmed working with [Filezilla](https://filezilla-project.org), while [WinSCP](https://winscp.net) is said to support FTPS as well.

**Comment by sajadahmerah** [comment]
thanks for replying. Im not really want to open it again. dont want install another app on windows. i want like the old version before this which still using ftp+windows explorer. where i can get the old apk? not 3.2.2 one, but latest that still using ftp, and better app layout. Temporary, im using 3.2.2, but the ftp layout is bad. ip address cant be read, because too big. already open  https://androidfilehost.com/?w=files&flid=73979 but only have 7 file : 3.4.1 , 3.2.0, ..., 3.1.0. where version between 3.4.1 - 3.2.0 that released on playstore?

**Comment by sajadahmerah** [comment]
> It seems Windows Explorer does not support FTPS (FTP over SSL). You may be better off using FTP clients that supports FTPS.
> 
> FTPS support is confirmed working with [Filezilla](https://filezilla-project.org), while [WinSCP](https://winscp.net) is said to support FTPS as well.
> 
> Please test with these two clients, and let us know if you still have problem accessing Amaze's FTP server with SSL enabled.
> 
> Will close issue for the time being. Feel free to reopen it if you still have problems.

thanks for replying. Im not really want to open it again. dont want install another app on windows. i want like the old version before this which still using ftp+windows explorer. where i can get the old apk? not 3.2.2 one, but latest that still using ftp, and better app layout. Temporary, im using 3.2.2, but the ftp layout is bad. ip address cant be read, because too big. already open  https://androidfilehost.com/?w=files&flid=73979 but only have 7 file : 3.4.1 , 3.2.0, ..., 3.1.0. where version between 3.4.1 - 3.2.0 that released on playstore?

**Comment by TranceLove** [comment]
You should be able to disable SSL at FTP server's login setting dialog - we chose to enable this by default now because of the security implications brought by plaintext FTP protocol.

And if you need to use previous versions of Amaze, [right here at GitHub](https://github.com/TeamAmaze/AmazeFileManager/releases).

**Comment by sajadahmerah** [comment]
> You should be able to disable SSL at FTP server's login setting dialog - we chose to enable this by default now because of the security implications brought by plaintext FTP protocol.
> 
> And if you need to use previous versions of Amaze, [right here at GitHub](https://github.com/TeamAmaze/AmazeFileManager/releases).

thanks..........

**Comment by TranceLove** [comment]
For reference, where to disable SSL connection for FTP:

![Screenshot_20200418-142500_Amaze](https://user-images.githubusercontent.com/251819/79632384-67352a80-8191-11ea-8038-4215ce423965.png)

Uncheck this checkbox.
![Screenshot_20200418-142510_Amaze](https://user-images.githubusercontent.com/251819/79632393-6dc3a200-8191-11ea-98e0-f7ea7f650097.png)

Agreed that we have room for improvement on UI/UX here, but may be of low priority task to us.

**Comment by sajadahmerah** [comment]
Thanks new version, ftp + windows explorer work fine. And for UI/UX the new version on playstore,, i think its already better, because im on "functional side" not "luxury side".
