### ISSUE TITLE
too many bugs

### ISSUE THREAD

**Issue by karthik2342323** [TeamAmaze/AmazeFileManager#1882]
Error : Couldn't find meta-data for provider with authority com.amaze.filemanager
 You Can Do It By Two Ways 
1)  first way : 
    By removing  applicationIdSuffix ".debug"  in debug   In order to maintain Original ID .
2) second way :
Alter Manifesto File  See the last tag 

<provider

            android:name="androidx.core.content.FileProvider"

            android:authorities="com.amaze.filemanager"

            android:exported="false"

            android:grantUriPermissions="true"
>
            <meta-data

                android:name="android.support.FILE_PROVIDER_PATHS"

                android:resource="@xml/provider_paths" />

        </provider>

Changes : android:authorities="com.amaze.filemanager" inside Provider tag

Thank You TranceLove For making me more focused on Solving error rather than making comment in Issue .

**Comment by TranceLove** [comment]
I'm not able to reproduce the problem you mentioned on Pixel emulator running stock 5.0.2 firmware, x86_64 with Google API enabled.

Can you provide more details of the problems you encountered? Including steps to reproduce, device you're using, etc.

**Comment by karthik2342323** [comment]
"""   Couldn't find meta-data for provider with authority com.amaze.filemanager   """
This Error Stops working the whole app

**Comment by TranceLove** [comment]
Seems to be related to faulty merge at #1860. #1875 should help.
