### ISSUE TITLE
Images not being opened in designated apps.

### ISSUE THREAD

**Issue by justdvnsh** [TeamAmaze/AmazeFileManager#1887]
**Describe the bug**
The app is not opening image and video files. Showing File Meta Data could not be provided.

**To Reproduce**
1. Go to 'amaze file explorer'
2. Click on 'images'
3. Select any image

**Expected behavior**
The app should be opening the images in gallery or designated apps.

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi Note 7s]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by justdvnsh** [comment]
Hi, I would like to be assigned, and work on this issue.

**Comment by TranceLove** [comment]
> Hi, I would like to be assigned, and work on this issue.

Yes please.

**Comment by justdvnsh** [comment]
Already Done . 
Please have a look at my commit, and then I'll create a pull request. 
https://github.com/justdvnsh/AmazeFileManager/commit/1ee068f071585e8293e5cff9eff9c223c48d942c

**Comment by TranceLove** [comment]
> Already Done .
> Please have a look at my commit, and then I'll create a pull request.
> [justdvnsh@1ee068f](https://github.com/justdvnsh/AmazeFileManager/commit/1ee068f071585e8293e5cff9eff9c223c48d942c)

Yes it is, but this omits the possibility of `debug` builds which developers will use.

#1875 will fix this, sorry.
