### ISSUE TITLE
(Request) Update the F-Droid release.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [TeamAmaze/AmazeFileManager#1913]
Hi, thank you for an amaze-ing file manager!
last F-Droid release was mid 2017, please consider pushing a fresh update there please! thank you.

**Comment by 5c0tt-b0t** [comment]
Closing this as F-droid was updated!
Thank you dev! :D

**Comment by cl0ne** [comment]
I don't see any updates at https://f-droid.org/packages/com.amaze.filemanager/

**Comment by VishalNehra** [comment]
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

Please use this fdroid repo

**Comment by sebma** [comment]
Actually : The IzzyOnDroid F-Droid Repository is [here](https://apt.izzysoft.de/fdroid).
