### ISSUE TITLE
Documents shortcut does not show any files

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamAmaze/AmazeFileManager#1916]
Amaze has shortcuts for recent files, images, videos, audio, APKs and documents. The documents shortcut does not show any files. All other shortcuts work as they should.

Phone: Xiaomi Mi 9T Pro
OS: MIUI 12
Amaze version: v3.4.3

**Comment by pcsaunak** [comment]
@VishalNehra  @TranceLove I see that the click / tap is handled onNavigationItemSelected in CustomNavigationView. But I am not able to get the flow where is the logic for selecting the contents within it ?

**Comment by pcsaunak** [comment]
@VishalNehra @TranceLove I think I got the flow. Thanks guys
