### ISSUE TITLE
Ftps cannot be logged in by win10

### ISSUE THREAD

**Issue by currencyporter** [TeamAmaze/AmazeFileManager#1938]
**Describe the bug**
Ftps cannot be logged in by win10,
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]
android 7.0
**Additional context**

**Comment by TranceLove** [comment]
As far as I know, Windows Explorer does not support FTPS. Either use a different FTP client that supports it (e.g. [Filezilla](https://filezilla-project.org/) is tested working with Amaze), or disable FTPS in FTP server screen, three dots -> Login -> untick "secure connection".

**Comment by currencyporter** [comment]
> 
> 
> As far as I know, Windows Explorer does not support FTPS. Either use a different FTP client that supports it (e.g. [Filezilla](https://filezilla-project.org/) is tested working with Amaze), or disable FTPS in FTP server screen, three dots -> Login -> untick "secure connection".

That's it. Thank you very much
