### ISSUE TITLE
Feature Request: Make number of tabs configurable 

### ISSUE THREAD

**Issue by macearl** [TeamAmaze/AmazeFileManager#1956]
# Description
I often switch between 3 or 4 different storage devices / directories and would like to have a separate tab for each of them.

With amaze right now I could bookmark each of these paths and switch between them that way however I think a simple swipe left or right or picking a tab from an always showing tab bar would be so much more comfortable 

I'm currently also using root explorer just for this feature. However as I generally like amaze more and would like to migrate everything to open source apps it would be nice if more than 2 tabs would be possible. 

Keep up the good work!

**Comment by EmmanuelMess** [comment]
This requires _some_ refactoring of the ways tabs is done, but shouldn't be too difficult

**Comment by VishalNehra** [comment]
We had initial few releases where we did implement this dynamic tabs approach. But for most people they don't use that many tabs, and for a simplistic design, we removed it later on. Maybe I'll attach the apk for those release and you can give it a shot. If you like we might give it a shot.

**Comment by macearl** [comment]
> We had initial few releases where we did implement this dynamic tabs approach. But for most people they don't use that many tabs, and for a simplistic design, we removed it later on. Maybe I'll attach the apk for those release and you can give it a shot. If you like we might give it a shot.

Sure I'd like to give the old version a go. It would probably be easier to reimplement that code instead of completely rewriting it

**Comment by VishalNehra** [comment]
#2744

**Comment by EmmanuelMess** [comment]
@VishalNehra the two issues are not the same thing.

**Comment by VishalNehra** [comment]
It's by design choice we keep two tabs, left and right. Regardless of the number of devices currently connected. If we want more tabs we can open more windows as pointed in #2744

**Comment by EmmanuelMess** [comment]
> It's by design choice we keep two tabs, left and right. Regardless of the number of devices currently connected. If we want more tabs we can open more windows as pointed in #2744

IMO a design discussion should be opened to use another system, unifying the TextEditor taks and tabs.

**Comment by EmmanuelMess** [comment]
See #3023
