### ISSUE TITLE
SFTP - security options improvment

### ISSUE THREAD

**Issue by DoctorD90** [TeamAmaze/AmazeFileManager#1961]
Hi! The app is amazing! I was using and it seems GREAT!
i'd like to ask if it'd be possible to increase/upgrade security options for the sftp protocol.
Actually Im using a ed25519 key type, but I noticed Amaze offers: ssh-rsa,ssh-dss [preauth]

Moreover ( I didn't edited my server to test them ), if Amaze could support most recents:
- **KexAlgorithms:** curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
- **Ciphers:** chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
- **MACs:** hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

Thanks!

**Comment by TranceLove** [comment]
Amaze's SSH implementation depends on [hierynomus/sshj](https://github.com/hierynomus/sshj), with some little tweak that disabled ECDSA (although on-device test did passed for ED25519 keys) to for stock and our own BouncyCastle co-existence.

After #1881 and #1890 merged to enable full BouncyCastle usage in our app maybe we can lift the tweaks to see if everything still work.

But for the new ciphers you mentioned, I could find chacha20-poly1305 in BouncyCastle, but not sure if it can be used with sshj itself.

Adding these ciphers may take time. Can't tell if it'll be at 3.6, but shall not happen at 3.5 cycle as we push hard towards public beta and release.

Anyway, let's lift the tweak first.

**Comment by TranceLove** [comment]
Support for AES-GCM cipher is being implemented at sshj upstream: https://github.com/hierynomus/sshj/pull/630

**Comment by TranceLove** [comment]
`chacha-poly1305@openssh.com` support had been implemented at sshj upstream: https://github.com/hierynomus/sshj/pull/682.

As soon as a new sshj is released, upgrade the lib will close this issue. Let's hope this will happen in 3.6 series then :)

**Comment by TranceLove** [comment]
With #2909 merged, `chacha20-poly1305@openssh.com` support in place, this should be marked as closed.
