### ISSUE TITLE
Simple Image viewer

### ISSUE THREAD

**Issue by DoctorD90** [TeamAmaze/AmazeFileManager#1963]
Hi, Example: Im in "DCIM" folder for example, and there are many photos.
I would like to open one but I failed, and to check the others I'd like to swipe.

I tried many apps but all of them just open ALL photos and do not allow to sort based on the source folder (mainly on date or tags etc).

Would be possible a simple image swiper? no special functions (data retrieve, change format, etc)
Just to simply check other images if we pick the wrong one. No need of additional software in this way :)

**Comment by EmmanuelMess** [comment]
This is a file manager, it's scope is to deal with files, I recomend using Simple Gallery, or some other gallery, or asking one of those dev's for this kind of feature.

**Comment by EmmanuelMess** [comment]
Merge with #2092
