### ISSUE TITLE
App drawer does not show up properly in landscape mode

### ISSUE THREAD

**Issue by pcsaunak** [TeamAmaze/AmazeFileManager#1967]
**Describe the bug**
In landscape mode, it shows strange behaviour. Refer the attached image.
![Screenshot_20200820-134539](https://user-images.githubusercontent.com/23631671/90737784-d3fd3480-e2eb-11ea-8c63-d96fc151e6a4.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 7t
 - OS: Android 10
 - Rooted: No

**Additional context**

**Comment by VishalNehra** [comment]
Duplicate of #1061
