### ISSUE TITLE
Show creation time for folders and files

### ISSUE THREAD

**Issue by lo9-u** [TeamAmaze/AmazeFileManager#1974]
**Is your feature request related to a problem? Please describe.**
It is a feature request.

In Amaze File Manager there is no possibility to display the creation time for folders and files under "Properties". Currently only the modified time for folders and files is displayed under "Properties".

**Describe the solution you'd like**
It should be generally possible to display the creation time for folders and files under "Properties".

**Describe alternatives you've considered**
There is no alternative, it should be officially supported.

**Additional context**
Here is the solution to implement it directly. See the Android documentation.
https://developer.android.com/reference/java/nio/file/attribute/BasicFileAttributes#creationTime()

**Comment by EmmanuelMess** [comment]
Related  #1028

**Comment by VishalNehra** [comment]
#1028 Added to milestone 3.6 :) 
Closing this, please track that issue instead.
