### ISSUE TITLE
Update Amaze translate hyperlink

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#1987]
While click on _Settings> about>  translate_ it open up https://www.transifex.com/amaze/amaze-file-manager-1/

Update it to https://www.transifex.com/amaze/amaze-file-manager/

**Comment by VishalNehra** [comment]
Can you make the same change in play flavour?

**Comment by Wetido** [comment]
> Can you make the same change in play flavour?

Which place do you mean exactly?

**Comment by VishalNehra** [comment]
Search through project, we have two versions of AboutActivity. One is for play store version other is for fdroid version.
