### ISSUE TITLE
Open amaze without flashing ⸮⸮⸮

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#1988]
It not a problem.We can say it's a minor improvement.
When we open Amaze it takes fraction of second to flash white background then it opens up amaze.

There are some apps like WPS office, Librera Pro, VLC etc who open their app without flashing, though they take little amount of time to open. These apps just wait that fraction second & open the app directly.

It would be nice if Amaze open without white flash.

(Sorry if this is related to android limitations)

**Comment by VishalNehra** [comment]
This is already been fixed on 3.5.x beta series.. please opt into beta program from play store or wait for stable release.
