### ISSUE TITLE
Last APK missing signature

### ISSUE THREAD

**Issue by IzzySoft** [TeamAmaze/AmazeFileManager#2014]
Could you please make sure "lower" signatures are present? My updater just complained:

```
DOES NOT VERIFY
ERROR: No JAR signatures
ERROR: 
repo/com.amaze.filemanager_89.apk: 
ERROR: Old APK signature failed to verify: repo/com.amaze.filemanager_89.apk

jar is unsigned.
```

So it misses at least v1 sigs – which prevents it from being included with the index.

**Comment by VishalNehra** [comment]
I understand. Will include it.

**Comment by VishalNehra** [comment]
I've uploaded v1 signature apk to release named v3.5.0.
Please check :)

**Comment by EmmanuelMess** [comment]
@VishalNehra Pls sign with key

**Comment by IzzySoft** [comment]
Thanks! Yes, that verifies (will be published with the next sync). Btw: No need to have multiple APKs just for the sigs. Just tick all boxes (v1, v2, v-whatever-depending-on-your-targetSdk), they can co-exist :wink:

**Comment by VishalNehra** [comment]
@IzzySoft I understand.. will take care of that next time :)

**Comment by IzzySoft** [comment]
Great, thanks! General rule: if you sign with vX, just include all lower vY as well. In theory, an APK signed v2-only targeting Oreo+ and having minSDK set to Oreo+ as well would be fully valid. Thing is, ApkSigner seems to always complain when there's no v1. So picking our example again: That Oreo+ app is also fully valid if signed with v2 AND v1. And I guess even if signed v1 to v4. Hence the idea to just include all lower sigs as well…

Thanks again for taking such quick action!
