### ISSUE TITLE
Bottom tabs

### ISSUE THREAD

**Issue by Pranab009** [TeamAmaze/AmazeFileManager#2054]
Please move down every tabs like
(cut, copy, paste, properties etc)
Nowadays every phone's screen is too large (6.5 inch)
So it is not handy.

**Comment by EmmanuelMess** [comment]
How would that work in Material design?

**Comment by VishalNehra** [comment]
@EmmanuelMess Even I'm wondering how we're gonna make this work out without making it something like Solid explorer copy

**Comment by Pranab009** [comment]
But you also understand the problem. May be you also use the long screened phone.

**Comment by Pranab009** [comment]
No this is not a copy.
Everyone adopted good features .
like Android copy some ios features and ios also copy some android features it's very common thing.
You can add some more features like offline file sharing etc.
Lastly if possible then add it on fdroid it is the future

**Comment by Pranab009** [comment]
You can add this features
Junk or cache file cleaner.
Built in app lock inside it.
Clone file finder.
Add storage consumption details per file
Storage analyser
Built in vault for images and files.
Offline file sharing like shareit.

**Comment by VishalNehra** [comment]
One thing at a time please.. we'll see whether bottom tabs are feasible design solution or not.
