### ISSUE TITLE
Support system dark theme on Android 10

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#2056]
Per user feedback on Google Play. May become an theme selection option in preferences.

Reference: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by VishnuSanal** [comment]
Let me work on this?

**Comment by TranceLove** [comment]
Sure, please do.

**Comment by PFARN** [comment]
@TranceLove

**Comment by PFARN** [comment]
@TranceLove Nice
