### ISSUE TITLE
The thumbnails aren't correct one I scroll down.

### ISSUE THREAD

**Issue by vertago1** [TeamAmaze/AmazeFileManager#2068]
**Describe the bug**
The thumbnails in my downloads folder started scrambling once I had more files than will fit on one screen. Additionally, I have a file with no thumbnail so that might be a factor.

**Expected behavior**
Either the correct thumbnails should be shown or no thumbnail should be shown for files that don't have the correct thumbnail.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 11
 - Rooted: No
 - Version: 3.5

**Additional context**

**Comment by EmmanuelMess** [comment]
Dupe

**Comment by vertago1** [comment]
Would you mind linking the duplicate? I would like to subscribe to it.

**Comment by TranceLove** [comment]
> Would you mind linking the duplicate? I would like to subscribe to it.

Duplicate of #2060, should have been fixed by #2062.
