### ISSUE TITLE
Add app version and grid view to AppManager

### ISSUE THREAD

**Issue by zz1616611** [TeamAmaze/AmazeFileManager#2069]
1. ~~Amaze Text Editor: error Cannot open large text~~ Dupe #1275
2. App Manager: View package name version
3. App Manager: Number of columns in grid view 4

**Comment by EmmanuelMess** [comment]
This seems too much for a file manager.

**Comment by shuvashish76** [comment]
Package name, Version, Size these are too much to ask from a Filemanager.
There are specific standalone apps like https://github.com/MuntashirAkon/AppManager for that.

#1986
