### ISSUE TITLE
Range selection

### ISSUE THREAD

**Issue by HT-7** [TeamAmaze/AmazeFileManager#2070]
Apparently this has not been suggested so far, albeit very important.

## Range selection

From [Wikipedia](https://en.wikipedia.org/wiki/ES_File_Explorer#Popularization_and_functionality):

> Another early feature [of ES File Explorer] to allow the selection of many files and folders without the need to tap on each file individually was range selection, where only two items need to be highlighted to select all listed items inbetween.

This was a **vital hallmark** of ES File Explorer (the grandfather of Android file explorers, which has sadly not aged so well), and I myself used that feature **a lot**.

When using Amaze for the first time, it was the first thing I noticed a lack of.

Therefore, I strongly encourage implementing that feature.

**Comment by EmmanuelMess** [comment]
Added a USD5 bounty to this issue: https://www.bountysource.com/issues/94807779-range-selection. This is mostly to test bounties.

**Comment by EmmanuelMess** [comment]
> Okay, it seems this is the way ES File Manager does range selection. I personally would prefer a system more like the range selection for Google Photos (Edit: long press on a file until it is selected, then drag down to select more).

**Comment by EmmanuelMess** [comment]
> Agreed here, need something like Google photos. I think there's an API which supports drag and pass us all the ui elements present below it. We can make use of that api. Maybe just support whatever adapter elements are there at one screen for now, and support for list auto-scrolling if drag comes to bottom part of the screen can be added later.

(from VishalNehra pr #2254)

**Comment by Jenjen1324** [comment]
Just learned about this Google Photos feature (thanks for that I guess) but I have some concerns about the UX.

When managing files you want to be efficient and the most beneficial use-case for range selection is in my opinion to be able to *quickly* select a lot of files. The range select in Google Photos is either a constant speed or it will get finicky and unpredictable if you try to add some kind of acceleration.

If range selection would be implemented, I think the baseline should be the "select two and click to fill between" because this enables a much faster interaction:

 1. Select first item
 2. Quickly scroll to the last item
 3. Select it
 4. Click the range select button

Whereas the Google Photos method removes the "Quickly" part from the interaction.

Having both where selecting a small amount of items is practical with the Google Photos method and a large amount using the button would be ideal.

**Comment by EmmanuelMess** [comment]
Is there a way to implement the select two and fill between that allows for:
* More than one range selection (like the shift key on PC)
* Is intuitive so that users know it exists and find it easy to use?

**Comment by EmmanuelMess** [comment]
@VishalNehra you should probably claim the bounty.

**Comment by VishalNehra** [comment]
Haha I was meaning to ask but forgot 😅

**Comment by maltfield** [comment]
Can you please paste a link to the documentation that describes how a user can range-select a set of files in Amaze?

I found this issue when searching to figure out how to do shift+tap multi-select of files on Amaze, but after reading the entire issue, I guess it's possible but I have no idea how.

Please post a link to the range-select section of the Amaze docs for myself & other readers.

**Comment by VishnuSanal** [comment]
this was implemented using #2427. please check the code for further references.

**Comment by VishnuSanal** [comment]
> To be clear: I'm asking for usage documentation, not implementation code.

oh! sorry for the trouble. to range select, click on an item and drag/scroll on either direction (top/bottom) to select items in between. we do not have usage documentation as of now.

**Comment by VishnuSanal** [comment]
@maltfield Please enable "drag and drop" & set it to select items from the settings.

**Comment by HT-7** [comment]
> Intuitively, I would expect that I could tap-and-hold to select the first item, then scroll-to and tap-to-select the last item, and then click some `select all items between` option in the overflow menu to select everything between the two.

Exactly! That's also what ES File Explorer does. It is like Shift+Click selection that desktop computers and laptops had for decades.

Drag-to-select is inferior to A-to-B range selection and just slightly faster than individual selection.

**Comment by VishalNehra** [comment]
Please create a new issue for this, shouldn't take long to implement. Will take this on priority.

> > Intuitively, I would expect that I could tap-and-hold to select the first item, then scroll-to and tap-to-select the last item, and then click some `select all items between` option in the overflow menu to select everything between the two.
> 
> Exactly! That's also what ES File Explorer does. It is like Shift+Click selection that desktop computers and laptops had for decades.
> 
> Drag-to-select is inferior to A-to-B range selection and just slightly faster than individual selection.

**Comment by maltfield** [comment]
@VishalNehra per your comment above, I created a new ticket for this UX improvement

 * https://github.com/TeamAmaze/AmazeFileManager/issues/3989

**Comment by HT-7** [comment]
Honestly, drag-to-select is better than nothing. But it can only select 10 to 20 items per second. A-to-B selection like ES File Explorers can immediately select 5000 items.

**Comment by VishalNehra** [comment]
> Honestly, drag-to-select is better than nothing. But it can only select 10 to 20 items per second. A-to-B selection like ES File Explorers' can immediately select 5000 items.

This is already implemented, select 2 files, you'll be able to fill select between them
