### ISSUE TITLE
Ability to directly navigate to entered path

### ISSUE THREAD

**Issue by HT-7** [TeamAmaze/AmazeFileManager#2071]
In order to navigate faster to the path copied in clipboard, I suggest adding the ability to manually enter a path in the navigation bar to open, which would be more convenient than having to tap on the folders to navigate there.

**Comment by TranceLove** [comment]
We should have this function available already.

Enable Custom Path in settings

![Screenshot_1604534270](https://user-images.githubusercontent.com/251819/98181242-c005be00-1f3d-11eb-844a-9465530db973.png)

Then back to file manager, long tap the location, you will be able to enter the custom path you wish to navigate.

![Screenshot_1604534329](https://user-images.githubusercontent.com/251819/98181344-f2172000-1f3d-11eb-97e2-6b85f27f5b10.png)

**Comment by HT-7** [comment]
Thanks, this is good enough for now. Closing.
