### ISSUE TITLE
Feature Request: Add Icon Packs

### ISSUE THREAD

**Issue by FredHappyface** [TeamAmaze/AmazeFileManager#2072]
**Is your feature request related to a problem? Please describe.**
I've been using the papyrus icon pack for my launcher and when I was using Linux earlier this year I was pretty fond of using papyrus in KDE. So my question is: would it be possible to add this to Amaze? 

I'd be very happy to take a look at this should it be decided that this is something that would be beneficial

**Describe the solution you'd like**
See above 

**Describe alternatives you've considered**
Alternative 1

Use an alternative file manager that supports this

This isn't ideal in my eyes as I would much rather use and support this project if possible

**Additional context**
NA

**Comment by EmmanuelMess** [comment]
How much would this increase the size of the app?

**Comment by FredHappyface** [comment]
I'm not sure. I wouldn't have thought it would have been too significant
