### ISSUE TITLE
Scrolling speed limit when using scroll bar

### ISSUE THREAD

**Issue by HT-7** [TeamAmaze/AmazeFileManager#2073]
**Describe the bug**
When I scroll down a long list of files by dragging the side scroll bar, the actual scrolling only follows slowly.

Example: When I drag the scroll bar to the bottom of a long file list and release it, it still scrolls to the bottom, but at a very limited speed. It takes 20 to 30 seconds to reach the bottom of around 1500 files.

**To Reproduce**
1. Open any folder with many files in it 
2. Drag the side bar to the bottom

**Expected behavior**

It should scroll to the bottom immediately, with no speed limit.

**Comment by VishalNehra** [comment]
@HT-7 This should've been fixed with v3.5.0  what version of Amaze do you use?

**Comment by HT-7** [comment]
> what version of Amaze do you use?

3.4.3

I will check if the updated version still has this bug. But if it is fixed, thanks in advance!

**Comment by shuvashish76** [comment]
I uploaded a video of it on Amaze Telegram Support group describing the same issue.
https://t.me/AmazeFileManager/544

I can confirm that it has been fixed.
