### ISSUE TITLE
New installation creates 4 tabs

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2079]
**Describe the bug**
Try to install Amaze on new device, preferably on lower API version. It'll create 4 tabs after you accept storage permission.

**Smartphone (please complete the following information):**
 - Device: Nexus 6p, API 25 (emulator)
 - Amaze version 3.5.0

**Additional context**
Race condition clearing tabs db call and creating new ones after storage permission is accepted.

**Comment by TranceLove** [comment]
#2080 merged, closing.

**Comment by VishalNehra** [comment]
@TranceLove Why 'Fixes' keyword not auto closing the issues on GitHub 🤔
