### ISSUE TITLE
Bookmarks can be added but are not accessable afterwards- "Bookmark not found, recreating..."

### ISSUE THREAD

**Issue by ioogithub** [TeamAmaze/AmazeFileManager#2084]
**Describe the bug**
When a bookmark is selecting from the list, and error is displayed "Bookmark not found, recreating..."

**To Reproduce**
1. Navigate to a folder
2. Click ... -> Add to Bookmarks
3. Swipe from left side of screen, tap on the Bookmark
4. Error is displayed: Bookmark not found, recreating.

The Open As menu is now displayed to the user.

**Expected behavior**
I expect that after a bookmark is added that it can be accessed. Otherwise this feature is not useful.

**Smartphone (please complete the following information):**
 - Device: Tested on two phones: Moto G7 and Moto G7 Plus
 - OS: LineageOS 17 (Android 10)
 - Rooted: Yes
 - Version: v3.12 RC1

**Additional context**
I have tried bookmarking several folders and always get the same result.

**Comment by VishalNehra** [comment]
Can't reproduce on Amaze v3.5.0
Please try latest version.

**Comment by ioogithub** [comment]
When will this be released to F-Droid?

I have another issue related to this, copying files causes amaze to crash.

**Comment by VishalNehra** [comment]
Please download fdroid build from here
https://f-droid.org/packages/com.amaze.filemanager/

**Comment by honjarado** [comment]
Not fixed in latest version 3.8.4. 
This happens when accessing the dir requires su permission.
An unsafe workaround would be to change target dir's permissions to allow execute permission to 'others'. Not tested.
