### ISSUE TITLE
Amaze can't remember default app in app chooser dialog

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2087]
**Describe the bug**
Amaze can't remember default app to open a file. Choosing 'Always' on file chooser don't remember the app with which file was opened.

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - Android 10

**Comment by TranceLove** [comment]
Pixel 4 emulator running Android 10.

![vokoscreenNG-2020-11-13_16-27-37](https://user-images.githubusercontent.com/251819/99047386-1e324100-25cf-11eb-928e-5ea69529ee24.gif)

Perhaps with steps to reproduce?

**Comment by VishalNehra** [comment]
Closed with #2095
