### ISSUE TITLE
Bugs in CrDroid File Manager

### ISSUE THREAD

**Issue by Supratip10** [TeamAmaze/AmazeFileManager#2089]
Bug :
Copy and Paste, Cut and Paste and Deleting Problems in CrDroid File Manager. If I try to copy and paste or cut and paste any file from phone storage to my sd card or from sd card to phone storage it always fails and says an error message "Operation unsuccessful". 

When I delete any file from phone storage or sd card it says "Operation successful" but it stil stays there until I refresh it.

To Reproduce :
1. Tap on 3 dots next to a file name in phone storage
2. Tap Copy or Cut
3. Go to sd card
4. Tap paste icon on top
5. Error : Operation unsuccessful

1. Go to sd card
2. Tap on 3 dots next to a file name
3. Hit Delete
4. Shows "Operation successful" but it still stays there
5. Refresh the screen
6. File gets deleted

Expected behaviour :
When I tap the paste icon on top it should display copying status in the norification bar in case of big file and after copying it should say "Operation successful" and I should see the file in the destination or instantly copies in case of small files. When I delete something from both storage files should be deleted without me refreshing the screen.

Smartphone :

 - Device: Coolpad Note 3 Lite
 - OS: Android 7 Nougat
 - Rooted: Yes
 - Version: 7.1.2

**Comment by VishalNehra** [comment]
I'm sorry but this is not crdroid file manager.

**Comment by EmmanuelMess** [comment]
Cr is a rom, this could very well be it's file manager

**Comment by Supratip10** [comment]
Can I get help from this place?

**Comment by EmmanuelMess** [comment]
Please do confirm that you are using amaze file manager though.

**Comment by marcdw1289** [comment]
Late response.
@Supratip10  The crDroid file manager is indeed based on Amaze but that makes it a fork. All issues regarding its behavior has to be taken up with the crDroid people.

Is crDroid (or your ROM builder) still putting out Nougat builds? I doubt they'll be looking to fix any issues if not.

**Comment by EmmanuelMess** [comment]
> Is crDroid (or your ROM builder) still putting out Nougat builds?

Amaze still supports nougat.

**Comment by marcdw1289** [comment]
Yes, but I wasn't referring to Amaze. The crDroid file manager is based on Amaze (complete with branding) but I seriously doubt anyone on the crDroid team is going to fix any issues on Nougat when the current offerings are for Android 9, 10, and probably 11.

I run mostly Nougat and Oreo ROMs knowing that there won't be any assistance for ROM related issues. They've long since reached end-of-life.
