### ISSUE TITLE
Unable to download pages with only domain name or only parameters in URL.

### ISSUE THREAD

**Issue by HT-7** [TeamAmaze/AmazeFileManager#2090]
**Describe the bug**
Unable to download pages with nothing or **only** URL parameters after domain name.

**To Reproduce**
1. Share `https://example.org/` or `https://example.irg/?1` to Amaze file manager.
2. Tap *Download*
3. error:
> could not download: length=0, index=-1

**Expected behavior**
> A clear and concise description of what you expected to happen.

Save file name with domain name. Also consider #2078.

**Comment by VishalNehra** [comment]
For me both the link types are working on v3.5.0. Please confirm Amaze version you're using.

**Comment by HT-7** [comment]
> For me both the link types are working on v3.5.0. Please confirm Amaze version you're using.

Whoops! I guess I confused Amaze with Primitive FTPd, which also has an integrated downloading feature.

My Amaze version: 3.4.3 . But both this post and #2078 were intended for [Primitive FTPd.](https://github.com/wolpi/prim-ftpd/issues). Closing.
