### ISSUE TITLE
Cannot rename foo.PNG to foo.png

### ISSUE THREAD

**Issue by abda11ah** [TeamAmaze/AmazeFileManager#2098]
**Describe the bug**
Amaze won't rename an file to the same filename with lowercase. It says "a file with the same name already exists"

**To Reproduce**
1. Try to rename something to lowercase or uppercase

**Expected behavior**
Renaming of the file

**Smartphone (please complete the following information):**
 - Device: Meizu M6Note
 - OS: Android 7.1.2
 - Rooted: Yes
 - Version: 3.5

**Comment by TranceLove** [comment]
Are you renaming files on your phone, or remote files? If this is the case, since FAT filesystem is case insensitive, rename `.PNG` to `.png` would not work since they will be pointing to the same file.

**Comment by abda11ah** [comment]
I'm working from my phone.
I think it's on an ext4 FS.
You can write a hack that will firstly rename to a temporary name, then to the desired new name.

**Comment by VishalNehra** [comment]
Wuoah!! Really creative thinking there 😃 maybe we'll pick it up

**Comment by TranceLove** [comment]
@VishalNehra Shall make use of File.getCanonicalPath() to detect file existence.

**Comment by EmmanuelMess** [comment]
Dupe  #773
