### ISSUE TITLE
Cant create a folder after cut/copy

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2115]
Trying to copy to a new folder I'll usually go to the copy site and the create a new folder, but if I have files in the clipboard I cant.

**Comment by EmmanuelMess** [comment]
Tagging @VishalNehra

**Comment by VishalNehra** [comment]
@EmmanuelMess I don't understand.. isn't the paste button in snackbar now.. you can create a new folder even if you have content in clipboard.

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess I don't understand.. isn't the paste button in snackbar now.. you can create a new folder even if you have content in clipboard.

The "+" converts to an "x".

**Comment by VishnuSanal** [comment]
I'd like to work on this :)
