### ISSUE TITLE
stat listing output not consistent on new magisk busybox update

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2125]
**Describe the bug**
Stat listing output not consistent on new magisk busybox update

**To Reproduce**
Try listing any root directories

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus nord
![Screenshot_20201208-090149](https://user-images.githubusercontent.com/5211568/101457978-3aba6280-395c-11eb-8552-67bcc4c6de0d.jpg)

**Comment by EmmanuelMess** [comment]
I don't understand what the issue is here, why is consistency with busybox an issue?

**Comment by VishalNehra** [comment]
stat output is not consistent among different versions. We're giving user an option to choose listing to ls if stat doesn't work.
