### ISSUE TITLE
Empty tab on app startup instead of internal storage

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2139]

**Comment by gre0j** [comment]
This can be closed…it was solved after i clear all the app related user data and cache in Android…
![Screenshot_20201214-001904.png](https://user-images.githubusercontent.com/23266409/102027808-e1609200-3da6-11eb-91cf-f419f49cecd7.png)

Referenz…

https://github.com/TeamAmaze/AmazeFileManager/issues/2140#issuecomment-744091072

**Comment by VishalNehra** [comment]
Thanks for writing. Made our job easy :) Otherwise would be really difficult to trace.
