### ISSUE TITLE
Update Bouncy Castle version

### ISSUE THREAD

**Issue by Neustradamus** [TeamAmaze/AmazeFileManager#2169]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@TranceLove, @VishalNehra: Thanks!

**Comment by VishalNehra** [comment]
Changes reverted with #2179, reopening

**Comment by TranceLove** [comment]
`jcifs-ng` has calls to BouncyCastle components which are made non-public in their latest release, thereby breaking Amaze as seen in #2179.

I'm making patches for jcifs-ng, but not sure when will they look into it. Let's hope we won't end up hosting our own fork...

**Comment by TranceLove** [comment]
PR for jcifs-ng: https://github.com/AgNO3/jcifs-ng/pull/262

**Comment by Neustradamus** [comment]
Possibility to update to 1.69?
