### ISSUE TITLE
reopen: amaze crashes when sharing a file with target save as #1623

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#2177]
I don't have the permissions to reopen #1623, so I'm making this placeholder.

**Comment by VishalNehra** [comment]
Please test with v3.5.x with Play Store or IzzyOnDroid's fdroid repo.
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager
https://play.google.com/store/apps/details?id=com.amaze.filemanager

**Comment by TjrGithub** [comment]
It now saves a text file with the url to the apk. I'm not sure which app is responsible, but I would have expected it to save an actual .apk archive.

Also, #2181 for the 2-year-old version on Fdroid.
