### ISSUE TITLE
outdated version on f-droid

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#2181]
**Describe the bug**
I would expect the f-droid version to follow the github or izzydroid version. However, it's stuck at 3.1.2 RC1

**To Reproduce**
Go to https://f-droid.org/packages/com.amaze.filemanager/

**Expected behavior**
Version  v3.5.x 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Beryllium
 - OS: Lineage-Microg  17.1
 - Rooted: Magisk
 - Version:  n/a

**Additional context**

**Comment by EmmanuelMess** [comment]
Dupe #1684
