### ISSUE TITLE
Can't read root folders correctly.

### ISSUE THREAD

**Issue by ShazStar** [TeamAmaze/AmazeFileManager#2216]
Issues:
Amaze can't read root folders correctly, it shows every root folders empty. Every folders have +0800 in beginning.

Screenshots:
![QxjNpeB - Imgur](https://user-images.githubusercontent.com/64887990/104351295-31667c00-5540-11eb-89cd-b85eca65216c.jpg)
![AsHsSFf - Imgur](https://user-images.githubusercontent.com/64887990/104351307-34616c80-5540-11eb-96f3-06ef60dfb64e.jpg)

 - Device: OnePlus 5T
 - OS: crDroid 6.13 // Android 10 (Additional notes: This issue already exist when I'm on OxygenOS 10.0.1 // Android 10.)
 - Rooted: Yes // Magisk 21.2
 - Version: 3.5.3

**Comment by VishalNehra** [comment]
@ShazStar Can you try to use option 'use legacy listing for root' in amaze settings menu?

**Comment by ShazStar** [comment]
All good. Just enabled that option and it can read the folders correctly now, Thank you! :)

**Comment by ShazStar** [comment]
@VishalNehra All good. Just enabled that option and it can read the folders correctly now, Thank you so much! :)
