### ISSUE TITLE
SFTP does not reconnect after closing the app

### ISSUE THREAD

**Issue by bugnano** [TeamAmaze/AmazeFileManager#2220]
**Describe the bug**
When I create an SFTP connection, Amaze correctly connects to the server and shows the directory listing.
After closing Amaze, when I click on the previously created SFTP connection, an empty directory listing is shown instead.
I cannot delete the connection either, as when I click on the delete button, nothing happens. So I'm stuck with a non-working connection.

**To Reproduce**
1. Create an SFTP connection
2. Notice that the SFTP directory listing is OK
3. Close Amaze (I close it by clicking on the square multitasking button and swiping Amaze out of it)
4. Open Amaze
5. Click on the previously created SFTP connection
6. Notice that the directory listing is empty

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 7
 - OS: LineageOS 17.1 (Android 10)
 - Rooted: No
 - Version: 3.5.3 (But 3.5.2 and 3.5.1 also show the same problem. I haven't tested older versions)

**Additional context**

**Comment by bugnano** [comment]
An update on this issue:

This issue seems related to the default path when creating the connection.
If I specify a path when creating the SFTP connection, then the problem appears, but if I leave the default path blank, then I can use the connection after closing Amaze.

**Comment by VishalNehra** [comment]
Thanks for pointing the issue. Ping @TranceLove
