### ISSUE TITLE
"Open with" doesn't work for compressed files

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2233]
Relatively often when I open a zip file I get the "Open With" android sheet. Pressing Amaze there doesn't do anything.

**Comment by TranceLove** [comment]
Perhaps because both production and debug versions are installed? This is what happened to me.

**Comment by EmmanuelMess** [comment]
> Perhaps because both production and debug versions are installed? This is what happened to me.

Yes, it also happens when SimpleFileManager and Amaze are installed.

**Comment by TranceLove** [comment]
This seems not exist on 3.7 branch any more, as tested with Amaze Production, Amaze Debug, and Simple File Manager all installed on the same Pixel 2 emulator running Android 11.

Please re-open in case you still have such problem.
