### ISSUE TITLE
Multi-line filenames and smaller paddings

### ISSUE THREAD

**Issue by tamas646** [TeamAmaze/AmazeFileManager#2349]
If the name of a file is long, then it's either equipped with marquee effect or shortened by dots.
I personally don't really like marquee effect in a file manager, so for me the filename is not fully displayed which is a bit annoying. (no offense)

I think the solution would be to split the filename into multiple lines.
Maybe if you could reduce the paddings (and/or margins), the list would be more transparent and it would give enough space for multi-line filenames.

What do you think?

**Comment by EmmanuelMess** [comment]
Disscussed at #496, but that was solved using marquee.

I would submit this to a vote, as the issue is already solved by using marquee and this would add/replace with another solution to the same long file name issue.

**Comment by TranceLove** [comment]
@EmmanuelMess Personally I'm more inclined to have multi-line filenames as an option like Lawnchair do. For filenames that are too long to break the list layout we can still truncate it.

**Comment by VishalNehra** [comment]
We already had this discussion, marquee effect seem to be working for most people for long time now. Also I've seen other open source projects such as VLC use marquee (which has much larger userbase).
Good thing is, Amaze is open source, if you feel you don't need marquee and need multi lines, you can simply modify the rowlayout (resources/layout/rowLayout.xml) as per your needs :)
