### ISSUE TITLE
Split apks have broken icons

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2360]
[AmazeFileManager.zip](https://github.com/TeamAmaze/AmazeFileManager/files/6137147/AmazeFileManager.zip)

![imagen](https://user-images.githubusercontent.com/10991116/111077152-30b17e00-84ce-11eb-8061-829359f6a36f.png)

**Comment by yasharzb** [comment]
Hi. I want to reproduce this bug. How did you get these split apks?
