### ISSUE TITLE
LinearLayout leaked at MainActivity

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2366]
┬───
│ GC Root: System class
│
├─ android.app.ActivityThread class
│    Leaking: NO (MainActivity↓ is not leaking and a class is never leaking)
│    ↓ static ActivityThread.sCurrentActivityThread
├─ android.app.ActivityThread instance
│    Leaking: NO (MainActivity↓ is not leaking)
│    mInitialApplication instance of com.amaze.filemanager.application.AppConfig
│    mSystemContext instance of android.app.ContextImpl
│    mSystemUiContext instance of android.app.ContextImpl
│    ↓ ActivityThread.mActivities
├─ android.util.ArrayMap instance
│    Leaking: NO (MainActivity↓ is not leaking)
│    ↓ ArrayMap.mArray
├─ java.lang.Object[] array
│    Leaking: NO (MainActivity↓ is not leaking)
│    ↓ Object[].[1]
├─ android.app.ActivityThread$ActivityClientRecord instance
│    Leaking: NO (MainActivity↓ is not leaking)
│    activity instance of com.amaze.filemanager.ui.activities.MainActivity with
│    mDestroyed = false
│    ↓ ActivityThread$ActivityClientRecord.activity
├─ com.amaze.filemanager.ui.activities.MainActivity instance
│    Leaking: NO (Activity#mDestroyed is false)
│    mainActivity instance of com.amaze.filemanager.ui.activities.MainActivity
│    with mDestroyed = false
│    mApplication instance of com.amaze.filemanager.application.AppConfig
│    mBase instance of androidx.appcompat.view.ContextThemeWrapper
│    ↓ MainActivity.toast
│                   ~~~~~
├─ android.widget.Toast instance
│    Leaking: UNKNOWN
│    Retaining 5.5 kB in 56 objects
│    mContext instance of com.amaze.filemanager.ui.activities.MainActivity with
│    mDestroyed = false
│    ↓ Toast.mNextView
│            ~~~~~~~~~
╰→ android.widget.LinearLayout instance
​     Leaking: YES (ObjectWatcher was watching this because android.widget.
​     LinearLayout received View#onDetachedFromWindow() callback)
​     Retaining 3.5 kB in 46 objects
​     key = cd8c1348-d143-4f0a-9386-82f8651021fe
​     watchDurationMillis = 621010
​     retainedDurationMillis = 616007
​     View not part of a window view hierarchy
​     View.mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     mContext instance of com.amaze.filemanager.ui.activities.MainActivity
​     with mDestroyed = false

METADATA

Build.VERSION.SDK_INT: 30
Build.MANUFACTURER: Google
LeakCanary version: 2.6
App process name: com.amaze.filemanager.debug
Stats: LruCache[maxSize=3000,hits=6716,misses=119807,hitRate=5%]
RandomAccess[bytes=6199021,reads=119807,travel=40205556726,range=27676333,size=3
4171605]
Heap dump reason: 1 retained objects, app is not visible
Analysis duration: 6472 ms

**Comment by bholanathbarik9748** [comment]
can you plz Explain where is XML Files

**Comment by TranceLove** [comment]
Thought you may be looking for the layout XML files, under [app/src/main/res](https://github.com/TeamAmaze/AmazeFileManager/tree/release/3.6/app/src/main/res)... but I think otherwise, that it's MainActivity which retained the LinearLayout instance instead.

**Comment by EmmanuelMess** [comment]
Its MainActivity.toast
