### ISSUE TITLE
Auto Capitalization & Request Focus while creating new file or folder

### ISSUE THREAD

**Issue by VishnuSanal** [TeamAmaze/AmazeFileManager#2429]
![New](https://user-images.githubusercontent.com/50027064/115818467-6e34ef80-a41a-11eb-82a4-4cbb5beb46fd.jpg)

IMO: It would be nice if it's focused on the EditText (auto-keyboard popup) & if it has auto-capitalisation

@EmmanuelMess What do you think? :)

**Comment by VishalNehra** [comment]
I've been thinking to do this for a long time. +1 from my side.
