### ISSUE TITLE
Scrolling up in "open with" app selection bottom sheet is very difficult

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2439]
Scrolling up in "open with" app selection bottom sheet is very difficult

**Comment by VishnuSanal** [comment]
> Scrolling up in "open with" dialog is very difficult

Scroll? That dialog is quite small. Right?

**Comment by TranceLove** [comment]
If you're to fix it, would you like to use the material-dialogs library?

https://github.com/afollestad/material-dialogs/blob/main/documentation/BOTTOMSHEETS.md

**Comment by EmmanuelMess** [comment]
> Scroll? That dialog is quite small. Right?

Sorry, it was the app selection bottom sheet, not the open with dialog.

**Comment by VishnuSanal** [comment]
> > Scroll? That dialog is quite small. Right?
> 
> Sorry, it was the app selection bottom sheet, not the open with dialog.

Oh Yeah. +1 Scrolling up too in that sense. I had to scroll down & then up for it to work! Else, it closes the bottom sheet.
