### ISSUE TITLE
Distinguish between debug & release versions

### ISSUE THREAD

**Issue by VishnuSanal** [TeamAmaze/AmazeFileManager#2441]
![Reference](https://user-images.githubusercontent.com/50027064/117262251-abfc3400-ae6e-11eb-8c0a-2bd356fd56a4.jpg)

Implement some ways to distinguish between debug & release versions. Like some dev/debug badge on the icon. [This](https://github.com/akaita/easylauncher-gradle-plugin) may help!

**Comment by danger-ahead** [comment]
I can help. Can you assign me?

**Comment by danger-ahead** [comment]
Hi, I have fixed the issue. Kindly have a look!

**Comment by VishnuSanal** [comment]
Why didn't this get closed automatically?!
