### ISSUE TITLE
Cannot access folders in /data and /storage/emulated/0/Android/data [Android 11]

### ISSUE THREAD

**Issue by fusionneur** [TeamAmaze/AmazeFileManager#2442]
Rooted with latest magisk 22.1
Android 11
Amaze 3.5.3

Browsing to /data shows folders with names changed (+0200 or +0300 appended) and they are empty

Eg:
+0200 user
+0300 data

Might be related with #1409

**Comment by fusionneur** [comment]
All other folders show fine

**Comment by VishalNehra** [comment]
You can use legacy listing option from amaze settings

**Comment by fusionneur** [comment]
with legacy listing I am able to browse /data correctly
However, /storage/emulated/0/Android/data still shows as empty

**Comment by VishalNehra** [comment]
That's a known issue if you're on Android 11

**Comment by fusionneur** [comment]
I tested "File Manager" from f-droid and it is able to browse these locations with root permissions.
Source code is available at: https://gitlab.com/axet/android-file-manager

Maybe it helps..

**Comment by VishalNehra** [comment]
Sure. Closing this now as this is duplicate to #2015.
