### ISSUE TITLE
Optional thumbnail caching or other preview speedup possible?

### ISSUE THREAD

**Issue by revuwa** [TeamAmaze/AmazeFileManager#248]
I think I found a solution for my situation here: https://github.com/arpitkh96/AmazeFileManager/issues/201
I use this image viewer: https://github.com/snowdream/android-imageviewer (which doesn't need OpenGL ES drivers).
So I use the grid view of your great app and could open the images with the app above.

The only little downer is, that Amaze doesn't seems to cache the thumbnails of the media files, and so I have to wait some time for the preview of some pictures after entering folders with several files in it.

So my question is: would you consider to implement a feature for caching that thumbnails or speedup them with other methods, please?

**Comment by vishal0071** [comment]
It might be a bit late but we're already working on it. We have a working prototype and  caching did drastically improve the performance.

**Comment by VishalNehra** [comment]
Duplicate to #807 
Follow that issue for updates.
