### ISSUE TITLE
Runs have logs that are too long

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2506]
Any run has logs that easily have more than 20000 lines for Run test cases. That is unusable.

**Comment by EmmanuelMess** [comment]
@TranceLove how can "Transforming *.aar (*:*:*) with JetifyTransform" lines be silenced?

**Comment by TranceLove** [comment]
https://stackoverflow.com/a/52353446

This looks so idiot, but let's try it.
