### ISSUE TITLE
MainFragment can have null list

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2587]
**Describe the bug**
MainFragment.listElements can be null. This should be fixed.

**Comment by Soroyesodiq** [comment]
I will like to work on this, but I have a question, are you referring to 
the variable "private ArrayList<LayoutElementParcelable> LIST_ELEMENTS"

**Comment by VishalNehra** [comment]
> I will like to work on this.

Yes

**Comment by Soroyesodiq** [comment]
> **Describe the bug**
> MainFragment.listElements can be null. This should be fixed.

Can you please explain more, I have gone through the MainFragment class of the current branch[release/3.7] but I couldn't find any variable with the name listElements.

**Comment by VishalNehra** [comment]
https://github.com/TeamAmaze/AmazeFileManager/blob/release/3.7/app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt#L39

You can join our telegram group if you need clarification. No need to go through whole codebase without necessity :) 
https://t.me/AmazeFileManager

**Comment by Soroyesodiq** [comment]
> https://github.com/TeamAmaze/AmazeFileManager/blob/release/3.7/app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt#L39
> 
> You can join our telegram group if you need clarification. No need to go through whole codebase without necessity :)
> https://t.me/AmazeFileManager

Okay, thanks

**Comment by Fros1er** [comment]
Hi, is this issue still open? I'd like to work on it.

**Comment by VishnuSanal** [comment]
> Hi, is this issue still open? I'd like to work on it.

Yes, please do!
