### ISSUE TITLE
Shortcut icons not recognisable

### ISSUE THREAD

**Issue by VishnuSanal** [TeamAmaze/AmazeFileManager#2604]
# App shortcut icons looking bad - refer SS

![IMG_20210610_154918](https://user-images.githubusercontent.com/50027064/121513335-5f28f180-ca08-11eb-8d8e-07a4e2d565bb.jpg)

**Comment by EmmanuelMess** [comment]
Context?

**Comment by VishnuSanal** [comment]
> Context?

I'm using a blackish wallpaper. It appears as in shown in the SS in light mode.

This might happen with light wallpaper & when using Dark mode
