### ISSUE TITLE
SMB discover feature doesn't work

### ISSUE THREAD

**Issue by DoctorD90** [TeamAmaze/AmazeFileManager#2622]
I have a SMB server and it is discoverable by app like VLC. I can stream content and access to it.
In Amaze it can't be automatically discovered and it works only if I manually add the IP and port.
The SMB server has also login features and they works. The only missing point is the automatic discover.
Is it broken or should I active any feature server side?

Samba version 4.9.5-Debian
Android 7.1.1 & 9 (not rooted both)

**Comment by NeutralBit** [comment]
I Have this problem too. Network discovery is enabled on PC. But Amaze doesn't find anything automatically. Only manual login works.

**Comment by EmmanuelMess** [comment]
@VishalNehra any idea how this feature was originally implemented?

**Comment by TranceLove** [comment]
@EmmanuelMess Did looked for example either. NbtAddress.getAllByName() seems to be the nearest thing I could find, but I'm not sure.

**Comment by VishalNehra** [comment]
I didn't work on it. But would really appreciate if we fix this. This is a clear long time bug, this thing never worked to begin with.

**Comment by TranceLove** [comment]
The code is correct, actually AFAIK Solid Explorer uses the same way to do server enumeration, but they are using the original jcifs.

And the jcifs-ng we are using actually had deprecated server/workgroup enumeration

https://github.com/AgNO3/jcifs-ng/issues/22

As author said, Windows had disabled this by default, and moved to SSDP/WS Discovery or uPnP for service discovery as part of SMB1 replacement. If we are to work on a new server enumeration mechanism SubnetScanner will need a rewrite.
