### ISSUE TITLE
Rename "Show shortcuts" & "Shortcuts" from settings

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#2653]
from what I understand
shortcut= folders/files which we add to device launcher home screen
bookmark= folders which we add to Amaze app sidebar

---
example of shortcut
![photo_2021-06-26_17-50-16](https://user-images.githubusercontent.com/48226312/123513179-504d6a80-d6a9-11eb-801b-a615a8b40791.jpg)

example of bookmark
![photo_2021-06-26_17-50-20](https://user-images.githubusercontent.com/48226312/123513193-5d6a5980-d6a9-11eb-98f9-83b8a39eb1f2.jpg)

even when we edit them from sidebar we call it bookmark
![photo_2021-06-26_17-43-39](https://user-images.githubusercontent.com/48226312/123513205-7246ed00-d6a9-11eb-8996-90ccb61ade64.jpg)

but when we go to `Settings> Sidebar` we call it shortcut instead🤷‍♂️, which might create confusions.
![photo_2021-06-26_17-44-03](https://user-images.githubusercontent.com/48226312/123513228-90ace880-d6a9-11eb-9844-c32c416eeab8.jpg)

**Describe the solution you'd like**
simply rename both Show shortcuts & Shortcuts  (from `Settings> Sidebar`) to Show bookmarks & Bookmarks

**Comment by shuvashish76** [comment]
& Sidebar bookmarks
![photo_2021-06-26_18-37-32](https://user-images.githubusercontent.com/48226312/123513988-e1264500-d6ad-11eb-9ee7-897ad76bf597.jpg)

**Comment by VishnuSanal** [comment]
@EmmanuelMess Why is this a discussion issue?

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess Why is this a discussion issue?

We need to discuss how to name shortcuts and quick accesses.

**Comment by VishnuSanal** [comment]
> simply rename both Show shortcuts & Shortcuts (from Settings> Sidebar) to Show bookmarks & Bookmarks

I assumed this to be the solution...!

**Comment by VishnuSanal** [comment]
Fixed with #2787
