### ISSUE TITLE
SMB paths

### ISSUE THREAD

**Issue by staticEndeavour** [TeamAmaze/AmazeFileManager#2660]
Is there a definitive path format for smb shares?

Scan won't find my smb server and manually adding wont connect either. 

I've tried any combination of / and //, \ and \\\\ with smb:// and without. I've used just the server ip box and also tried the share box.

Very little feedback on what the problem is, just 'Oops, something went wrong!'

Sometimes  it loads for a while before returning the error  and sometimes it's instantaneous.

The smb share works with every other device in the house.

If anyone could provide a screenshot of a working smb path format I'd appreciate it.

 - Device: Samsung Galaxy A6
 - OS: Android 10
 - Rooted: No
 - Version: 3.6.1

**Comment by TranceLove** [comment]
Try enter the share name without prefixing `/` - this is what is supposed to work.

i.e.
`smb://127.0.0.1/share`, enter `share`
`smb://127.0.0.1/share/a/sub/folder`, enter `share/a/sub/folder`

Would be nice if you can get us a logcat when "Oops, something went wrong!" pops up.
