### ISSUE TITLE
a NPE crash in doInBackground

### ISSUE THREAD

**Issue by 2021QTester** [TeamAmaze/AmazeFileManager#2661]
**Describe the bug**
I am doing some test on AmazeFileManager with automated testing tools just like Monkey. Recently, I found a NPE crash with the following logs. I found no suspicious actions except an rotation, but I am not sure whether the rotation leads to the crash since from the log we can see the bug is related to an asynchronous operation, isn't it?
Would you please help me find the root cause and fix the bug? Thank you very much

logcat:
java.lang.RuntimeException: An error occurred while executing doInBackground
at android.os.AsyncTask.done AsyncTask.java:309 	
at java.util.concurrent.FutureTask.finishCompletion FutureTask.java:354 	
at java.util.concurrent.FutureTask.setException FutureTask.java:223 	
at java.util.concurrent.FutureTask.run FutureTask.java:242 	
at android.os.AsyncTask.run AsyncTask.java:234 	
at java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1113 	
at java.util.concurrent.ThreadPoolExecutor.run ThreadPoolExecutor.java:588 	
at java.lang.Thread.run Thread.java:818 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.flush  ' on a null object reference	
at java.io.BufferedOutputStream.flush BufferedOutputStream.java:86 	
at java.io.FilterOutputStream.close FilterOutputStream.java:61 	
at java.io.BufferedOutputStream.close BufferedOutputStream.java:152 	
at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.ZipExtractor.extractEntry ZipExtractor.java:137 	
at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.ZipExtractor.extractWithFilter ZipExtractor.java:84 	
at com.amaze.filemanager.filesystem.compressed.extractcontents.Extractor.extractEverything Extractor.java:77 	
at com.amaze.filemanager.asynchronous.services.ExtractService.doInBackground ExtractService.java:315 	
at com.amaze.filemanager.asynchronous.services.ExtractService.doInBackground ExtractService.java:225 	
at android.os.AsyncTask.call AsyncTask.java:295 	
at java.util.concurrent.FutureTask.run FutureTask.java:237

**Smartphone (please complete the following information):**
 - Device: x86 Android emulator provided by Google 
 - OS: Android 6.0
 - Rooted: Yes 
 - Version: 3.5.3

**Comment by VishalNehra** [comment]
This should've been fixed. Please checkout latest code from master branch.
Please reopen if it's not. 
Reference - #2436
