### ISSUE TITLE
Index out of bounds in TextEditorActivity

### ISSUE THREAD

**Issue by cadasilv** [TeamAmaze/AmazeFileManager#2677]
## Issue explanation (write below this line) ## Exception * __User Action:__ UI Error * __Request:__ Application crash * __Version:__ 3.5.9 * __OS:__ Linux motorola/panell_26_dt/panell_dt:7.0/NRD90M.06.046/046:user/release-keys 7.0 - 24 * __Device:__ panell_dt * __Model:__ Moto C Plus * __Product:__ panell_26_dt <details><summary><b>Crash log </b></summary><p> java.lang.IndexOutOfBoundsException: getChars (0 ... 27000) ends beyond length 26999 at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1283) at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1162) at android.text.SpannableStringBuilder.toString(SpannableStringBuilder.java:1184) at com.amaze.filemanager.ui.activities.TextEditorActivity$1.run(TextEditorActivity.java:432) at java.util.TimerThread.mainLoop(Timer.java:555) at java.util.TimerThread.run(Timer.java:505) </details> <hr>

**Comment by EmmanuelMess** [comment]
Unofficial version
