### ISSUE TITLE
Zip from multilevel folder created on Amaze are buggy on Windows 10

### ISSUE THREAD

**Issue by MagTun** [TeamAmaze/AmazeFileManager#2686]
**Describe the bug**
When I open on Windows 10 a zip of a multi-level folder created via Amaze, I get "empty folder in windows explorer. If I use 7zip, the folder is extracted but the subfolders type is set to file so I can't access their contents.

**To Reproduce**
1. Go to Amaze and create a folder with some subfolders and files
2. Click on the parent folder and select compress (you can also enter this parent folder and select the subfolders and files)
3. Send the zip to windows 10
4. Double click on the zip. You can also open it with 7zip 

**Expected behavior**
Well, seeing on windows 10 the same structure as the one I zipped in Amaze

**Screenshots**
On the left the zip in windows explorer, on the right the folder extracted with 7zip (src and data are supposed to be folders each containing several files):

![image](https://user-images.githubusercontent.com/15843700/126036203-1898a8ff-040e-411a-b747-69cb208baa65.png)

**Smartphone (please complete the following information):**
 - Device: Redmi7a
 - OS: Android 10
 - Rooted: No
 - Version: 3.6.1

**Additional context**
Thanks for your time!

**Comment by EmmanuelMess** [comment]
This has to be check if it is a compressing bug or a windows 10 bug.

**Comment by TranceLove** [comment]
I'd believe this is a limitation of Windows 10 Compressed Folder itself. Perhaps possible to create a zip of such folder structure with Windows 10, and compare with the one created by Amaze or just zip4j (the library we are using for handling zips).

May want to put it to lower priority since 7zip is just easily available as Paint.NET do IMO, though I do agree less hassle is always the best thing.

**Comment by MagTun** [comment]
@TranceLove,  it's not working even with 7zip: on the 7zip printscreen (on the right) you can see that src and data (which are folders each containing several files) are extracted as file type and not folder. Their content are inaccessible even via 7zip.

**Comment by TranceLove** [comment]
Noted.

From what I compare the zip entries between Windows 10 compressed folders and ZipService/zip4j, most notable is a prefix `/`

Under `zip -lv ${zip file}`, Windows 10 compressed folders shows
```
    1380  Defl:N      363  74% 2021-09-09 20:11 6207d99d  memstick/PSP/SYSTEM/CACHE/NPJH50263.glshadercache
     428  Defl:N      159  63% 2021-09-08 00:36 cc8ca2bf  memstick/PSP/SYSTEM/CACHE/UCJS10100.glshadercache
    2044  Defl:N      587  71% 2021-09-10 22:30 02bb45a6  memstick/PSP/SYSTEM/CACHE/ULUS10025.glshadercache
    1364  Defl:N      393  71% 2021-08-16 09:14 8adf7471  memstick/PSP/SYSTEM/CACHE/ULUS10064.glshadercache
     485  Defl:N      251  48% 2021-09-10 22:38 9bed13f4  memstick/PSP/SYSTEM/controls.ini
   10396  Defl:N     3353  68% 2021-09-10 22:38 a659248b  memstick/PSP/SYSTEM/ppsspp.ini
```
While Amaze showed
```
31260267  Defl:N  8423970  73% 2021-09-01 23:20 a9066149  /leakcanary-com.amaze.filemanager.debug/2021-09-01_23-20-11_652.hprof
29035555  Defl:N  7762630  73% 2021-09-02 22:40 e3bfdec3  /leakcanary-com.amaze.filemanager.debug/2021-09-02_22-40-40_263.hprof
29863204  Defl:N  7929352  73% 2021-09-11 00:02 e1f92f04  /leakcanary-com.amaze.filemanager.debug/2021-09-11_00-02-43_373.hprof
33770730  Defl:N  8794658  74% 2021-09-11 00:03 e4cbe8f6  /leakcanary-com.amaze.filemanager.debug/2021-09-11_00-03-50_526.hprof
```

Will check.
