### ISSUE TITLE
Use generated IV instead of hard coded ones, even in build file

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#2702]
It is best to generate the IV for file encryption on first app starts. The IV will then be saved in app's preferences and kept secret (except rooted devices, where one can access app's private storage easily).

Since files cannot be decrypted anyway if user deliberately clear app's settings, app's behaviour is not changed at this point.

However, we also need to take care of users who are using hardcoded IV and upgraded our app - that is, this feature will be a breaking change. So I will suggest this to be done at 4.0 and we can have more time on deciding what to do.

**Comment by VishalNehra** [comment]
Continued discussion at #2841
