### ISSUE TITLE
Network file sharing: protocol change (WebDAV/http(s)/sftp/scp).

### ISSUE THREAD

**Issue by 0xlne** [TeamAmaze/AmazeFileManager#2704]
**Is your feature request related to a problem? Please describe.**
Amaze uses the ftp(s) protocol, which has been removed from mainstream browsers (example: firefox). Accessing files from other devices (laptops/regular non-Windows computers) is thus a challenge without additional software.

**Describe the solution you'd like**
Consider replacing or enriching the list of protocols to choose from for network file sharing. Example of universal ones WebDAV, http(s).
Secure alternative: sftp/scp.

**Comment by TranceLove** [comment]
@0xlne WebDAV server request was seen in #1163.

Last time I checked with Bromite (Chromium's derived, which is Chrome's derived), FTP server browsing is still possible, and I think Firefox would behave the same.

(Disclaimer: 99% Firefox in daily usage, except unusual situations)

Personally I think WebDAV is even less popular than FTP server. Additionally, one must deal with WebDAV over HTTPS, which in turn requires self signed cert - like #2492, requiring end user to install CA cert in advance.

SFTP/SCP to replace FTP server is indeed a good idea however, and I'd consider it a better solution than WebDAV if we are to replace the FTP server.

**Comment by 0xlne** [comment]
Thank you for taking the time to think about this & share your thought process ;]

**Comment by EmmanuelMess** [comment]
Dupe #1163
