### ISSUE TITLE
Running tests seems to have broken

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2717]
Lately tests for PR have not been running, there are issues downloading correct files, and compilation errors, but the CI passes for some reason.

https://github.com/TeamAmaze/AmazeFileManager/runs/3231527608#step:6:1212

I cannot get the tests to run on my PC either.

**Comment by EmmanuelMess** [comment]
ping @TranceLove

**Comment by TranceLove** [comment]
Possible something was going on.

Separate Macbook, can be considered a clean one, got this during test run, then it just hang at running a certain number of tests.

```
com.amaze.filemanager.ui.activities.MainActivityTest > testUpdateSmbExceptionShouldNotThrowNPE FAILED
    java.lang.ExceptionInInitializerError at AndroidTestEnvironment.java:114
        Caused by: java.lang.IllegalStateException at ApplicationShutdownHooks.java:66
```
