### ISSUE TITLE
Trying to open navigation drawer using swipe gesture for devices with back gesture on sides

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2734]
So since most of OEMs are shifting to navigation gestures instead of navigation buttons at bottom, the left screen swipe to open navigation drawer is hindering with the system gesture. Ideally we should disable left screen gesture by system and allow it to open navigation drawer otherwise user has to press on hamburger icon which is quite high up on the screen.

**Comment by EmmanuelMess** [comment]
Any ideas how Telegram does this? Because Telegram has the ability to swipe right anywhere on the screen to open drawer, and has folders (that work similar to our work spaces), so this issue should have presented to them too.

**Comment by VishalNehra** [comment]
Nice thought. I'll check.
