### ISSUE TITLE
Open folders in new task

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#2744]
![20210822_183538](https://user-images.githubusercontent.com/48226312/130356355-47d44e83-4076-4240-9cf2-2c6c518f0275.jpg)
![20210822_183534](https://user-images.githubusercontent.com/48226312/130356368-5eedf13c-6a56-4978-a2fe-72beb178ceb4.jpg)
- Screenshot from [Material Files ](https://github.com/zhanghai/MaterialFiles)

https://user-images.githubusercontent.com/48226312/130356453-eb434be8-3836-40a2-9aff-0fe633ab8336.mp4

#725 #734

**Comment by EmmanuelMess** [comment]
See #3023
