### ISSUE TITLE
Night mode based on "Battery saver"

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#2748]
![Screenshot_2021-08-23-09-58-52](https://user-images.githubusercontent.com/48226312/130390263-fc263415-3b69-4f5e-a448-92fbeb06e044.jpeg)

https://user-images.githubusercontent.com/48226312/130390012-74b6765a-1db5-44ce-a6ba-8c51d057f331.mp4

**Comment by seelchen** [comment]
I would like to work on this. 
I think that an improvement to this feature would be to offer "Based on battery saver" as an additional option for the "Light", "Daytime" and "System" themes. If the option is selected, the selected theme would apply as normal except when battery saver is turned on, which would turn the theme dark.
The other themes are already dark, so this additional option would be pointless.

My plan is to have a toggle button at the bottom of the list to enable "Based on battery saver". The toggle button would only appear when one of the prior mentioned themes is selected.

**Comment by seelchen** [comment]
I tried to integrate the toggle button into the "Theme" dialog. However, I could not get the dialog to update when a theme was selected and keep the dialog open. The GitHub repository of the library used is sadly archived so I don't think that I can get this layout to work.

My plan now is to add the toggle button in the "Appearance" menu under "Theme" and only show the toggle when an appropriate theme is selected.
