### ISSUE TITLE
Bypass open file dialog

### ISSUE THREAD

**Issue by VishnuSanal** [TeamAmaze/AmazeFileManager#2761]
Bypass this step if there's only one supporting app installed

<img src="https://user-images.githubusercontent.com/50027064/131634032-6a978542-2ffa-441a-bce0-77419ae0bb46.jpg" height ="500">

**Comment by CharleeBrown** [comment]
I would like to look into this.

**Comment by VishalNehra** [comment]
@CharleeBrown just to be clear. What we expect is, if there's only one app that'll handle the file type that's being opened, it should directly open the file instead of showing this OpenFileFragment.
Do Let us know if any doubt. You can connect on https://t.me/AmazeFileManager

**Comment by VishnuSanal** [comment]
@CharleeBrown Any updates here?

**Comment by CharleeBrown** [comment]
@VishnuSanal  Sorry, had some personal things pop up and I haven't been able to work on this. You can remove me from it.

**Comment by VishnuSanal** [comment]
> You can remove me from it.

I see you yourself remove your assignment.

> Sorry, had some personal things pop up and I haven't been able to work on this. 

No worries, take care :)
