### ISSUE TITLE
App crashes when entering Downloads folder

### ISSUE THREAD

**Issue by Prahlis** [TeamAmaze/AmazeFileManager#2777]
**Describe the bug**
The app crashes when opening the downloads folder. Next time you open the app it remembers downloads as your most recent folder so it automatically opens it and crashes again and again

**To Reproduce**
1. Go to the downloads folder either via the side menu or via the folder structure in Android.
2. The app crashes. This happens every time.

**Expected behavior**
The app doesn't crash

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - OS: Android 10
 - Rooted: No
 - Version: 3.6.1

**Comment by EmmanuelMess** [comment]
We need the stack trace it gives you after it crashes.
