### ISSUE TITLE
Open text files in new task is broken

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2783]
Open text files in new task doesn't work anymore.

To reproduce:

1. Set the option as active.
2. Create a text file
3. Open the text file with AmazeTextEditor

Now, the text file has no "up" button (arrow on appbar), and if you go to [recent apps](https://developer.android.com/guide/components/activities/recents), you dont have Amaze as an app.

With this option you should be able to switch beween the Amaze app and any text files you have opened without using the app, just with the OS, via the [recents screen](https://developer.android.com/guide/components/activities/recents).

-----

This now has a bounty, [here](https://app.bountysource.com/issues/111966450-open-text-files-in-new-task-is-broken).

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by VishalNehra** [comment]
Test github telegram bot

**Comment by uli-on** [comment]
Please, somebody check the archive viewer, seems to include that one, too.

**Comment by VishnuSanal** [comment]
> Please, somebody check the archive viewer, seems to include that one, too.

@uli-on did you mean the archive viewer is broken too? if yes, please create a new issue with more details like what type of file where you trying to open, your device details etc.

**Comment by uli-on** [comment]
Sorry, Vishnu, I know too little about the open-as-separate-task feature in order to place a bug report for it. It's just - like I wrote in the translation topic - that I couldn't find any difference in behaviour between a) setting activated and and opening a zip and b) setting deactivated and opening a zip.

**Comment by EmmanuelMess** [comment]
This now has a bounty, [here](https://app.bountysource.com/issues/111966450-open-text-files-in-new-task-is-broken).

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by Tooniis** [comment]
@EmmanuelMess can you confirm this issue is still present? If yes, can you share some reproduction steps? I can't reproduce this on latest release/4.0 branch 45e82bfae195249cf1ac36e32843af0fc08d27b8 (although I'm not sure I understand what the bug is exactly, hence why I'm asking for reproduction steps).

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess can you confirm this issue is still present? If yes, can you share some reproduction steps? I can't reproduce this on latest release/4.0 branch [45e82bf](https://github.com/TeamAmaze/AmazeFileManager/commit/45e82bfae195249cf1ac36e32843af0fc08d27b8) (although I'm not sure I understand what the bug is exactly, hence why I'm asking for reproduction steps).

To reproduce:

1. Set the option as active.
2. Create a text file
3. Open the text file with AmazeTextEditor

Now, the text file has no "up" button (arrow on appbar), and if you go to [recent apps](https://developer.android.com/guide/components/activities/recents), you dont have Amaze as an app.

With this option you should be able to switch beween the Amaze app and any text files you have opened without using the app, just with the OS, via the [recents screen](https://developer.android.com/guide/components/activities/recents).
