### ISSUE TITLE
Adhere to Google drive branding guidelines

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2814]
This is a part of ongoing approval process for Google Drive API for Amaze. Marking high priority as if not done before Sept end we won't be able to serve to Google drive api requests.
 We have to adhere to Google drive branding guidelines. We seem to be missing few things
- Add a (TM) at the end of name
- Replace existing with suggested icon

More info https://developers.google.com/drive/api/v3/branding

**Comment by TranceLove** [comment]
People who will work on this, use this when you need the Google Drive icon. It has XML Drawables so you don't need to worry about scaling issues or work with different resolutions.

https://materialdesignicons.com/icon/google-drive

**Comment by TranceLove** [comment]
The "Works with Google Drive" badge, perhaps better put it at the Cloud plugin.

https://developers.google.com/drive/api/v3/branding#use_the_works_with_google_drive_badge
