### ISSUE TITLE
Aescrypt support

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#2841]
Currently we are writing our own file encryption and decryption routines. It would be nice if we can migrate to [Aescrypt](https://www.aescrypt.com), a documented, (seemingly) widely used, cross platform file encryption format.

Aescrypt file format contains IV in the encrypted file itself. Not just we can lift the overhead of solving problems that end user cannot decrypt their files when they uninstalled Amaze on their device, encrypted files can also be shared across devices and platforms.

Aescrypt file format spec:
https://www.aescrypt.com/aes_file_format.html

On their website there is a Apache-licensed Java code that can be downloaded. And in fact, [Android version of Aescrypt does exist](https://play.google.com/store/apps/details?id=com.dewdrop623.androidcrypt): https://github.com/ndew623/AndroidCrypt

**Comment by VishalNehra** [comment]
How can it decrypt even after reinstalling?

**Comment by TranceLove** [comment]
It uses the IV embedded in the encrypted file itself.

Reading the file spec aside, may also read the source code of `AESCrypt.decrypt()`.

https://github.com/ndew623/AndroidCrypt/blob/f20a1ef1f09c93ef6f699ecd80068502b1219a09/app/src/main/java/es/vocali/util/AESCrypt.java#L411-L518

**Comment by VishalNehra** [comment]
@TranceLove IV isn't an issue, it's just a salt.. the issue is the key.  where does this generating and keep it's key?

**Comment by VishalNehra** [comment]
@TranceLove Currently we're using android keystore that keeps the key with it, it's in android's sandbox and is safe, but loses the key once app is uninstalled..

**Comment by TranceLove** [comment]
@VishalNehra This part can do exactly what we planned to do for improvement: generate at startup and save it to preferences 😀
