### ISSUE TITLE
Short description of Quick access & Recent files feature

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#2896]
![20210922_184720](https://user-images.githubusercontent.com/48226312/134350749-eb387fc8-3b8e-48f3-97dc-58f846954ee0.jpg)

mention a short description of what it does

_Originally posted by @shuvashish76 in https://github.com/TeamAmaze/AmazeFileManager/discussions/2831_

-----

This now has a bounty, [here](https://app.bountysource.com/issues/104758276-short-description-of-quick-access-recent-files-feature), bounty expires in one month from 2022-01-14, if you have been working, please alert us so that we can extend it.

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by EmmanuelMess** [comment]
This issue now has a [bounty](https://app.bountysource.com/issues/104758276-short-description-of-quick-access-recent-files-feature).
