### ISSUE TITLE
Crash when opening changelog without a web browser

### ISSUE THREAD

**Issue by THEtomaso** [TeamAmaze/AmazeFileManager#2913]
### Issue:
"Guru Meditation" App/UI crash.

### How to reproduce:
Go to 'Settings' > 'About Amaze File Manager' > 'Changelog'.

### Note:
Not internet connected phone.

--

### System info:
* Amaze File Manager version: v3.6.5
* Android device: Samsung Galaxy XCover 4s
* Android version: 11

**Comment by VishalNehra** [comment]
Yes that is relevant. You essentially don't have any app available that can handle the INTENT to open a webpage.

**Comment by voidEnum** [comment]
Hi, I wanted to start working on this, but I believe it has already been fixed by the commit that fixed issue #3963. Just letting you know so you can mark is as closed.
