### ISSUE TITLE
Add different panes to preferences

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2968]
Add different panes to preferences activity. 

-----

This now has a bounty, [here](https://app.bountysource.com/issues/104727912-add-different-panes-to-preferences), bounty expires in one month from 2022-01-13, if you have been working, please alert us so that we can extend it.

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by aniket691** [comment]
Can u elaborate and assign me. I want to take this issue.

**Comment by VishnuSanal** [comment]
> Can u elaborate

@EmmanuelMess

**Comment by EmmanuelMess** [comment]
Something like this:
![imagen](https://user-images.githubusercontent.com/10991116/143321240-c821a7d4-22d4-46e9-a2d6-a63a87af6973.png)

This issue requires a discussion on the design first. Use this like as guide https://developer.android.com/guide/topics/ui/settings/organize-your-settings and the design of Telegram's preferences.

**Comment by nicbn** [comment]
I'm working on this

**Comment by EmmanuelMess** [comment]
Please provide a small graph of how it will be layout so that the design can be approved.

**Comment by nicbn** [comment]
![image](https://user-images.githubusercontent.com/20824501/150417225-0f53f77a-d0d0-443e-bc4e-7a2c9c531174.png)

<details>

* Appearance
  * Theme
  * Color (inline the current page)
  * Use circular icons
  * Show dividers
  * Show headers
  * Automatically hide toolbar
  * Number of columns in grid view
  * Enable marquee effect for file names
* Interface
  * Sidebar
  * All other show/hide options
  * Back navigation
  * Drag and drop preference
  * Advanced:
    * Show permissions
* Behavior
  * Remember paths
  * Clear cache
  * Advanced search
  * Custom paths
  * Open as new task
  * Archive folder
  * Advanced:
    * Use legacy for root
    * Root explorer
* Security
  * Master password
  * Fingerprint

</details>

WDYT?

**Comment by EmmanuelMess** [comment]
I like it. @VishalNehra @TranceLove @VishnuSanal ?

**Comment by EmmanuelMess** [comment]
@nicbn are the icons what the material design guidelines recommends?

**Comment by nicbn** [comment]
I couldn't find anything about icons on settings at the material design guidelines. I simply used icons I found appropriate for each category and added a backdrop as the Android system settings does.

**Comment by EmmanuelMess** [comment]
> I couldn't find anything about icons on settings at the material design guidelines. I simply used icons I found appropriate for each category and added a backdrop as the Android system settings does.

It looks like Android settings has that kind of icons, so its ok.

**Comment by TranceLove** [comment]
@EmmanuelMess +1. Looks really nice.

**Comment by VishalNehra** [comment]
+1

**Comment by VishalNehra** [comment]
although this can be conflicting with #3109

**Comment by EmmanuelMess** [comment]
@nicbn The layout is approved, but dont touch the about activity layout.
