### ISSUE TITLE
I can't Access recent files. 

### ISSUE THREAD

**Issue by Amalreji111** [TeamAmaze/AmazeFileManager#3000]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishalNehra** [comment]
Can you update to v3.6.7 and try?

**Comment by Amalreji111** [comment]
Okay
