### ISSUE TITLE
Reason for requesting "All files access" is not mentioned

### ISSUE THREAD

**Issue by sivaraam** [TeamAmaze/AmazeFileManager#3012]
**Describe the bug**
Recently I upgraded the Amaze to v3.6.7. After that when I opened the app it asked me for the "All files access" permission out of the blue and it was mentioned that the app would *not* function without it. Screenshot of the dialog:

![image](https://user-images.githubusercontent.com/12448084/141522843-82d6b467-7d03-4f91-9154-27e42e06dee2.png)

Honestly, my knee-jerk reaction is that the dialog had a threatening tone. While the intention would've been good, the words are failing to convey it. It would be nice if the request was put in a more polite way.

One other thing that totally confused: Why does the app even need the "All files access" permission mandatorily out of the blue? I've been using the app on an Android 11 device for all this time without much issue. So, I couldn't really understand what caused the app to request for the "All files access". It would be wonderful if someone could explain the reasoning behind this. Also, if possible do evaluate if this could be made optional. I for one haven't observed any glaring issues while using the app when it didn't have the "All files access" permission.

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - OS: Android 11
 - Rooted: No
 - Version: 3.6.7

**Comment by VishalNehra** [comment]
Yes, agreed. I should've thought out better on the message. Already received a review stating they didn't like the permission and I had to clarify to them that we already had this permission it's just Google is forcing us to put this otherwise we won't be able to publish updates after 1 Nov 2021 on Play Store.
I say we make another hotfix for this plus the changeset in #3008
@TranceLove can you please work on this?

**Comment by TranceLove** [comment]
That means improving the wordings in #3008 then - just found that sentence did had to improve anyway.

**Comment by VishalNehra** [comment]
> That means improving the wordings in #3008 then - just found that sentence did had to improve anyway.

Yes

**Comment by sivaraam** [comment]
>  I had to clarify to them that we already had this permission it's just Google is forcing us to put this otherwise we won't be able to publish updates after 1 Nov 2021 on Play Store.

But I don't remember granting this permission to the app before. I had to grant it just now. Was it possibly optional before and I just didn't use any features that would've required this? 🤔

**Comment by VishalNehra** [comment]
> > I had to clarify to them that we already had this permission it's just Google is forcing us to put this otherwise we won't be able to publish updates after 1 Nov 2021 on Play Store.
> 
> But I don't remember granting this permission to the app before. I had to grant it just now. Was it possibly optional before and I just didn't use any features that would've required this? 🤔

Like I said, Google has made this mandatory to put if we want to publish updates to app after 1 Nov
 https://developer.android.com/distribute/best-practices/develop/target-sdk
