### ISSUE TITLE
Allow FTP on LAN for Wifi

### ISSUE THREAD

**Issue by iamaravindim** [TeamAmaze/AmazeFileManager#3024]
# Problem
The current version of the app only supports FTP over WiFi hotspot. It doesn't allow the FTP to be run over Home WiFi which allows it to be accessible in the LAN network.

# Solution
Give option to the user whether to use FTP over WiFi or using WiFi hotspot in the FTP screen. Add functionality for the WiFi based FTP transfer as well.This allows user to access the contents of the phone through the laptops/desktops/phones connected to the same WiFi. 

## Additional details
This is very useful feature for people who don't want to carry around wires for connecting phones to PC. The current FTP feature forces the user to switch the network connection of the Laptop/Desktop to transfer files over to it. Having it over the already connected WiFi makes it faster to use and also allows both the devices to do other network tasks like browsing the web while the FTP file transfer is happening.

**Comment by TranceLove** [comment]
@iamaravindim You should be able to do this already - the built-in FTP server can run as long as you are connected to a network, wired or wireless; only in situations where WiFi is not available you will need the device's hotspot mode.

But do let us know if you have any problem using the FTP server with your existing WiFi network.
