### ISSUE TITLE
Modify strings and default value on App Manager

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#3026]
![Screenshot_2021-11-15-14-46-47](https://user-images.githubusercontent.com/48226312/141755039-89769350-b98b-41a7-9061-f6549cd228cb.jpeg)
- Rename "Third party apps" to "User apps"

![Screenshot_2021-11-15-14-50-05](https://user-images.githubusercontent.com/48226312/141755373-c65a3190-4ceb-417d-802a-3dc2c9eefbfa.jpeg)
- Keep "Show system apps" unchecked by default

**Comment by pree-T** [comment]
May I work on this?

**Comment by VishnuSanal** [comment]
> - Add F-Droid option (check if the app available on F-Droid)

@shuvashish76 This works out of the box, it shows a picker with Play Store & the F-Droid client you've installed

> May I work on this? 

Sure, please do.

**Comment by VishalNehra** [comment]
Althogh, i'm not sure if the part 'remember show system apps' is what we want. @shuvashish76  don't bundle multiple feature requests into one.

**Comment by pree-T** [comment]
I am just supposed to add the fdroid option? @VishnuSanal

**Comment by VishalNehra** [comment]
As suggested by @VishnuSanal fdroid option works out of the box. For now can you just rename 'third party apps' to 'user apps'?
@shuvashish76 please confirm about the fdroid thing.

**Comment by pree-T** [comment]
Yes, I will do that @VishalNehra

**Comment by VishnuSanal** [comment]
> Althogh, i'm not sure if the part 'remember show system apps' is what we want.

I think persisting the value of "Show system app" would be good. Or making it unchecked by default.

> I am just supposed to add the fdroid option? @VishnuSanal
> > For now can you just rename 'third party apps' to 'user apps'?

Yes, and I think you can wait until a decision is made, so that your work won't go in vain if things change!

**Comment by shuvashish76** [comment]
@VishnuSanal 
> This works out of the box, it shows a picker with Play Store & the F-Droid client you've installed

Ok.👍🏿

> I think persisting the value of "Show system app" would be good. Or making it unchecked by default.

I think most of the time we use App Manager feature to backup "**User Apps**" not System apps. So +1 for _uncheck Show system apps_. But it's just my personal preference. 

I believe "Remember last selection mode" would be good for everyone.

---
@VishalNehra 
> Althogh, i'm not sure if the part 'remember show system apps' is what we want

Remember last selection mode not <del> 'remember show system apps' <del>

**Comment by VishalNehra** [comment]
> I think most of the time we use App Manager feature to backup "**User Apps**" not System apps. So +1 for _uncheck Show system apps by default_. But it's just my personal preference.

Then what can be done is,  by default 'show system apps' can remain unchecked always, only when it's checked do we show the system apps. I don't want to remember last selection for this checkbox is my point.

**Comment by shuvashish76** [comment]
> Then what can be done is, by default 'show system apps' can remain unchecked always, only when it's checked do we show the system apps. I don't want to remember last selection for this checkbox is my point.

Ok👍🏿 (_atleast that satisfies my personal preference_)

> don't bundle multiple feature requests into one.

Sorry, mentioned here as its related to App Manager.

---
Small addition to this issue
`AppManager > Sort By > Last Modified `

The meaning of **Modified** could be `change in signature`, `disabled/enabled`, `cleared app's cache or data` etc...

Rename "Last Modified" to "**Last Updated**" 
(I believe the current option is for Last Updated as it matches with [AM](https://github.com/MuntashirAkon/AppManager)'s `Last Update` apps sorting)

**Comment by pree-T** [comment]
Will someone brief what I am actually supposed to do as a fix to this issue?

**Comment by VishalNehra** [comment]
@pree-T @shuvashish76 update this issue title and description with what we discussed. Also i presume fdroid thing isn't required anymore, so Remove that as well.

**Comment by VishnuSanal** [comment]
> @pree-T @shuvashish76 update this issue title and description with what we discussed. Also i presume fdroid thing isn't required anymore, so Remove that as well.

I did the edit. @VishalNehra @shuvashish76 Please verify.

> Will someone brief what I am actually supposed to do as a fix to this issue?

@pree-T Please take reference from the first comment on this thread (I have edited those)

**Comment by pree-T** [comment]
Thank you @VishnuSanal !

**Comment by pree-T** [comment]
Where will I find the default value of App Manager i. e. , displaying system apps? I tried finding it but couldn't figure out.

**Comment by VishnuSanal** [comment]
@pree-T It's
AppListFragment.java
, IIRC

**Comment by shuvashish76** [comment]
@VishnuSanal thanks

- Ignore f-droid part as it seems unnecessary.
- [x] Rename "Third party apps" to "User apps"
- [x] Keep 'show system apps' option unchecked by default
- [ ] Rename "Last Modified" to "Last Updated" (ping @VishalNehra for confirmation)

@pree-T thanks for picking up this issue :)

**Comment by pree-T** [comment]
I am done with renaming "Third party apps" to "User apps" and renaming "Last Modified" to "Last Updated". However ,I am bit stuck at keeping 'show system apps' option unchecked by default. Can someone help me with this?

**Comment by VishnuSanal** [comment]
> However ,I am bit stuck at keeping 'show system apps' option unchecked by default. Can someone help me with this?

@pree-T It's being checked on `AppsListFragment#onCreateOptionsMenu()` So you can essentially remove that line and it would be good to go :)
