### ISSUE TITLE
SFTP failing to connect over wifi

### ISSUE THREAD

**Issue by aplatypus** [TeamAmaze/AmazeFileManager#3051]
**Describe the bug**
I have 

- I have START-ed the FTP server in Amaze on my tablet (SM-T220, Galaxy Tab A7 lite)
- Filezilla keeps giving me connection timeouts
- command line `sftp` just reports connection closed, no password prompt

**To Reproduce**

1. Amaze FTP server
2. Check IP address from the Wi-Fi
2. settings: host=192.168.xxx,yyy user=tab pw=12344578 port=2211
3. click start
4. start filezilla
5. connect to 'tab'
6. Connection is refused

**Expected behavior**
* Expect a connection to be established*

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: SM-T220, Galaxy Tab A7 lite
 - OS: Android 11
 - Rooted: NO
 - Version: One UI  3.1

**Additional context**
FTP Clients on Linux 20.04
- filezilla
- sftp (openssh)

**Comment by TranceLove** [comment]
@aplatypus Sorry but FTP server in Amaze File Manager does only FTP and FTP over SSL protocols.

Please use command line ftp or choose FTP when using Filezilla to connect to Amaze's FTP server.
