### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jeze001** [TeamAmaze/AmazeFileManager#3089]
Hello Developers, congratulations for the excellent work with this OpenSource file manager, it is very complete, I would just like to leave a suggestion, could you add a file share on a local network with this file manager, for example to be able to download and upload files to the cell phone or Desktop, accessing the smartphone's local IP address in the browser, this function would be very interesting, as I don't find many opensource software that do this, the best was Trebleshot, but it has been discontinued, so it would be very interesting to have this function present in this manager in the next version, is the suggestion.
Thanks.

**Comment by EmmanuelMess** [comment]
Dupe #1317. Please add a comment there if you feel something is missing.
