### ISSUE TITLE
Add feature of browsing terminal emulator directories as folders in Android

### ISSUE THREAD

**Issue by Ashutoshlakhnaora** [TeamAmaze/AmazeFileManager#3091]
Need a feature to browse terminal emulator 'termux ' directories as folders in Android.

I will suggest to add terminal emulator button below root. 
It would be good.

![Screenshot_2021-12-29-18-01-50-22_c805f5d11352526404ab3b8e4b655523.jpg](https://user-images.githubusercontent.com/96478739/147665076-1f73fbe3-e07d-4c96-af12-87d6ef6e073e.jpg)![Screenshot_2021-12-29-18-00-36-99_5734e8eb49b4234b62f913f831715b0f.jpg](https://user-images.githubusercontent.com/96478739/147665094-04ee183e-2020-4b9f-8016-12c7d1df59ab.jpg)![Screenshot_2021-12-29-18-15-40-74_5734e8eb49b4234b62f913f831715b0f.jpg](https://user-images.githubusercontent.com/96478739/147665109-fe530c1f-a09b-457c-944c-160ad67125a0.jpg)![Screenshot_2021-12-29-18-15-46-34_5734e8eb49b4234b62f913f831715b0f.jpg](https://user-images.githubusercontent.com/96478739/147665115-b8a53be0-569b-497f-925e-a940e5ad905b.jpg)

**Comment by Ashutoshlakhnaora** [comment]
![Screenshot_2021-12-29-18-15-46-34_5734e8eb49b4234b62f913f831715b0f.jpg](https://user-images.githubusercontent.com/96478739/147663724-f61bb35f-e165-4785-bf72-ca60af56117f.jpg)![Screenshot_2021-12-29-18-15-40-74_5734e8eb49b4234b62f913f831715b0f.jpg](https://user-images.githubusercontent.com/96478739/147663731-4d72cf17-d15c-4014-bbae-9488b00dde6e.jpg)![Screenshot_2021-12-29-18-00-36-99_5734e8eb49b4234b62f913f831715b0f.jpg](https://user-images.githubusercontent.com/96478739/147663741-93b32228-b725-4a21-b33c-eb7f98633891.jpg)![Screenshot_2021-12-29-18-01-50-22_c805f5d11352526404ab3b8e4b655523.jpg](https://user-images.githubusercontent.com/96478739/147663747-77438750-743c-4f62-856d-f82aa75fd8fe.jpg)

**Comment by Ashutoshlakhnaora** [comment]
Its a request plz include feature of browsing terminal file in Android
 as folders and files are browsed in Android.
As we open directories using character user Interface (CLI).
It some how relate with GUI interface in linux mint etc...   along with terminal.
Thanks

This feature is in the inbuild Android file manager that is hidden in system apps.

**Comment by john-peterson** [comment]
I am also looking for a termux integration if you know another app tell me. I might try to copy it from Squircle into this. I am addicted to Linux coding and need it on the go

**Comment by john-peterson** [comment]
I mean acode can open the termux home folder. It is needed for execution chmod +X. But it can't open sftp to my build machine... Really confusing seems like I am the first one to do serious development on the phone instead of desktop

**Comment by VishnuSanal** [comment]
thanks for reaching out with a new feature request. this feature is already being tracked in #2666, please follow the specified issue to get updates on this feature.
