### ISSUE TITLE
Option to disable File loading animation

### ISSUE THREAD

**Issue by gitpubber** [TeamAmaze/AmazeFileManager#3106]
**Is your feature request related to a problem? Please describe.**
Yeah. I find animation as quite weird(My opinion).

**Describe the solution you'd like**
I would like an option to disable animations/atleast respect default animation mentioned in android settings

**Describe alternatives you've considered**
Other apps like [Material Files](https://github.com/zhanghai/MaterialFiles) do offer option to disable animations.

**Additional context**
N/A

**Comment by EmmanuelMess** [comment]
I think this is a won't fix, as adding code to remove animations seems a bit excessive and not very much used.
