### ISSUE TITLE
Blank screen after opening on Android 11

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#3138]
**Describe the bug**
![photo_2022-01-20_19-38-36](https://user-images.githubusercontent.com/10991116/150433480-6b72950f-663b-47c3-ba9f-2836a22e7549.jpg)

**To Reproduce**
1. Open app

-----

This now has a bounty, [here](https://app.bountysource.com/issues/104944933-blank-screen-after-opening-on-android-11), bounty expires in one month from 2022-01-20, if you have been working, please alert us so that we can extend it.

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by EmmanuelMess** [comment]
Line 402 of MainActivity is getting called: `java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()`

**Comment by NanyangTaiji** [comment]
Still happens now and then, have to reinstall to get rid of it.

**Comment by VishnuSanal** [comment]
> Still happens now and then, have to reinstall to get rid of it.

@NanyangTaiji Do you have a crash report? If yes, feel free to open a new issue.

**Comment by NanyangTaiji** [comment]
> 

Sorry, not crash, just hang with black screen, or white screen. After that, exit/reopen will start with the same black/white screen. It then needs to restart the device to get back to the normal. It happens more often when an external USB driver was attached, so not able to trace Log cat.

**Comment by VishnuSanal** [comment]
> Sorry, not crash, just hang with black screen, or white screen. After that, exit/reopen will start with the same black/white screen. It then needs to restart the device to get back to the normal. It happens more often when an external USB driver was attached, so not able to trace Log cat.

@EmmanuelMess

> It happens more often when an external USB driver was attached, so not able to trace Log cat.

@NanyangTaiji You still can extract the logs, please try. Also, verify that you're on the latest version.

**Comment by ValdikSS** [comment]
Just for the information, I just installed Amaze on Android 4.4.4 and all I see is black screen. I don't know if it's related to this issue.

**Comment by VishnuSanal** [comment]
not reproducible, closing. can be reopened upon regression.

**Comment by VishnuSanal** [comment]
unpinning this for now...
