### ISSUE TITLE
Add a splash screen when Amaze loads

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#3139]
Follow these guidelines: https://developer.android.com/guide/topics/ui/splash-screen

**Comment by MohitMandalia** [comment]
Please assign this issue to me if it is open for contribution.

Thanks.

**Comment by EmmanuelMess** [comment]
> Please assign this issue to me if it is open for contribution.
> 
> Thanks.

Assigned!

**Comment by dhruvpatidar359** [comment]
Hello @EmmanuelMess  i am ready to work on it but the problem is the minimun sdk requirement for creating a new activity is now 16 but in the gradle.build the minimum requirement written is 14 , can i change the build.gradle(minSdk to 16) for working on it.  Or i am doing something wrong.


Thanks.

**Comment by EmmanuelMess** [comment]
@dhruvpatidar359 you will have to create it by hand or backport it.

**Comment by VishalNehra** [comment]
https://user-images.githubusercontent.com/5211568/209670365-1411cdaf-621d-438e-8faf-4139490cc1aa.mp4

I think we can close this issue as new android versions by default shows a splash screen.

**Comment by dhruvpatidar359** [comment]
ok sure

**Comment by nilerudra** [comment]
Is this issue is open?

**Comment by VishnuSanal** [comment]
> Is this issue is open?

not likely, since there's a default splash screen from Android 13+ @VishalNehra @TranceLove @EmmanuelMess thoughts?

**Comment by EmmanuelMess** [comment]
> not likely, since there's a default splash screen from Android 13+ @VishalNehra @TranceLove @EmmanuelMess thoughts?

If the splash screen for Android 13 works as ours would, I wouldn't close this issue.

**Comment by VishnuSanal** [comment]
closing, since it would be redundant from Andorid 13+. @nilerudra you can look into other good first issues [here](https://github.com/TeamAmaze/AmazeFileManager/issues?q=is%3Aopen+is%3Aissue+label%3A%22Issue-Easy+%28good+first+issue%29%22)
