### ISSUE TITLE
Reword "Show the date and time when the file was modified last time"

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#3146]
"Show the date and time when the file was modified last time" to "Show the date and time of last modification" (less words) or "Show the date and time when the items was modified last time", reported as issue in Transifex.

**Comment by ashway171** [comment]
Where do we need to reword this phrase?

**Comment by VishnuSanal** [comment]
> Where do we need to reword this phrase?

In `strings.xml` (@EmmanuelMess CMIIW)

**Comment by ashway171** [comment]
Could you please assign it to me?
