### ISSUE TITLE
Files encryption "Warning" related suggestions

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileManager#3156]
Current **Warning** screen👇🏿
![Screenshot_2022-02-05-12-58-54](https://user-images.githubusercontent.com/48226312/152632989-0e92b4ea-b481-46a9-91d9-af035dcc2464.jpeg)

Usually we never read such disclaimer/warning, we just click yes/ok/agree/accept. Though Amaze has another extra button for it called "Don't Inform Again" which makes it worse.

Suggestions: 
1. add a timer to current "Got it" button (check screen recording)
2. add a checkbox for "Don't inform again" to the bottom_left of the screen(check screenshot)
3. Replace "Don't inform again" with Exit

https://user-images.githubusercontent.com/48226312/152633297-67582d93-3747-44d3-a1ba-eb0437a4c6fb.mp4

source: [SecondScreen](https://github.com/farmerbb/SecondScreen) app

![Screenshot_2022-02-05-11-36-31](https://user-images.githubusercontent.com/48226312/152633334-6535542b-8cbb-4536-97ee-2bf7bff7f3b7.jpeg)

source: [AppManager](https://github.com/MuntashirAkon/AppManager) app

---
Now ppl just can't "_mark the checkbox-click Got it_" & Encrypt quickly.
We make sure users read the Disclaimer by adding 3 steps in total. (_though for some ppl 5sec is not enough to read full disclaimer it prevents users to skip the warning subconsciously/auto-mode_)

This is an important issue as ppl losing their personal files & IMO Amaze should provide a quick-hotfix as soon as possible till Amaze add #2841.

ThankYou🙏🏿

**Comment by VishnuSanal** [comment]
> Usually we never read such disclaimer/warning, we just click yes/ok/agree/accept. Though Amaze has another extra button for it called "Don't Inform Again" which makes it worse.

> Suggestions:
> 
> 1. add a timer to current "Got it" button (check screen recording)
> 2. add a checkbox for "Don't inform again" to the bottom_left of the screen(check screenshot)
> 3. Replace "Don't inform again" with Exit

> Now ppl just can't "_mark the checkbox-click Got it_" & Encrypt quickly. We make sure users read the Disclaimer by adding 3 steps in total. (_though for some ppl 5sec is not enough to read full disclaimer it prevents users to skip the warning subconsciously/auto-mode_)

> This is an important issue as ppl losing their personal files & IMO Amaze should provide a quick-hotfix as soon as possible till Amaze add #2841.

+1 to all your suggestions, but #2841 is almost done (track at #3182). Behavior of the aforementioned dialog [is changing](https://github.com/TeamAmaze/AmazeFileManager/pull/3182#issuecomment-1061678264) too. So the possibility of user doing this in _auto mode_ would be reduced. Now the user would have to uncheck the AESCrypt checkbox and accept the confirmation & enter the passwords inorder to successfully encrypt a file/folder using `.aze.` format. What do you think? @shuvashish76
