### ISSUE TITLE
Update F-Droid version

### ISSUE THREAD

**Issue by dtbj** [TeamAmaze/AmazeFileManager#3172]
F-Droid version is too old maybe you devs forgot to take a look please update it.

**Comment by VishnuSanal** [comment]
@dtbj Amaze is temporarily not available on Fdroid. While we work with fdroid team to figure out the issue, you can use Izzy's fdroid repo to download Amaze.
It is maintained by one of the maintaners of original fdroid and has exactly the same version fdroid would provide.

You can download it here

**Comment by dtbj** [comment]
@VishnuSanal Thanks for the support but can you tell me why your app is having 
![image](https://user-images.githubusercontent.com/87176273/154413330-4d43c0c6-f183-4326-a4a7-5f25da631837.png)
and can you please tell me on which service you are dependent that you have NonFreeNet Tag??

**Comment by VishnuSanal** [comment]
> can you please tell me on which service you are dependent that you have NonFreeNet Tag??

@VishalNehra

**Comment by shuvashish76** [comment]
Check #1684 discussion.
Subscribe the discussion thread for future updates.
