### ISSUE TITLE
Make App's minimal requirement to Kitkat (4.4)

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#3189]
**Is your feature request related to a problem? Please describe.**
- Devices running below 4.4 is of very low percentage worldwide as of now
- supporting Android below 4.4 is of very low value
- one of the Espresso testing library, UiAutomator, [requires minimal SDK 18](https://developer.android.com/training/testing/other-components/ui-automator). Enable the use of UiAutomator shall also increase code coverage over UI related code

**Describe the solution you'd like**
Declare `minSdkVersion 18` in this line
https://github.com/TeamAmaze/AmazeFileManager/blob/12cc5306a9b80afba16e7ee54e7f2f071c236f73/app/build.gradle#L24

**Describe alternatives you've considered**
None

**Comment by EmmanuelMess** [comment]
it looks like we have a few users with android <4.4 (less than 500 users).

And Google stopped publishing data for android API < 16 but it looks like less than 1%:
![image](https://user-images.githubusercontent.com/10991116/155891955-654b3406-a891-4eed-a090-120b43f79302.png)

**Comment by EmmanuelMess** [comment]
I feel that out of principle we should keep supporting, but it doesn't make much sense. I issue an abstention.

**Comment by EmmanuelMess** [comment]
ping @VishalNehra @VishnuSanal

**Comment by VishnuSanal** [comment]
I feel like we should support older versions too. I've been told that Amaze works on devices that are no longer supported by other FMs including Mi Files & Files by Google.

IDK much about testing, but it necessary to increase the `minSDKVerison` inorder to use `UIAutomator`? Can't we implement 'em for newer versions only, like we do for backward incompatible APIs?

**Comment by VishalNehra** [comment]
@VishnuSanal Amaze will still be usable on older devices it's just there won't be any updates for them.

**Comment by EmmanuelMess** [comment]
> @VishnuSanal Amaze will still be usable on older devices it's just there won't be any updates for them.

And new users won't be able to find Amaze on Play Store.

**Comment by VishnuSanal** [comment]
i vote in favor

**Comment by EmmanuelMess** [comment]
New data

![image](https://user-images.githubusercontent.com/10991116/199791687-634e1f50-9502-4680-aad6-f7c6dd613486.png)

**Comment by VishnuSanal** [comment]
@VishalNehra can you pull out our user API level distribution chart from Play Store too?

**Comment by EmmanuelMess** [comment]
Data for Android 4.4 or below:
![image](https://user-images.githubusercontent.com/10991116/199797926-9ffe74c8-6007-4cb1-86db-8fa55e87f29c.png)
![image](https://user-images.githubusercontent.com/10991116/199798095-e215da7b-10ff-4e07-bad8-2e6485a07f9e.png)

**Comment by ildar** [comment]
I'm just a passer-by.
Yes, supporting such an ancient targets actually doesn't make any sense. I agree.
Yet the moment for that change isn't yet right IMHO ;-)
The question of the UiAutomator is easily solved by replacing one line in the build.prop, right? If so then it really ok to have minsdk == 14 and giving the UiAutomator built with minsdk = 18... I suppose the project doesn't use any API deprecated by the API==18..
Right?
