### ISSUE TITLE
If you add a "." before the file name when renaming, the file cannot be found

### ISSUE THREAD

**Issue by sjl872964789** [TeamAmaze/AmazeFileManager#3218]
**Describe the bug**
If you add a "." before the file name when renaming, the file will not be found again

**To Reproduce**
1. Rename any file
2. Add a "." before the new name
3. It looks like the file is still there (because I can't create a new file with the same name) but it can't be found anymore

**Expected behavior**
Files can be seen and searched

**Screenshots**
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/15941953/158055425-1709b3ae-74b8-43bf-918a-39430fc1ba3b.gif)

**Smartphone (please complete the following information):**
 - OS: Android 8.0
 - Rooted: No
 - Version: 3.6.7

**Comment by VishnuSanal** [comment]
@sjl872964789 A file whose name starts with a dot is a hidden file. You can make it visible by turning on Show Hidden Files and Folders from Settings -> General
