### ISSUE TITLE
Potential problem when sharing cloud files

### ISSUE THREAD

**Issue by Fros1er** [TeamAmaze/AmazeFileManager#3223]
**Describe the bug**
When back navigation is enabled, `mainFragmentViewModel.listElements[0].mode` is always `OpenMode.UNKNOWN`. 
https://github.com/TeamAmaze/AmazeFileManager/blob/adfd4438f33618aca201b16707d152726a4b0eb6/app/src/main/java/com/amaze/filemanager/utils/MainActivityActionMode.kt#L289-L305

**To Reproduce**
As amaze cloud plugin is not available to me in google play, and I doesn't have a paypal account now, so I can't check whether the bug exists now.

**Comment by VishalNehra** [comment]
@Fros1er Should've mentioned this on group. I'll send you the apk file for testing.
