### ISSUE TITLE
Path bar glitch 

### ISSUE THREAD

**Issue by neekless** [TeamAmaze/AmazeFileManager#323]
I'm still having this path bar glitch even on the latest version 3.1.0 beta 2. It's been like this for the past few versions. Apparently not many people have it but I'm very certain this is happening on my phone. Nexus 6p Android 7.﻿

I'm aware that this issue is not present if the Animator Duration Scale in Developer Settings is set to 1.0 or higher, but some users prefer faster animations, and glitches should not happen no matter what the user's choice of animation speed is.

This is only a visual bug and an urgent fix is not needed, but it should still be fixed nonetheless.

https://drive.google.com/file/d/0B0u8_WTGBLT8QUF6LTBxdUtTUkE/view

**Comment by GuardianMajor** [comment]
I have this issue as well and I am running on Nexus 6 (shamu) running 7.1.1 (N6F26R)
That being said, thank you for the app, it looks great and so far seems to work well. 

However, there is some difficulty with copying something from an SMB location to a local device, it hangs showing copying and it ends up freezing up the whole UI and force close is only way around it. If it keeps happening I will document and post it in a new issue.

**Comment by EmmanuelMess** [comment]
I think this was fixed some time ago.
