### ISSUE TITLE
The search bar doesn't follow theme

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#3233]
1. Change theme to dark
2. Open search bar

**Comment by DoozyDoz** [comment]
@VishalNehra , @EmmanuelMess 
In the latest version, this issue has re-appeared yet it was fixed in PR #3237, the code also no longer exists in the latest.

**Comment by VishnuSanal** [comment]
> In the latest version

did you mean v3.7.2?

> this issue has re-appeared yet it was fixed in PR #3237, the code also no longer exists in the latest.

#3237 was merged to `release/3.8` and we haven't rolled v3.8 yet. can you check it after building from `release/3.8`?

**Comment by DoozyDoz** [comment]
> > In the latest version
> 
> did you mean v3.7.2?
> 
> > this issue has re-appeared yet it was fixed in PR #3237, the code also no longer exists in the latest.
> 
> #3237 was merged to `release/3.8` and we haven't rolled v3.8 yet. can you check it after building from `release/3.8`?

I meant 3.8, When you check the changed files from the PR the changes do not exist hence if u run the latest code the issue is still there.

**Comment by VishnuSanal** [comment]
> > > In the latest version
> > 
> > 
> > did you mean v3.7.2?
> > > this issue has re-appeared yet it was fixed in PR #3237, the code also no longer exists in the latest.
> > 
> > 
> > #3237 was merged to `release/3.8` and we haven't rolled v3.8 yet. can you check it after building from `release/3.8`?
> 
> I meant 3.8, When you check the changed files from the PR the changes do not exist hence if u run the latest code the issue is still there.

update ping: it works now - i.e, on v3.8
