### ISSUE TITLE
Failed to move a file

### ISSUE THREAD

**Issue by AcerJhaze** [TeamAmaze/AmazeFileManager#3250]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**
![Screenshot_20220410-120547](https://user-images.githubusercontent.com/103346889/162601021-df53c73d-b60d-4bfd-9e79-e44b38c9b9da.png)

**Comment by VishnuSanal** [comment]
@AcerJhaze Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
