### ISSUE TITLE
crash and exit when try to use certificate installer to open file

### ISSUE THREAD

**Issue by jyjsunny** [TeamAmaze/AmazeFileManager#3304]
**Describe the bug**
crash and exit when try to use certificate installer to open file

**To Reproduce**
1. Click into "Internal Storage"
2. Click on the button "Add a file" in the lower right corner
3. Add a file named "www.google.com"
4. Click on "search" in the upper right corner
5. Type in "www.google.com" to search for it
6. Click on the file name "www.google.com" in the search results
7. Click on "Just Once" and choose to open it with certificate installer
8. Prompt "Certificate Installer has stopped."
9. Crash and exit

**Expected behavior**
The application should not crash and exit because it cannot be opened with the certificate installer.

**Screenshots**

https://user-images.githubusercontent.com/92309998/167291156-9ba13724-9286-45de-b6ed-5e79a7c9041a.mov

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 4]
 - OS: [Android 8]
 - Rooted: [No]
 - Version: [3.6.7]

**Comment by VishnuSanal** [comment]
@jyjsunny Thanks for reporting, but we can't help but wonder that it's `certificate installer` that's crashing and not AmazeFileManager. Feel free to report issues with Amaze here.
