### ISSUE TITLE
Show Number of Files In Each Folder

### ISSUE THREAD

**Issue by HonestAbe7** [TeamAmaze/AmazeFileManager#3336]
Could you please add a feature to show the number of files in each folder? I like to know the count of each item. 

Attached is a screenshot of the app Simple File Manager where each item is counted:

![Screenshot_20220530-112503](https://user-images.githubusercontent.com/88217236/171024295-d824e7cd-3018-4363-9680-2d6c6185eff5.png)

**Comment by shuvashish76** [comment]
Dupe #2415
