### ISSUE TITLE
Layout overlap in copy/paste snackbar

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#3348]
Attachment:
There is an overlapping text view and button in snack bar for copy/paste

<img src="https://user-images.githubusercontent.com/5211568/173237534-1f12e0fb-1c13-4b28-b14c-8728e2e70a66.jpg" height=600/>

**Comment by VishnuSanal** [comment]
@VishalNehra Can I get the screen size or the device?

**Comment by VishalNehra** [comment]
Increase display/ font size from system settings > display
