### ISSUE TITLE
The Add button is visible in some places, but cannot be added successfully

### ISSUE THREAD

**Issue by LL12138LL** [TeamAmaze/AmazeFileManager#3356]
**Is your feature request related to a problem? Please describe.**

The Add button is visible in some places, but cannot be added successfully

**Describe the solution you'd like**

The Add button is not displayed on these locations

**Describe alternatives you've considered**

The user can add files at these locations

**Additional context**

https://user-images.githubusercontent.com/101189845/173604867-0f546d1d-3d1a-4fcd-b951-85157003ad97.mp4

**Comment by VishalNehra** [comment]
The locations where you're trying to create files aren't valid. The 'Documents' tab is a logical group of all the documents available in your storage, and emulated directory is outside the space available to user to write files by the Android OS.
