### ISSUE TITLE
about search bar

### ISSUE THREAD

**Issue by phoenix26** [TeamAmaze/AmazeFileManager#337]
if you search sometihing in root folder ( "/"),it takes too long time and no results means it doesn't work.if you try to search smth in sdcard it shows very well and if you try it again,it shows duplicated results.And can you guys add suggestions to search typing? or while typing search text it can filter at same time? 
And you've to hide fab button while showing search bar.you can click fab button by mistake (and if you ask me,text reader's search feature is better than main search.its highlighting/filtering in text while you are typing.)
I hope you guys fix this bugs and add this features to this app! thank you

**Comment by vishal0071** [comment]
You're right, lemme find some time to get back to this later.

**Comment by VishnuSanal** [comment]
fixed with #3730
