### ISSUE TITLE
Rotate device and search, rotate again, then keyboard still appear

### ISSUE THREAD

**Issue by XYIheng** [TeamAmaze/AmazeFileManager#3394]
**Describe the bug**
Rotate device and search, rotate again, then keyboard still appear(should disappear)

**To Reproduce**
1. rotate devices
2. Click on search
3. rotate again
4. See keyboard still appear

**Expected behavior**
After step 3, the keyboard should disappear

**video**

https://user-images.githubusercontent.com/31406320/178173199-a00a78db-ef2f-4729-8520-6b1ba43a24aa.mp4

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [ Android 8]
 - Rooted: [e.g. No]
 - Version: [3.7.2]

**Additional context**
Sometimes, it behaves normally on AmazeFileManager 3.4.2, the keyboard disappear after rotation

**Comment by Burhan7777** [comment]
will try to work on it

**Comment by Burhan7777** [comment]
ok spend the whole day on it and finally figured it out. Will pull request soon

**Comment by Burhan7777** [comment]
please review the pull request. First time contributor.
