### ISSUE TITLE
[root] treats /data/data as /

### ISSUE THREAD

**Issue by ildar** [TeamAmaze/AmazeFileManager#3476]
**Describe the bug**
Navigating to `/ Root` brings to `/data/data`

**To Reproduce**
1. Tap on `/ Root`
2. See `/` on top but the real contents is of `/data/data`

**Expected behavior**
Show the contents of `/`

**Smartphone (please complete the following information):**
 - Device: phhgsi_arm64_ab / AGM H3
 - OS: Android 12 / lineage_arm64_bvS
 - Rooted: [e.g. No]
 - Version: 3.8

**Additional context**
AFM shows /data/data/* contents and **a user cannot navigate** to ..
The possible reason may be the following: the Phh's SU brings to /data/data instead of `/` as other `su` implementations:
```
phhgsi_arm64_ab:/ $ su
:/data/data #
```

**Comment by VishalNehra** [comment]
So if I understand correctly, it's more of an issue with su binary than of our app.

**Comment by TranceLove** [comment]
Speaking of Phh's SU binary, Google pointed me to https://github.com/seSuperuser/Superuser which I saw the repo had not been updated for years. Perhaps they are stable enough to survive all Android versions, but I'd wonder why using this when there is a more recent, still developed SU kit, [Magisk](https://github.com/topjohnwu/Magisk), available?

I'd recommend you to use that, with busybox module installed via https://github.com/Fox2Code/FoxMagiskModuleManager, and see if it can solve your problem.

I think I'll choose closing this issue.

**Comment by ildar** [comment]
Is it not just to insert something like:
> cmd = "cd /;" + cmd;
somewhere here?
https://github.com/TeamAmaze/AmazeFileManager/blob/00076315b8b408598bb048687ae0334bd191d4b7/app/src/main/java/com/amaze/filemanager/filesystem/root/base/IRootCommand.kt#L66

**Comment by ildar** [comment]
or getting deeper:
what's the point of this? why getting rid of "/" ?
https://github.com/TeamAmaze/AmazeFileManager/blob/45e82bfae195249cf1ac36e32843af0fc08d27b8/app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt#L115

**Comment by ildar** [comment]
No.
The problem is that the app assumes that `su` gives a shell with PWD==/.
But that's undefined for Android.
