### ISSUE TITLE
Got Array index out of bound exception while saving a file from Flipkart.

### ISSUE THREAD

**Issue by mohitkumar00** [TeamAmaze/AmazeFileManager#3547]
**Describe the bug**
Got index array index out of bound exception while saving a file from Flipkart 

**To Reproduce**
1. Go to 'Flipkart' app
2. Click on download invoice for any of the orders
3. Click on save

**Expected behavior**
The file should be downloaded and opened successfully.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: [e.g. Android 12
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by mohitkumar00** [comment]
Here is the crash report



## Issue explanation (write below this line)



## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.95
* __OS:__ Linux
OnePlus/OnePlus8T_IND/OnePlus8T:12/SKQ1.210216.001/R.202202232300:user/release-keys
12 - 31
* __Device:__ OnePlus8T
* __Model:__ KB2001
* __Product:__ OnePlus8T_IND
<details><summary><b>Crash log </b></summary><p>

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 4
at java.lang.String.checkBoundsBeginEnd(String.java:3942)
at java.lang.String.substring(String.java:2467)
at
com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.onActivityCreated(CompressedExplorerFragment.java:219)
at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
at
androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
at
androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
at
androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
at
androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
at
androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
at
androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
at
androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
at
androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
at
androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>


Thanks
Mohit

**Comment by VishnuSanal** [comment]
@mohitkumar00 [In reply to . .]
Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
