### ISSUE TITLE
Set default application to open with

### ISSUE THREAD

**Issue by ComeBurguburu** [TeamAmaze/AmazeFileManager#3584]
**Describe the bug**
 When open a file (pdf) we can't set the default application 

**To Reproduce**
1. Open a folder
2. Open pdf file
3. Choose Google PDF viewer
4. Repeat step 1 to 3 you need to choose application again 

**Expected behavior**
Allow to set default app from open menu (Files app did it well)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: [e.g. Android 11
 - Rooted:  No
 - Version: 3.8.2

**Comment by VishnuSanal** [comment]
@ComeBurguburu you can select the default app by pressing the 'Always' button on the file picker.

<img src="https://user-images.githubusercontent.com/50027064/197339409-a2e94c14-0ea8-4ef1-b9ef-d4dda764c5f2.png" height=800/>

also, make sure you have installed Amaze from the official links

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases

**Comment by ComeBurguburu** [comment]
Only drive can be set to default 

![Screenshot_20221022-144254.png](https://user-images.githubusercontent.com/10062185/197339581-1f990514-0097-43b5-8fde-c2055ebaf5b2.png)

**Comment by VishnuSanal** [comment]
> Only drive can be set to default

@ComeBurguburu don't other apps come to the top position upon opening it multiple times?

**Comment by ComeBurguburu** [comment]
Nope 😥

**Comment by VishnuSanal** [comment]
> Nope disappointed_relieved

okay, thanks for reporting. we'll look into it. can you provide the following details too?

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Rooted: 
 - Version:

**Comment by VishalNehra** [comment]
> Nope 😥

This is not possible. Can you try to clear cache from amaze settings > behaviour > clear cache.

**Comment by ComeBurguburu** [comment]
Okay I retry 
It only doesn't work with Google PDF reader com.google.android.apps.viewer.PdfViewerActivity
(work with Drive)

Device: Pixel 2
OS: Android 11
Rooted: no
Version: 3.8.2
