### ISSUE TITLE
A plus sign in filenames is causing issues

### ISSUE THREAD

**Issue by lukash** [TeamAmaze/AmazeFileManager#3585]
**Describe the bug**
Renaming a file with a + in the name causes a new directory to be created, with the new name (and with a space instead of the plus sign) instead of doing the rename.

Cut & Paste of the file results in an "Operation Unsuccessful" error.

I haven't tested other operations, there'll probably more weird failures.

**To Reproduce**
1. Have a file named e.g. "test+.txt"
2. either tap three dots, go to Rename, enter "test2+.txt", tap SAVE
3. or select the file, tap the cut icon, then paste in a different directory

**Expected behavior**
A file rename working, cut&paste working.

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 9
 - OS: Android 12
 - Rooted: No
 - Version: 3.8.2

**Comment by VishnuSanal** [comment]
dupe #3560
