### ISSUE TITLE
Renaming and only changing case fails

### ISSUE THREAD

**Issue by lukash** [TeamAmaze/AmazeFileManager#3587]
**Describe the bug**
When renaming a file, if only changing case of a letter, the operation fails with an "already exists" error.

**To Reproduce**
1. Go to rename a file
2. Only change a case of a letter
3. Attempt to save

**Expected behavior**
Rename happens.

**Smartphone (please complete the following information):**
 - Device: Auss Zenfone 9
 - OS: Android 12
 - Rooted: No
 - Version: 3.8.2

---
This now has a bounty, [here](https://app.bountysource.com/issues/113047903-renaming-and-only-changing-case-fails).

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

**Comment by VishnuSanal** [comment]
@lukash thanks for reaching out to us, but I'm afraid there's not much we can do about it since FAT filesystem is case insensitive. @TranceLove do you have anything to add?

**Comment by TranceLove** [comment]
> @lukash thanks for reaching out to us, but I'm afraid there's not much we can do about it since FAT filesystem is case insensitive. @TranceLove do you have anything to add?

Yes that's true - FAT filesystems are case-insensitive, and we can do nothing about it.

**Comment by lukash** [comment]
Well, I can rename "a" to "b" and then rename again to "A".

On that premise:
- as a user that doesn't want to deal with nonsense: A quality app shouldn't give me silly errors, it should handle this for me instead.

- as a developer: Come on, guys.
  Also, to elaborate, if the error is being raised from the FS layer, it either:
  - stores the name case-insensitive and there's a hard collision there, but then it has to store the original case somewhere else (seems inefficient). In that case there could be an API to just change the cased value?
  - or it stores case-sensitive value and for some reason just does an extra case-insensitive check. Worst case scenario, you have to do the double move I described. Yes, it's not atomic anymore. I still feel it's much better than the error.

**Comment by EmmanuelMess** [comment]
This now has a bounty, [here](https://app.bountysource.com/issues/113047903-renaming-and-only-changing-case-fails).

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!
