### ISSUE TITLE
Unable to decrypt .aze after deleting app data or reinstalling it

### ISSUE THREAD

**Issue by ChuckBartowski91** [TeamAmaze/AmazeFileManager#3605]
**Describe the bug**
Message "unable to decrypt" pops out when I try to decrypt .aze file after removing data app or reinstalling it, how to solve?

**To Reproduce**
1. Go to the folder containing encrypted file
2. Click on it
3. See error unable to decrypt

**Expected behavior**
Click on the file, touch the sensor, decrypt file.

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11 lite 5g ne
 - OS: MIUI 13.0.12 android 12
 - Rooted: no
 - Version: 3.8.2

**Additional context**
Is there a way to decrypt them in some way? Maybe an alternative app which can connect to amaze to look for a password or fingerprint and try to decrypt them all?

**Comment by VishnuSanal** [comment]
I'm afraid you can't. AZE format takes your android device's keystore as the key. there is no way to decrypt it now that the app data got cleared. (this is why we have a warning shown when trying to encrypt to AZE format)

**Comment by ChuckBartowski91** [comment]
> I'm afraid you can't. AZE format takes your android device's keystore as the key. there is no way to decrypt it now that the app data got cleared. (this is why we have a warning shown when trying to encrypt to AZE format)

I know, but when the app gets frozen and won't start it's too bad for your files. Luckily I have backups, but my modest opinion is that there should be a restore method which can recover that key (if it's possible something like that) and allow to decrypt from the same device with the same password or fingerprint.

**Comment by VishnuSanal** [comment]
> I know, but when the app gets frozen and won't start it's too bad for your files.

when did the app get froze?

> but my modest opinion is that there should be a restore method which can recover that key (if it's possible something like that) and allow to decrypt from the same device with the same password or fingerprint.

unfortunately, we can't do that with AZE format. we have started supporting AEScrypt format of encryption too (which let's you decrypt a file from any device as long as you have the password) from v3.7.0.
