### ISSUE TITLE
[Question] If rooted, can we avoid to require permissions on "strorage/Android/data"?

### ISSUE THREAD

**Issue by oOtroyOo** [TeamAmaze/AmazeFileManager#3632]
Because the SAF access requires permissions to access "/storage/emulated/0/Andoird/data", and it is **REALLY SLOW**. 
I wonder if you can use `su` commands to list files on this directory on rooted devices. In order to avoid such permissions.
I'm sure that I can list theses directories on terminal by using `su` commands.

**Comment by VishalNehra** [comment]
@TranceLove please confirm if this is required anymore, as now we're following a different approach to list files in /Android/data which isn't really slow.

**Comment by TranceLove** [comment]
@VishalNehra Let's hope we don't need to do this some time in the future...

**Comment by oOtroyOo** [comment]
So, now what? am I using the correct version? (v3.8.2 from play store)

It's still really slow and sometimes crashs as same as #3631

**Comment by VishalNehra** [comment]
We've published new version on play Store you should wait for 3.8.3 which would be available in few hours.
