### ISSUE TITLE
Amaze does not properly handle file with "+" in the name

### ISSUE THREAD

**Issue by emjas92** [TeamAmaze/AmazeFileManager#3636]
**Describe the bug**
Similar to #3560 but for files.

Amaze fales to open, rename, delete, or display properties for a file with a plus "+" in the name.

**To Reproduce**
1. Use a terminal (or other app) to create a file named `file+name.txt` and put something in it (non empty file)
2. Try open the file from Amaze - associated app closes immediately
3. Check the file properties in Amaze - 0 file size, no md5 etc
5. Try rename the file in Amaze - not renamed, or a folder is created with the new name
6. Try delete the file in Amaze - file not deleted

**Expected behavior**
All actions work as expected - open file, rename file, see file size

**Smartphone**
 - Nokia 6.1, Lineage OS, Amaze 3.8.2 (Fdroid)
 - Sony Xperia XA, lastest Amaze from Play Store

**Additional context**
Discovered after downloading a file from the web with a name like `Something+foo+-+bar.pdf`
Can do more testing if needed.

**Comment by THEtomaso** [comment]
It has the same problem with folders.
Also, if you open a folder with a + in the name, all of its contents will be invisible!

**Comment by edilberto507h** [comment]
Hello, i have the same problem with my Moto G20, Android 11, Amaze 3.8.4 f-droid versión, cant handle files or folders with a + on the name
