### ISSUE TITLE
[Bug] FTP over TLS not work

### ISSUE THREAD

**Issue by wuniversales** [TeamAmaze/AmazeFileManager#3656]
**Describe the bug**
FTP over TLS not work
I try to connect to this server and it does not work.
https://myrient.erista.me/ftp/

**Device info:**
 - Device: Xiaomi
 - OS: Android 12
 - Rooted: No
 - Version: google play (latest)

**Additional context**

**Comment by wuniversales** [comment]
Any solution ? ...

**Comment by TranceLove** [comment]
We will have one. Stay tuned - some more unit tests before I'm confident to put changes up.

<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/251819/b2348756-6bbe-466c-9ec2-50d1552c37ae" alt="" width="40%" height="40%" />
