### ISSUE TITLE
crashing everytime i open amaze on quest 2

### ISSUE THREAD

**Issue by jtapps1** [TeamAmaze/AmazeFileManager#3678]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
@jtapps1 Please provide more details. Are you getting a crash report?

**Comment by jtapps1** [comment]
i was having issues but i restarted my pc and it resolved the issue

**Comment by jtapps1** [comment]
im still having issues im getting the same crash report as the other people but its not letting me report it on my quest

**Comment by jtapps1** [comment]
> @jtapps1 Please provide more details. Are you getting a crash report?


im still having issues im getting the same crash report as the other people but its not letting me report it on my quest
