### ISSUE TITLE
Opening PDF using  Amaze PDF Viewer is very shady.

### ISSUE THREAD

**Issue by smith901** [TeamAmaze/AmazeFileManager#3685]
**Not a bug since it is deliberately programmed to do so**
Like title says. Redirects to download another app. App isn't compatible with device.

**To Reproduce**
1. Go to any PDF within Amaze
2. Click on PDF
3. Scroll down to Amaze PDF Viewer
4. See message about downloading another app

**Expected behavior that any other app does**
Open PDF

**Screenshots**
It'll work on your machine, trust me. Why use screenshots for the obvious. But I got them tho.

**Smartphone (please complete the following information):**
 - Device: An Android
 - OS: Android
 - Rooted: Android
 - Version: Android

**Additional context**
This is fraud. If it doesn't open PDFs it shouldn't be an option. Sad money grab attempt using shady programming and tactics.

Did a search to make sure I wasn't trippin before posting. Found this thread: https://forum.f-droid.org/t/amaze-file-manager-abuses-the-intent-interface-to-promote-apparently-non-free-apps/19975
Your responses in the issues I've read make it seem like you're unaware. Very scammy behavior.

**Comment by VishalNehra** [comment]
Unless you have a real issue / crash report to post please don't create a new issue here. 
If you have such opinion then don't use our app, simple as that.

**Comment by smith901** [comment]
Don't be mad at the truth. You did it. It IS a REAL issue.

So I did that for openess and posterity. Had you been upforth in a toast message or the README about that happening, I wouldn't have bothered. Simple as that.
Shady programming gimicks, I don't care for. Str8 trash cus you don't even understand how that is a problem.

**Comment by VishalNehra** [comment]
Oh I am not mad. I'm just stating that if you're not okay with us promoting our new open source app here you're more than welcome to switch to other apps which are full of ads / sell your data to earn. 
What I won't tolerate is your disrespect towards the hard work so many contributors have put here, I can't find any other respectful way than simply asking you to switch to some other app.
