### ISSUE TITLE
[regression] hangs in Android 4.2

### ISSUE THREAD

**Issue by ildar** [TeamAmaze/AmazeFileManager#3697]
**Describe the bug**
The initial run hangs with blank screen and ANR

**To Reproduce**
1. Get Android 4.2
2. Install the latest from F-Droid
3. Run

**Smartphone (please complete the following information):**
 - Device: PIPO S3
 - OS: Android 4.2 / CM10.1
 - Rooted: Yes
 - Version: 3.8.4

**Additional context**
[Full log](https://github.com/TeamAmaze/AmazeFileManager/files/10391136/1.txt)

**Comment by VishalNehra** [comment]
Is this relevant? We've already moved to 4.4 as min sdk which includes 100% of the devices (as per android studio)
