### ISSUE TITLE
Can't edit .jar files with a + in their name

### ISSUE THREAD

**Issue by Pacomatic1** [TeamAmaze/AmazeFileManager#3710]
Dead simple:
There is a .jar file.
Let's say the name is "amogus+1.1.jar"
If I try to copy, move, edit, rename, whatever...
It doesn't work. It says the operation failed.

But if I go into another program, and change the name to "amogus-1.1.jar",
Then it'll start working again, and Amaze will now able to do stuff to it.

I am on Android 10, running ColorOS 8.1 on an Oppo F9 with 64 gigabytes of space, 4 gigabytes of RAM, and an Octa-core processor.

**Comment by VishnuSanal** [comment]
thanks for reporting, this issue is a duplicate to #3636 & it is currently being worked on in #3661
