### ISSUE TITLE
Allow setting app language irrespective of device language

### ISSUE THREAD

**Issue by VishnuSanal** [TeamAmaze/AmazeFileManager#3711]

**Comment by VishalNehra** [comment]
More info: this feature is being added in Android 13 and will be made backward compatible with appcompat version 1.6+
So we'll support this after we target api 33. 
https://developer.android.com/guide/topics/resources/app-languages

**Comment by TranceLove** [comment]
Blocked by #3737 - requires AppCompat >= 1.6.0 for downward compatibility on implementation.

**Comment by TranceLove** [comment]
Reference: https://stackoverflow.com/a/74713646
