### ISSUE TITLE
Logcat monitored that ‘Error initializing jcifs’

### ISSUE THREAD

**Issue by RiShinku** [TeamAmaze/AmazeFileManager#3729]
**Describe the bug**
Network disk module said Error initializing jcifs

**To Reproduce**
1. Click the icon of plus sign.
2. Click Network Disk.
3. See 'Error initializing jcifs''

**Smartphone (please complete the following information):**
 - OS: Android 9

**Comment by TranceLove** [comment]
Problem came with original implementation of SubnetScanner, which is for SMBv1 and will not work on modern SMB services, including Windows and Linux Samba.

A new one is being implemented. See #3704.
