### ISSUE TITLE
Debug banner missing from debug builds

### ISSUE THREAD

**Issue by VishnuSanal** [TeamAmaze/AmazeFileManager#3731]
We used to have a debug banner, seems like it broke recently.

**Comment by aydenvraa** [comment]
it want to wrok

**Comment by VishnuSanal** [comment]
> it want to wrok

@aydenvraa hi, thanks for your interest. but there's already a pull request open for fixing this issue. you can look into other good first issues [here](https://github.com/TeamAmaze/AmazeFileManager/issues?q=is%3Aopen+is%3Aissue+label%3A%22Issue-Easy+%28good+first+issue%29%22)
