### ISSUE TITLE
Going back in SFTP connection leaves trailing slash

### ISSUE THREAD

**Issue by chuckwagoncomputing** [TeamAmaze/AmazeFileManager#3739]
**Describe the bug**
If you are in a directory, and go back to the parent directory, it leaves a trailing slash. Going back and forth between a parent and a child builds up a series of forward slashes. There is also an issue that seems to be related which results in "No files" being shown.

**To Reproduce**
1. Connect to a SFTP server
2. Navigate to some directory
3. Go back to parent
4. See trailing slash
5. Tap on (any) child directory
6. See two slashes between parent and child

**Expected behavior**
When going back, the trailing slash should be removed

**Screenshots**
This screenshot also shows the "No files" issue. I navigated between "Downloads" and "rusefi" a number of times before it stopped showing the files.
![Screenshot_20230218-173801_Amaze](https://user-images.githubusercontent.com/1531127/219904334-a41b3ab5-1623-426d-b75b-51b85686fe78.png)

**Smartphone (please complete the following information):**
 - Device: Oneplus 7T
 - OS: LineageOS 20
 - Rooted: No
 - Version: 3.8.5

**Comment by VishalNehra** [comment]
Thanks for reporting and donating us. We expect this to be fixed with  #3661  right @TranceLove ?

**Comment by TranceLove** [comment]
> Thanks for reporting and donating us. We expect this to be fixed with #3661 right @TranceLove ?

As I read from the code I think they are not related. Hence may be doing in a separate PR.
