### ISSUE TITLE
Disables Amaze inbuilt media players from file chooser (not work)

### ISSUE THREAD

**Issue by userkilled** [TeamAmaze/AmazeFileManager#3753]
**Describe the bug**

**To Reproduce**
1. I turn on this setting
2. reboot the application
3. and nothing, I also see everything on the menu of the program from Amaze

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [blackview bv6300pro]
 - OS: [e.g. Android 10]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.8.4]

**Additional context**

I generally hope that I correctly understood the purpose of this setting

**Comment by VishalNehra** [comment]
The setting allows you to disable inbuilt media players in our file utilities from file chooser when file utilities app is not installed. Please write if you need more clarification.
