### ISSUE TITLE
Not Showing up.

### ISSUE THREAD

**Issue by grimbobeans** [TeamAmaze/AmazeFileManager#3794]
So i downloaded this on my quest2, did the sidequest stuff, deleted it. then tried to redownload and it wont pop up in the unknown resource tab now.

**Comment by VishnuSanal** [comment]
> So i downloaded this on my quest2, did the sidequest stuff, deleted it. then tried to redownload and it wont pop up in the unknown resource tab now.

didn't get you, is this a problem with Amaze?
