### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by ocramPD** [TeamAmaze/AmazeFileManager#3796]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by ocramPD** [comment]
crash right as i get one

**Comment by VishnuSanal** [comment]
> crash right as i get one

@ocramPD please share the crash report here

**Comment by loafvrvr** [comment]
i crash when i get on

**Comment by VishnuSanal** [comment]
> i crash when i get on

@ocramPD please share the crash report that you are getting with us to diagnose the issue (by pressing the copy to clipboard button)
