### ISSUE TITLE
Names of the folders and files in root directory with enabled root explorer contains permissions, directories etc.

### ISSUE THREAD

**Issue by krija** [TeamAmaze/AmazeFileManager#380]
More info here: 
http://forum.xda-developers.com/showpost.php?p=69829149&postcount=496

**Comment by vishal0071** [comment]
Alright, I'm working on fixing this. Expect fix in near future.

**Comment by aybikeaydemir** [comment]
Hi, did you solve this problem?

**Comment by vishal0071** [comment]
Yes, rest assured, though we'll have to switch to busybox to solve this problem, I've already wrote some helper methods to do the same. Expect the fix in upcoming beta versions.

**Comment by EmmanuelMess** [comment]
AFAIK this was fixed.
