### ISSUE TITLE
crash on load up. app/ui crash on start up

### ISSUE THREAD

**Issue by mr-manb** [TeamAmaze/AmazeFileManager#3812]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
@mr-manb please share the crash report that you are getting with us to diagnose the issue.
