### ISSUE TITLE
م، Vishnu Sanal T ***@***.***> كتب:

### ISSUE THREAD

**Issue by Denamohamed5895** [TeamAmaze/AmazeFileManager#3837]
كتب:

Closed #3811 as not planned.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

_Originally posted by @Denamohamed5895 in https://github.com/TeamAmaze/AmazeFileManager/issues/3811#issuecomment-1544324844_

_Originally posted by @Denamohamed5895 in https://github.com/docker-captains/about/issues/26_

**Comment by Denamohamed5895** [comment]
3399222


مُرسل من بريد Yahoo لجهاز iPhone


بتاريخ الأحد, يونيو 4, 2023, 6:33 ص، ÿ®ÿØÿ± ÿ≠ÿ≥ŸÜŸâ ÿ≠ÿ≥ŸÜ ŸÖÿ≠ŸÖÿØ ÿπŸÑŸâ ***@***.***> كتب:




كتب:

Closed #3811 as not planned.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

Originally posted by @Denamohamed5895 in #3811 (comment)

Originally posted by @Denamohamed5895 in docker-captains/about#26

**Comment by Denamohamed5895** [comment]
Bbbbbb

**Comment by VishnuSanal** [comment]
please share the crash report that you are getting; unfortunately, we can't know the specifics of your issue without a crash report or clearcut description of the issue you are facing!
