### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by SUCKSGAME** [TeamAmaze/AmazeFileManager#3862]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by SUCKSGAME** [comment]
It just crashes please fix

**Comment by VishnuSanal** [comment]
@SUCKSGAME please provide us with the crash report, only then we can diagnose the issue (and potentially fix it)!
