### ISSUE TITLE
cant reinstall amaze after deleting amaze on oculus quest 2

### ISSUE THREAD

**Issue by Rahe3sh** [TeamAmaze/AmazeFileManager#3869]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
@Rahe3sh Please share the crash report here
