### ISSUE TITLE
Saving edited file works for Amaze Text Editor, but doesn't for third-party editor

### ISSUE THREAD

**Issue by resolritter** [TeamAmaze/AmazeFileManager#3874]
**Describe the bug**

I tried to edit and save a text file with Amaze Text Editor. It worked.

I tried to edit and save that same file with a third-party editor. It did not work.

Please check the video below for a full demonstration of the problem. Note that the file is placed in the phone's Internal Storage.

**Screenshots**

https://github.com/TeamAmaze/AmazeFileManager/assets/17429390/cf251103-578b-470a-988a-5d2bf306a63e

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy M23 5G
 - OS: Android 13
 - Rooted: No
 - Version: 3.8.4

Note: the same problem happens for my other device with Android 11.

**Comment by backtabber** [comment]
Ghost Commander and Material Files can both send a file to a 3rd party text editor with modification access. Storage Access Framework issue?
