### ISSUE TITLE
Can't share logs from release builds

### ISSUE THREAD

**Issue by VishnuSanal** [TeamAmaze/AmazeFileManager#3887]
The log file appears to be empty.

**Comment by VishalNehra** [comment]
This is high priority for the release.

**Comment by Nana250999** [comment]
> ไฟล์บันทึกดูเหมือนจะว่างเปล่า

in:titel
author:app/USERNANE
branch_protection.yaml
brinary_artifacts.yaml
assignce:USERNAME
is:pubic
linked:issue
linked:private
Status:failurge
reactions:n
reactions:..n
