### ISSUE TITLE
The README is misleading about in-app purchases.

### ISSUE THREAD

**Issue by beli-sk** [TeamAmaze/AmazeFileManager#3892]
**Describe the bug**
The README on Github is misleading users by saying "No ads or In-app purchases" yet Google Play clearly states the app contains in-app purchases. Not good for reputation.
Screenshots provided.

**Screenshots**
![README screenshot](https://github.com/TeamAmaze/AmazeFileManager/assets/1942417/22d10a41-a1a3-4ded-98db-e1e231f9d75d)
![Google Play screenshot](https://github.com/TeamAmaze/AmazeFileManager/assets/1942417/5a82e213-574f-41f0-95d4-ec75264eda71)
Screenshots taken 2023-07-26 14:40 GMT

**Comment by VishalNehra** [comment]
The Play Store description mentions the following
`This is the full version of app, you do not unlock anything on donations within the application.`
Google Play Store policy doesn't allow to use any other third party payment provider to accept donations other than Google billing library itself, hence the banner saying 'in-app purchases' there.
The releases posted on github are fdroid releases which doesn't use google billing library at all. It'll redirect you to our Paypal address for donation.
