### ISSUE TITLE
how you're accessing the Android/data folder 

### ISSUE THREAD

**Issue by wingsonflutter** [TeamAmaze/AmazeFileManager#3908]
The reason I'm asking is because after the release of Android 11, We cannot Directly open Android/data folder but When i open the AmazeFile Manager , u guys are done easily . How is it possible to do Android 11 phone , Can u explain about that ?

**Comment by VishnuSanal** [comment]
@TranceLove's implementation 🙇🏿 via #2828 as a fix to #2015

**Comment by wingsonflutter** [comment]
Can u tell me the permissions u have been using to view Android/data/ folder in Amaze File Manager App in Android 11

**Comment by VishnuSanal** [comment]
the implementation details are present in the threads mentioned above (the issue & the PR). you may refer to them for further reference. :)
