### ISSUE TITLE
Unable to find out how to view the bookmarks

### ISSUE THREAD

**Issue by encrus** [TeamAmaze/AmazeFileManager#3927]
I am unable to view the bookmarks. I have clicked on the hamburger (3 horizontal lines) icon and see the menu, but only closest entries there that I see are "Quick access" but it doesn't house the bookmarks.

To reproduce, simply create a bookmark of any folder
Then try to view all you bookmarks - there is no menu or entry to do this !! 

This is observed on Android 9, 10, 11 
Seems to be issue with the app GUI and not android

**Comment by VishnuSanal** [comment]
@encrus please check the visibility of bookmarks from settings

**Comment by encrus** [comment]
Thanks, it works now.
