### ISSUE TITLE
How to set IPv4 address when using FTP server with hotspot?

### ISSUE THREAD

**Issue by ACodeHX** [TeamAmaze/AmazeFileManager#3928]
Why does Amaze not provide an IPv4 address when I enable the hotspot? How can I set an IPv4 address when enabling the hotspot or add IPv4 as an option?

**Comment by VishnuSanal** [comment]
hotspot? Amaze doesn't have such a feature. please verify whether you downloaded Amaze from the official sources.

 Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases

**Comment by ACodeHX** [comment]
> hotspot? Amaze doesn't have such a feature. please verify whether you downloaded Amaze from the official sources.
> 
> Play Store https://play.google.com/store/apps/details?id=com.amaze.filemanager
> 
> FDroid https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager
> 
> AFH https://www.androidfilehost.com/?w=files&flid=73967
> 
> GitHub https://github.com/TeamAmaze/AmazeFileManager/releases

I'm sorry, I may not have explained it clearly. When I open the mobile hotspot, Amaze's FTP server doesn't have an address like IPv4, only something like this.

![Screenshot_20230927_084051](https://github.com/TeamAmaze/AmazeFileManager/assets/127362983/dd7ae99f-7d18-40d5-bab1-c24a284bced7)

However, when I connect to WiFi, I have an address like this. 

![ipv4](https://github.com/TeamAmaze/AmazeFileManager/assets/127362983/6b06bb8d-5a64-4601-be52-4dc52ad15841)

So, I hope that when I open the hotspot, it can also have functionality like this.

**Comment by ACodeHX** [comment]
> hotspot? Amaze doesn't have such a feature. please verify whether you downloaded Amaze from the official sources.
> 
> Play Store https://play.google.com/store/apps/details?id=com.amaze.filemanager
> 
> FDroid https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager
> 
> AFH https://www.androidfilehost.com/?w=files&flid=73967
> 
> GitHub https://github.com/TeamAmaze/AmazeFileManager/releases

I downloaded Amaze from GitHub.

**Comment by VishnuSanal** [comment]
no idea, @TranceLove do you have a word here? 🤔

**Comment by TranceLove** [comment]
> no idea, @TranceLove do you have a word here? 🤔

Perhaps. See if #3946 can help.

**Comment by VishnuSanal** [comment]
@ACodeHX please try with [this](https://github.com/TeamAmaze/AmazeFileManager/suites/16751024873/artifacts/956825836) APK & check whether this is fixed.

**Comment by ACodeHX** [comment]
> @ACodeHX please try with [this](https://github.com/TeamAmaze/AmazeFileManager/suites/16751024873/artifacts/956825836) APK & check whether this is fixed.

I've already checked this APK and it seems to be error-free. 
![Debug](https://github.com/TeamAmaze/AmazeFileManager/assets/127362983/3c75dab2-8029-4097-986f-c7b01e67e820)

The computer can also be successfully connected
