### ISSUE TITLE
Play Store version mismatch

### ISSUE THREAD

**Issue by Fmstrat** [TeamAmaze/AmazeFileManager#3934]
**Describe the bug**
The Google Play Store is running on v3.8.5, while GitHub is only at v3.8.4. When using alternative stores like Obtainium or F-Droid, the version mismatch causes update issues. Either the versions should be in sync, or their app namespace should be different.

**Expected behavior**
Version matching across stores.

**Smartphone (please complete the following information):**
 - Device: S9+
 - OS: Android 11
 - Rooted: No
 - Version: 3.8.?

**Comment by VishalNehra** [comment]
We'll take care of this from next release.

**Comment by Fmstrat** [comment]
@VishalNehra I see this was closed, but its been over a year since the last release (despite what appears to be a lot of great activity on the repo). Any plans to update the release soon?

**Comment by VishnuSanal** [comment]
> @VishalNehra I see this was closed, but its been over a year since the last release (despite what appears to be a lot of great activity on the repo). Any plans to update the release soon?

we'll release v3.10 very soon 🙂
