### ISSUE TITLE
Where is GlideApp defined? Not able to identify it in this project.

### ISSUE THREAD

**Issue by NanyangTaiji** [TeamAmaze/AmazeFileManager#3950]

**Comment by VishnuSanal** [comment]
@NanyangTaiji Please check https://github.com/TeamAmaze/AmazeFileManager/blob/release/4.0/app/src/main/java/com/amaze/filemanager/application/GlideApplication.java Is this what you meant?

**Comment by NanyangTaiji** [comment]
No, GlideApp is used in MainActivity and other places for loading images.

**Comment by NanyangTaiji** [comment]
thanks
