### ISSUE TITLE
Bug: Files or folders do not match the section when selecting "None On Top" in Directory Sort Mode

### ISSUE THREAD

**Issue by XYIheng** [TeamAmaze/AmazeFileManager#3990]
**Describe the bug**
When I select "None On Top" in the Directory Sort Mode,  the files and folders are listed together. However, the grey "Folders" and "Files" indicators confuse me, because folders are listed under the "Files" and files are listed under the "Folders". 

I suggest removing the grey "Folders" and "Files" to avoid confusion when selecting "None On Top" in the Directory Sort Mode.

**To Reproduce**
1. open amaze
2. Click 'options' 
3. click sort
4. click "Directory Sort Mode"
5. Select "None On Top"
6. See error. The grey indicators "Folders" and "Files" appear, and folders are listed under the "Files" indicator

**Expected behavior**
The grey "Folders" and "Files" should not be displayed. Because the sorting doesn't split folders and files

**Screenshots**
![image](https://github.com/TeamAmaze/AmazeFileManager/assets/31406320/92688aca-3ea6-4e7f-af87-e5a95a161e86)

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [Android 8]
 - Rooted: [No]
 - Version: [3.8.4]

**Comment by TranceLove** [comment]
@XYIheng Should be fixed by #3966. Stay tuned for the new release🙂

**Comment by XYIheng** [comment]
@TranceLove Nice update! Thank you 👍
