### ISSUE TITLE
I thought FDROID is a FOSS STORE ?

### ISSUE THREAD

**Issue by primski** [TeamAmaze/AmazeFileManager#4005]
20 day trial lmaooo

**Comment by VishalNehra** [comment]
We'll unlock your membership for any sort of donation to our app, be it monetary or through translations. 
And to answer your question: yea, fdroid is foss store. Free in open source doesn't mean free of cost.

**Comment by primski** [comment]
did you find a loophole? everybody in the world knows FOSS != TRIAL 

but yeah make me the bad guy

**Comment by VishnuSanal** [comment]
https://www.gnu.org/philosophy/free-sw.html

> you should think of “free” as in “free speech,” not as in “free beer.”
