### ISSUE TITLE
not able to update to play store version 3.8.5

### ISSUE THREAD

**Issue by kevin0t** [TeamAmaze/AmazeFileManager#4013]
**Describe the bug**
not able to update to play store version 3.8.5 , i am .currently on the playstore version 3.8.4

**To Reproduce**
1. Go to playstore
2. Click on update amaze file manager
3. play store tries to download update.
4. Play store gives an error " can't install amaze file manager"

**Expected behavior**
it should be ablr to update easily..

**Screenshots**
<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/93819980/3ce84b97-7411-4763-a10d-d30f4a5c7f73" height=600 />

**Smartphone (please complete the following information):**
 - Device: motorola g 82
 - OS: Android 13
 - Rooted: No
 - Version: 3.8.4

**Additional context**
i suspect it maybe happening due to changes in signing keys of the app.
Due to recent changes in apps for smart tv , app needsto be submitted only as bundles and google signs it. so i am guessing that.

**Comment by VishnuSanal** [comment]
@VishalNehra

**Comment by VishalNehra** [comment]
We've been signing bundles since a long time, and also our signing keys never changed, regardless of whether google signs it or us. I guess this is some other issue. Can you try uninstalling and reinstalling it.

**Comment by kevin0t** [comment]
yeah uninstalling and re-installing will solve it, but i wondered why it wouldn't let me update and if its just in my case. I have seen this issue happening in other apps who have started submitting bundles.
