### ISSUE TITLE
Search Result Title disappears after screen rotation

### ISSUE THREAD

**Issue by XYIheng** [TeamAmaze/AmazeFileManager#4016]
**Describe the bug**
After screen rotation, the search result title disappears.

**To Reproduce**
1. Go to Amaze file manager
2. Click on Search button
3. Try to find a file /folder
4. Then rotate the device
5. Search result title fails to reappear

**Expected behavior**
The search result title should appear

**Bug video**

https://github.com/TeamAmaze/AmazeFileManager/assets/31406320/74ea8334-0b17-45c0-b6c2-ce3f04b73305

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [Android 8]
 - Rooted: [e.g. No]
 - Version: [3.8.4]

**Additional context**
It seems a regression https://github.com/TeamAmaze/AmazeFileManager/issues/1978 
It was fixed but occurs again.

**Comment by VishnuSanal** [comment]
um... we've redesigned the entire search experience (please see #3984). this issue is no longer relevant in the new UI -- the new overlay that displays the search results gets hidden upon rotation.

**Comment by XYIheng** [comment]
Ok, I get it! Thanks for your explanation!
