### ISSUE TITLE
Documents and Recent files do not show the file just created

### ISSUE THREAD

**Issue by XYIheng** [TeamAmaze/AmazeFileManager#4017]
**Describe the bug**
After I create a txt file and add text into it, the Documents and Recent files do not show the file I created. But the Quick access shows the file I created.

**To Reproduce**
1. Create a txt file and edit it.
2. Open drawer
3. Click Quick access -> see the file I created. fine
4. Open drawer
5. Click Recent file -> error: the file doesn't appear. 
6. Open drawer
7. Click Documents -> error: the file doesn't appear. 

**Expected behavior**
The txt file I just created should display in Documents and Recent files

**Screenshots**
![image](https://github.com/TeamAmaze/AmazeFileManager/assets/31406320/691f9db0-160b-4127-81b9-ca1a540663b4)
![image](https://github.com/TeamAmaze/AmazeFileManager/assets/31406320/1ba664fb-4472-411d-8cbb-eae791598141)

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [Android 8]
 - Rooted: [e.g. No]
 - Version: [3.8.4]

**Additional context**

**Comment by VishnuSanal** [comment]
@XYIheng thanks for reaching out! I think what you mentioned is the expected behavior. quick accesses are maintained by us & recent files are provided by the Android system.

**Comment by XYIheng** [comment]
@VishnuSanal Thanks for your explanation! But why Documents also doesn't show the files?

**Comment by VishnuSanal** [comment]
> But why Documents also doesn't show the files?

that's fixed currently & will be rolled with the new release :)
