### ISSUE TITLE
Missing source code for version 3.9 available from Google Play

### ISSUE THREAD

**Issue by aldafu** [TeamAmaze/AmazeFileManager#4022]
The lastest published version on Google Play is 3.9. The code published here in the repository is still on 3.8.5. Are you plannig to push your latest changes into the repository here too?

Other APK Stores like on F-Droid are also missing the latest version.

When the app was installed from F-Droid this will lead to an error message in Google Play as it will try to update that to the newer version, but of course will fail due to the difference in signing keys for the APK.

**Comment by kevin0t** [comment]
I am still on 3.8.5 version of google playstore  and its still not showing any updates to 3.9 .

**Comment by VishalNehra** [comment]
3.10 is available now as milestone and on fdroid.
