### ISSUE TITLE
Please add provision to import / export settings

### ISSUE THREAD

**Issue by encrus** [TeamAmaze/AmazeFileManager#4026]
**Is your feature request related to a problem? Please describe.**
Not related a problem, but a new feature request

**Describe the solution you'd like**
Pls add provision to export and import settings. 
This should allow to copy the settings and re-create this on another phone of the same OS.
It should also allow it to import settings upon upgrade or reinstall of Amaze.

Preferably settings should be in human readable xml file

**Comment by VishnuSanal** [comment]
Thanks for reaching out! This feature has been implemented, will be rolled in the next release. :)
