### ISSUE TITLE
Show deep search results in `SearchView`

### ISSUE THREAD

**Issue by seelchen** [TeamAmaze/AmazeFileManager#4041]
**Is your feature request related to a problem? Please describe.**
Currently, the search results of the deep search are not shown in the `SearchView` like the other searches but in the `MainView`. Integrating it into the `SearchView` will lead to a more consistent design. It also enables sorting of the deep search results and prevents bugs like using the `MainView`'s context menus (which exits the search).

**Describe the solution you'd like**
Move deep search result list to `SearchView`.

**Additional context**
Would also resolve the remaining tasks of #3357.

**Comment by VishnuSanal** [comment]
that's rigt, thanks, this requires reinventing the wheel, hence I skipped this on the first version. :D we'll implement it later :)

**Comment by seelchen** [comment]
I would also be interested in implementing this if you currently accept contributions for this :D

**Comment by VishnuSanal** [comment]
> I would also be interested in implementing this if you currently accept contributions for this :D

yes, please!!
