### ISSUE TITLE
Warn users to put phone on flat surface before writing to USB OTG.

### ISSUE THREAD

**Issue by HT-7** [TeamAmaze/AmazeFileManager#4051]
Holding the phone in the hand while writing data to OTG (USB stick connected to charging port through an adapter) could lead to data loss because the movements of the hand could lead to the interruption of the connection to the USB drive.

Technical details: Operating systems such as Android and Linux use write caching to improve performance and prevent lagging. However, if the data storage device is disconnected before the cached data is "flushed", meaning written to the device, any unwritten data is lost.

I recommend advising the user to put the phone down on a flat surface such as the ground or a table before writing data to OTG.

**Comment by VishnuSanal** [comment]
thanks for the concern, but I don't think this comes in the scope of our file manager!
