### ISSUE TITLE
resource/folder support

### ISSUE THREAD

**Issue by axet** [TeamAmaze/AmazeFileManager#419]
http://stackoverflow.com/a/26651827/855895

```java
    Uri selectedUri = Uri.parse(Environment.getExternalStorageDirectory() + "/test");
    Intent intent = new Intent(Intent.ACTION_VIEW);
    intent.setDataAndType(selectedUri, "resource/folder");

    if (intent.resolveActivityInfo(getPackageManager(), 0) != null)
    {
        startActivity(intent);
    }
    else
    {
        // if you reach this place, it means there is no any file 
        // explorer app installed on your device
    }
```

**Comment by vishal0071** [comment]
I've pushed a fix, please test when beta version comes out.

**Comment by axet** [comment]
Seems like you add "resource/folder" + "file://" links.

Are you going to add "resource/folder" + "content://" not sure if it is even a android documented feature?

**Comment by VishalNehra** [comment]
This was resolved.

**Comment by EmmanuelMess** [comment]
@axet 

> Are you going to add "resource/folder" + "content://" not sure if it is even a android documented feature?

content is a sticking point, if its not yet implemented, please open another issue.
