### ISSUE TITLE
Can not open folder with Amaze from Syncthing

### ISSUE THREAD

**Issue by pchampin** [TeamAmaze/AmazeFileManager#450]
I'm using [Syncthing](https://syncthing.net/) on my phone to synchronize some folders with my PC. I used to have ES installed, and Syncthing was able to open synchronized folders with ES (with the "Open with" menu).

Now that I removed ES and installed Amaze instead, Syncthings tells me "No compatible file manager installed".

I don't know if the "open with" feature is completely missing from Amaze (in which case this issue should probably be renamed, replacing "Syncthing" from "another application") or if this is due to the specific way that Syncthing requires the action. But in any case, I think this is a feature worth having.

**Comment by gsantner** [comment]
Maybe upstream: <https://github.com/syncthing/syncthing-android/issues/838>

**Comment by FeuRenard** [comment]
This is a duplicate of #419.

**Comment by pchampin** [comment]
Agreed with @FeuRenard about the duplicate (confirmed by the discussion in the Syncthing issue). Closing.
