### ISSUE TITLE
From the search bar you can click invisible buttons

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#489]
The colors represent different actions on tap:
![screenshot_20170324-134546 1](https://cloud.githubusercontent.com/assets/10991116/24306667/20ab8920-10a0-11e7-8fbf-730e2da6eb71.png)

If you click on the red/light blue zones the button that is behind the search bar (sidebar and menu respectively) is clicked; I propose that the green section is extended:

![screenshot_2](https://cloud.githubusercontent.com/assets/10991116/24305966/8ec8058a-109d-11e7-8ec9-0ce25fe9a152.png)
(Sorry for the bad PS skills)

**Comment by EmmanuelMess** [comment]
Soving this

**Comment by vishal0071** [comment]
No need, that's how it's supposed to act, right? If you don't give a margin it'll look really bad.

**Comment by EmmanuelMess** [comment]
The thing is that it is very easy to click the hamburger button while trying to click back.

**Comment by vishal0071** [comment]
Ok. Decrease the margins but try to keep them in check with for eg. Play Store app.

**Comment by EmmanuelMess** [comment]
I'm using [SearchView lib](https://github.com/lapism/SearchView), that basically shows the same search bar as the play store.

**Comment by vishal0071** [comment]
Ok

**Comment by vishal0071** [comment]
I guess you're done with this

**Comment by EmmanuelMess** [comment]
No, what?

**Comment by EmmanuelMess** [comment]
This was fixed.
