### ISSUE TITLE
Image Viewer

### ISSUE THREAD

**Issue by JunkyardCat** [TeamAmaze/AmazeFileManager#502]
is it possible to implement an internal image viewer?

**Comment by vishal0071** [comment]
It's absolutely possible, however I have no plans for it. Contributions are most welcome though.

**Comment by EmmanuelMess** [comment]
Why would we need such viewer?
I recommend leaving the hassle to another app, reducing the weight of this one and allowing the user to choose which features they would want (by choosing an app to fit their needs).
I chose [LeafPic](https://github.com/HoraApps/LeafPic).
