### ISSUE TITLE
Can't select daytime theme

### ISSUE THREAD

**Issue by shanavas786** [TeamAmaze/AmazeFileManager#509]

**Comment by vishal0071** [comment]
State some description. It's working fine for me. It is supposed to set dark/light theme based on day time (sets dark theme after 6pm and vice versa)

**Comment by EmmanuelMess** [comment]
But the option is never properly "selected" (the dot on the side is never "on"), is that supposed to happen (if so it's a bit weird).

**Comment by shanavas786** [comment]
A nice behavior would be to keep daytime button selected and open the app in light/dark theme based on system time. 
Switching theme at realtime would be great.

**Comment by vishal0071** [comment]
That's what it was doing earlier. I was not aware that it's broken.
