### ISSUE TITLE
Move files without copying them

### ISSUE THREAD

**Issue by KOLANICH** [TeamAmaze/AmazeFileManager#513]
For now if I move a file it is copied and then the original is deleted. It has tons of drawbacks such as flash memory wear and inability to "move" when flash if full. Move instead.

**Comment by vishal0071** [comment]
That's what move is. Right? In the end the file is not been present at origin.

**Comment by KOLANICH** [comment]
Not right. ```mv``` doesn't copy files, it only modifies file system structures, if it is possible.

**Comment by vishal0071** [comment]
Well. Things are not always just ````mv```` and a simple system call.
You're basically failing whole Samba API by telling us to use ````mv```` or ````cp```` instead

**Comment by KOLANICH** [comment]
This issue is not about samba. It is about moving a file from one folder to another within the same filesystem.

**Comment by vishal0071** [comment]
Guess what, samba connection and your internal memory is not on the same file system.

**Comment by KOLANICH** [comment]
Yes, but when I tried to move a file within a filesystem I saw it was copied first? How did I know that Amaze has tried to copy it first? I got an error that the disk is full. Then I used mv from the terminal emulator and this have worked.

**Comment by vishal0071** [comment]
I didn't know you were referring to moving within smb server. Now I know what you're talking about. Expect a fix for this in next update.

**Comment by KOLANICH** [comment]
It is not about smb at all. It is entirely ablut local fs.

**Comment by vishal0071** [comment]
From your earlier reply, ````It is about moving a file from one folder to another within the same filesystem. And don't use cli utilites, use the API provided by OS.```` Would you point to the API?

**Comment by KOLANICH** [comment]
>Would you point to the API?

http://man7.org/linux/man-pages/man2/rename.2.html

**Comment by KOLANICH** [comment]
I have just realized (when run out of free space) that 3.2.1 still copies the files instead of moving.

**Comment by EmmanuelMess** [comment]
Yes, [here](https://github.com/TeamAmaze/AmazeFileManager/commit/e870a9d24684e9d614b239ae0539048a30c86de0#diff-bb81bcd45553a7ac4875062150470f5bR243).
