### ISSUE TITLE
Per-Folder Sort Settings

### ISSUE THREAD

**Issue by jimbo1qaz** [TeamAmaze/AmazeFileManager#528]
Currently I cannot set the sorting order per-folder. For example, I want Download to be newest-first, folders last, but /sdcard to be sorted by name, folders first. Is it possible to implement such a feature?

**Comment by vishal0071** [comment]
It's absolutely possible, but doing so will probably lead to slow UX. Like we would need to save these preferences in database, map them with path. Now searching each entry in database for a specific path is pretty heavy operation. List loading will be heavily effected even for those paths on which there is no sort option selected.

**Comment by jimbo1qaz** [comment]
Well this feature is present on Windows. I personally consider it a fundamental basic feature, and am surprised at how no Android file manager has it. Is it possible to configure a default folder sort, with a handful of overrides (eg downloads folder)? Windows stores in per-folder desktop.ini, would a central database be appropriate for Amaze?

**Comment by EmmanuelMess** [comment]
Load every folder that has ordering on app start into a trie, check routes against that trie, then load the preference from a preloaded map, I don't think it really is so time consuming. You could improve by not checking subdirectories of a dir that doesn't exist (substring check in trie).

**Comment by MaanooAk** [comment]
I'm willing to try implement this feature (when I will have some time) and make it so it can be disabled from the settings in order to avoid the overhead.
@vishal0071 (or anyone else) If you have planning implementing it yourself or you are opposed to it just let me know

**Comment by vishal0071** [comment]
@MaanooAk I had not planned yet. Go ahead (:

**Comment by jerryn70** [comment]
+1 for this. This is a must need feature for me also.
@MaanooAk is there any progress in your work ?

**Comment by MaanooAk** [comment]
@jerryn70 no (cough up in other project)
I did some tests on storing sorting per folder, nothing really good came out of it. I will post here if I'll start again

**Comment by tamalbuk** [comment]
@jimbo1qaz Solid Explorer has per folder sorting options.
