### ISSUE TITLE
Handle externally sourced read-only files

### ISSUE THREAD

**Issue by splondike** [TeamAmaze/AmazeFileManager#558]
The polipoid application allows users to view its log file in any activity that can handle the text/plain mimetype. As it is a log file, polipoid provides read only access. Amaze accepts the Intent, but then immediately tries to write back to the file and crashes with a permission denied error.

My suggestion is to implement a read-only mode in the TextReader activity, and use it when the incoming Intent doesn't have the FLAG_GRANT_WRITE_URI_PERMISSION flag set.

Affects version: 3.1.2 RC3

**Comment by EmmanuelMess** [comment]
AFAIK readonly files are supported in the integrated reader and the correct intents are generated now.
