### ISSUE TITLE
[feature-request] Way to type paths

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#569]
A way to type a path and access it.

**Comment by jsveiga** [comment]
Yes please! Not sure why but my /storage/emulated is now "drwx--x--x root everybody" so I can't navigate to /storage/emulated/0 (but I can "cd" to it on a shell).

**Comment by EmmanuelMess** [comment]
There is a way to access it (I think), add it as shortcut.

**Comment by jsveiga** [comment]
It's possible to add as a bookmark, but first you have to get there, which
is no longer possible (well, it is because I had set it as "home", luckily).

**Comment by EmmanuelMess** [comment]
Do you have the dev version?

**Comment by EmmanuelMess** [comment]
Nevermind then, you'll have to wait.

**Comment by EmmanuelMess** [comment]
Working on this
