### ISSUE TITLE
Adjust FAB position and shadow/elevation to fit Googles design

### ISSUE THREAD

**Issue by G00fY2** [TeamAmaze/AmazeFileManager#573]
Atm the FAB is too high and has too much shadow. Should be more like in Googles design guidelines or the Google apps.

**Comment by vishal0071** [comment]
Well, we;re using (this)[https://github.com/Clans/FloatingActionButton]
It's support seem to have discontinued, so I guess we'll resort to using the Google's implementation.
Expect fix in near future.

**Comment by G00fY2** [comment]
I guess PR #869 fixed my issue.
