### ISSUE TITLE
Default Audio Player

### ISSUE THREAD

**Issue by RamolaWeb** [TeamAmaze/AmazeFileManager#579]
Currently there is no default audio player to play the media file like .mp3. It will be great to build a inbuilt media player to play the media file .

**Comment by EmmanuelMess** [comment]
Why would we need an audio player?
I recommend leaving the hassle to another app, reducing the weight of this one and allowing the user to choose which features they would want (by choosing an app to fit their needs).
I chose [Shuttle](https://github.com/timusus/Shuttle).
