### ISSUE TITLE
Add share intent handler for saving data to filesystem

### ISSUE THREAD

**Issue by tjnycum** [TeamAmaze/AmazeFileManager#615]
Some other popular file managers (such as ES File Explorer) include the very useful feature of providing an entry in share menus for saving data to the filesystem, a kind of "save as" dialog.

For example, many banking apps allow you to share transaction receipts/confirmations. Google Drive provides a "Save to Google Drive" handler and Google Photos provides an "Upload to Photos" handler, but it's useful to be able to simply save something, any arbitrary shareable data, to a file on the device. Short of this option being included in Android itself, a file manager like Amaze is a natural candidate to provide this functionality.

**Comment by vishal0071** [comment]
Implemented! Be sure to test with upcoming beta.
