### ISSUE TITLE
Many ANR log while our stress test 

### ISSUE THREAD

**Issue by Jo2joe** [TeamAmaze/AmazeFileManager#621]
Good day developer Mr. Vishal Nehra

This is Joe Oh from Point Mobile. As I e-mailed you, I am trying to report v3.1.2 RC3 issue in AmazeFileManager git. 
We are doing final test our latest model which is Android 6.0.1 with your Amaze File Manager these days. 

While our stress test (Randomly run app or make touch event), we found ANR 91 times in v3.1.2 RC3 version  

 ![anr](https://cloud.githubusercontent.com/assets/29136641/26709878/fcbb811e-4790-11e7-848e-e7aa38cc1ae5.png)

If you have chance, please check the log file which I attach and share us your comment of this issue. 

[2f301df_MonkeyFailLog.zip](https://github.com/arpitkh96/AmazeFileManager/files/1046614/2f301df_MonkeyFailLog.zip)

**Comment by vishal0071** [comment]
I am currently out of station. Let me get back to this later.

**Comment by Jo2joe** [comment]
TGIF Developer! 

Our team just took the logs of Amaze File Manager app crash and ANR during Monky Test. 
Please kindly check zip file. Sorry it is more than 10MB, that I left the Google Drive link 
https://drive.google.com/file/d/0B4AlMBvpljfTeEZyS3FvQnRlWjA/view?usp=sharing 

Please kindly review the log from us and consider some exception code in the Amaze File Manager App

**Comment by EmmanuelMess** [comment]
These would have to be rerun now.
