### ISSUE TITLE
When viewing zip file path is shown as "/" (root)

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#623]
Open a zip file, check appbar, ..."/*.zip" is now "/". It probably should be ".../Desktop.zip/" or similar.
<img src="https://cloud.githubusercontent.com/assets/10991116/26757437/84c47bdc-4891-11e7-8009-d70f59a11934.png" height=350/>

**Comment by vishal0071** [comment]
Not a bug, it's by design.

**Comment by EmmanuelMess** [comment]
@vishal0071 It would be nicer if you left "Amaze" in the appbar and put *.zip/ in the route.

**Comment by vishal0071** [comment]
Sure, sounds good. But putting full path might not be a good idea, just a ````xyz.zip/``` preceding it would be fine. In case one want to see the full path, we can add an action mode menu item saying 'Details' and show a properties dialog, like we have in Amaze Text Viewer.
