### ISSUE TITLE
FTP server won't write to SD card

### ISSUE THREAD

**Issue by ghost** [TeamAmaze/AmazeFileManager#630]
I can read the card contents fine by accessing the server, but not write. I'm using a Linux native filemanager to access the server, and attempting to write gives an error. I'm at work and don't remember the exact message, i can edit it later if necessary.

Writing on the SD card works fine by just using Amaze itself on the device, which has permissions to do so. I'm not sure i understand Android permissions system correctly if at all, but it seems weird that the filemanager app can write to the card, but the FTP server run *by* the filemanager app cannot.

Ideas?

**Comment by vishal0071** [comment]
FTP server is started for a local file system, I cannot find any API that is compatible with android style permission, so it's impossible for server to find any SD Card let alone write it. I'm surprised you're able to navigate to your SD Card on Server, 
For the answer this, won't be fixed.

**Comment by Generator** [comment]
FTP server on MiXplorer is able to write on SD Card if i'm not wrong.

I have a workaround to write on SD Card, instead of using the standard path to sdcard i use [SD Card Write Access Enabler](https://forum.xda-developers.com/apps/magisk/magisk-v9-module-sd-write-access-t3503988) and use `/mnt/media_rw/[sdcard_name]/` as FTP path.

**Comment by vishal0071** [comment]
Great workaround. But nit everyone knows about magisk.. see if you can find how MiXplorer guy does it.

**Comment by Alexander--** [comment]
Unless MiXplorer guy have found a way to hack Android file storage framework, he probably just uses ContentProvider API in place of filesystem calls. His FTP server is either written in Java (and uses SAF API directly) or overrides C file functions — `fopen`, `read`, `write` etc to invoke Android APIs via JNI.

@vishal0071

"Local filesystem" and Android sdcard API aren't some mutually exclusive concepts. The later is implemented on top of former (using FUSE/AUFS). Root apps can read/write both internal and external storage directly without need for Android permissions.

**Comment by noam09** [comment]
Not sure if this is relevant, but ES's FTP server is also able to read/write to SD card.

**Comment by sid32** [comment]
Solid can write to SD card as well in its FTP addon.

**Comment by teal77** [comment]
There is an open source ftp server on FDroid maybe this helps?
https://f-droid.org/en/packages/org.primftpd/
Source: https://github.com/ppareit/swiftp

**Comment by TranceLove** [comment]
Fixed by #2341.
