### ISSUE TITLE
When using with RTL items break

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#649]
Right to left languages wreck the app:
<img src="https://user-images.githubusercontent.com/10991116/27756377-49f4580a-5dcd-11e7-9618-a01a3bf900b7.png" width="200"/>

**Comment by vishal0071** [comment]
This is a serious bug, thanks for reminding.

**Comment by vishal0071** [comment]
Fixed (atleast for rowLayout)

**Comment by EmmanuelMess** [comment]
Have you tested in a device/emulator?

**Comment by EmmanuelMess** [comment]
There are some other issues I've seen, like the FAB button being on the right side:
<img src="https://user-images.githubusercontent.com/10991116/28220826-501daa68-6897-11e7-9e68-9c80d980553f.png" width="150px"/>
Or this text on the left:
<img src="https://user-images.githubusercontent.com/10991116/28220827-50206a64-6897-11e7-935d-c46602eebe88.png" width="150px"/>

**Comment by EmmanuelMess** [comment]
@VishalNehra was this fixed?

**Comment by EmmanuelMess** [comment]
This is somehow even more broken now, forcing right to left produces no changes in the app.
