### ISSUE TITLE
Copying/creating .zip from root folder not possible (3.1.2 RC3, Nexus 5X, LinOS 7.1.2)

### ISSUE THREAD

**Issue by Foxdelmar** [TeamAmaze/AmazeFileManager#650]
I tried to copy some folders from /data/data/app-name to the folder /sdcard/ and to /sdcard/Download on my 
Nexus 5X
Amaze 3.1.2 RC3 (F-Droid)
Android 7.1.2 Lineage OS from 29.05.2017
Rooted

I was asked to allow root that I accepted.
I copied the files, went into the destination folder and after tapping the insert button on top of the screen a pop up shortly appeared and something with "nil, .." was shown but no files were copied. I was able to copy single files but no folders.

Is this problem known? I can not find an issue. What could be the reason?

best regards
Fox

**Comment by EmmanuelMess** [comment]
@VishalNehra is creating zip in root working correctly?

**Comment by VishalNehra** [comment]
I don't think we can zip in root directories, but this issue isn't regarding that 🤔 
For this issue, need to test.

**Comment by VishalNehra** [comment]
This is very old version. Need validation on latest v3.6.0. Can be reopened it required.
