### ISSUE TITLE
Fusion RarAdapter and RecyclerAdapter

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#651]
[RarAdapter](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/java/com/amaze/filemanager/adapters/RarAdapter.java) is doing basically the same thing as [RecyclerAdapter](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java) but for compressed files. They should be fusioned so that one file's code has to be maintained and not two.

**Comment by vishal0071** [comment]
That'll complicate the code, too much clutter. It's good idea to keep them separate.

**Comment by EmmanuelMess** [comment]
There seems to be a lot of similarities between the two, maybe keep some interconnection so as to not repeat code.

**Comment by vishal0071** [comment]
Is this really necessary? let's not mess things up :/
