### ISSUE TITLE
Problems uninstalling apps

### ISSUE THREAD

**Issue by superlex** [TeamAmaze/AmazeFileManager#653]
Hi, 
with 3.1.2 RC versions of Amaze I have problems uninstalling apps, because they are not removed.
No problems with 3.1.1 version.
Thanks for your work.

**Comment by superlex** [comment]
3.1.2 RC4 from Play Store deosn't fix the issue.
I'm using Flyme 6 global based on Lollipop.
I think the are problems with root: if I edit a system file (e.g. build.prop) and I save the file, changes aren't maintained.

**Comment by vishal0071** [comment]
Can you please provide a logcat. The problem is probably with the root binary.. you might also wanna update your su binary (su from chainfire is recommended).

**Comment by superlex** [comment]
Thanks for your reply. I'm using SuperSU (2.82) and su binary is updated. When I save a file a popup tell me "Done", but changed are not saved.

**Comment by vishal0071** [comment]
Use aLogcat or similar app from Play Store.

**Comment by vishal0071** [comment]
Let us know if you're still facing this bug

**Comment by superlex** [comment]
Hi, sorry for my absence.
It seems to be related to FlymeOS and his non-complete/limited root.
Now i'm using LineageOS 14.1 with SuperSU (flashed through twrp, not apk as in FlymeOS) and Amaze works very well.

**Comment by vishal0071** [comment]
Great!
