### ISSUE TITLE
Suppport for SMB2 and SMB3

### ISSUE THREAD

**Issue by GlassGruber** [TeamAmaze/AmazeFileManager#670]
Hey there!
Since your implementation of SMB is based on jcifs-1.3.18 library only SMB1 version is supported. [[source](https://lists.samba.org/archive/jcifs/2016-January/010328.html)]

This way many of the patched Windows devices for Wanna Cry outbreak are cut out. 
A quick research and I found this https://github.com/hierynomus/smbj, which should support SMB2 and SMB3.

Unfortunately I'm not very into Java and Android development and this is as far as I can get, if I can help with something else let me know!

**Comment by gadget1999** [comment]
Just found this library maybe similar to jcifs: https://github.com/AgNO3/jcifs-ng

I never worked on Android app before, will give it a try

**Comment by Talwvs** [comment]
There is also a commercial library, jNQ, that supports the encrypted SMB3.1.1 dialect:
https://visualitynq.com/products/jnq-java-smb-client

**Comment by TranceLove** [comment]
Superseded by #1633. We should use [hierynomus/smbj](https://github.com/hierynomus/smbj) now.
