### ISSUE TITLE
Force refresh when cutting-pasting a file

### ISSUE THREAD

**Issue by dRaiNe** [TeamAmaze/AmazeFileManager#674]
When I cut a file (from my External SD, but it doesn't matter) and paste it into a directory, the file is not visible in this directory immediately. I have to scroll upwards in order to refresh this view and see the file, so I can be sure the operation completed successfully.

So force redraw after cut-paste operation (maybe copy-paste, too?) completes.

**Comment by vishal0071** [comment]
Why did you close? Is the issue fixed?

**Comment by dRaiNe** [comment]
Oh, I though it was works, but it doesn't! It works on internal card, but it doesn't refresh the view on my external SD card on my Xperia Z3 Compact.
Affected operations (create file called x.txt, then copy it into a folder):
- Copying
- Cut & Paste
- Deletion of the file

So, I copy a file into a directory, then I see there's notification about copying the file, which disappears when the operation finishes successfully, but the view is not refreshed. I have to scroll up to refresh the view a see the new file.

Reopen this, if you can, thanks.

**Comment by EmmanuelMess** [comment]
Could you test again?

**Comment by dRaiNe** [comment]
It works now! Thank you!
