### ISSUE TITLE
Amaze doesn't support opening folders

### ISSUE THREAD

**Issue by denimwho** [TeamAmaze/AmazeFileManager#675]
Code to open folder:

`Intent openFolderIntent = new Intent(Intent.ACTION_VIEW);`
`openFolderIntent.setData(Uri.fromFile(new File(folderPath));`
`openFolderIntent.setType("resource/folder");`  
`startActivity(openFolderIntent);`

Amaze doesn't show in list of opens to open.

**Comment by vishal0071** [comment]
How do I test?

**Comment by denimwho** [comment]
Use adb to send intents to app

http://www.xgouchet.fr/android/index.php?article42/launch-intents-using-adb

**Comment by vishal0071** [comment]
Nice catch.. I completely forgot about this 👍👍
Will be working on the fix.

**Comment by denimwho** [comment]
Thanks

**Comment by EmmanuelMess** [comment]
Reopen this as it not yet solved.

**Comment by vishal0071** [comment]
Should've been fixed with v3.2.0

**Comment by denimwho** [comment]
I can't still open folders from another app using the above code.

**Comment by vishal0071** [comment]
Press on 'Select' from three-dot pop menu for that folder in the list
