### ISSUE TITLE
Cannot remove folder bookmarks

### ISSUE THREAD

**Issue by Alexander230** [TeamAmaze/AmazeFileManager#709]
I found option to add bookmark in folder context menu, but I didn't found how to remove bookmark. And when I added bookmark again, duplicated bookmark had been created.

**Comment by EmmanuelMess** [comment]
From settings under sidebar you can find the option to delete the bookmark.

**Comment by Alexander230** [comment]
Found it. App crashed multiple times while I was removing long list of bookmarks, but it works.

**Comment by EmmanuelMess** [comment]
Can you send crash logs? It would really help.

**Comment by Alexander230** [comment]
Where can I find them?

**Comment by Alexander230** [comment]
I tried to run "logcat | grep -i amaze" and reproduced 2 crashes: on bookmark creating and bookmark deleting:



I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{6012164 token=Token{3dd49ef7 ActivityRecord{11c61af6 u0 com.amaze.filemanager/.activities.MainActivity t5048}}} to stack=1 task=5048 at 0
V/WindowManager( 1223): Based on layer: Adding window Window{6063b85 u0 Starting com.amaze.filemanager} at 3 of 9
I/ActivityManager( 1223): Start proc 6073:com.amaze.filemanager/u0a95 for activity com.amaze.filemanager/.activities.MainActivity
V/WindowManager( 1223): Adding window Window{56d48ad u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} at 3 of 10 (before Window{6063b85 u0 Starting com.amaze.filemanager})
I/ActivityManager( 1223): START u0 {cmp=com.amaze.filemanager/.activities.PreferencesActivity} from uid 10095 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{144cfd92 token=Token{261eb71d ActivityRecord{2a283f4 u0 com.amaze.filemanager/.activities.PreferencesActivity t5049}}} to stack=1 task=5049 at 0
V/WindowManager( 1223): Adding window Window{28b31bdb u0 Starting com.amaze.filemanager} at 4 of 10 (after Window{56d48ad u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
V/WindowManager( 1223): Adding window Window{32872b53 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 11 (before Window{28b31bdb u0 Starting com.amaze.filemanager})
V/WindowManager( 1223): not Base app: Adding window Window{2dcf29af u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
V/WindowManager( 1223): not Base app: Adding window Window{17d33f16 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
V/WindowManager( 1223): not Base app: Adding window Window{5603284 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
W/ActivityManager( 1223):   Force finishing activity 1 com.amaze.filemanager/.activities.PreferencesActivity
W/ActivityManager( 1223): Activity pause timeout for ActivityRecord{2a283f4 u0 com.amaze.filemanager/.activities.PreferencesActivity t5049 f}
I/WindowState( 1223): WIN DEATH: Window{5603284 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
I/ActivityManager( 1223): Process com.amaze.filemanager (pid 6073) has died
I/WindowState( 1223): WIN DEATH: Window{32872b53 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{2af9b703 token=Token{37279bb2 ActivityRecord{1aa679bd u0 com.amaze.filemanager/.activities.MainActivity t5050}}} to stack=1 task=5050 at 0
V/WindowManager( 1223): Based on layer: Adding window Window{25b02598 u0 Starting com.amaze.filemanager} at 3 of 9
I/ActivityManager( 1223): Start proc 6351:com.amaze.filemanager/u0a95 for activity com.amaze.filemanager/.activities.MainActivity
V/WindowManager( 1223): Adding window Window{1518c4e0 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} at 3 of 10 (before Window{25b02598 u0 Starting com.amaze.filemanager})
I/ActivityManager( 1223): START u0 {cmp=com.amaze.filemanager/.activities.PreferencesActivity} from uid 10095 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{1e944509 token=Token{29d72610 ActivityRecord{1fda5ad3 u0 com.amaze.filemanager/.activities.PreferencesActivity t5051}}} to stack=1 task=5051 at 0
V/WindowManager( 1223): Adding window Window{1eb7b5e6 u0 Starting com.amaze.filemanager} at 4 of 10 (after Window{1518c4e0 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
V/WindowManager( 1223): Adding window Window{bcd9bbe u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 11 (before Window{1eb7b5e6 u0 Starting com.amaze.filemanager})
V/WindowManager( 1223): not Base app: Adding window Window{29c3b5ca u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
V/WindowManager( 1223): not Base app: Adding window Window{e77b817 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
W/ActivityManager( 1223):   Force finishing activity 1 com.amaze.filemanager/.activities.PreferencesActivity
W/ActivityManager( 1223): Activity pause timeout for ActivityRecord{1fda5ad3 u0 com.amaze.filemanager/.activities.PreferencesActivity t5051 f}
I/WindowState( 1223): WIN DEATH: Window{bcd9bbe u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
I/ActivityManager( 1223): Process com.amaze.filemanager (pid 6351) has died
I/WindowState( 1223): WIN DEATH: Window{e77b817 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{9dd62e7 token=Token{1588b8a6 ActivityRecord{dee201 u0 com.amaze.filemanager/.activities.MainActivity t5052}}} to stack=1 task=5052 at 0
V/WindowManager( 1223): Based on layer: Adding window Window{6fa3c2c u0 Starting com.amaze.filemanager} at 3 of 9
I/ActivityManager( 1223): Start proc 6497:com.amaze.filemanager/u0a95 for activity com.amaze.filemanager/.activities.MainActivity
V/WindowManager( 1223): Adding window Window{2d4e06f4 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} at 3 of 10 (before Window{6fa3c2c u0 Starting com.amaze.filemanager})
I/ActivityManager( 1223): START u0 {cmp=com.amaze.filemanager/.activities.PreferencesActivity} from uid 10095 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{3985d978 token=Token{49f9adb ActivityRecord{14d9c7ea u0 com.amaze.filemanager/.activities.PreferencesActivity t5053}}} to stack=1 task=5053 at 0
V/WindowManager( 1223): Adding window Window{1a14c089 u0 Starting com.amaze.filemanager} at 4 of 10 (after Window{2d4e06f4 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
V/WindowManager( 1223): Adding window Window{3ac6f7c1 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 11 (before Window{1a14c089 u0 Starting com.amaze.filemanager})
V/WindowManager( 1223): not Base app: Adding window Window{2f0a4efd u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
V/WindowManager( 1223): not Base app: Adding window Window{1573913e u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
W/ActivityManager( 1223):   Force finishing activity 1 com.amaze.filemanager/.activities.PreferencesActivity
W/ActivityManager( 1223): Activity pause timeout for ActivityRecord{14d9c7ea u0 com.amaze.filemanager/.activities.PreferencesActivity t5053 f}
I/ActivityManager( 1223): Process com.amaze.filemanager (pid 6497) has died
I/WindowState( 1223): WIN DEATH: Window{1573913e u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
I/WindowState( 1223): WIN DEATH: Window{3ac6f7c1 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{1d222902 token=Token{1508aa4d ActivityRecord{24dc85e4 u0 com.amaze.filemanager/.activities.MainActivity t5054}}} to stack=1 task=5054 at 0
V/WindowManager( 1223): Based on layer: Adding window Window{1471e08b u0 Starting com.amaze.filemanager} at 3 of 9
I/ActivityManager( 1223): Start proc 6655:com.amaze.filemanager/u0a95 for activity com.amaze.filemanager/.activities.MainActivity
V/WindowManager( 1223): Adding window Window{267645f3 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} at 3 of 10 (before Window{1471e08b u0 Starting com.amaze.filemanager})
I/ActivityManager( 1223): START u0 {cmp=com.amaze.filemanager/.activities.PreferencesActivity} from uid 10095 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{84f77e0 token=Token{17bc91e3 ActivityRecord{2ad39612 u0 com.amaze.filemanager/.activities.PreferencesActivity t5055}}} to stack=1 task=5055 at 0
V/WindowManager( 1223): Adding window Window{3429e3d1 u0 Starting com.amaze.filemanager} at 4 of 10 (after Window{267645f3 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
V/WindowManager( 1223): Adding window Window{2e643c09 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 11 (before Window{3429e3d1 u0 Starting com.amaze.filemanager})
V/WindowManager( 1223): not Base app: Adding window Window{2b0b8fc5 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
I/ActivityManager( 1223): START u0 {flg=0x10000000 cmp=com.amaze.filemanager/.activities.PreferencesActivity} from uid 10095 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{3a85e627 token=Token{11c040e6 ActivityRecord{331a6341 u0 com.amaze.filemanager/.activities.PreferencesActivity t5056}}} to stack=1 task=5056 at 0
V/WindowManager( 1223): Adding window Window{bb9a66c u0 Starting com.amaze.filemanager} at 4 of 10 (after Window{2e643c09 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity})
V/WindowManager( 1223): Adding window Window{1da19eb1 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 11 (before Window{bb9a66c u0 Starting com.amaze.filemanager})
I/ActivityManager( 1223): START u0 {act=android.intent.category.LAUNCHER cmp=com.amaze.filemanager/.activities.MainActivity} from uid 10095 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{1a202f22 token=Token{20074ed ActivityRecord{7405704 u0 com.amaze.filemanager/.activities.MainActivity t5057}}} to stack=1 task=5057 at 0
V/WindowManager( 1223): Adding window Window{2af4102b u0 Starting com.amaze.filemanager} at 4 of 10 (after Window{1da19eb1 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity})
V/WindowManager( 1223): Adding window Window{33fb0f6 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} at 4 of 11 (before Window{2af4102b u0 Starting com.amaze.filemanager})
I/ActivityManager( 1223): Killing 6655:com.amaze.filemanager/u0a95 (adj 9): remove task
I/WindowState( 1223): WIN DEATH: Window{33fb0f6 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}
I/Timeline( 5641): Timeline: Activity_launch_request id:com.amaze.filemanager time:561916598
I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{1baa4cfa token=Token{7fb8325 ActivityRecord{2fd25b1c u0 com.amaze.filemanager/.activities.MainActivity t5063}}} to stack=1 task=5063 at 0
V/WindowManager( 1223): Based on layer: Adding window Window{23a73c23 u0 Starting com.amaze.filemanager} at 3 of 9
I/ActivityManager( 1223): Start proc 21320:com.amaze.filemanager/u0a95 for activity com.amaze.filemanager/.activities.MainActivity
W/XPrivacy(21320): Hooking package=com.amaze.filemanager
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:341)
V/WindowManager( 1223): Adding window Window{e7f528b u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} at 3 of 10 (before Window{23a73c23 u0 Starting com.amaze.filemanager})
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity$3.onPostExecute(MainActivity.java:480)
W/System.err(21320): 	at com.amaze.filemanager.utils.AppConfig$1.onPostExecute(AppConfig.java:104)
I/ActivityManager( 1223): Displayed com.amaze.filemanager/.activities.MainActivity: +894ms
I/Timeline( 1223): Timeline: Activity_windows_visible id: ActivityRecord{2fd25b1c u0 com.amaze.filemanager/.activities.MainActivity t5063} time:561917515
W/PackageManager( 5248): Failure retrieving resources for com.amaze.filemanager: Resource ID #0x0
I/Timeline( 5641): Timeline: Activity_launch_request id:com.amaze.filemanager time:561923167
I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
I/Timeline( 1223): Timeline: Activity_windows_visible id: ActivityRecord{2fd25b1c u0 com.amaze.filemanager/.activities.MainActivity t5063} time:561923631
W/PackageManager( 5248): Failure retrieving resources for com.amaze.filemanager: Resource ID #0x0
I/Timeline( 5641): Timeline: Activity_launch_request id:com.amaze.filemanager time:562031901
I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
I/Timeline( 1223): Timeline: Activity_windows_visible id: ActivityRecord{2fd25b1c u0 com.amaze.filemanager/.activities.MainActivity t5063} time:562032365
V/WindowManager( 1223): Adding window Window{2b9bfcc0 u0 PopupWindow:8ee5a4} at 4 of 10 (after Window{e7f528b u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(21320): 	at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:117)
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.onBookAdded(MainActivity.java:2767)
W/System.err(21320): 	at com.amaze.filemanager.utils.DataUtils$1.run(DataUtils.java:210)
V/WindowManager( 1223): Adding window Window{3610e1a2 u0 PopupWindow:1be32453} at 4 of 11 (after Window{e7f528b u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(21320): 	at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:117)
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.onBookAdded(MainActivity.java:2767)
W/System.err(21320): 	at com.amaze.filemanager.utils.DataUtils$1.run(DataUtils.java:210)
V/WindowManager( 1223): Adding window Window{307c54c6 u0 PopupWindow:1b519dd} at 4 of 11 (after Window{e7f528b u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.onBookAdded(MainActivity.java:2767)
W/System.err(21320): 	at com.amaze.filemanager.utils.DataUtils$1.run(DataUtils.java:210)
W/System.err(21320): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(21320): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(21320): 	at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:117)
E/AndroidRuntime(21320): Process: com.amaze.filemanager, PID: 21320
E/AndroidRuntime(21320): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1659)
E/AndroidRuntime(21320): 	at com.amaze.filemanager.activities.MainActivity.onBookAdded(MainActivity.java:2767)
E/AndroidRuntime(21320): 	at com.amaze.filemanager.utils.DataUtils$1.run(DataUtils.java:210)
W/ActivityManager( 1223):   Force finishing activity 1 com.amaze.filemanager/.activities.MainActivity
W/PackageManager( 5248): Failure retrieving resources for com.amaze.filemanager: Resource ID #0x0
I/ActivityManager( 1223): Process com.amaze.filemanager (pid 21320) has died
I/Timeline( 5641): Timeline: Activity_launch_request id:com.amaze.filemanager time:562076772
I/ActivityManager( 1223): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity bnds=[546,845][714,1098]} from uid 10085 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{16f47874 token=Token{1951a847 ActivityRecord{c773786 u0 com.amaze.filemanager/.activities.MainActivity t5064}}} to stack=1 task=5064 at 0
V/WindowManager( 1223): Based on layer: Adding window Window{1a1b9755 u0 Starting com.amaze.filemanager} at 3 of 9
I/ActivityManager( 1223): Start proc 22407:com.amaze.filemanager/u0a95 for activity com.amaze.filemanager/.activities.MainActivity
W/XPrivacy(22407): Hooking package=com.amaze.filemanager
W/System.err(22407): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(22407): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(22407): 	at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:341)
V/WindowManager( 1223): Adding window Window{27ad627d u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} at 3 of 10 (before Window{1a1b9755 u0 Starting com.amaze.filemanager})
W/System.err(22407): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(22407): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(22407): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1558)
W/System.err(22407): 	at com.amaze.filemanager.activities.MainActivity$3.onPostExecute(MainActivity.java:480)
W/System.err(22407): 	at com.amaze.filemanager.utils.AppConfig$1.onPostExecute(AppConfig.java:104)
I/ActivityManager( 1223): Displayed com.amaze.filemanager/.activities.MainActivity: +909ms
I/Timeline( 1223): Timeline: Activity_windows_visible id: ActivityRecord{c773786 u0 com.amaze.filemanager/.activities.MainActivity t5064} time:562077705
I/Timeline(22407): Timeline: Activity_launch_request id:com.amaze.filemanager time:562082923
I/ActivityManager( 1223): START u0 {cmp=com.amaze.filemanager/.activities.PreferencesActivity} from uid 10095 on display 0
V/WindowManager( 1223): addAppToken: AppWindowToken{f2fdf22 token=Token{7c0e4ed ActivityRecord{22fc8704 u0 com.amaze.filemanager/.activities.PreferencesActivity t5065}}} to stack=1 task=5065 at 0
V/WindowManager( 1223): Adding window Window{2810002b u0 Starting com.amaze.filemanager} at 4 of 10 (after Window{27ad627d u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
W/System.err(22407): 	at com.amaze.filemanager.fragments.preference_fragments.Preffrag.onCreate(Preffrag.java:129)
W/System.err(22407): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.hardware.fingerprint.FingerprintManager" on path: DexPathList[[zip file "/data/app/com.amaze.filemanager-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
V/WindowManager( 1223): Adding window Window{117249a3 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 11 (before Window{2810002b u0 Starting com.amaze.filemanager})
I/ActivityManager( 1223): Displayed com.amaze.filemanager/.activities.PreferencesActivity: +234ms
I/Timeline( 1223): Timeline: Activity_windows_visible id: ActivityRecord{22fc8704 u0 com.amaze.filemanager/.activities.PreferencesActivity t5065} time:562083369
V/WindowManager( 1223): not Base app: Adding window Window{3555dcff u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
V/WindowManager( 1223): not Base app: Adding window Window{3aa6f7b8 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
V/WindowManager( 1223): not Base app: Adding window Window{5cc60f6 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity} at 4 of 10
E/AndroidRuntime(22407): Process: com.amaze.filemanager, PID: 22407
E/AndroidRuntime(22407): 	at com.amaze.filemanager.fragments.preference_fragments.FoldersPref$3.onClick(FoldersPref.java:257)
W/ActivityManager( 1223):   Force finishing activity 1 com.amaze.filemanager/.activities.PreferencesActivity
W/ActivityManager( 1223): Activity pause timeout for ActivityRecord{22fc8704 u0 com.amaze.filemanager/.activities.PreferencesActivity t5065 f}
I/WindowState( 1223): WIN DEATH: Window{5cc60f6 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
I/ActivityManager( 1223): Process com.amaze.filemanager (pid 22407) has died
I/WindowState( 1223): WIN DEATH: Window{117249a3 u0 com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}
W/

**Comment by vishal0071** [comment]
Try clearing Amaze data from system settings

**Comment by Alexander230** [comment]
It didn't help. Amaze crashes on every 2 deleted bookmarks.

**Comment by EmmanuelMess** [comment]
Can replicate. Just select add to favorites in file menu and delete in settings.

**Comment by vishal0071** [comment]
So the problem is with adding bookmarks from preferences.

**Comment by EmmanuelMess** [comment]
No, "add to favorites", in item menu. Delete from settings.

**Comment by bowiechen** [comment]
I can't seem to replicate this issue. Can anyone write a more detailed step to reproduce?

**Comment by EmmanuelMess** [comment]
Maybe this is old, will close.
