### ISSUE TITLE
Crash on opening ftp tab

### ISSUE THREAD

**Issue by Damjan94** [TeamAmaze/AmazeFileManager#711]
The app crashes when you try to open a ftp tab, while not connected to a wifi....

**Comment by vishal0071** [comment]
Please submit the crash report from FC dialog.

**Comment by Damjan94** [comment]
I sent the feedback, if that's what you meant, if you want me to post the log here, please explain how to obtain it...

**Comment by vishal0071** [comment]
It's fine, submitting the feedback from fc dialog wold do it.

**Comment by vishal0071** [comment]
Should've been fixed with v3.2.0
