### ISSUE TITLE
Cutting and pasting a lot of files crashes the app

### ISSUE THREAD

**Issue by will9183** [TeamAmaze/AmazeFileManager#715]
Hello, when I try to cut and paste a lot of files from my internal storage to my sdcard the app crashes when I select cut.

Device: Amazon Fire tablet from 2015
App: From Google Play

And that is it

**Comment by vishal0071** [comment]
Kindly press on 'send feedback' or report option in the force close dialog.

**Comment by will9183** [comment]
But when it crashes it doesn't come up with a force close dialog box, it just closes to the home screen.

**Comment by vishal0071** [comment]
Then would need a logcat

**Comment by will9183** [comment]
OK so here is the logcat from the time I select the items to when it crashes.
I ran the command adb logcat | grep amaze so it should only shown logs from Amaze
[logcat.txt](https://github.com/TeamAmaze/AmazeFileManager/files/1232244/logcat.txt)

**Comment by szholdiyarov** [comment]
@vishal0071 the version on the Play Market is not the latest isn't?

**Comment by vishal0071** [comment]
@szholdiyarov the latest one on play store is v3.2.0

**Comment by will9183** [comment]
I updated the app and now the bug is gone. Now I can get back work. Thanks. 😃
