### ISSUE TITLE
Move CloudAsyncTask out of MainActivtity

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#720]
Move CloudAsyncTask out of MainActivtity, [here](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L2583). Also, if possible, the [LoaderCallbacks](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L2500). That will free some space in the 2800 lines file.

**Comment by MattiaPrimavera** [comment]
what about moving to **rxJava2** in order to directly get read of **Loaders** and **AsyncTasks**, freeing up a lot of space in the code base ?

**Comment by EmmanuelMess** [comment]
@MattiaPrimavera by how much will the ProGuarded apk grow in size if we implement this? How much code could we actually get rid of? Why is it better (from an asymptotic complexity standpoint)?

**Comment by MattiaPrimavera** [comment]
Why is the **Proguard** APK size increase so important?

**Comment by EmmanuelMess** [comment]
>  [...] will the ProGuard**ed** apk grow in size [...]?

(énfasis added)

[ProGuard](https://www.guardsquare.com/en/proguard).

**Comment by MattiaPrimavera** [comment]
Isn't proguard meant to reduce the APK of signed code through shrinking code procedure as well? Why should that increase more than a debug build would?

**Comment by EmmanuelMess** [comment]
Adding libraries inherently increases size, as more functions with more code are added and used. Also some libraries require extensive preservation of complete classes, thus making the final size quite a bit larger.

**Comment by MattiaPrimavera** [comment]
Of course it does but isn't 90% of the app size resources related? 

I think **Proguard** is mostly useful for **code obfuscation** and yes **shrink code** since it's useless to include unused methods plus the **65k limit** ... 

I mean it does reduces the app size but in an amount that does really have an important effect?

**Comment by MattiaPrimavera** [comment]
> how much code could we get rid of

If we lean on **Rx**, by combining it with **retrolambda**, plus the following : 
- **RxPermissions**
- **RxActivityResult**
- **RxBindings**

Well there would be a gain in **code readability**, less classes would be necessary to separate concerns (replacing **AsyncTask** with **Observable**), all **Loaders** code converted to **Observables** would be reduced and clearer.

Furthermore **Rx** facilitates handling errors in one spot, gives uniformity to **interfaces** needed to **pass** the information, above all among a background thread and the **UI**, proposes a lot of operators to **transform** the data... Treating data as a stream has its advantages ...

**Comment by EmmanuelMess** [comment]
- I ask for file size of Proguaded apk because it would be the real size of the file a new user would have to download from Play Store (for the standard user, as download sizes depend on a number of factors).
- How much inefficiency does this create?
- Retrolamba was proposed in #713.
