### ISSUE TITLE
open file in separate process

### ISSUE THREAD

**Issue by seregaxvm** [TeamAmaze/AmazeFileManager#725]
Why Amaze opens files inside it's own task? Probably it's better to spawn separate process. This way you can switch between opened windows.

**Comment by EmmanuelMess** [comment]
So, what you want is to be able to open several files at the same time?

**Comment by seregaxvm** [comment]
Basically, yes. Right now I use module from xposed framework to simulate this behavior. It sets `FLAG_ACTIVITY_NEW_TASK` for new tasks.

**Comment by EmmanuelMess** [comment]
Ok, I understand, probably should use `FLAG_ACTIVITY_NEW_DOCUMENT` though.

**Comment by EmmanuelMess** [comment]
You should start explaining to @vishal0071 why anyone would use this feature, so that my pull request can exit limbo.
