### ISSUE TITLE
Default home should be sdcard

### ISSUE THREAD

**Issue by mirh** [TeamAmaze/AmazeFileManager#729]
Not /

**Comment by vishal0071** [comment]
It is SD Card when you have one inserted, otherwise it's root.

**Comment by mirh** [comment]
Since ics days, I don't think /sdcard has ever actually been a physical SD card
It's the internal storage partition, aka /storage/emulated/0

**Comment by vishal0071** [comment]
Path don't matter, if you've SD Card inserted it'll show up in drawer, and as second tab once you give permissions.

**Comment by mirh** [comment]
I'm not talking about sd cards!
Which phones may or may not have. 

I'm talking about `/sdcard`, which is there in every one. 
The internal storage. 

If you are saying that's already the expected case, on my Xperia S it seemingly isn't.

**Comment by vishal0071** [comment]
So you're saying internal memory is not being detected by Amaze by default on your device?

**Comment by mirh** [comment]
It is (albeit #730) but home is set to /

**Comment by vishal0071** [comment]
In one tab, the another tab does set it to internal memory.
Left tab sets home to root i.e. ````/```` in case we can't find any external SD Card, and the right tab is always the internal memory unless you manually change it. Let me know if this is not the default behavior for you.

**Comment by mirh** [comment]
Both tabs default to /

**Comment by vishal0071** [comment]
Alright, have you given correct storage permissions to Amaze? Confirm that from system settings -> apps -> Amaze -> Permissions -> storage

**Comment by mirh** [comment]
Yes, I can browse it.

**Comment by mase76** [comment]
You can set the default home for both tabs.

**Comment by mirh** [comment]
*Yeees* - but the question is.. Why didn't it already set in the first place?

**Comment by EmmanuelMess** [comment]
Could I ask which directories (paths) you think should have been set as home for each of the two tabs in your device?

**Comment by mirh** [comment]
> and the right tab is always the internal memory unless you manually change it

The one dev already claimed should be supposed to be?

**Comment by EmmanuelMess** [comment]
@mirh I need to make sure that there isn't any code doing something it shouldn't and information in this thread is to vague, please do answer the question with the two paths.

**Comment by mirh** [comment]
\*At least\* one tab should be set to `/sdcard`
At the moment (I touched nothing) both are `/`

**Comment by mirh** [comment]
Ok, I have a tentative explanation for this. 
If you open settings/whatever when #730, the app just accepts the 'current' fallback default
