### ISSUE TITLE
Tapping "Report Bugs" in 'About Amaze File Manager' Force Closes the App

### ISSUE THREAD

**Issue by digital-idiot** [TeamAmaze/AmazeFileManager#732]
**Tapping "Report Bugs" in 'About Amaze File Manager' Force Closes the App**

Amaze File Manager Version : 3.2.1
Lineage OS version : 14.1-20170817-NIGHTLY
Kernel version : 3.18.31
Device : mido

Logcat : [Github Gist](https://gist.github.com/digital-idiot/c15ea1f9fa20c0085c740f475525e5cb)

**Comment by vishal0071** [comment]
You don't have any internet browser installed?

**Comment by digital-idiot** [comment]
My bad. I had stock browser only and there was an issue in stock browser in that nightly Lineage build. The issue has been resolved when I installed Firefox. Stock browser also has been fixed it in the latest nightly. I should have checked the logcat myself before reporting the issue.
