### ISSUE TITLE
Amaze File Manager is showing Wrong Path in some cases

### ISSUE THREAD

**Issue by digital-idiot** [TeamAmaze/AmazeFileManager#733]
Amaze File Manager is showing **Wrong Path** in some cases. For illustration please see the below screen shots:

<img src="https://user-images.githubusercontent.com/10576475/29688514-ab19aefa-893d-11e7-9c40-094482a9d6e6.png" height="500px"/><img src="https://user-images.githubusercontent.com/10576475/29688520-b31284ce-893d-11e7-897a-3df1fcc41df8.png" height="500px"/>

It generally adds an extra **'/'**

Amaze File Manager Version : 3.2.1
Lineage OS version : 14.1-20170817-NIGHTLY
Kernel version : 3.18.31
Device : mido

**Comment by EmmanuelMess** [comment]
Also happens using amaze cloud.

**Comment by vishal0071** [comment]
It's intentional in Amaze cloud (otg and smb too), but the extra / in root directories indeed is a bug. Will try to fix it since I'm the one who introduced it.
