### ISSUE TITLE
Timed light/dark theme doesn't always coincide with day/night

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#736]
Currently the code checks for the time (between 6 and 18 is day), I am open to suggestion for better ways to check for day/night.

**Comment by EmmanuelMess** [comment]
Well, I found [this](https://android.stackexchange.com/a/96986), have no idea if I will be able to implement it, but it's a start.

**Comment by EmmanuelMess** [comment]
I am having problems importing `com.android.server.twilight.TwilightService`.

**Comment by AnirudhaAgashe** [comment]
Unfortunately the TwilightService is not exposed to developers so you won't be able to use it.

To calculate sunrise and sunset timing for any particular day it is necessary to have the co-ordinates for that location.

Currently the application is not requesting location permission. You will need to first take a call whether to integrate this feature at cost of location permission or not ?


If the function needs to be implemented then we can use either of the two approaches

1. Integarte [TwilightCalculator ](https://github.com/aosp-mirror/platform_frameworks_base/blob/lollipop-release/services/core/java/com/android/server/TwilightCalculator.java)in application and use it to select LIGHT or Dark theme

2. [DayNight theme](https://android-developers.googleblog.com/2016/02/android-support-library-232.html#daynight) introduced in appcompat library 23
**Note:** When no location is provided the sunrise and sunset times are constant as explained in the [post](https://medium.com/@chrisbanes/appcompat-v23-2-daynight-d10f90c83e94#e304)

**Comment by j12i** [comment]
You don't need to get the exact location for this calculation, just let users enter geocoordinates as precisely as they desire.

**Comment by EmmanuelMess** [comment]
Who does the nontrivial calculation of the position of the sun?

**Comment by AnirudhaAgashe** [comment]
I think solution suggested by @j12i is ideal one. Since we only need the latitude and longitude(approx entered by user) and date(obtained from the device) to calculate sun rise and sun set timing for that date we can implement the feature without having to request additional location permission.

**Comment by EmmanuelMess** [comment]
Too much trouble to get the user to get the location coordinates. Also which library would do the sunrise sunset calculation?

**Comment by AnirudhaAgashe** [comment]
The Geo Co-ordinates can be found using Google Maps. This might not be the most user friendly method but tech savvy people might have some idea as to to their co-ordinates or can find it quite easily.

As for the sunrise and sunset calculation refer my message from earlier

Integrate [TwilightCalculator](https://github.com/aosp-mirror/platform_frameworks_base/blob/lollipop-release/services/core/java/com/android/server/TwilightCalculator.java) in application and use it to select LIGHT or Dark theme


[TwilightCalculator](https://github.com/aosp-mirror/platform_frameworks_base/blob/lollipop-release/services/core/java/com/android/server/TwilightCalculator.java) will do the calculation and you will get sunrise and sunset time in long.

One approach for better UX would be to let user control if he wants to grant the application location permission or enter his co-ordinates manually.
