### ISSUE TITLE
When pasting multiple folders the manager reloads multiple times

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#740]
When pasting multiple folders the manager reloads multiple times, once for each pasted folder.

**Comment by vishal0071** [comment]
That's awesome, right?!

**Comment by EmmanuelMess** [comment]
It's redundant… If the folder didn't change (only their contents changed), reloading makes no sense…

**Comment by Alexander--** [comment]
@vishal0071 it sounds like @EmmanuelMess is talking about lack of refresh throttling. "Pasting multiple folders" isn't the worst thing, that may be cause frequent updates. Try to paste a folder with thousands files and enter it immediately, after it gets created. Whoops…

**Comment by vishal0071** [comment]
I don't think he's talking about that. I did put a 5 sec refresh window in observer.  So if files get created within that time, it won't refresh the list.

**Comment by Alexander--** [comment]
> I did put a 5 sec refresh window 

@vishal0071 interesting, I missed that. Did you means 5 *milliseconds*? The code calls `getTimeInMillis`, then compares difference with `5`…

Btw, the implementation looks subtly buggy. Some events can be missed: if the event arrives within the interval after the previous event (and the previous refresh has already completed), no new refresh will be triggered (so the change gets silently lost).

**Comment by vishal0071** [comment]
@Alexander-- my bad, I intended to put the defer time to 5 secs.. thanks for pointing.

**Comment by EmmanuelMess** [comment]
To clarify, cut 5 folders "a" to "e" (with, say, 35MB of stuff) and paste them into another folder "C", when "a" is finished getting pasted "C" will refresh, repeat until "e". Folders should be silently added to the list, you don't need to reload, there's no need to recheck the whole directory for changes because you already know the changes, just check if the pasted folder exists.

**Comment by vishal0071** [comment]
This is the job of observer. I tried achieving this in past but due to our code, and amount of callbacks the observer was making, it made possible for list data to get corrupted.
Regardless, I think I'll give it another go at fixing everything with the observer.
