### ISSUE TITLE
While the copy tree is being generated nothing happens

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#741]
While the copy tree is being generated nothing happens, after the search finishes the copy/cut dialog is shown (skip, overwrite, etc.) or pasting starts, this can lead to the user accidentally cancelling or overwriting something.

**Comment by vishal0071** [comment]
You can set some loading message in dialog so that user know it's being processed. Since you assigned this to yourself, I hope you can fix this (:

**Comment by EmmanuelMess** [comment]
Fixed with PR #797.
