### ISSUE TITLE
Add support for saving a file from external intent to a read-only filesystem

### ISSUE THREAD

**Issue by vishal0071** [TeamAmaze/AmazeFileManager#743]
When having intent data, if user decides to - with root permissions, save the file in root directory which he doesn't have permission to write to, it will possibly fail.

**Comment by EmmanuelMess** [comment]
Pardon me but read-only is, by definition, not writeable, so you can't save anything.

**Comment by vishal0071** [comment]
@EmmanuelMess this refers to the talk me and @Alexander-- had in (this)[https://github.com/TeamAmaze/AmazeFileManager/commit/1de64b24afcab6f35989d701021ce6a3ad223387] commit.

**Comment by vishal0071** [comment]
Amaze will return with a toast notification stating the operation is not allowed, so that user can save the file to r/w filesystem first and then move file later from Amaze to the r/o filesystem where he wanted. Reason - it'll add lot of unnecessary code and is not worth it.
