### ISSUE TITLE
First entry in SMB table is ignored by drawer

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#744]
The first SMB connection ever created is never shown up in drawer, hence forcing the user to create a new connection.

**Comment by singpolyma** [comment]
I find than no matter how many times I create the connection, it never shows up and I have to re-create it every time.

I think I once got it to save the connection, but then it would crash every time I opened Amaze until I cleared the app data...

**Comment by vishal0071** [comment]
What version of Amaze do you use?

**Comment by TranceLove** [comment]
Should be closed by #1099.
