### ISSUE TITLE
Missing 3.2.1 tag

### ISSUE THREAD

**Issue by mimi89999** [TeamAmaze/AmazeFileManager#746]
Please add it for F-Droid.

**Comment by CryptOwl** [comment]
Seconded, where's the tag?

**Comment by mimi89999** [comment]
@vishal0071 You bumped the version in https://github.com/TeamAmaze/AmazeFileManager/commit/984ccac877133ddc0ca002fdc467779f456f0d3a, but didn't add any tag

**Comment by EmmanuelMess** [comment]
It has been added.
