### ISSUE TITLE
No storage is selected when the app starts

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#749]
No storage is selected when the app starts.

**Comment by vishal0071** [comment]
As far as I'm concerned, we ask for storage permissions at start for right tab. Once permitted, the home changes to the internal memory. For the left tab, the home is set to external memory (SD Card) if there is one. 
Am I missing something?

**Comment by EmmanuelMess** [comment]
Yes, I am not saying that 'home' is wrongly set, I am saying that no storage item (in the drawer) is selected when the app starts.

**Comment by vishal0071** [comment]
I understand
