### ISSUE TITLE
File list doesn't update after file extraction

### ISSUE THREAD

**Issue by 12people** [TeamAmaze/AmazeFileManager#750]
When I extract a zip file, I would expect the contents to be shown in the folder list right away. 
Instead, I have to refresh the list to see them (that took me a bit of time to figure out). Please consider always refreshing the list after extraction.

**Comment by vishal0071** [comment]
Where were you trying to extract the file (internal memory/sd card/smb or cloud)?

**Comment by 12people** [comment]
@vishal0071 Internal memory, downloads folder

**Comment by vishal0071** [comment]
It won't refresh unless you're in that folder where you extracted it. For eg. if you extracted it from inside the zip viewer, it won't obviously refresh as you're not in it.

**Comment by 12people** [comment]
@vishal0071 I know that. I was extracting the ZIP file in Downloads, and that folder didn't update. Could you reopen this bug?

**Comment by EmmanuelMess** [comment]
I can't replicate.

**Comment by vishal0071** [comment]
@12people what device and android version do you use?

**Comment by 12people** [comment]
@vishal0071 Nexus 5, Android Marshmallow
