### ISSUE TITLE
Scrolling down the sdcard directory crashes Amaze

### ISSUE THREAD

**Issue by JORGETECH** [TeamAmaze/AmazeFileManager#751]
Trying to scroll down the sdcard root directory will eventually crash the app.

I tried doing the same thing with the internal memory and it does not crash.

Issue is present in both stable and beta Google Play versions.

I attached a logcat in case it is useful, I found some interesting message in it that could point to the issue:

E/dalvikvm(26077): Could not find class 'android.graphics.drawable.VectorDrawable', referenced from method com.amaze.filemanager.activities.MainActivity.initFabToSave

-------------------------------------------------------
Android version: KitKat 4.4.2 (EMUI)

Logcat: https://mega.nz/#!O4kFBRCB!K0N97VNZ06CsduwGUHWi4wiKT4OJsgFbTL-rOm2eSOw

**Comment by EmmanuelMess** [comment]
You sent a link to an app (*.apk file).

**Comment by JORGETECH** [comment]
Yeah, Drive trolled me again, reuploaded with a decent service.

**Comment by EmmanuelMess** [comment]
Commit [494974f](https://github.com/TeamAmaze/AmazeFileManager/pull/723/commits/494974f5002e2d2fa2c7805b552355bda972978c) might solve this.

**Comment by JORGETECH** [comment]
I'll report back as soon as the next build arrives.

**Comment by EmmanuelMess** [comment]
This is most likely fixed, we'll reopen if you test and it isn't.
