### ISSUE TITLE
Proposition: Use Butterknife

### ISSUE THREAD

**Issue by MattiaPrimavera** [TeamAmaze/AmazeFileManager#766]
Why not to use **Butterknife** lib to delete all **findViewById** boilerplate code through **annotations**? It can avoid declaring lots of **event listeners** as well.

As example, `FTPServerFragment` contains : 

```java
statusText =(TextView) rootView.findViewById(R.id.text_view_ftp_status);
username = (TextView) rootView.findViewById(R.id.text_view_ftp_username);
password = (TextView) rootView.findViewById(R.id.text_view_ftp_password);
port = (TextView) rootView.findViewById(R.id.text_view_ftp_port);
sharedPath = (TextView) rootView.findViewById(R.id.text_view_ftp_path);
ftpBtn = (Button) rootView.findViewById(R.id.startStopButton);
startDividerView = rootView.findViewById(R.id.divider_ftp_start);
statusDividerView = rootView.findViewById(R.id.divider_ftp_status);
``` 

All these `bindings` would than appear within the `class attributes` declaration, as follows : 

```java
@BindView(R.id.text_view_ftp_status) TextView statusText;
@BindView(R.id.text_view_ftp_username) TextView username;
...
``` 

Trying to count `findViewById` occurrences across the entire codebase gives : 

``` bash
find . -name "*.java"|xargs -n 1 grep "findViewById"| wc -l                                                                                                                                                
     294
```

**Comment by EmmanuelMess** [comment]
No, as API 26 solves the issue of casting and the annotations not actually being inside the function can decrease the readability.

**Comment by MattiaPrimavera** [comment]
Agreed on solved casting problem, which makes **findViewById** lines lighter. 

On code readibility instead I think a developer could forget calls to **findViewById**, which would lead to **NullPointeException**, and having lot of **findViewById** calls I think does bother code readability since it adds extra lines with no useful, but repetitive information, I think it's a lot easier to add annotation on the attribute declaration as an habit to take. Plus **18000** stars on github is pretty much a sign of appreciation from the community. This stays my humble opinion ;)

**Comment by MattiaPrimavera** [comment]
Anyway ticket can be closed if not gonna be applied :)

**Comment by EmmanuelMess** [comment]
@MattiaPrimavera a lot of fields need initialization on activity/view creation, forgetting a findViewById() is not something you usually do, as Android Studio will show a warning.
From the example you have shown the lines would still be there, before the method, in annotations (same number of lines, different syntax, syntax that might be confusing to new devs).
I have not closed the ticket to let you defend your proposal.

**Comment by MattiaPrimavera** [comment]
If u mean extra weight in **kB** I don't think that will affect a lot ... Or do u refer to **65k methods limit** ? 

On the learning curve I'd say that would be pretty low, still I'd be happy handling this issue if I can, and the purpose is accepted ;)

**Comment by EmmanuelMess** [comment]
[Butterknife](http://jakewharton.github.io/butterknife/) should not be very spacious as it changes the annotations to a compact function on compilation, as far as I could learn from the web.
If @vishal0071 approves it would be added in the future.
After update to API 26.

**Comment by MattiaPrimavera** [comment]
Is there already an issue for that update? Particular issues foreseen on that? Or should be easy one?

**Comment by EmmanuelMess** [comment]
#748

**Comment by EmmanuelMess** [comment]
Okay, [Kotlin Android Extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html) is better (I think). It autodecleares the variables with the name id provided in XML.

**Comment by EmmanuelMess** [comment]
superseded by #2101
