### ISSUE TITLE
There are lines of code that require higher API versions

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#768]
Scattered though the code are lines that require higher API versions like [this](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/ui/notifications/FTPNotification.java#L92) one in FTPNotification or [this](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java#L847) and [this](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java#L872). These lines might cause unexpected crashes.

**Comment by vishal0071** [comment]
First one has already an API check

**Comment by EmmanuelMess** [comment]
Not the correct one, api 17 (oldest with the method) > API 16 (jelly bean, inside if).
