### ISSUE TITLE
No shortcut generated

### ISSUE THREAD

**Issue by DTsEMT** [TeamAmaze/AmazeFileManager#771]
Hi there. Recently updated Nexus 6P to Oreo. I'm trying to generate a shortcut to an audio file. I open Amaze, navigate to the file, and long press to select. Tapping the overflow menu, the drop down shows the option to "Add shortcut". Tapping that option, the program pauses or seems to do something, but no shortcut is created (at least, none that I can find)

Thanks!

**Comment by Alexander--** [comment]
Yup, the old way to create launcher shortcuts might have stopped working. I suspect, that this might be fixable by detecting the launcher app and sending targeted broadcast directly to it's package (instead of untargeted broadcast, which stopped working).
