### ISSUE TITLE
Why make comparison between EMAIL_ADDRESS pattern and path then changing openmode to root?

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#782]
https://github.com/TeamAmaze/AmazeFileManager/blob/bc8265249f38ae8499993993b8195f1ce95ec960/app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java#L119-L120

Why does this comparison exist? Why does it change the openmode to ROOT?

**Comment by vishal0071** [comment]
I didn't write that code. Will fix this soon.
