### ISSUE TITLE
storage_count can be read before it is correctly set

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#783]
This variable storage_count:
https://github.com/TeamAmaze/AmazeFileManager/blob/bc8265249f38ae8499993993b8195f1ce95ec960/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L196
The code that sets storage_count is in MainActivity.refreshDrawer():
https://github.com/TeamAmaze/AmazeFileManager/blob/bc8265249f38ae8499993993b8195f1ce95ec960/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L1403-L1427
That seems to only get called (when first starting the app) from CloudAsyncTask.onPostExecute():
https://github.com/TeamAmaze/AmazeFileManager/blob/bc8265249f38ae8499993993b8195f1ce95ec960/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L2754-L2760
storage_count is used in TabFragment.onCreateView():
https://github.com/TeamAmaze/AmazeFileManager/blob/bc8265249f38ae8499993993b8195f1ce95ec960/app/src/main/java/com/amaze/filemanager/fragments/TabFragment.java#L109-L113
If CloudAsyncTask is sufficiently slow or everything that occurs before TabFragment.onCreateView() is sufficiently fast storage_count will be 0 when read, and the directory on first open (or always if "don't save directory" setting is enabled) will be root.

**Comment by vishal0071** [comment]
Usage of volatile for storage_count is now not required. I was trying to make refreshDrawer for background processing in the past.
Why do you think CloudAsyncTask would be slow? It just has to query keys from already existing database and decrypt them. And TabFragment.onCreateView will only be called from MainActivity after it has processed the refreshDrawer call. I don't think this will lead to a 0.

**Comment by EmmanuelMess** [comment]
I have been optimizing the file loading (still some bugs left) and this issue popped up.

**Comment by vishal0071** [comment]
I need to see the changes you made to optimise file loading. As according to our code, TabFragment is instantiated only after we have the drawer entries, and hence, storage_count.
