### ISSUE TITLE
Crash on copy

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#785]
While copying a single file from internal to sd, crash occurred after line 102 of PrepareCopyTask.

```
com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: service_startup_watcher
                                                           Process: com.amaze.filemanager, PID: 6949
                                                           java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                               at java.util.ArrayList.remove(ArrayList.java:405)
                                                               at com.amaze.filemanager.utils.ServiceWatcherUtil$2.run(ServiceWatcherUtil.java:173)
                                                               at android.os.Handler.handleCallback(Handler.java:746)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by EmmanuelMess** [comment]
Did I agree to work on this?

**Comment by LAfricain** [comment]
I have the same problem.

**Comment by jpage4500** [comment]
I was also running into crashes when trying to copy files (I was copying from SMB source to local target fwiw).

I ended up forking the project and running it on my device and ran into 3 different crashes including this one. I fixed the crashes in my branch here (https://github.com/jpage4500/AmazeFileManager) and I can create a pull request if anyone wants to take a look.

However, I also noticed that if you try to copy multiple files only the first one will get copied but at least a single file copy seems to work now.

btw - I'm running on an S7 running 7.0

**Comment by EmmanuelMess** [comment]
The crashes also happen for encrypting (tested) and should happen for any other service (compressing, extracting and decypting).

**Comment by jpage4500** [comment]
i created a PR for this issue: https://github.com/TeamAmaze/AmazeFileManager/pull/853

**Comment by jpage4500** [comment]
FYI - I created a new issue #857 in case the crashes I saw are different from this specific one

**Comment by jpage4500** [comment]
FWIW - I tried the steps above and they work at least for me.. maybe b/c of android OS version or the fixes in the PR above?

>> While copying a single file from internal to sd

**Comment by VishalNehra** [comment]
Was fixed with [6b4b199](https://github.com/TeamAmaze/AmazeFileManager/commit/6b4b1999cc365402bf72adb7e4919099319026dc)

**Comment by EmmanuelMess** [comment]
Nope, can replicate on master.

**Comment by VishalNehra** [comment]
That branch is not master

**Comment by EmmanuelMess** [comment]
#853 that supposedly fixes this crash is now merged. Though that the commit was from there, nevertheless I would recommend closing issues when they are fixed on master.

**Comment by VishalNehra** [comment]
This issues was fixed in #916 
I'm reworking on rebasing it with master after that this issue can be closed.

**Comment by EmmanuelMess** [comment]
@VishalNehra please add tag to auto close (and test).

**Comment by EmmanuelMess** [comment]
The crash seems to show more often when almost no space is left in internal storage and moving files to external storage or compressing.
