### ISSUE TITLE
File operation status, please!

### ISSUE THREAD

**Issue by gbakeman** [TeamAmaze/AmazeFileManager#788]
Loving the app so far. I'd really like to see a file operation status indicator of some sorts, like when we're moving files. For example, some apps will show a little screen that displays how many files are moved, the transfer rate, ETA, etc. Even just having a simple notification saying that it's doing something would be helpful, rather than nothing at all.

**Comment by EmmanuelMess** [comment]
If the copy is sufficiently large a notification should appear, for small copies it might disappear too fast.

**Comment by tgp1994** [comment]
@vishal0071 May I ask why this was closed? Was the feature implemented?

**Comment by vishal0071** [comment]
Yes, it was already there.. if the operation is long enough you should see a notification and pressing on the notification gets your to the Process Viewer where you can see the chart of progress with other info.

**Comment by tgp1994** [comment]
What is "long enough"? I was moving several GB's worth of files, and I never saw a notification. The app would just sit there, occasionally freezing my phone as it moved the files without any kind of visual notification. I've never seen any Process Viewer before either, are we using the same app? This is for Amaze file manager 3.2.1.

**Comment by EmmanuelMess** [comment]
Okay, this might be a bug, please provide information relating to the files (amount, size, type and anything else that might be of interest).

**Comment by tgp1994** [comment]
Sorry for the confusion; when I read your first message, I thought you were agreeing in that the feature should be implemented.

Now that I'm running a fresh ROM, I just noticed the Process Viewer notification for the first time. It had plenty of issues though:

1. When copying files (40+ JPEG files, averaging about 2MB in size), the copy process will say it's finished before it's even done.
2. The process notification cannot be dismissed.
3. Cancelling a copy process doesn't actually seem to cancel it.
4. When copying a single large file (OBB, over 500MB), the amount copied status doesn't seem to update at a reasonable rate.

**Comment by EmmanuelMess** [comment]
This is still happening file copy status is broken for large files

**Comment by VishalNehra** [comment]
The issue was originally for showing the notification, which was being shown. I know there are issues with copy notification. But for them separate issues should be created.

**Comment by EmmanuelMess** [comment]
Ok
