### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by keunes** [TeamAmaze/AmazeFileManager#790]
Hi @vishal0071
A couple of months ago (July, to be precise) you asked for a translations maintainer on Transifex. I'm now updating strings on Transifex for Dutch, but it seems that certain strings present in the app aren't available on Transifex. So I was wondering if you found a new maintainer?

Best,
Keunes

**Comment by vishal0071** [comment]
No, sadly we haven't.

**Comment by comradekingu** [comment]
@VishalNehra 
I can maintain/administrate the translations if you move them to Hosted Weblate :)
