### ISSUE TITLE
Missing alot of file: BaseFile, HFile,.. 

### ISSUE THREAD

**Issue by hvlong** [TeamAmaze/AmazeFileManager#792]
I has opened source code, but i cannot run it,
Because It's missing alot of file
import com.amaze.filemanager.filesystem.BaseFile;
import com.amaze.filemanager.filesystem.HFile;
import com.amaze.filemanager.fragments.AppsList;
import com.amaze.filemanager.fragments.ProcessViewer;
import com.amaze.filemanager.fragments.ZipViewer;
import com.amaze.filemanager.asynchronous.CopyService;
import com.amaze.filemanager.asynchronous.DeleteTask;
import com.amaze.filemanager.asynchronous.asynctasks.CopyFileCheck;
import com.amaze.filemanager.utils.AppConfig;
import com.amaze.filemanager.utils.files.Futils;

Please share me files or other way to run it.
Thanks

**Comment by vishal0071** [comment]
Please change build variants from lower left of Android Studio to playDebug

**Comment by hvlong** [comment]
I got it.
Thank you so much.
