### ISSUE TITLE
Esperanto translation

### ISSUE THREAD

**Issue by giobeatle1794** [TeamAmaze/AmazeFileManager#793]
Hi. I think this app would be better if it has a translate in Esperanto. I tried to request this language in Transifex, but I can't select the Esperanto language, it doesn't exist in the list. I can translate it. Thanks.

**Comment by vishal0071** [comment]
Please translate the values inside the tags of this file, and give me the final xml file. Leave the rest to me (:
https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/res/values/strings.xml

**Comment by EmmanuelMess** [comment]
Which code (strings-?) is esperanto?

**Comment by vishal0071** [comment]
@EmmanuelMess values-eo

**Comment by giobeatle1794** [comment]
Hi! Here's the Esperanto translation:
[strings.txt](https://github.com/TeamAmaze/AmazeFileManager/files/1448541/strings.txt)
Thanks.

**Comment by VishalNehra** [comment]
@giobeatle1794 thank you very much ^_^
