### ISSUE TITLE
Can't stream videos from SMB share

### ISSUE THREAD

**Issue by fighuass** [TeamAmaze/AmazeFileManager#795]
So, I have some videos on my PC (most mp4, some mkv, some wmv), and I want to stream them from Amaze. However, when I play the file, it automatically closes, or closes after 2-3 seconds. I'm also using MX Player.

**Comment by doodhout** [comment]
Has been mentioned here* already.

* https://github.com/TeamAmaze/AmazeFileManager/issues/382

**Comment by EmmanuelMess** [comment]
I've reopened #382, present your issue there.
