### ISSUE TITLE
Not available in Google Play Store for Android TVs

### ISSUE THREAD

**Issue by denilsonsa** [TeamAmaze/AmazeFileManager#796]
PR #665 added support for Android TVs. Woohoo!
But somehow I still can't find it in the Google Play Store in my Android TV.

I don't why it is not available, maybe @vishal0071 needs to enable it in the Google Play console, or maybe something else. https://developer.android.com/training/tv/start/start.html

@Luca1991 , can you take a look?

[Google+ discussion](https://plus.google.com/+DenilsonSa/posts/5P69BnP1i6a)

**Comment by vishal0071** [comment]
Alright, I thought just adding screenshots will enable Amaze to be used on Android TV market, seems like that was not the case. As I explored the console I found an option that was supposed to be checked.
I've enabled it from my side now, but it'll take some time to reflect the changes.

The option says -
Your app contains a Leanback launch intent, indicating it's designed for Android TV. Before publishing apps to the Play Store on Android TV devices, we review apps for usability with a D-pad and other quality guidelines. 

So it seems this is gonna take more time than publishing a normal update which normally takes about 30 mins to reflect to publication.

Thanks for bringing this up (:

**Comment by denilsonsa** [comment]
Might be worth reviewing the guidelines...
I don't know what they say, I haven't read them. I'm saying that just to make sure it's accepted on the first review. ;-)

**Comment by vishal0071** [comment]
Can you check it once now if it's available? @denilsonsa

**Comment by Luca1991** [comment]
I'm hoping to be wrong, but I'm afraid that the review will fail because I used Amaze on my ShieldTV with keyboard and mouse (and not with Joypad/D-Pad).

I had some problems while trying to use Amaze with my Shield Controller, so I switched to keyboard and mouse.

**Comment by vishal0071** [comment]
Yep, the review indeed failed us up. Here's the eligibility report.

''''
Eligibility issues:

Your app contains text that is cut off on the edges of the TV screen. Please refer to our Overscan documentation for details: http://developer.android.com/training/tv/start/layouts.html#overscan ------------
''''

**Comment by denilsonsa** [comment]
I quickly tried using Amaze on my phone with a Bluetooth gamepad, and the experience was less-than-optimal. I quickly switched back to using touch after being frustrated.

Right now I'm kinda busy, but I may someday try side-loading the Amaze APK from Google Play or from F-Droid on the TV and record the experience. Still, I have the feeling that trying to use the app with a gamepad will be a close approximation of using the app with an IR remote control.

**Comment by VishalNehra** [comment]
Working on fixing navigation issues and publishing for TV on [this](https://github.com/TeamAmaze/AmazeFileManager/tree/android-tv) branch.

**Comment by EmmanuelMess** [comment]
@VishalNehra was this fixed?

**Comment by VishalNehra** [comment]
Nope, it's still planned for 3.6 or a future release. But even I wanna get this done ASAP 😬 will pick this up.

**Comment by ShapeShifter499** [comment]
I'm running into this issue after buying my first Android TV device, a Google TV, are there any updates?

**Comment by VishalNehra** [comment]
> I'm running into this issue after buying my first Android TV device, a Google TV, are there any updates?

Yes I'm working on it. Will update if it'll be possible by v3.6 release.

**Comment by VishalNehra** [comment]
Fixed via #2530
