### ISSUE TITLE
Directories reset after changing settings

### ISSUE THREAD

**Issue by dandv** [TeamAmaze/AmazeFileManager#803]
1. Navigate in one panel to /data/data/com.termux
2. Go to Settings and change a setting, e.g. toggle showing hidden files

Notice how the directory moved away from /data/data/termux

**Comment by EmmanuelMess** [comment]
Cannot replicate, check if the folder you're in isn't hidden.

**Comment by rupak0577** [comment]
It only happens if you were viewing system folders. Which probably isn't an issue.

**Comment by EmmanuelMess** [comment]
@rupak0577 even for that I cannot replicate...
