### ISSUE TITLE
Add WebDAV, Nextcloud / own cloud support

### ISSUE THREAD

**Issue by scanno** [TeamAmaze/AmazeFileManager#804]
A good enhancement for the cloud plugin would be to add support for WebDAV and also for Nextcloud/ownCloud that are WebDAV based.

Apologies if this enhancement was already mentioned.

**Comment by DJCrashdummy** [comment]
this is a duplicate of #376.

**Comment by EmmanuelMess** [comment]
I'd say related #376.
