### ISSUE TITLE
Use glide to load images more optimally

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#807]
[Glide](http://bumptech.github.io/glide/):
> Glide supports fetching, decoding, and displaying video stills, images, and animated GIFs. Glide includes a flexible api that allows developers to plug in to almost any network stack. 
> Glide’s primary focus is on making scrolling any kind of a list of images as smooth and fast as possible, but Glide is also effective for almost any case where you need to fetch, resize, and display a remote image.

Also would help with image resizing without changing aspect ratio.

**Comment by vishal0071** [comment]
This is indeed a necessity. It was actually long planned but was never completed. 
I request you to please work on this (:
