### ISSUE TITLE
Open Download folder on LG G3 and Amaze crashes

### ISSUE THREAD

**Issue by gmorph** [TeamAmaze/AmazeFileManager#812]
On my LG G3 when I click on Download Amaze crashes with the standard "Unfortunately, Amaze has stopped."  I clicked the Report link and sent it through.  Now I have to go into settings and apps, click on Amaze and click on "Clear data" and clear its datafiles otherwise it doesn't start up again.

Thanks, Grant.

**Comment by EmmanuelMess** [comment]
Isn't this
