### ISSUE TITLE
Clicking on OTG usb shortcut crashes Amaze

### ISSUE THREAD

**Issue by LAfricain** [TeamAmaze/AmazeFileManager#814]
Hello,
When I plug an flashdisk on tablet, and click on OTG usb shortcut, Amaze crashes. But I can access to the usb browsing manuallyt to /mnt/usbhost.
I necessary I can add informations, but I don't know how to find it.

**Comment by VishalNehra** [comment]
Please press on 'Send feedback' button in crash and let me know your device configs so that I can view the logs.

**Comment by LAfricain** [comment]
>Please press on 'Send feedback' 

I can't find this Button during crash it say just: amaze stop...

Modèle onda v989 air core 8 Android 4.4.4 firmware 1.0.6

**Comment by VishalNehra** [comment]
Hmm, where did you install Amaze from?

**Comment by LAfricain** [comment]
From fdroid, I would like to replace ESexplorer.

Le 02/11/2017 à 19:21, Vishal Nehra a écrit :

**Comment by EmmanuelMess** [comment]
This is why we need ACRA...

**Comment by LAfricain** [comment]
Le 02/11/2017 à 19:46, Emmanuel a écrit :
>
> This is why we need ACRA...
>

?? What's Acra?

**Comment by VishalNehra** [comment]
@EmmanuelMess I've used ACRA before, I'd prefer crashlytics. But then again, we need more contributors.

**Comment by Biswa96** [comment]
@VishalNehra I've also seen this issue in my android phone (MIUI 9). I've installed it from Google Play. When I connect my USB flash drive, this app shows an OTG option in sidebar. When I clicked that option, it showed `"Select the root of OTG device"` and then showed `"Turn on Documents in Settings > Installed apps first"`. 
Here are some geeky stuff that I've tried. From this Android StackExchange Q&A "[Where is the mount point/folder for a USB pen drive mounted on Marshmallow?](https://android.stackexchange.com/a/140282)" I found that the mount point of that USB drive would be `/mnt/media_rw/random-hex-id`. Then I opened `/mnt` and the `media_rw` mount point is grayed out. I also tried to open with the direct path of that USB drive mount point `/mnt/media_rw/A65B-6116/` but the app does not open it. The string `A65B-6116` varies as USB drives.

![screenshot](https://user-images.githubusercontent.com/31443074/34359640-b0a71364-ea7f-11e7-8cdc-2170b2fd9b39.png)

**Comment by VishalNehra** [comment]
@Biswa96 Please post a screenshot of screen presented when asked to select the root of OTG device

**Comment by Biswa96** [comment]
My bad mind tickles me 😈 Why not you just reverse engineer a stock Android file explorer?

**Comment by EmmanuelMess** [comment]
This should be fixed since #1172.
