### ISSUE TITLE
101 errors when tried to compile code

### ISSUE THREAD

**Issue by xxrocks** [TeamAmaze/AmazeFileManager#815]
Hello ,   
 I'm new to android coding.   I tried to compile code using Android Studio . Which Gave me 110 Errors 

> 
> C:\android projects\AmazeFileManager-master\app\src\main\java\com\amaze\filemanager\fragments\MainFragment.java
> Error:(194, 40) error: incompatible types: MainActivity cannot be converted to UtilitiesProviderInterface
> Error:(204, 40) error: cannot find symbol method getColorPreference()
> Error:(205, 41) error: cannot find symbol method getColorPreference()
> Error:(206, 44) error: cannot find symbol method getColorPreference()
> Error:(728, 38) error: cannot find symbol method setPaste(PasteHelper)
> Error:(738, 88) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> Error:(790, 68) error: cannot find symbol variable KEY_INTENT_LOAD_LIST_FILE
> Error:(917, 88) error: incompatible types: MainActivity cannot be converted to Activity
> Error:(924, 67) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> Error:(931, 102) error: incompatible types: MainActivity cannot be converted to Activity
> Error:(934, 101) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> Error:(1318, 59) error: cannot find symbol method getSupportFragmentManager()
> Error:(1351, 34) error: cannot find symbol method runOnUiThread(()->{ int [...]; } })
> Error:(1426, 82) error: cannot find symbol variable KEY_INTENT_LOAD_LIST
> Error:(1563, 49) error: cannot find symbol method getContentResolver()
> Error:(1707, 42) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> C:\android projects\AmazeFileManager-master\app\src\main\java\com\amaze\filemanager\adapters\RecyclerAdapter.java
> Error:(83, 42) error: cannot find symbol method getColorPreference()
> Error:(84, 44) error: cannot find symbol method getColorPreference()
> Error:(135, 66) error: cannot find symbol method startSupportActionMode(Callback)
> C:\android projects\AmazeFileManager-master\app\src\main\java\com\amaze\filemanager\fragments\CloudSheetFragment.java
> Error:(48, 40) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> Error:(107, 44) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> Error:(110, 44) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> Error:(113, 44) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> Error:(116, 44) error: incompatible types: FragmentActivity cannot be converted to MainActivity
> C:\android projects\AmazeFileManager-master\app\src\fdroid\java\com\amaze\filemanager\activities\MainActivity.java
> Error:(93, 40) error: cannot find symbol class BaseFile
> Error:(95, 40) error: cannot find symbol class HFile
> Error:(97, 39) error: cannot find symbol class AppsList
> Error:(102, 39) error: cannot find symbol class ProcessViewer
> Error:(105, 39) error: cannot find symbol class ZipViewer
> Error:(107, 42) error: cannot find symbol class CopyService
> Error:(108, 42) error: cannot find symbol class DeleteTask
> Error:(109, 53) error: cannot find symbol class CopyFileCheck
> Error:(123, 35) error: cannot find symbol class AppConfig
> Error:(135, 41) error: cannot find symbol class Futils
> Error:(160, 67) error: cannot find symbol class Preffrag
> Error:(160, 1) error: static import only from classes and interfaces
> Error:(161, 67) error: cannot find symbol class Preffrag
> Error:(161, 1) error: static import only from classes and interfaces
> Error:(163, 35) error: cannot find symbol class ThemedActivity
> Error:(180, 22) error: cannot find symbol class BaseFile
> Error:(198, 22) error: cannot find symbol class BaseFile
> Error:(199, 32) error: cannot find symbol class BaseFile
> Error:(219, 13) error: cannot find symbol class Futils
> Error:(2225, 34) error: cannot find symbol class BaseFile
> Error:(221, 27) error: incompatible types: MainActivity cannot be converted to Context
> Error:(286, 5) error: method does not override or implement a method from a supertype
> Error:(288, 9) error: cannot find symbol variable super
> Error:(294, 9) error: cannot find symbol method setContentView(int)
> Error:(295, 35) error: cannot find symbol variable sharedPref
> Error:(299, 39) error: method search in class MainActivityHelper cannot be applied to given types;
> required: SharedPreferences,String
> found: String
> reason: actual and formal argument lists differ in length
> Error:(304, 37) error: incompatible types: MainActivity cannot be converted to Context
> Error:(305, 41) error: incompatible types: MainActivity cannot be converted to Context
> Error:(306, 41) error: incompatible types: MainActivity cannot be converted to Context
> Error:(308, 24) error: cannot find symbol variable AppConfig
> Error:(309, 17) error: cannot find symbol method getFutils()
> Error:(313, 57) error: incompatible types: MainActivity cannot be converted to Context
> Error:(315, 13) error: cannot find symbol method getSupportLoaderManager()
> Error:(318, 16) error: cannot find symbol method getIntent()
> Error:(319, 25) error: cannot find symbol method getIntent()
> Error:(320, 18) error: cannot find symbol method getIntent()
> Error:(325, 23) error: cannot find symbol class BaseFile
> Error:(335, 38) error: cannot find symbol method getString(int)
> Error:(344, 38) error: cannot find symbol method getString(int)
> Error:(384, 13) error: cannot find symbol method getAppTheme()
> Error:(390, 13) error: cannot find symbol method getWindow()
> Error:(392, 13) error: cannot find symbol method getWindow()
> Error:(395, 13) error: cannot find symbol method getAppTheme()
> Error:(396, 67) error: incompatible types: MainActivity cannot be converted to Context
> Error:(401, 21) error: incompatible types: MainActivity cannot be converted to Activity
> Error:(400, 29) error: cannot find symbol constructor (MainActivity,DrawerLayout,int,int,int)
> Error:(417, 13) error: cannot find symbol method getSupportActionBar()
> Error:(418, 13) error: cannot find symbol method getSupportActionBar()
> Error:(419, 13) error: cannot find symbol method getSupportActionBar()
> Error:(438, 21) error: cannot find symbol method getColorPreference()
> Error:(437, 39) error: cannot find symbol method getResources()
> Error:(439, 13) error: cannot find symbol method setTaskDescription(TaskDescription)
> Error:(444, 14) error: cannot find symbol variable sharedPref
> Error:(446, 13) error: cannot find symbol variable sharedPref
> Error:(449, 48) error: package AppConfig does not exist
> Error:(449, 9) error: cannot find symbol variable AppConfig
> Error:(542, 29) error: cannot find symbol method getResources()
> Error:(546, 36) error: cannot find symbol method getResources()
> Error:(552, 42) error: cannot find symbol method getResources()
> Error:(562, 69) error: cannot find symbol method getContentResolver()
> Error:(563, 51) error: cannot find symbol method getResources()
> Error:(564, 17) error: cannot find symbol method finish()
> Error:(578, 13) error: cannot find symbol variable rootMode
> Error:(578, 12) error: illegal start of type
> Error:(655, 49) error: cannot find symbol method checkStoragePermission()
> Error:(658, 70) error: incompatible types: MainActivity cannot be converted to Context
> Error:(661, 40) error: cannot find symbol variable Futils
> Error:(665, 13) error: cannot find symbol variable ThemedActivity
> Error:(665, 12) error: illegal start of type
> Error:(681, 63) error: cannot find symbol variable USB_SERVICE
> Error:(688, 13) error: cannot find symbol variable sharedPref
> Error:(691, 13) error: cannot find symbol variable sharedPref
> Error:(696, 5) error: method does not override or implement a method from a supertype
> Error:(718, 40) error: cannot find symbol class ZipViewer
> Error:(719, 13) error: cannot find symbol class ZipViewer
> Error:(719, 36) error: cannot find symbol class ZipViewer
> Error:Execution failed for task ':app:compileFdroidDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED in 13s
> Information:101 errors
> Information:1 warning
> Information:See complete output in console

**Comment by EmmanuelMess** [comment]
Did you set the build flavor to play?

**Comment by xxrocks** [comment]
When I select   "playDebug"  Now It's Giving Me  Different Errors.  I set the Build variant using Build -- Edit variants  & specify "playDebug" in build.gradle    I'm using Android Studio 3.0 

Here is  build.gradle


`
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

     flavorDimensions "playDebug"


    dexOptions {
        jumboMode = true
    }
`
    
These are the errors

> Error:Error converting bytecode to dex:
> Cause: com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/logging/impl/LogFactoryImpl;
> Error:com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/logging/impl/LogFactoryImpl;
> Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
> Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
> Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
> Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
> Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
> Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
> Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
> Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
> Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForPlayDebug'.

> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/logging/impl/LogFactoryImpl;
Information:BUILD FAILED in 6s
Information:15 errors
Information:1 warning
Information:See complete output in console

**Comment by EmmanuelMess** [comment]
There's no `flavorDimensions "playDebug"` in any .gradle files. You shouldn't be editing any build variants, you should simply select playDebug.

**Comment by VishalNehra** [comment]
@xxrocks AS 3.0 is currently not supported and will require some changes before it can be compiled successfully. Use lower versions of AS and wait for us to push changes to support the new version.

**Comment by EmmanuelMess** [comment]
For the record, I am using AS 3.0…

**Comment by jimandreas** [comment]
On a fresh clone, and building with AS 3.0, my only changes for a clean build and install are:

1) `gradle-wrapper.properties`: change to the 4.1 version of gradle:

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-bin.zip`

2) Build Variant: click the tab and then select `playDebug` in the Build Variants drop down.

The repo then built and installed and started up successfully.
