### ISSUE TITLE
Repeating folder refresh when a file is being downloaded

### ISSUE THREAD

**Issue by aunriz** [TeamAmaze/AmazeFileManager#828]
I get this issue while i download a video file of size more than 1gb, when i visit the folder while its downloading, i get a repeating folder refresh which makes any operations impossible

**Comment by EmmanuelMess** [comment]
What version? Last in master or Play Store?

**Comment by aunriz** [comment]
Version 3.2.1 from the playstore, i use a oneplus 5 device with Android Nougat, it happens when i download via torrent or simply via chrome browser, its easily reproducible

**Comment by Solybum** [comment]
I have been meaning to report this as well.
The refreshes happen regardless of the size of the file being downloaded, however sometimes the multiple refreshes don't happen until I refresh once (as if like Amaze is not aware of the file until I refresh).

**Comment by EmmanuelMess** [comment]
Should be fixed in development, will test later

**Comment by VishalNehra** [comment]
This has already been fixed. Please wait for new update.

**Comment by EmmanuelMess** [comment]
Tested with 1GB download via Firefox, fixed.
