### ISSUE TITLE
Remove Google Plus integration

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#841]
AFAIK we are using G+ only to show a user's picture, which seems ridiculous given that we are a file manager. I propose removing G+ integration from this app.
Maybe it could be replaced by letting the user change the picture via settings.

**Comment by VishalNehra** [comment]
It's optional... Permissions are taken dynamically as per new Android guidelines. I don't see any problem with that.

**Comment by EmmanuelMess** [comment]
But it is deprecated and it's more code to maintain, we don't need this. How many people actually use this?

**Comment by VishalNehra** [comment]
A lot ! I use it personally (:

**Comment by EmmanuelMess** [comment]
Why?

**Comment by Lionirdeadman** [comment]
Yeah, G+ should be removed. Adding one through settings would give the same results without relying on Google for it.

**Comment by VishalNehra** [comment]
@Lionirdeadman some people like me are just too lazy to do that. We like to leave that to Google. It also leaves a consistent user experience for user. For eg. he's using Google Play Store/Inbox/ any other Google app then Amaze will also seem a familiar screen for him to browse.

**Comment by EmmanuelMess** [comment]
Why do you want your picture in a file manager?...

**Comment by EmmanuelMess** [comment]
Also how do you know that
> A lot !

of people use this feature? We don't send telemetry, right?

**Comment by VishalNehra** [comment]
@EmmanuelMess we don't, but Google Console does show us the telemetry.
![capture](https://user-images.githubusercontent.com/5211568/33221508-09f625f4-d176-11e7-98c8-5deaab19fca3.PNG)

**Comment by EmmanuelMess** [comment]
If you present me with a good reason as to why we need the user's face in a file manager I will close the issue.

**Comment by VishalNehra** [comment]
Face and cover picture

**Comment by EmmanuelMess** [comment]
Ok, if you present me with a good reason as to why we need the user's face and cover picture in a file manager I will close the issue.

**Comment by Lionirdeadman** [comment]
Also, including G+ in Amaze means we're pushing the users towards their platform and I don't think that's something we should be doing.

**Comment by EmmanuelMess** [comment]
Also, isn't Google Plus the only thing keeping us from having a common release with f-droid (instead of the play/fdroid divide)?

**Comment by EmmanuelMess** [comment]
Ok, as per agreement @VishalNehra has until Tuesday 00:00 UTC+5:30 to present code (for G+ integration) that isn't deprecated and works, on build tools v26.

**Comment by EmmanuelMess** [comment]
Time has run out...
