### ISSUE TITLE
Encypted txt file cache

### ISSUE THREAD

**Issue by TerkiKerel** [TeamAmaze/AmazeFileManager#846]
Hi,

I using an important/private txt file on local drive of android (/storage/emulated/0). I encrypt it with amaze file manager. 

I search about my question but I could not find anything: 

If I open this encripted file from 'amaze file manager' (the is no other choice) + I open this text file with 'amaze file manager''s built-in text editor, after I close the 'amaze file manager' will the file stays on local on cache or anywhere else?

I checked it: It stays on cache directory even I close the amaze file manager app  /storage/emulated/0/Android/data/com.amazfilemanager/cache/myprivatefile.txt

Is this normal behavior?

Thank you

**Comment by EmmanuelMess** [comment]
Cache, as far as I know, isn't cleaned manually.

**Comment by VishalNehra** [comment]
I'm working on the fix. Will keep this issue updated.

**Comment by EmmanuelMess** [comment]
Fixed in commit 0c5aed9627c717fa7840ae197efbfb12d4512d49.
