### ISSUE TITLE
Unable to copy multiple files

### ISSUE THREAD

**Issue by jpage4500** [TeamAmaze/AmazeFileManager#856]
Using an S7 running 7.0

- connect to SMB source
- select multiple files and hit Copy
- change to external SD card and hit Paste

I added some log statements to see what was happening.. only the first selected file gets copied

```
12-01 10:33:15.536	com.amaze.filemanager	8230	-	D	PrepareCopyTask	 startService: COPY: smb://192.168.0.100/MEDIA/TV/testfile.mkv to /storage/29A4-1410/MEDIA/TV
12-01 10:33:15.537	com.amaze.filemanager	8230	-	D	PrepareCopyTask	 startService: COPY: smb://192.168.0.100/MEDIA/TV/testfile2.mkv to /storage/29A4-1410/MEDIA/TV
...
12-01 10:33:16.016	com.amaze.filemanager	8230	8360	D	GenericCopyUtil	 startCopy: smb://192.168.0.100/MEDIA/TV/testfile.mkv (SMB) to /storage/29A4-1410/MEDIA/TV/testfile.mkv (FILE)
```

log statements can be seen here: https://github.com/jpage4500/AmazeFileManager/commit/9ffce62d05137ecbf2b184bb0e4355906d5cc60a

**Comment by jpage4500** [comment]
here's where I *think* the issue is occurring.. in CopyService it iterates over each file to copy but there's a check here that's only true the first time through. I haven't dug into the code to figure out why this is here or where the other files should be copied over (I assume the idea is to wait until the first file is copied and *then* start the next one.. but it never happens)

```
                    for (int i = 0; i < sourceFiles.size(); i++) {
                        sourceProgress = i;
                        HybridFileParcelable f1 = (sourceFiles.get(i));

...
                            if (!progressHandler.getCancelled()) {
```

**Comment by VishalNehra** [comment]
Is this still an issue?
