### ISSUE TITLE
File saving can never succeed

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#868]
This can never return true:

https://github.com/TeamAmaze/AmazeFileManager/blob/3f6c063942579d983a382e0c010fdc0be351df60/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L594

`FileUtil.writeUriToStorage(..., getCurrentMainFragment().getCurrentPath()); ` 
checks:
`FileOutputStream output = new FileOutputStream(file, true);` 
on a folder resulting in the exception:
`java.io.FileNotFoundException: [the current directory]: open failed: EISDIR (Is a directory)`
that is catched and returns false:
https://github.com/TeamAmaze/AmazeFileManager/blob/3f6c063942579d983a382e0c010fdc0be351df60/app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java#L643-L656

**Comment by VishalNehra** [comment]
Known issue, had planned to fix this.

**Comment by EmmanuelMess** [comment]
You should post these issues and assign them to yourself so you don't forget.

**Comment by VishalNehra** [comment]
why reopen them all?

**Comment by EmmanuelMess** [comment]
So that they can be closed when the PR is pulled.

**Comment by ildar** [comment]
Crashed again: in F-Droid I open the installed apps list then Share to
"Save As..."

**Comment by EmmanuelMess** [comment]
@ildar what makes you think this specific issue is to blame?

**Comment by ildar** [comment]
emm, sorry, I may be wrong and it's more like
https://github.com/TeamAmaze/AmazeFileManager/issues/928 (with NPE at
checkNotNull(Preconditions.java:111))
