### ISSUE TITLE
Selected tick looks weird in grid view

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#873]
Selected tick looks weird in grid view because the tick and the icon are the same color.

**Comment by VishalNehra** [comment]
Why would you choose accent and icon color to be the same knowing the tick is overlay'd on folder in grid view. Doesn't sound like a bug to me.

**Comment by EmmanuelMess** [comment]
I think both have the same color (accent).

**Comment by VishalNehra** [comment]
No, tick color is the accent color and directory color is the icon color preference.
