### ISSUE TITLE
Last point in ProcessWatcherFrament has copy speed that's incoherent

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#875]
It always happens that the copy speed goes up→down→up→...→absurdly up.
<img height="250px" src="https://user-images.githubusercontent.com/10991116/34055386-b987415a-e1ad-11e7-82c9-ae81a04528a6.png" />

**Comment by VishalNehra** [comment]
Not really...
There *is* this thing that the update interval is 1 sec throughout but at last sec... If progress completes before a second, then it's updated at that moment only instead of waiting for a whole second to update which I guess is an expected behavior.

**Comment by EmmanuelMess** [comment]
Where's the waiting code?

**Comment by VishalNehra** [comment]
There's no waiting code, I'm saying that we don't wait for a second to complete and post update whenever the progress actually completes. Maybe the copy speed actually was that much for you in that last second?

**Comment by EmmanuelMess** [comment]
It happens always, I don't think it's my phone.

> There is this thing that the update interval is 1 sec throughout but at last sec...

Where's the waiting code for the "update interval of 1 sec".

**Comment by VishalNehra** [comment]
In [ServiceWatcherUtil](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/main/java/com/amaze/filemanager/utils/ServiceWatcherUtil.java#L97)

**Comment by EmmanuelMess** [comment]
One day, I'll have to edit that class...

**Comment by EmmanuelMess** [comment]
Also happens encripting, I suppose it should be fixed, it doesn't seem real:

<img src="https://user-images.githubusercontent.com/10991116/34059106-5173437a-e1bc-11e7-8054-864d2d466b7a.png" height="250px"/>

**Comment by VishalNehra** [comment]
Can't reproduce, please try to reproduce on a different device.

**Comment by VishalNehra** [comment]
Alright, I reproduce this issue with the changes in your PR #876 
Can't reproduce on master.

**Comment by EmmanuelMess** [comment]
Why?

**Comment by EmmanuelMess** [comment]
Nope, on master also occurs, where did you copy the file? I did it on internal memory.

**Comment by VishalNehra** [comment]
Yep, in internal memory. Can't reproduce on master but in your PR.

**Comment by EmmanuelMess** [comment]
> Haven't really changed the way the code works in PR #876.

**Comment by EmmanuelMess** [comment]
@TranceLove could you test?

**Comment by TranceLove** [comment]
Sure, will look into it tomorrow. It's late in the night here now.

**Comment by TranceLove** [comment]
Had been battling during the day, so I only tried copy over SFTP for a quick verification.

I think #916 also helped on fixing the problem however.

![screenshot_1516871963](https://user-images.githubusercontent.com/251819/35380675-f76aa7a2-01f4-11e8-9677-3bc4d123129d.png)

If #876 is also needed, you will have to fix the conflicts with #916... but before it happens, #916 needs to be accepted, which also has its own problem to fix first.

**Comment by VishalNehra** [comment]
I'm on finalising #916

**Comment by EmmanuelMess** [comment]
Then #876 isn't causing this issue and can be pulled...

**Comment by EmmanuelMess** [comment]
Cannot replicate anymore, closing.
