### ISSUE TITLE
USB OTG doesn't work on Nexus 7 (2012) and stock Lollipop 5.1.1

### ISSUE THREAD

**Issue by Cysioland** [TeamAmaze/AmazeFileManager#878]
As in title. There **is** an OTG option in Amaze sidebar, but on the permission dialog it shows empty folder. Other apps made for OTG browsing on Nexus work fine.

I noticed a certain thing when using them, though, a permission dialog came up and asked for a permission to use USB device. Maybe that's a hook to use? [Here's a possibly relevant part of the docs](https://developer.android.com/guide/topics/connectivity/usb/host.html#permission-d)

**Comment by VishalNehra** [comment]
Please post screenshots of that empty screen you see.
