### ISSUE TITLE
When copying files to a directory, Amaze spam refreshes if you're in said directory

### ISSUE THREAD

**Issue by integralfx** [TeamAmaze/AmazeFileManager#891]
I noticed this issue when copying files from my PC to my phone. If Amaze is open on the directory you're copying your files to, it will constantly refresh and you'll be unable to do anything.

Amaze version 3.2.1
HTC One M8
LineageOS 15.0 (unofficial)

**Comment by nezorflame** [comment]
Have the same issue, except it can be reproduced in Download folder when you're downloading something - it starts reupdating the folder like crazy and eventually crashes.

Amaze version 3.2.1 from F-Droid
Oneplus 3
NitrogenOS (Android 8.1)

**Comment by EmmanuelMess** [comment]
Already fixed in master, wait for update.
