### ISSUE TITLE
Loading images from cloud is broken

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#893]
Images from dropbox won't load, a model must be added to support `DROPBOX://` and other similar paths.

**Comment by EmmanuelMess** [comment]
@VishalNehra I believe you were working on this?

**Comment by TranceLove** [comment]
Test with current master on my Oneplus One running Slim7 (7.1.2).

Onedrive and Dropbox are both working. Possibly due to the way I setup my phone, I couldn't link my Google Drive account with Amaze, so can't tell... but I think it should also work.

Outside the cloud plugin, images can also be opened over SFTP connections, but not over SMB connections... but it didn't happen with Galaxy S2 running SlimLP (5.1.1).

On 7.1.2 app would crash of `android.os.NetworkOnMainThreadException`.

**Comment by VishalNehra** [comment]
@TranceLove this issue was for loading of icons not the images themselves. I'm already working on this in another branch.

**Comment by EmmanuelMess** [comment]
Any progress, can I help?

**Comment by VishalNehra** [comment]
I might need some help over here. Will let you know after a few more tries. Basically, we're loading icons on main thread now, it throws NetworkOnMainThread exception when loading cloud icons. I've written models and helper classes to pool the requests and load them in background. But now icons are not being loaded at all. 
Like I said, will let you know if I fail this weekend.

**Comment by EmmanuelMess** [comment]
News? At least update a fix branch to the repo...

**Comment by VishalNehra** [comment]
Will update the branch once I finalize. I've managed to pinpoint the problem and fix is almost been worked up.

**Comment by EmmanuelMess** [comment]
I now see there's branch [fix-glide-iconloading](https://github.com/TeamAmaze/AmazeFileManager/commits/fix-glide-iconloading) for this. I still don't understand why you implemented your own threaded solution to download (in `IconLoaderUtil`) I would image Glide already has one...

**Comment by EmmanuelMess** [comment]
You don't tell me where you got stuck... So I've read your code, side by side with the [official guide](http://bumptech.github.io/glide/tut/custom-modelloader.html#writing-a-custom-modelloader).
I will write what I think are mistakes:

1. The ModelLoader (A) has a redundant name (see point 3) (B) takes an InputStream and not a String (URLs are now InputStreams?) and (C) returns true...
InputStreamModelLoader:
```java
    @Override
    public boolean handles(InputStream inputStream) {
        return true;
    }
```
2. Why is the KEY for caching the current time in milliseconds?! 
```java
    @Nullable
    @Override
    public LoadData<InputStream> buildLoadData(InputStream inputStream, int width, int height, Options options) {
        return new LoadData<>(new ObjectKey(System.currentTimeMillis()), new InputStreamDataFetcher(inputStream));
    }
```
3. InputStreamDataFetcher should have a more specific name (like CloudServiceDataFetcher). Also, `loadData` is not doing the loading? 
>[...] loadData() is the method where Glide expects you to do your heavy lifting. You can queue an asynchronous task, start a network request, load some data from disk or whatever you’d like. loadData() is always called on one of Glide’s background threads. A given DataFetcher will only be used on a single background thread at a time, so it doesn’t need to be thread safe. However, multiple DataFetchers may be run in parallel, so any shared resources accessed by DataFetchers should be thread safe.

-- [source](http://bumptech.github.io/glide/tut/custom-modelloader.html#loaddata)


```java
   @Override
    public void loadData(Priority priority, DataCallback<? super InputStream> callback) {
        callback.onDataReady(inputStream);
    }
```

Maybe [Advanced Usecases](http://bumptech.github.io/glide/tut/custom-modelloader.html#advanced-use-cases) will help you, anyways, the code is very long and I'm trying to not have to understand it all, because multi-threading can be very tiering for me, please do tell me WHERE you are stuck/don't know how to not reinvent the wheel.

**Comment by VishalNehra** [comment]
Thank you, your last advice about loadData handling all the heavy work for icon loading really helped as I seem to have skipped it while reading documentation.
I've made a PR which should fix this issue.
