### ISSUE TITLE
Why do the file images show  with a background in list view and colorized in grid view?

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#894]
Why do the file images show  with a background in list view and colorized in grid view?

Here are some of the lines that cause this:
On list view:
https://github.com/TeamAmaze/AmazeFileManager/blob/8a956c516843aeb4c5dee3d251997b29abd49784/app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java#L566-L578
On grid view:
https://github.com/TeamAmaze/AmazeFileManager/blob/8a956c516843aeb4c5dee3d251997b29abd49784/app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java#L627-L660

**Comment by VishalNehra** [comment]
Because the function of "colorize icon" in settings is that background to all the generic icons except directory will be set to anything random color. If this option is unset then this background color is picked from the icon color preference. 
This is a necessary feature as in many cases user might not want to set hundreds of icons with same color in it's background.
That being said, this behavior needs fixes for various other mime types.
One such case is the generic icon for an encrypted (.aze) file. It's background is always the icon color regardless of whether "Colorize icons" is set or not.

**Comment by EmmanuelMess** [comment]
But why is there a diference between grid and list? Shouldn't both be the same? Why shouldn't grid have a backgroud in each item?

**Comment by VishalNehra** [comment]
Because huge boxes filled with color won't look that good. 
List view icon takes about 20% of space for the item, while grid view icon takes 80% space. Now imagine 80% of your grid filled with color.

**Comment by EmmanuelMess** [comment]
> Because the function of "colorize icon" in settings is that background to all the generic icons except directory will be set to anything random color. If this option is unset then this background color is picked from the icon color preference.

And in grid instead of randomizing the background, the icons are of "randomized" colors.

PS: neither are random:
Grid colors:
https://github.com/TeamAmaze/AmazeFileManager/blob/8a956c516843aeb4c5dee3d251997b29abd49784/app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java#L91-L102
List colors:
https://github.com/TeamAmaze/AmazeFileManager/blob/8a956c516843aeb4c5dee3d251997b29abd49784/app/src/main/java/com/amaze/filemanager/utils/color/ColorUtils.java#L19-L50
I do understand your point though, thanks for your time.

**Comment by VishalNehra** [comment]
I understand your point now. In that case, what I think would be better is, keeping circular background for grid too i.e. in it's square placeholder, and the generic icon color to white. Just like in list view.

**Comment by EmmanuelMess** [comment]
Yes, I think that would be a good idea.

**Comment by EmmanuelMess** [comment]
What you are proposing is the one on the left, but I think the one on the right is a viable approach too:
<img height="150px" src="https://user-images.githubusercontent.com/10991116/34470770-ce4185a2-ef17-11e7-948e-f4314b565e35.png"/>
In context:
<img height="350px" src="https://user-images.githubusercontent.com/10991116/34470772-da289c70-ef17-11e7-85ee-3162467922ac.png"/>
