### ISSUE TITLE
Optimize RoundedImageView

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#898]
There are object creations in onDraw() and bitmap duplication (I think).

**Comment by VishalNehra** [comment]
Please atleast let us know the class name.

**Comment by EmmanuelMess** [comment]
RoundedImageView.java

**Comment by VishalNehra** [comment]
Oh, my bad, didn't see the title. There indeed are certain instances that could've been avoided. However, some are important for backward compatibility.
