### ISSUE TITLE
Cant set Master Password to empty after it is set to something

### ISSUE THREAD

**Issue by RichyHBM** [TeamAmaze/AmazeFileManager#903]
As the title says, once you have set a master password you can not set it to empty meaning to use a different method you have to clear the apps preferences

**Comment by VishalNehra** [comment]
To use a different method? From that you mean switching to fingerprint later after you've encrypted some files with master password? 
There shouldn't be any problem doing that AFAIK

**Comment by RichyHBM** [comment]
Well in my case I was trying to empty the master password to be able to use different passwords for each file again

**Comment by VishalNehra** [comment]
In that case you need to manually change password everytime from settings. I don't see any bug regarding this.

**Comment by RichyHBM** [comment]
Hmm is there any reason why you shouldn't be able to remove the master password from settings though?

**Comment by VishalNehra** [comment]
Any password set is instance dependent. Means it'll be set based on the value at the time while you encrypted the file. If you decide to change (or remove) the password later, then any file encrypted after that point will reflect this change, not the ones that were already encrypted.

**Comment by EmmanuelMess** [comment]
To have master passwords there should be a 'chain-lock' where individual file's passwords are saved, so that you can open the chain-lock and thus everything with just one password. Removing the master password would destroy the chain-lock, making each file only openable with it's creation password. Maybe this is what @RichyHBM meant by reseting the master password.

**Comment by RichyHBM** [comment]
I assumed rather than it being a master password it was actually a default password (saving you having to enter the same password to encrypt multiple files) which sounds like it isn't.

That said, I would expect to have the ability to encrypt a file with an individual password after having set a master password (preferably without having to just change the master password) without having to wipe amaze' data
