### ISSUE TITLE
Encryption warning

### ISSUE THREAD

**Issue by RichyHBM** [TeamAmaze/AmazeFileManager#904]
I wanted to ask, when encrypting you get a popup along the lines of "if you change your pattern you won't be able to decrypt"

What is this in reference to? I tried changing my phone lock and could decrypt just fine.

Also, I have seen on a bug that if you wipe Amaze you can no longer decrypt, possibly due to a database? Is that expected behaviour or a bug? It seems very dangerous that you wouldn't be able to decrypt on a different device or location, specially with the cloud plugin as I imagine one of the main reasons to encrypt a file is to put it on the cloud.

If that is the case I would like to suggest removing the need of the database completely, have the files extension determine if its been encrypted, (foo.aez is encrypted once, foo.aez.aez is an encryption of an encryption, etc) that way it would allow you to move encrypted files around safely

**Comment by EmmanuelMess** [comment]
Encryption is hell, we need to create a new standard from scratch. Tar a file or folder and encrypt using AES 128.

**Comment by RichyHBM** [comment]
I like that you can still see the folder structure easily, so my vote would be against taring a whole folder (but rather doing each individual file)

**Comment by EmmanuelMess** [comment]
Why would taring the folder destroy it's structure?

**Comment by EmmanuelMess** [comment]
> The archive data sets created by tar contain various file system parameters, such as name, time stamps, ownership, file access permissions, **and directory organization**.

Source: [Wikipedia - tar (computing)](https://en.wikipedia.org/wiki/Tar_(computing)). Emphasis added.

**Comment by RichyHBM** [comment]
Oh no, sorry I didnt mean it like that, I meant it gives you the ability to go through the structure without uncompressing/using a zip app. But more so if the folder itself wasnt tar'ed I think it would be easier to then support adding additional files and encrypting only the new files. (Think backing up a folder on the phone where new files get added all the time)

**Comment by RichyHBM** [comment]
So just to double check, the warning about changing the pattern in the security settings, does that mean anything?

**Comment by EmmanuelMess** [comment]
> Oh no, sorry I didnt mean it like that, I meant it gives you the ability to go through the structure without uncompressing/using a zip app.

It's a tar, not zip, no compression will be ideal. Read/write operations should be fast enough.
Also, I don't think that letting anyone know what files (by name[1]) or how many there are is a good idea.
[1] Name obfuscation ("photo.jpg"->HfdL4oKN45Ffoe) would difficult knowing which file to decrypt ("which one of these 1000 file is what you are looking for?" type situations).

> So just to double check, the warning about changing the pattern in the security settings, does that mean anything?

@VishalNehra should be able to answer that.

**Comment by VishalNehra** [comment]
@RichyHBM most probably you won't be loosing if you have Android M+
I tried the best I could to not let it forget the keys, however there's no assurance, atleast not officially. 
As for the database problem, I have plans to deal with it later. 
As for filenames encryption, it's also in the todo. 
Ps. There seems to be update to original bugtracker issue and it confirms you can't loose keys now, after you change lockscreen. More info [here](https://issuetracker.google.com/issues/36983155)

**Comment by RichyHBM** [comment]
Thanks for clearing that up, I didnt realise that was a bug in android!
On a completelly unrelated note, is there anyway to sign up to be a beta tester? The play store doesnt let me as it says its full

**Comment by VishalNehra** [comment]
Yes, I'll just have to increase the limit. Will do it later today so check back there after some time.

**Comment by PatRiot1337** [comment]
hm... if I change back my lockscreen (as it was at time of encryption), is it then still possible to lose ability to decrypt? and what's about biometrical? If I add a finger, does it count as a "change" then? Thanks!
