### ISSUE TITLE
[CRASH] while sharing text with Save As...

### ISSUE THREAD

**Issue by ildar** [TeamAmaze/AmazeFileManager#912]
Steps:
1. Select text
2. Share
3. Tap "Save As..."
4. When Amaze appears, tap Arrow Down button in bottom right.

logcat doesn't look too informative but still:
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: Process: com.amaze.filemanager, PID: 19467
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: Theme: themes:{default=overlay:org.cyanogenmod.hexolibre, iconPack:org.twelf.cmtheme, fontPkg:org.cyanogenmod.hexolibre, com.android.systemui=overlay:org.cyanogenmod.hexolibre, com.android.systemui.navbar=overlay:org.cyanogenmod.hexolibre}
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: Caused by: java.lang.NullPointerException: uri
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:60)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:647)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.FileUtil$1.doInBackground(FileUtil.java:190)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at com.amaze.filemanager.utils.AppConfig$1.doInBackground(AppConfig.java:98)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at com.amaze.filemanager.utils.AppConfig$1.doInBackground(AppConfig.java:82)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 01-09 09:21:23.916 19467 19508 E AndroidRuntime: 	... 4 more

**Comment by ildar** [comment]
Ah! Amaze Version 3.2.1 (63) F-Droid, Android 6

**Comment by VishalNehra** [comment]
Duplicate to #868 
Please follow that issue for the fix.
