### ISSUE TITLE
After saving an image the name is 'null'

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#920]
Using the 'share' dialog to save an image from Firefox app the name is 'null'.

**Comment by VishalNehra** [comment]
That's the framework's problem

**Comment by EmmanuelMess** [comment]
It is difficult to find another app that does more or less the same thing, but Google's Photos has an upload feature that goes back to the original app, so it is not a problem in the framework.

**Comment by VishalNehra** [comment]
Well, for my own defense, I tested on another device and it doesn't have this issue. 
This is given in the documentation of ````finish()```` method.
````
/**
     * Call this when your activity is done and should be closed.  The
     * ActivityResult is propagated back to whoever launched you via
     * onActivityResult().
     */
````

**Comment by EmmanuelMess** [comment]
I've learned not to call finish().

**Comment by EmmanuelMess** [comment]
I've learned not to call finish().

**Comment by EmmanuelMess** [comment]
Why is this closed?

**Comment by VishalNehra** [comment]
Sorry, I meant to close #921

**Comment by EmmanuelMess** [comment]
Tested, the issue seems to be of Firefox. With Chrome this issue doesn't exist.
