### ISSUE TITLE
After saving an image the app throws me to the launcher, not the last used app

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#921]
After saving an image through the share dialog the app throws me to the launcher, not the last app.

**Comment by VishalNehra** [comment]
That's the framework's problem.

**Comment by EmmanuelMess** [comment]
It is difficult to find another app that does more or less the same thing, but Google's Photos has an upload feature that goes back to the original app, so it is not a problem in the framework.

**Comment by EmmanuelMess** [comment]
Prove it is the framework.

**Comment by VishalNehra** [comment]
Because it's behaviour is different for different device vendors.

**Comment by EmmanuelMess** [comment]
It is Android, that argument doesn't really make sense.

**Comment by VishalNehra** [comment]
Hence we can't possibly program for every device vendor out there. 
There's nothing we can do if a vendor decides to override finish callback to redirect to their launcher instead of the last app opened.

**Comment by EmmanuelMess** [comment]
"Their" launcher, I'm using [FlickLauncher](https://github.com/michelelacorte/FlickLauncher)? I don't think anyone is overriding the finish().

**Comment by PiwwowPants** [comment]
I can't seem to reproduce this in 8.1 on either Pixel Launcher or FlickLauncher on the master branch.
Is there a specific app being used? Launching in to save through Edge or Chrome returns me back to those apps when I save in Amaze.

**Comment by EmmanuelMess** [comment]
Will test with Chrome tomorrow.

**Comment by EmmanuelMess** [comment]
Tested, the issue seems to be of Firefox. With Chrome this issue doesn't exist.
