### ISSUE TITLE
Alternative payment methods

### ISSUE THREAD

**Issue by xxvixxy** [TeamAmaze/AmazeFileManager#923]
I am wondering two things, 
1. Could you offer a method to pay for the cloud, and donate via other methods. I do not use the play store, nor do I have a gmail account to use the store. 
2. Support NextCloud, and pCloud? 

Thank you

**Comment by EmmanuelMess** [comment]
What do you propose for payments?

**Comment by VishalNehra** [comment]
[Write me a mail](mailto:vishalmeham2@gmail.com), I'll give you the details for our PayPal donation profile and send you over the apk.
