### ISSUE TITLE
Recursive copy from smb

### ISSUE THREAD

**Issue by thetwom** [TeamAmaze/AmazeFileManager#925]
Trying to copy a folder from a smb-location which contains other folders (lets name them child folders) would only create the child folders at the target location but ignore the contents of the child folders. 

It would be nice to be able to do recursive copies. 

Amaze version; 3.2.1

Best regards.

**Comment by BaumGuard** [comment]
The bug still exists in the latest version 3.4.3! Why has the bug still not been fixed although it is known for a few years? Bugs are there to be fixed and not to be ignored!
In another issue I've read that the notification reads that the copy procedure was successful although the copying procedure is still running in the background. Such a notification is misconceptional and contradictory!

**Comment by TranceLove** [comment]
A too restricted Operations.isFileNameValid() was the culprit. Sorry about that.

See #1865
