### ISSUE TITLE
Adaptable storage corrupt after installing amaze...

### ISSUE THREAD

**Issue by arjhun** [TeamAmaze/AmazeFileManager#930]
I installed amaze on a Moto X play with android 7 Nougat.

After I installed amaze and rebooted my phone, my SD card used as internal storage is corrupt.... The phone reports "SD card missing".

The strange thing is that when I put the card in an OTG card reader, it does get recognized and works fine! And putting a different SD card in the same slot works perfectly fine... so It seems that only that particular card is not working anymore in the standard internal SD slot...

Could this be caused by me installing amaze?

**Comment by VishalNehra** [comment]
No
