### ISSUE TITLE
Secure connection is greyed on on ftp server settings.

### ISSUE THREAD

**Issue by nextgenthemes** [TeamAmaze/AmazeFileManager#932]
Using Copperhead OS lastest based on android 8 and the v3.2.1 of Amaze that ships with Fdroid.

The FTP server setting show secure connection greyed out with no indication why.

**Comment by VishalNehra** [comment]
Are you connected to a wifi network?

**Comment by nextgenthemes** [comment]
Yes I am. Why does that matter in regards to setting up and starting a SFTP server?

Should I not be able to set it up, start it, connect to wifi later anyway? Anyway I was connected.

**Comment by p3k** [comment]
same here

**Comment by realmain** [comment]
OnePlus 3T, LineageOS 15.1 (Android 8.1)

Same issue.

**Comment by EmmanuelMess** [comment]
It seems that this is the cause:
https://github.com/TeamAmaze/AmazeFileManager/blob/5cf10b4545bfe534ac8de1077e771c2434ab80a3/app/src/main/java/com/amaze/filemanager/fragments/FTPServerFragment.java#L252-L255

**Comment by TranceLove** [comment]
Logic seems OK with Robolectric test, but was with another KeyStore created with JKS which only exists on workstations; the original BouncyCastle-based keystore seems to hang.

Let's see if I can get something out.
