### ISSUE TITLE
Cannot run, Error on MainActivity.java

### ISSUE THREAD

**Issue by wahyuridiansyah** [TeamAmaze/AmazeFileManager#935]
> Information:Gradle tasks [:app:assembleFdroidDebug]
> /Users/wahyuridiansyah/AndroidStudioProjects/AmazeFileManager/app/src/fdroid/java/com/amaze/filemanager/activities/MainActivity.java
> Error:(123, 41) error: cannot find symbol class Futils
> Error:(146, 67) error: cannot find symbol class Preffrag
> Error:(146, 1) error: static import only from classes and interfaces
> Error:(147, 67) error: cannot find symbol class Preffrag
> Error:(147, 1) error: static import only from classes and interfaces
> Error:(149, 35) error: cannot find symbol class ThemedActivity
> Error:(166, 22) error: cannot find symbol class BaseFile
> Error:(175, 12) error: cannot find symbol class FloatingActionMenu
> Error:(184, 22) error: cannot find symbol class BaseFile
> Error:(185, 32) error: cannot find symbol class BaseFile
> Error:(205, 13) error: cannot find symbol class Futils
> Error:(2211, 34) error: cannot find symbol class BaseFile
> Error:Execution failed for task ':app:compileFdroidDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED in 31s
> Information:13 errors
> Information:0 warnings
> Information:See complete output in console
<img width="1026" alt="jepretan layar 2018-01-18 pada 20 51 58" src="https://user-images.githubusercontent.com/17635407/35101351-d370b9e4-fc91-11e7-9b4b-656919d4e29c.png">

**Comment by EmmanuelMess** [comment]
Build > Select Build Variant > playDebug
