### ISSUE TITLE
Cannot duplicate a file

### ISSUE THREAD

**Issue by thewizardstudio** [TeamAmaze/AmazeFileManager#949]
#### Expected Behavior
Copying and Pasting a file in the same directory should either allow an overwrite of the original file OR paste a copy of the file with a slightly modified name (e.g. appended with 'COPY').  

#### Actual Behavior
Copying and Pasting a file in the same directory results in a dialogue box asking if you want to Overwrite, but the Overwrite button is greyed out and unselectable.  

#### Discussion
It is common for people to want to make duplicates of the same file within the same directory for many reasons.  Most file systems just make the copy without prompting for an overwrite, and modify the name of the file automatically so as not to create a duplicate.

#### How to Reproduce
1. Launch Amaze File Manager 3.2.1 on Android 8.1.0
2. Click the 3 Vertical Dots icon to the right of a File
3. Click 'Copy'
4. Click the Clipboard icon in the Upper Right to Paste
5. Try to click Overwrite

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.2.1
---

#### Recording of the Bug
![AmazeFileManager_CannotOverwriteCopiedFile.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516164346/kocxooxtr1bs9pnukuch.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/cannot-copy-and-paste-a-file-into-same-directory">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by superlex** [comment]
I agree.
It should ask for pasting with another name, or there could be a new menu entry "duplicate file".

**Comment by EmmanuelMess** [comment]
Duplicate #721.
