### ISSUE TITLE
Selecting a Textual Representation of a Folder in Directory Navigation Does Nothing

### ISSUE THREAD

**Issue by thewizardstudio** [TeamAmaze/AmazeFileManager#957]
#### Expected Behavior
Activating the directory navigation feature by clicking the directory path, and then clicking on the name of a folder will take the user to that folder.

#### Actual Behavior
Activating the directory navigation feature by clicking the directory path, and then clicking on any of the text representations of a folder does nothing.  Clicking on a directory represented by an icon does work as expected, but not the ones represented by their textual name.

#### How to Reproduce
1. Launch Amaze File Manager 3.2.1 on Android 8.1.0
2. Navigate to a Directory
3. Tap the Directory Path at the top to activate Directory Navigation
4. Click on a Directory represented by an icon and note it takes you there
5. Click on a Directory represented by text and note it does nothing

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.2.1
---

#### Recording of the Bug
![Amaze_SelectingDirectoryNameTextDoesNothing.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516418014/kjcexiuoev8vtsspsptg.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/selecting-a-textual-representation-of-a-folder-in-directory-navigation-does-nothing">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by VishalNehra** [comment]
Working fine for me on current master.

**Comment by EmmanuelMess** [comment]
@VishalNehra With what android version?

**Comment by EmmanuelMess** [comment]
OK, tested in master with android API 27 and it works.
