### ISSUE TITLE
Use automated tests to verify behaviour?

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#959]
As issues and PRs are stacking up, I wonder if we should

- write tests to verify behaviour
- include testing as part of building process

To some extent, it also eases my testing effort ;)

Downside of this approach:
 - Devs may hate writing tests, either unit tests or UI tests
 - UI tests are heavyweight and slows down builds
 - You gonna want to test manually anyway
 - Writing tests takes time, longer than manually testing which costs a few taps within a minute
 - You need to maintain yet another set of code

I had some work in progress, at [TranceLove:AmazeFileManager/feature/testonbuild](https://github.com/TranceLove/AmazeFileManager/tree/feature/testonbuild) and I wrote a test case for #938, at [TranceLove:AmazeFileManager/verify/pr938](https://github.com/TranceLove/AmazeFileManager/tree/verify/pr938).

I won't think of writing tests for everything, but at least for new code and issues.

It still goes a long way till I can have an Android emulator instance inside travis-ci though (is using a private Travis Docker instance for the purpose).

If you like this I shall file an PR officially once the Android emulator problem is fixed. Until then, maybe I'll keep my tests in my own repo...

**Comment by EmmanuelMess** [comment]
I have no idea how to make tests, but we do need tests, if you can make some I'll try to copy them and make more. 

About the downsides:
 - I don't think any of us *hates* making tests, it makes testing easier
 - AFAIK test are built when you are using them, and don't slow down general builds
 - We won't have to test manually a lot of other stuff (preventing "worked in last update" issues) and we can write specific tests for specific projects
 - Can't we try to reduce as much as possible the test writing time? Testing automatically is faster when compounded
 - We would need to maintain code that reduces the time of maintaining other code

**Comment by TranceLove** [comment]
Currently some big hurdles to get through, and hence it had been hold back.

- Still struggling to find a way to launch Android emulator in travis-ci. I did tried some configurations with [Travis's online docs](https://docs.travis-ci.com/user/languages/android/), but still haven't up to the result I wanted
- The test case written in `verify/pr938` was caught only passes when run with Android tablet emulator, that makes me feel uncomfortable (if I should launch an array of Android emulators and spread the tests to them on the CI server?)

It wouldn't be hard to make tests to be able to run from Android studio (that #963 and c6d4718 showed how it can be done), but it'd also defeat the purpose of enabling automated tests in the CI server.

**Comment by EmmanuelMess** [comment]
I didn't think you were trying to run them on the sever, it can be convenient, but there are more pressing matters right now, after release we can work on the CI sever.
Not so related: I wrote a Robolectric test in #963.

**Comment by cpfeiffer** [comment]
I found this PR by chance and wanted to mention http://robolectric.org/ which allows running tests locally and in Travis without running an emulator.

**Comment by EmmanuelMess** [comment]
@cpfeiffer Any documentation on running robolectric on Travis?

**Comment by cpfeiffer** [comment]
Can't check right now, but @Freeyourgadget/Gadgetbridge we have just this line in .travis.yml for running the tests:
> script: ./gradlew build connectedCheck --stacktrace

**Comment by EmmanuelMess** [comment]
This is done now.
