### ISSUE TITLE
Recycle Bin

### ISSUE THREAD

**Issue by phankhanh1992** [TeamAmaze/AmazeFileManager#971]
Hi team!
When do you update the trash?
Thanks!

**Comment by EmmanuelMess** [comment]
Rephrase

**Comment by Alexander--** [comment]
@EmmanuelMess sounds like someone [has fallen victim](https://en.wikipedia.org/wiki/Trash_(computing)) to Google Translate.

As for trash bin — does Amaze not have it yet? It should be relatively easy to implement such functionality, — there are several Linux file managers that have it. Android even have special Intent to signal about free space exhaustion, that can assist in cleaning it automatically.

IMO, the hardest part is dealing with app removal — what if user removes Amaze without cleaning the directories hosting the recycle bin? The garbage inside might stick around, especially if it is on removable storage, which got removed before uninstalling Amaze.

**Comment by EmmanuelMess** [comment]
It would take some time to get right (so not for v3.3.0), and should probably be added as an "opt in" feature. But can be done.
@VishalNehra What do you think?

**Comment by phankhanh1992** [comment]
@EmmanuelMess  I think feature is necessary. And you? ^^

**Comment by VishalNehra** [comment]
I agree with @Alexander--

**Comment by k2arim99** [comment]
i think is highly optional but many times i had wished i had it

**Comment by EmmanuelMess** [comment]
There is a design issue now: #2629

**Comment by VishnuSanal** [comment]
fixed!
