### ISSUE TITLE
Update Proguard and enable it

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#977]
Proguard helps maintain apk size down, but for it to work some libs have special requirements, I think CloudRAIL was one of them.

**Comment by VishalNehra** [comment]
For Cloudrail, [this](https://github.com/CloudRail/cloudrail-si-android-sdk/issues/34) should be able to bypass it.

**Comment by EmmanuelMess** [comment]
The snippet:
`-keep class com.cloudrail.** { *; }`

**Comment by EmmanuelMess** [comment]
@TranceLove Please update proguard with rules relating to sshj and other networking libs you have added as I don't know how those libs work.
