### ISSUE TITLE
Remove java file headers and put Copyright headers where missing

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#985]
Remove all
```java
/**
 * @author x at 00:00
 */
```
And add the correct Copyright to files.

**Comment by VishalNehra** [comment]
Why so? It's auto generated by AS, plus gives us a better idea of the history of file.

**Comment by EmmanuelMess** [comment]
You can go to GitHub blame to have a good idea, line by line, of changed what. That just uses space.

**Comment by VishalNehra** [comment]
Not everything is on GitHub. Consider someone using the project and putting it on some other VCS .
Plus, this just gets a good idea with a quick view... Instead of going all the way to GitHub and reviewing.

**Comment by EmmanuelMess** [comment]
Why would you need to know who made the original file?

> Not everything is on GitHub. Consider someone using the project and putting it on some other VCS .

Even less is in that header, it just says who's the person who created the file, I most probably was modified afterwards by other people.

**Comment by VishalNehra** [comment]
Author and timestamp are the basic info, can always see the blame to see who all contributed to it. Author does deserve some mentioning and timestamp gives pretty basic idea of file history.
I don't see any problem with this. And it seems neither does Google. Earlier they used to just mention author, now they also mention timestamp. This proves they're updating this as standard in Android programming.

**Comment by EmmanuelMess** [comment]
You can (should) add yourself to copyright when editing.

**Comment by EmmanuelMess** [comment]
This has been mostly fixed now.
