### ISSUE TITLE
Use Android field naming convention or Java's?

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#986]
From [AOSP Java Code Style for Contributors](https://source.android.com/setup/code-style#follow-field-naming-conventions):

> Follow Field Naming Conventions
> * Non-public, non-static field names start with m.
> * Static field names start with s.
> * Other fields start with a lower case letter.
> * Public static final fields (constants) are ALL_CAPS_WITH_UNDERSCORES.
> 
> For example:
> 
> ```
> public class MyClass {
>     public static final int SOME_CONSTANT = 42;
>     public int publicField;
>     private static MyClass sSingleton;
>     int mPackagePrivate;
>     private int mPrivate;
>     protected int mProtected;
> }
> ```

And from [Java Code Conventions](http://www.oracle.com/technetwork/java/codeconventions-135099.html):

> Identifier Type | Rules for Naming | Examples
> -------------- | ------------------ | ---------
> Variables | Except for variables, all instance, class, and class constants are in mixed case with a lowercase first letter. Internal words start with capital letters. Variable names should not start with underscore _ or dollar sign $ characters, even though both are allowed.<br /><br />Variable names should be short yet meaningful. The choice of a variable name should be mnemonic- that is, designed to indicate to the casual observer the intent of its use. One-character variable names should be avoided except for temporary "throwaway" variables. Common names for temporary variables are i, j, k, m, and n for integers; c, d, and e for characters. | int&nbsp;i;<br />char&nbsp;c;<br />float&nbsp;myWidth;

I personally prefer the second one, because of less clutter. But right now we have both, so which one should be enforced?

**Comment by TranceLove** [comment]
I used to code the Java way, so I'd vote for Java's coding convention. My previous work was in AOSP's coding style because - just to make sure I'm with Android's standard to reduce the chance of the PR being rejected.

(Though, what happened then was not related to naming conventions at all ;))

**Comment by tryton-vanmeer** [comment]
I also prefer the second one when writing Java code. Jake Wharton also has a [good post](http://jakewharton.com/just-say-no-to-hungarian-notation/) on the subject.

**Comment by EmmanuelMess** [comment]
Well, I'll use Java notation on new PRs (as always) and enforce Java notation in new PRs. That is if no one proposes a counter argument.

**Comment by VishalNehra** [comment]
I tend to follow the AOSP style.

**Comment by EmmanuelMess** [comment]
It's decided then.
